### ISSUE TITLE
Level Reupload Doesn't Work

### ISSUE THREAD

**Issue by TehDANKESTMemeLord** [Cvolton/GMDprivateServer#100]
When i try reuploading a level (Bloodbath, etc...) It show some kind of error.
![image](https://user-images.githubusercontent.com/33117639/32043186-ad95c71e-ba42-11e7-86a4-f18182f3b297.png)

**Comment by Cvolton** [comment]
it literally says in the error what you're supposed to do

**Comment by TehDANKESTMemeLord** [comment]
Turns out, Altervista is an actual piece of shit to host a PS on, but i really had no other choice.... You need to send a sms to unlock the connection....I sent sms from some weird website....Nothing happened. Also free web hosting area registering is down so i really need something to have my PS on

**Comment by TehDANKESTMemeLord** [comment]
Nevermind i emailed freewha to create a account and i managed to create one. No more altervista!
