### ISSUE TITLE
LevelReupload.php Fatal Error

### ISSUE THREAD

**Issue by pKunnn** [Cvolton/GMDprivateServer#1000]
Well. So when trying to reupload a level this error pops up:

`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'levelName' cannot be null' in /home/PKun/public_html/gdbrazilian/database/tools/levelReupload.php:124 Stack trace: #0 /home/PKun/public_html/gdbrazilian/database/tools/levelReupload.php(124): PDOStatement->execute(Array) #1 {main} thrown in /home/PKun/public_html/gdbrazilian/database/tools/levelReupload.php on line 124`

or when i deactivate the error reporting this shows up:

`An error has occured.
Error code: error code: 1005`

i am not that smart so yeah (issue #1000 lol)

**Comment by MegaSa1nt** [comment]
error 1005 means gdps ipban from robtop

**Comment by pKunnn** [comment]
> 
oh, thanks, 7m.pl is probably ipbanned i guess?
