### ISSUE TITLE
genMulti makes an sql query per every level

### ISSUE THREAD

**Issue by Cvolton** [Cvolton/GMDprivateServer#1003]
thats dumb it should just use the info fetched by the query in getGJLevels itself

**Comment by MegaSa1nt** [comment]
is my pr good?

**Comment by Cvolton** [comment]
it looks like a good solution to the problem, i'll look at it properly tomorrow

**Comment by Cvolton** [comment]
fixed in pr #1004, thank you @MegaSa1nt
