### ISSUE TITLE
Cant Replace Servers

### ISSUE THREAD

**Issue by IpGa13** [Cvolton/GMDprivateServer#1005]
whenever i search for the base64 strings of boomlings.com i get nothing. i can only replace the plain text

**Comment by CoderQCFromScraatch** [comment]
aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL2RhdGFiYXNl

**Comment by IpGa13** [comment]
i read the wiki, and followed along there, i used http, i did all the b64 stuff. still no luck

**Comment by MegaSa1nt** [comment]
remove "/" at end of link

**Comment by IpGa13** [comment]
> remove "/" at end of link

oh my god you're a lifesaver!
