### ISSUE TITLE
Level download failed

### ISSUE THREAD

**Issue by zkayns** [Cvolton/GMDprivateServer#1009]
I've looked at prior issues concerning this problem, but none of the fixes seemed to work. I've thoroughly checked that all of the URLs in the gdps executable have been changed (base64 encoded ones included) This is the only thing on my GDPS that doesn't work.

**Comment by zkayns** [comment]
I've pinpointed the issue; the level string is empty for every level uploaded. How do I fix this?

**Comment by zkayns** [comment]
data folder was broken🤑🤑🤑🤑🤑🤑🤑🤑🤑🤑fixed

**Comment by NikitaPupy** [comment]
how did you fix that, i have same problem and there is only deleted folder in data
