### ISSUE TITLE
How to recover password?

### ISSUE THREAD

**Issue by OmgRod** [Cvolton/GMDprivateServer#1011]
I made a test account on my GDPS and I forgot my password. Are there any ways to recover it?

**Comment by MegaSa1nt** [comment]
create another account, copy hashed password from new to old and login to old account

**Comment by Myshy-Official** [comment]
Replace the password string in phpmyadmin with "$2y$10$Qbpn4X9.8st6cOCkyu14juA7rNkzYDjBz1/rOqWuvNBcR8bmseHD2" which replaces the password with "12345677" without needing to create a new account

**Comment by 0mgRod** [comment]
Thanks!

**Comment by Xytriza** [comment]
1. Create a new account in game
2. Save the values from the old one
3. Delete old one
4. Transfer the values from the old one to new one (not gjp/password)
5. Done
