### ISSUE TITLE
bug in online levels with wrong starCoins

### ISSUE THREAD

**Issue by MigMatos** [Cvolton/GMDprivateServer#1016]
If an amount greater than 1 or less than 0 is placed in starCoins, online levels will not be able to be displayed in GD due to that incorrect amount (because GD can only interpret 1 as verified coins or 0 as unverified)

Number key: 38

This bug can happen with the `!rate` command

**Comment by MigMatos** [comment]
@MegaSa1nt true but inexperienced guys using the `!rate` command can easily cause this bug

**Comment by MegaSa1nt** [comment]
their problem :trollface:

**Comment by MigMatos** [comment]
ok
