### ISSUE TITLE
Login Failed On Register And Login, Level download failed on any level

### ISSUE THREAD

**Issue by TehDANKESTMemeLord** [Cvolton/GMDprivateServer#102]
So i managed to get a server going on free web hosting area but whenever i try to register it just says Login Failed! Pls help!!!
Also level download failed on any level

**Comment by OfficialJonesy** [comment]
External database access is probably disabled

**Comment by UpriseDragon** [comment]
I have the same problem but external database is enabled

**Comment by pavlukivan** [comment]
check the server log, not enough info

**Comment by EMREOYUN** [comment]
Check to mysql errors on php pages
