### ISSUE TITLE
Replacing base64 breaks exe

### ISSUE THREAD

**Issue by GoodCat123** [Cvolton/GMDprivateServer#1021]
everytime I replace the boomlings base64 line (aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL2RhdGFiYXNl) with my own link (aHR0cHM6Ly9nb29kY2F0cHMuNnRlLm5ldC9kYXRhYmFzZQ==), the game won't run at all.

**Comment by MegaSa1nt** [comment]
your line and robs line have different chars count

**Comment by GoodCat123** [comment]
> your line and robs line have different chars count

yes, I've been trying to fix that and I still can't figure out what to do

**Comment by GoodCat123** [comment]
nevermind, had it set to https:// not http://
