### ISSUE TITLE
Base64 problem

### ISSUE THREAD

**Issue by NikitaPupy** [Cvolton/GMDprivateServer#1024]
Hello, everything good about your app, when i changed normal text links, everything worked fine but with encoded links app says that it will change file size, if i tap okay, gd is not working

**Comment by MegaSa1nt** [comment]
![image](https://github.com/Cvolton/GMDprivateServer/assets/49565695/55e2fe39-3e44-4e26-82de-0505ff0eaaf7)

**Comment by NikitaPupy** [comment]
Thx, i fixed it already

**Comment by NikitaPupy** [comment]
But i cant download any level, it just shows error
