### ISSUE TITLE
Levels are not downloading

### ISSUE THREAD

**Issue by NikitaPupy** [Cvolton/GMDprivateServer#1025]
If i open the game and find any level on server, click on view it says level download failed

**Comment by MegaSa1nt** [comment]
check, if data/levels folder has any files besides filler folder
if no, make sure, that this folder has 777 perms

**Comment by NikitaPupy** [comment]
One sec

**Comment by NikitaPupy** [comment]
How can i give it 777 perms

**Comment by NikitaPupy** [comment]
> check, if data/levels folder has any files besides filler folder if no, make sure, that this folder has 777 perms

How do i change perms

**Comment by Xytriza** [comment]
sudo chmod 777 /path/to/dir
