### ISSUE TITLE
Base64 problem

### ISSUE THREAD

**Issue by Bibou1494** [Cvolton/GMDprivateServer#1027]
Hello, i wanted to try this but the problem when i chnage the base64 thing so first this is my base64 url(the http://www.boomlings.com/)
```
aHR0cDovL2JpYm91MTQ5NC5mcmVlLm5mLw==
```
and when i remove the w==
```
aHR0cDovL2JpYm91MTQ5NC5mcmVlLm5mL
```
and below it's the boomlings base64 vs mine
```
aHR0cDovL2JpYm91MTQ5NC5mcmVlLm5mL
(mine)
aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL3
(boomlings)
```
or 
```
aHR0cDovL2JpYm91MTQ5NC5mcmVlLm5mLw==
(mine)
aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL3
(boomlings)
```
You see?
and i have a problem because the url don't work when i write the issue but it's work soon i think but help please.

**Comment by MegaSa1nt** [comment]
don't remove "w==", replace it with "3"

**Comment by Bibou1494** [comment]
Ok thank's i think
