### ISSUE TITLE
Cant Download Levels

### ISSUE THREAD

**Issue by NikitaPupy** [Cvolton/GMDprivateServer#1029]
I fi download a level it says cant download a level, but publishing and rating works fine

**Comment by Xytriza** [comment]
level doenst exist in /data/levels then

**Comment by NikitaPupy** [comment]
level exists

**Comment by Xytriza** [comment]
then it might be a different issue, i wouldnt know though

also you setup /config/connection.php correct?

**Comment by MegaSa1nt** [comment]
> also you setup /config/connection.php correct?

server works, its 100% set correct
@NikitaPupy, check if level is not unlisted (PMA -> `levels` -> check `unlisted` and `unlisted2` for value, set to 0 if its not)

**Comment by NikitaPupy** [comment]
unlisted and unlisted2 are 0

**Comment by MegaSa1nt** [comment]
> level exists

![image](https://github.com/Cvolton/GMDprivateServer/assets/49565695/1ade6797-1ed2-456e-a797-fd264e9ec0f4)
tf, then it doesnt exist? well, check if data folder has 777 permissions (not in PMA, lol)

**Comment by Xytriza** [comment]
if it doesnt work you can also just redo everything as a last option

**Comment by NikitaPupy** [comment]
Oh, i watched on incorrect page, everything works
