### ISSUE TITLE
Online levels can't be completed in normal mode.

### ISSUE THREAD

**Issue by Gamerexde** [Cvolton/GMDprivateServer#103]
Hi, i have a Geometry Dash server currently on a VPS Server using MariaDB as a Database manager and everything works ok but when i try to complete an online level as soon i complet it it fades to the level menu and it keeps on 0%...

I don't know if this is an error or what but this is strange for me, i guess the online level complete is disabled to prevent a glitch or something :/

Someone?

**Comment by Cvolton** [comment]
Levels with 8 stars and more must be medium at least, this is one of RobTop's anticheat mechanisms.
