### ISSUE TITLE
song is 6.69mb

### ISSUE THREAD

**Issue by Xytriza** [Cvolton/GMDprivateServer#1030]
please give me a solution to fix this stupid thing, i dont want a joke as a song file size i want the real one

**Comment by MegaSa1nt** [comment]
check if song size is not ~6.69mb

**Comment by Xytriza** [comment]
i didnt realize i had to use a proxy sorry lmfao

**Comment by Xytriza** [comment]
> check if song size is not ~6.69mb

also it wasnt at the time

i just had a blacklisted ip on robtop servers
