### ISSUE TITLE
Not possible to save a backup.

### ISSUE THREAD

**Issue by Bibou1494** [Cvolton/GMDprivateServer#1032]
Hi, I have enghout stars for create backup but it's failed and i cannot create a backup. Help me please.

**Comment by Xytriza** [comment]
You're asking for help without giving any context. Please give at least an error log or something to help anybody understand what you mean.

**Comment by Bibou1494** [comment]
I chant save my data on a cloud with the save option

**Comment by MegaSa1nt** [comment]
if you're using 7m.pl, then check if your save data is <1mb size, 7m.pl doesn't support >1mb save size

**Comment by Bibou1494** [comment]
No i use 000webhost

**Comment by Xytriza** [comment]
im still extremely confused, are you not able to save because a certain error, a 500 or what is happening?

**Comment by Bibou1494** [comment]
I have 0 log so i cannot help for that

**Comment by Xytriza** [comment]
Then no help can be provided likely

**Comment by Bibou1494** [comment]
But i never retryed because me pc SSD ded. So i need to make the mobile
client.

**Comment by Bibou1494** [comment]
I dont know how but now its working fine
