### ISSUE TITLE
Levels from the original game in gdps / game crashes when changing server

### ISSUE THREAD

**Issue by Nikita7ggg** [Cvolton/GMDprivateServer#1039]
Hello, I changed the server http://www.boomlings.com on mine, but levels from a regular game appear, I looked through HTTP Canary and saw that many actions were being done on the boomlings server, and not on mine, the solution should have been to replace the server with my own by using base64, but when encrypted, searching and replacing the server, the game starts to crash, what can I do? (sorry for bad English, I'm using a translator)

**Comment by MegaSa1nt** [comment]
Ты совершил какую-то ошибку, перечитай гайд
https://github.com/Cvolton/GMDprivateServer/wiki/Creating-Windows,-Android-and-IOS-Apps#windows

Игра крашится потому что ты заменяешь ссылки с другим количеством символов

**Comment by Nikita7ggg** [comment]
> Ты совершил какую-то ошибку, перечитай гайд https://github.com/Cvolton/GMDprivateServer/wiki/Creating-Windows,-Android-and-IOS-Apps#windows
> 
> Игра крашится потому что ты заменяешь ссылки с другим количеством символов

Да нет, если я заменяю просто текст и hex, то все нормально, адрес у меня из 17 символов (zailoxgdps1.rf.gd) и если не заменять base64 - все работает отлично (в плане клиента), но в этом то и проблема, если не заменять base64 код - игра не крашится, но 99% действий происходят на сервере гд, а если заменять - игра крашится, в туториале не написано про base64, этот способ я взял, когда кто-то задал почти такой же вопрос "у меня в гдпс лвла из обычной гд".

**Comment by MegaSa1nt** [comment]
написано, если у тебя на конце base64 ссылки `w==`, то замени его на `3`

**Comment by Nikita7ggg** [comment]
> написано, если у тебя на конце base64 ссылки `w==`, то замени его на `3`
> 
> Я скоро перепишу текстовые туториалы, чтобы они были более органичными и понятными

Да, я читал туториал, но в в конце ссылки (aHR0cDovL3phaWxveGdkcHMxLnJmLmdkL2RhdGFiYXNl) нету w==, я пытался добавить L3, чтобы было столько же символов, сколько в оригинале, странно ещё то, что я взял из туториал сервер, но игра из-за него вылетала

**Comment by MegaSa1nt** [comment]
в какой папке у тебя находятся файлы приватки?

**Comment by Nikita7ggg** [comment]
> в какой папке у тебя находятся файлы приватки?

site.com/database

**Comment by Nikita7ggg** [comment]
Я нашел решение проблемы (а точнее мою ошибку) 1. Hex editor больше не работает ("нет доступа к файлу" либо "only read file mode") поэтому нужно пользоваться сайтом hexed.it. 2. Нужно писать в графе поиск aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL2, но при этом НЕЛЬЗЯ В ГРАФЕ ЗАМЕНА ПИСАТЬ ЧТО ЛИБО, т.к. он не заменяет как надо. 3. Нужно нажать поиск - значок клавиатуры - вставляем наш сервер (ни одного байта не должно не доставать либо наоборот, ни одного байта не должно быть лишнего) потом жмём "искать дальше" и проделываем так раз ~9, после этого экспорт и готово, спасибо @MegaSa1nt за ответ, туториал помог с вопросом по кол-во байтов
