### ISSUE TITLE
How can I make quests?

### ISSUE THREAD

**Issue by AstroidexAdam** [Cvolton/GMDprivateServer#104]
When i click quests it crashes and says geometry dash stopped working

**Comment by Cvolton** [comment]
insert them manually into the quests table in mysql

**Comment by TechnologyB34R** [comment]
how

**Comment by cro128** [comment]
I do not understand very well how it works

**Comment by pavlukivan** [comment]
the dashboard is in progress, wait for it

**Comment by EndNation** [comment]
Will make a .php for this... The code might not be clean but it should do the trick :)

**Comment by Jecket22** [comment]
Go to your PHPmyAdmin, and go to "quests" in your database.
(https://imgur.com/FMRo5P9)
Then select "Insert"
(https://imgur.com/ADLOpyQ)
Then do something like I do
(https://imgur.com/NkyUz56)
Click on OK.
Then do 3 more. Atleast 4 quests are requiered, else it will crash.
