### ISSUE TITLE
This app cant run on your PC

### ISSUE THREAD

**Issue by LordHuang** [Cvolton/GMDprivateServer#1047]
![Uploading Screenshot_99.png…]()

**Comment by MegaSa1nt** [comment]
Failed linka changing

**Comment by LordHuang** [comment]
> Failed links changing

The link is correct, where's the wrong

**Comment by Kingminer7** [comment]
> > Failed links changing
> 
> The link is correct, where's the wrong

How many characters is your link?

**Comment by LordHuang** [comment]
> > > Failed links changing
> > 
> > 
> > The link is correct, where's the wrong
> 
> How many characters is your link?

6 Characters

**Comment by MegaSa1nt** [comment]
`http:/`?

**Comment by LordHuang** [comment]
> `http:/`?

http://idgdps.rf.gd

**Comment by LordHuang** [comment]
Wait, is this code already support 2.2? I test on gd 2.2

**Comment by LordHuang** [comment]
.
