### ISSUE TITLE
This app cant run on your PC

### ISSUE THREAD

**Issue by LordHuang** [Cvolton/GMDprivateServer#1048]
I have edited all domains "_www.boomlings.com_" to **my own domain**, but still cant run the app.
what is wrong with that?

**Comment by MegaSa1nt** [comment]
your link has different character count

**Comment by LordHuang** [comment]
> your link has different character count

What else?

**Comment by LordHuang** [comment]
I also test using my private network, the server id working. But I cant still open the app

**Comment by MegaSa1nt** [comment]
> > your link has different character count
> 
> What else?

Your link has different character count. That's all. You need to make same characters count for your link

**Comment by LordHuang** [comment]
> > > your link has different character count
> > 
> > 
> > What else?
> 
> Your link has different character count. That's all. You need to make same characters count for your link as robtop's one

So, example: _www.boomlings.com_ had 9 characters
So my link must be 9 characters?

**Comment by MegaSa1nt** [comment]
`www.boomlings.com` is 17 characters.

**Comment by LordHuang** [comment]
> > > your link has different character count
> > 
> > 
> > What else?
> 
> Your link has different character count. That's all. You need to make same characters count for your link as robtop's one

solved, thanks
