### ISSUE TITLE
await 2.11;

### ISSUE THREAD

**Issue by prixyn** [Cvolton/GMDprivateServer#105]
when do you plan on releasing 2.11

**Comment by AnubisTDG** [comment]
I believe that he said it's coming https://github.com/Cvolton/GMDprivateServer/issues/107

**Comment by Cvolton** [comment]
the permsDashboardUpdate branch includes some stuff from 2.11, even though I don't recommend using it yet, since updating it later on will be harder than it usually is, so I'd personally wait until it gets merged with the master branch
