### ISSUE TITLE
Daily/weekly not working

### ISSUE THREAD

**Issue by CustomGameGD** [Cvolton/GMDprivateServer#1052]
pls fix it

**Comment by CustomGameGD** [comment]
![Screenshot 2023-12-27 193150](https://github.com/Cvolton/GMDprivateServer/assets/96931028/9bbfe190-291b-4f13-b143-69bf4615c831)

**Comment by Cvolton** [comment]
do u have a daily set for today...

**Comment by CustomGameGD** [comment]
> do u have a daily set for today...

I did that and waited

**Comment by Ricky360** [comment]
Same issue:(
