### ISSUE TITLE
Connection failed: SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by LordHuang** [Cvolton/GMDprivateServer#1053]
![Screenshot 2023-12-27 213756](https://github.com/Cvolton/GMDprivateServer/assets/153101737/8388576e-f227-4120-9ec5-3bafbdb18077)
when i try using my private network (xampp), the database is work, can connect to my webserver. But when i try on web hosting, its always "connection refused". Idk where wrong.

**Comment by Cvolton** [comment]
config/connection.php is wrong

**Comment by LordHuang** [comment]
> config/connection.php is wrong

solved, thanks
