### ISSUE TITLE
Levels will not display

### ISSUE THREAD

**Issue by imadethisaccountsoicanmakeanissue** [Cvolton/GMDprivateServer#1054]
The levels i upload will not display. Not in recent, not in my uploaded levels, I tried getting to it with comments and that didn't work! I even tried daily/weekly and it only displayed the time left. What am i doing wrong??

**Comment by imadethisaccountsoicanmakeanissue** [comment]
Also, i am hosting the site on windows, so no chmod 777.

**Comment by jmxamongusmodder** [comment]
if this is 2.2 then this will happen.
also did you set your config.php correctly?

**Comment by imadethisaccountsoicanmakeanissue** [comment]
i fixed it by upgrading to better dashboard

**Comment by MegaSa1nt** [comment]
nice
