### ISSUE TITLE
Client doesn't show gauntlets in 2.2

### ISSUE THREAD

**Issue by M336G** [Cvolton/GMDprivateServer#1058]
<img width="579" alt="Screenshot of the database" src="https://github.com/Cvolton/GMDprivateServer/assets/75208577/5c018c96-2e1a-4766-a948-5de55859dbb7">

<img width="1680" alt="Screenshot in-game" src="https://github.com/Cvolton/GMDprivateServer/assets/75208577/3ffcd8cd-1dd1-4ff6-a39b-9b06ee01298b">

**Comment by MegaSa1nt** [comment]
2.2 has bug, when you need at least 1 full page of gauntlets to show it
