### ISSUE TITLE
Mod System doesn't work | 2.11

### ISSUE THREAD

**Issue by DonAlex0** [Cvolton/GMDprivateServer#106]
In database isAdmin it's set to 1, I've tried creating a new account and doesn't work, it says "Failed. Nothing found."

**Comment by Cvolton** [comment]
you need to create a mod role and assign it to the person, I'm moving away form the legacy isAdmin system, currently I don't recommend the "permsDashboardUpdate" branch to be used by anyone who doesn't know what they're doing
