### ISSUE TITLE
Sync Failed (2.2 version)

### ISSUE THREAD

**Issue by Neejik** [Cvolton/GMDprivateServer#1063]
### For some reason I can't load my save data (12 stars) because there's no <id> file in data/accounts
I tried setting 777 perms in the data folder with 'recursive' option and changing `$captchaType` to 0 and 1, but after those tries when saving and then loading there's still no file with my accountID

I'm using 000webhost so data size could not be the issue, all other things in the server works fine (backup too)
Help please
![image](https://github.com/Cvolton/GMDprivateServer/assets/130257833/a8c7876a-9869-4bb8-b3d7-b0c71e77959d)

**Comment by Bibou1494** [comment]
Same problem, some host, but in 2.1

**Comment by Neejik** [comment]
> Same problem, some host, but in 2.1. I think 000webhost doesn't support reciving data with a simple request.

In my old 2.1 server, things were working well, I used to think the problem it may be caused for using another branch but I tried with cvolton's repo and still nothing

**Comment by Neejik** [comment]
@Bibou1494 nevermind was a undefined function issue in `backupGJAccount.php` file from /accounts folder
Here you replace the line 3 with:
```php
if(function_exists("set_time_limit")) set_time_limit(0);
```
Credits to @MegaSa1nt
Also check more fixes of the same kind in #1056

**Comment by Bibou1494** [comment]
Ok thanks for fixing this
