### ISSUE TITLE
Cannot install 2.2 APK

### ISSUE THREAD

**Issue by M336G** [Cvolton/GMDprivateServer#1064]
Hey, so I've followed the guide to create a 2.2 APK for my GDPS, but it seems like it doesn't work for Android 12 and above.

How can I solve this problem?

[The APK I used to create the 2.2 version of my GDPS](https://www.dropbox.com/scl/fi/avlf7bjdef1364icv8m5w/Geometry-Dash-2.2.13.apk?rlkey=9x97zvxw2axsc5wbetsfh2wte&dl=0)

[The APK of my GDPS](https://gmd.pluscraft.fr/downloads/PLUSGDPS%202.2.apk)

![image](https://github.com/Cvolton/GMDprivateServer/assets/75208577/0a44510c-fef4-47eb-aa20-662c91ca342c)

**Comment by MegaSa1nt** [comment]
try using PC and uber-apk-signer
