### ISSUE TITLE
SFX cant download

### ISSUE THREAD

**Issue by Ricky360** [Cvolton/GMDprivateServer#1066]
![orca-image-535796197](https://github.com/Cvolton/GMDprivateServer/assets/78783028/80bd6947-1dac-467b-b2e5-e9b3fabb97f7)
![orca-image--1317643448](https://github.com/Cvolton/GMDprivateServer/assets/78783028/72c41971-7411-4c3c-a8d2-68bb2b8c4b61)

The thing is i cant download the SFX in GDPS idk why :(

**Comment by MegaSa1nt** [comment]
Update SQL to latest version, update `lists` branch to latest version

**Comment by Ricky360** [comment]
I already update the sql but theres no changes

**Comment by MegaSa1nt** [comment]
> I already update the sql but theres no changes

update level then

**Comment by Ricky360** [comment]
How

> > I already update the sql but theres no changes
> 
> update level then

How do i update level? In ftp or what?

**Comment by MegaSa1nt** [comment]
> How do i update level? In ftp or what?

Upload a level with same name in GD
