### ISSUE TITLE
Reuploading Songs turning intro music Library bug

### ISSUE THREAD

**Issue by Ricky360** [Cvolton/GMDprivateServer#1069]
When i sending Music at Song uploader it ended up turn into music library.....i used reupload songs and it is giving me an 8 digit (12804644) just like this.

**Comment by MegaSa1nt** [comment]
> When i sending Music at Song uploader it ended up turn into music library.....i used reupload songs and it is giving me an 8 digit (12804644) just like this.

You probably have last song ID 12804643, unfixable without deleting songs

**Comment by Ricky360** [comment]
> > When i sending Music at Song uploader it ended up turn into music library.....i used reupload songs and it is giving me an 8 digit (12804644) just like this.
> 
> You probably have last song ID 12804643, unfixable without deleting songs

No, my last song ID was 1280670 and when i reupload another song this give me the id (12804644) and when i enter in gd editor its give me error

**Comment by Ricky360** [comment]
No, my last song ID was 1280670 , when i upload another song, it came like that kind of digit and i try to get the song in the gd editor with this id 12804643 it gives error

**Comment by Ricky360** [comment]
How?

**Comment by Ricky360** [comment]
I used this repo in my gdps https://github.com/FamryAmri/GDPS-Song-Uploader/ and i think there is something wrong with the sql or the repo bc of gdps 2.2 repo, and that repo is supported for 2.11 only

**Comment by Ricky360** [comment]
How do i fix this issue?

**Comment by Ricky360** [comment]
https://github.com/FamryAmri/GDPS-Song-Uploader/ i used this repo and it is for 2.11

**Comment by Ricky360** [comment]
I think the problem is in that repo because its outdated

**Comment by Cvolton** [comment]
traditionally the default offset for reuploaded songs has been 5 mil but with the music library introducing 10 mil songs we can't rely on AUTO_INCREMENT handling that anymore, so this is gonna need a solution...
might be easiest to just raise the offset to something like 20 mil for new gdps song reuploads stuff then

**Comment by Ricky360** [comment]
> traditionally the default offset for reuploaded songs has been 5 mil but with the music library introducing 10 mil songs we can't rely on AUTO_INCREMENT handling that anymore, so this is gonna need a solution... might be easiest to just raise the offset to something like 20 mil for new gdps song reuploads stuff then

![Screenshot_20240111-071901~2](https://github.com/Cvolton/GMDprivateServer/assets/78783028/78aa26d2-aff5-462f-9a46-04cef58461b6)

**Comment by Ricky360** [comment]
Just like that?

**Comment by Ricky360** [comment]
> traditionally the default offset for reuploaded songs has been 5 mil but with the music library introducing 10 mil songs we can't rely on AUTO_INCREMENT handling that anymore, so this is gonna need a solution... might be easiest to just raise the offset to something like 20 mil for new gdps song reuploads stuff then

![Screenshot_20240111-072155~2](https://github.com/Cvolton/GMDprivateServer/assets/78783028/6daf58b8-8dbe-40e6-964f-96fda580430e)


Just like this?

**Comment by Ricky360** [comment]
> traditionally the default offset for reuploaded songs has been 5 mil but with the music library introducing 10 mil songs we can't rely on AUTO_INCREMENT handling that anymore, so this is gonna need a solution... might be easiest to just raise the offset to something like 20 mil for new gdps song reuploads stuff then

I did but then still not downloading the music from editor
