### ISSUE TITLE
Custom gauntlets aren't working in 2.2

### ISSUE THREAD

**Issue by M336G** [Cvolton/GMDprivateServer#1070]
In my PC client, I have replaced all those URLs:

https://www.boomlings.com/database/

https://www.geometrydash.com/database/

https://www.boomlings.com/databas/

However, when I click on a gauntlet that I have created on my GDPS, it shows normal GD levels; did I miss an encoded URL or something?

![image](https://github.com/Cvolton/GMDprivateServer/assets/75208577/8c17a770-92fa-44b3-b7a9-02d2a211cb32)

![image](https://github.com/Cvolton/GMDprivateServer/assets/75208577/0a8cfb70-3352-45b5-a2e1-071ad9505ecd)

**Comment by MegaSa1nt** [comment]
You missed one base64 link (`http://www.boomlings.com/database/getGJLevels21.php`)

**Comment by VoomiTo421** [comment]
> You missed one base64 link (`http://www.boomlings.com/database/getGJLevels21.php`)

I did all of that : it still show the gauntlets but when we click any gauntlet it shows "Something went wrong please try again later". (doesn't shows the levels, nothing.)

We got your sql files of GMDPrivateServer.
