### ISSUE TITLE
No diamonds when completing a list

### ISSUE THREAD

**Issue by M336G** [Cvolton/GMDprivateServer#1075]
How can I add a diamond reward to the lists created on my GDPS?

<img width="623" alt="Database" src="https://github.com/Cvolton/GMDprivateServer/assets/75208577/bb044310-94f1-4263-a65a-74f6f8e9500a">

<img width="1148" alt="In-game" src="https://github.com/Cvolton/GMDprivateServer/assets/75208577/3eb36968-8ae0-426f-876a-025ea4332d75">

**Comment by MegaSa1nt** [comment]
#1043 has all lists commands

**Comment by MegaSa1nt** [comment]
I dont see "countForReward" column on your screenshot, you need to have it to get list rated
