### ISSUE TITLE
How to upd from 2.1 to 2.2? 

### ISSUE THREAD

**Issue by Sagerka** [Cvolton/GMDprivateServer#1084]
I update mysql database and files in ftp, but gd didn't loading and tools didn't work

**Comment by MegaSa1nt** [comment]
1. Use https://github.com/MegaSa1nt/GMDprivateServer/tree/lists
2. Be sure you applied latest 4 SQLs in "_updates" folder

**Comment by Sagerka** [comment]
> 1. Use https://github.com/MegaSa1nt/GMDprivateServer/tree/lists
> 2. Be sure you applied latest 4 SQLs in "_updates" folder

now all good but all actions with accounts not working

**Comment by MegaSa1nt** [comment]
try to regenerate gjp2

**Comment by Sagerka** [comment]
> try to regenerate gjp2

How to did this? For example i got this error when try activate account
![Screenshot_2024-02-04-22-45-53-361_ru yandex searchplugin](https://github.com/Cvolton/GMDprivateServer/assets/105643210/24baee85-8bed-44da-8db6-ccb004de5192)

**Comment by MegaSa1nt** [comment]
You have very old version of gdps, try to import all files in "_updates" folder from link above

**Comment by Sagerka** [comment]
> You have very old version of gdps, try to import all files in "_updates" folder from link above

thx. now all working correctly, but new 2.2 lvls and old 2.1 lvls are not uploading
![Sgdps 2 0 Screenshot 2024 02 05 - 16 47 52 94](https://github.com/Cvolton/GMDprivateServer/assets/105643210/57988490-bde3-4cdf-9ea5-ec9e4796f6d7)

**Comment by MegaSa1nt** [comment]
are you sure you have levels data in data/levels?
