### ISSUE TITLE
duplicate leaderboard accounts of same acc

### ISSUE THREAD

**Issue by nojnis** [Cvolton/GMDprivateServer#1086]
So the problem is: there is 2 accounts that are the same account on the leaderboard one with older stats(even clicking other acc leads to regular acc) the user was leaderboard banned then unbanned. running cron didn fix this and idk if it could be anti raid causing this but i dont think so. (gdps is on 2.2 but this happened in 2.1)

**Comment by MegaSa1nt** [comment]
you probably have dublicates in `users` table

**Comment by nojnis** [comment]
i'll check

**Comment by nojnis** [comment]
ok there was... i wonder why i didnt see the duplicate
