### ISSUE TITLE
[2.11] Level upload/download problem

### ISSUE THREAD

**Issue by D4M5** [Cvolton/GMDprivateServer#109]
Cannot upload/download levels. I know this is kind of a beta but i cannot download and upload levels. :/

**Comment by Cvolton** [comment]
care to elaborate?

**Comment by Mystrz** [comment]
Well, i fixed the upload, but when i try to download levels (implemented them fromthe 2.1 database into 2.11), an error is occuring (Level download failed, try again later).

 I also can not get the colored text to work (i have set the mod things to 2 [elder mod] and set the color but it doesn't work)

**Comment by Mystrz** [comment]
ok nevermind with the color

**Comment by EndNation** [comment]
@Mystrz So mods work but not level uploads? Try deleting all levels from the levels table and uploading a new level...
