### ISSUE TITLE
2.2 full support

### ISSUE THREAD

**Issue by Xytrizareal** [Cvolton/GMDprivateServer#1091]
When will 2.2 support come?

**Comment by MegaSa1nt** [comment]
It is in `lists` branch, better use my repository, it has latest fixes and features

**Comment by Xytrizareal** [comment]
What is the branch for your repo

**Comment by MegaSa1nt** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/tree/lists is 2.2 without dashboard
https://github.com/MegaSa1nt/GMDprivateServer/tree/listscopy is 2.2 with dashboard
