### ISSUE TITLE
Actual GD syncs with my GDPS

### ISSUE THREAD

**Issue by GitPullrequest** [Cvolton/GMDprivateServer#1093]
My account on GD syncs with my GDPS. I think it might be the fact that both executables save to the GeometryDash directory in appdata local, but i have no idea how to change it.

**Comment by GitPullrequest** [comment]
To be fair, it's not that bad, I can just log out my GD and my GDPS would be fine. But it will be bad when people will actually play my GDPS.

**Comment by Cvolton** [comment]
rename gd exe to something else
