### ISSUE TITLE
I can't connect the database (hxd editor)

### ISSUE THREAD

**Issue by ILedoff** [Cvolton/GMDprivateServer#1095]
I can't find "http://www.boomlings.com" in the hxd code.
there is "https://www.boomlings.com " but its encoding adds a "==" at the end, which changes the file size and the game does not start at all. Please help me. (I am from Russia and used a translator)
![image](https://github.com/Cvolton/GMDprivateServer/assets/150476436/483a71ca-7441-4d61-8e51-58e5e0aba488)
![i33mage](https://github.com/Cvolton/GMDprivateServer/assets/150476436/01eda4be-fe35-47dd-a596-476157c7550c)
![im33333age](https://github.com/Cvolton/GMDprivateServer/assets/150476436/a9b6a2ae-8b67-40b9-93d6-e0f2a352c30a)

**Comment by MegaSa1nt** [comment]
все обычные ссылки в https, одна base64 ссылка в http

**Comment by ILedoff** [comment]
мне только ее заменять?

> все обычные ссылки в https, одна base64 ссылка в http

**Comment by MegaSa1nt** [comment]
все ссылки заменять

**Comment by ILedoff** [comment]
щас попробую

> все ссылки заменять

**Comment by ILedoff** [comment]
> все ссылки заменять

ура, спасибо!
