### ISSUE TITLE
There are levels in the database and in FileZilla, but they are not visible in the game [RU - EN]

### ISSUE THREAD

**Issue by ILedoff** [Cvolton/GMDprivateServer#1098]
There are levels in the database and in FileZilla, but they are not visible in the game. **The rest of the functions are working. (There are levels in Weekly and daily and you can even play them).**

**I applied the last 4 .sql in phpmyadmin (from _updates)** and overwritten almost all files in FileZilla (except connection.php , commands.php and some tools **because I have manually written codes there**).

![311342803-0bb861e4-c595-440a-ae35-af29ad0591a3](https://github.com/Cvolton/GMDprivateServer/assets/150476436/e64d524b-1dac-497a-a293-5fff2f01ea65)
![311342864-e5cdfda3-ba30-4ff5-b7ec-c3f4a375b42b](https://github.com/Cvolton/GMDprivateServer/assets/150476436/38d246aa-cdac-42ef-ab95-f7c939dd5299)
![311343000-b7c6a81b-4ace-42a7-a15e-3814f301b5d1](https://github.com/Cvolton/GMDprivateServer/assets/150476436/5011a3e9-47eb-415a-8867-d5339f88187a)
![311343076-ff1262bc-3ccc-4642-afda-ec803b95d503](https://github.com/Cvolton/GMDprivateServer/assets/150476436/c7bb58f0-9567-4812-b6c0-27755120b2b8)
![311343198-f383b436-731b-41a7-907b-4d77c660087c](https://github.com/Cvolton/GMDprivateServer/assets/150476436/adf85963-d891-411b-9aad-afa60846e279)

Please help me.

**Comment by GitPullrequest** [comment]
Might be a issue with getGJlevels.php, but check your webserver logs.

**Comment by GitPullrequest** [comment]
Maybe an issue with getGJlevels.php? do check the webserver logs...

**Comment by MegaSa1nt** [comment]
It was old version of the core with errors reporting enabled, issue is fixed
