### ISSUE TITLE
Levels didn't work

### ISSUE THREAD

**Issue by Sagerka** [Cvolton/GMDprivateServer#1100]
![Rar$exa21588 14265 Screenshot 2024 03 17 - 17 20 08 88](https://github.com/Cvolton/GMDprivateServer/assets/105643210/fb631b2a-3455-4716-89bb-4c9bc3553d83)
![Rar$exa21588 14265 Screenshot 2024 03 17 - 17 20 15 27](https://github.com/Cvolton/GMDprivateServer/assets/105643210/36a1f905-6036-47ab-91ef-339d13c658f1)

i update all to 2.2 but levels didn't work. (Delete data/levels folder and delete levels table didnt fix this)

**Comment by MegaSa1nt** [comment]
Make sure you updated SQL to latest version
If you dont know how, contact me on Discord: МегаСвятой#9096

**Comment by Sagerka** [comment]
fixed
