### ISSUE TITLE
Discord and rate

### ISSUE THREAD

**Issue by SkyLandYT2** [Cvolton/GMDprivateServer#1105]
how can I make sure that a message about this is sent to the discord channel when rate the level?

**Comment by MegaSa1nt** [comment]
use ObeyGDBot

**Comment by not733402** [comment]
I FUCKING KNOW

**Comment by Xytrizareal** [comment]
stop commenting on random issues

**Comment by MegaSa1nt** [comment]
use my repo: https://github.com/MegaSa1nt/GMDPrivateServer

**Comment by Xytriza** [comment]
use:

**Comment by Xytriza** [comment]
idk why this issue is still opened lol
