### ISSUE TITLE
The levels associated with online levels are not shown in the tabs

### ISSUE THREAD

**Issue by pavel355** [Cvolton/GMDprivateServer#1110]
I don't see online levels on my private server, just an empty tab, although there are already 4 levels, I even manage to create a pack of levels, but the levels in this pack are still not visible, I can give myself an administrator, but I still don't see the levels. I'm trying to do it on a local machine without hosting via wamp server, all settings from gdps are configured correctly, I'm sure, please help, I want to see my own and others' levels on my local gdps
![image](https://github.com/Cvolton/GMDprivateServer/assets/99824228/06cd23a3-908a-4a32-b943-9cf17a2aff8e)
![image](https://github.com/Cvolton/GMDprivateServer/assets/99824228/79d0e745-ae96-4915-94b8-e1b871f6b53e)

**Comment by Ghoster12154** [comment]
![image](https://github.com/Cvolton/GMDprivateServer/assets/99824228/05b65b14-443a-448d-8381-489da64c917c)

**Comment by Xytriza** [comment]
> I don't see online levels on my private server, just an empty tab, although there are already 4 levels, I even manage to create a pack of levels, but the levels in this pack are still not visible, I can give myself an administrator, but I still don't see the levels. I'm trying to do it on a local machine without hosting via wamp server, all settings from gdps are configured correctly, I'm sure, please help, I want to see my own and others' levels on my local gdps ![image](https://private-user-images.githubusercontent.com/99824228/326421176-06cd23a3-908a-4a32-b943-9cf17a2aff8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDg1NTAsIm5iZiI6MTcxNjc0ODI1MCwicGF0aCI6Ii85OTgyNDIyOC8zMjY0MjExNzYtMDZjZDIzYTMtOTA4YS00YTMyLWI5NDMtOWNmMTdhMmFmZjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE4MzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNzI0M2MzZGRhZTc2MWFjM2YxMTNiN2MxY2MxZTA1MjBmMThiNGYyZjJmMmYxODRjMTVkMjE0NTRmNTg5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wbf6owLAMAv2XkEDte7LnuWZVl1YQpjTn1lu_d0S1Ak) ![image](https://private-user-images.githubusercontent.com/99824228/326421185-79d0e745-ae96-4915-94b8-e1b871f6b53e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDg1NTAsIm5iZiI6MTcxNjc0ODI1MCwicGF0aCI6Ii85OTgyNDIyOC8zMjY0MjExODUtNzlkMGU3NDUtYWU5Ni00OTE1LTk0YjgtZTFiODcxZjZiNTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE4MzA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZDJiZWM0OGYwYjVjZTY3MjQyOTVmMDM5ZDA3NjM4YTU1YjY2ZmEzMmViNTBjODlkN2JjZjUyZTRmZDNiODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pwdtqczhl7PzOpmptK6DASF_ZvvegHV8qnZVGNCC1B0)

1. make sure ur custom gd links are correct
2. make sure you configured config/connection.php and imported database.sql to the database (using mysql or mariadb too)
3. if you arent using nginx or apache, use one of those. i recommend apache for the best support especially for Cvolton's repo
4. give https://github.com/MegaSa1nt/GMDprivateServer/tree/master a try and see if anything changes
5. make sure `/data/` folder has write permissions, like `777`

**Comment by Xytriza** [comment]
also if this is for example on your computer i recommend switching to a hosting provider like NoxiCloud or GDPSFH with dedicated GDPS support & free forever

**Comment by pavel355** [comment]
I ve found a solve
