### ISSUE TITLE
GD Network Requests Not Sending Response

### ISSUE THREAD

**Issue by jdd050** [Cvolton/GMDprivateServer#1117]
I'm making a 2.2 private server on my local PC, and I've setup nginx for both HTTP and HTTPS on localhost. All HTTPS does is return 301 (redirect) to the HTTP content, where the database is. In my access.log, I can see the requests, but it seems that nothing is being sent back when the request is made (hence in-game features aren't working in GD.

Here's a sample of 
- Me clicking on daily chests
- Attempting to register an account
- Me clicking on quests
- Attempting to view the leaderboards

Is this an issue with my nginx config, or is this an issue with the server files?

Edit: I've confirmed that my php configuration in nginx is working correctly and that HTTPS is redirecting correctly outside of GD, but any time I try to request php scripts I downloaded from the repo from GD, it doesn't return anything.

Edit 2: I tried testing with GD 2.1 just to see if anything changes, but I still got the same results. Since 2.1 uses http only, I was able to verify that I got a 200 (success) response when trying to make an account, but the game still indicated that an error occurred while trying to make the account.

![image](https://github.com/user-attachments/assets/fee7468b-79bc-439c-937c-7e8bcb75dd43)

```
127.0.0.1 - - [19/Aug/2024:22:27:05 -0500] "POST /database/databas/getGJRewards.php HTTP/1.1" 301 169 "-" "-"
127.0.0.1 - - [19/Aug/2024:22:27:06 -0500] "POST /database/databas/getGJRewards.php HTTP/1.1" 301 169 "-" "-"
127.0.0.1 - - [19/Aug/2024:22:27:28 -0500] "POST /database/databas/accounts/registerGJAccount.php HTTP/1.1" 301 169 "-" "-"
127.0.0.1 - - [19/Aug/2024:22:27:39 -0500] "POST /database/databas/updateGJUserScore22.php HTTP/1.1" 301 169 "-" "-"
127.0.0.1 - - [19/Aug/2024:22:28:04 -0500] "POST /database/databas/getGJChallenges.php HTTP/1.1" 301 169 "-" "-"
127.0.0.1 - - [19/Aug/2024:22:28:07 -0500] "POST /database/databas/updateGJUserScore22.php HTTP/1.1" 301 169 "-" "-"
127.0.0.1 - - [19/Aug/2024:22:28:08 -0500] "POST /database/databas/updateGJUserScore22.php HTTP/1.1" 301 169 "-" "-"
127.0.0.1 - - [19/Aug/2024:22:28:09 -0500] "POST /database/databas/updateGJUserScore22.php HTTP/1.1" 301 169 "-" "-"
127.0.0.1 - - [19/Aug/2024:22:28:09 -0500] "POST /database/databas/updateGJUserScore22.php HTTP/1.1" 301 169 "-" "-"
```

**Comment by Cvolton** [comment]
gd doesn't follow redirects, so you need to point to http directly if https is just being redirected to there

**Comment by jdd050** [comment]
@Cvolton I see. I've fixed that, then.
```
127.0.0.1 - - [20/Aug/2024:09:16:34 -0500] "POST /database/databas/getGJRewards.php HTTP/1.1" 200 117 "-" "-"
127.0.0.1 - - [20/Aug/2024:09:17:01 -0500] "POST /database/databas/accounts/registerGJAccount.php HTTP/1.1" 200 543 "-" "-"
```

The issue I'm encountering now is with the registerGJAccount script
```
2024/08/20 09:17:01 [error] 6388#26712: *9 FastCGI sent in stderr: "PHP Warning:  Undefined variable $db in C:\nginx\html\database\databas\accounts\registerGJAccount.php on line 21
PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in C:\nginx\html\database\databas\accounts\registerGJAccount.php:21
Stack trace:
#0 {main}
  thrown in C:\nginx\html\database\databas\accounts\registerGJAccount.php on line 21" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "POST /database/databas/accounts/registerGJAccount.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost"
  ```

**Comment by Cvolton** [comment]
`Undefined variable $db` implies incorrect database credentials in `config/database.php`, make sure these are correct then

**Comment by jdd050** [comment]
@Cvolton I managed to fix that issue. I started from scratch and created a entry in my HOSTS file for www.localhost.com so that I don't have to worry about directory stuff in the URL. So far everything is working, including admin perms, except for when I try to load online levels. I get the following error:

```
2024/08/20 23:44:02 [error] 15564#24056: *186 FastCGI sent in stderr: "PHP Warning:  Undefined variable $sugg in C:\nginx\html\database\incl\levels\getGJLevels.php on line 248
PHP Warning:  Undefined variable $sug in C:\nginx\html\database\incl\levels\getGJLevels.php on line 252" while reading response header from upstream, client: 127.0.0.1, server: www.localhost.com, request: "POST /database/getGJLevels21.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.localhost.com"
```

This is the directory it references, `/database/incl/levels/`
![image](https://github.com/user-attachments/assets/6934ecaa-963c-4ccc-af5e-ae8c5d30a500)


I stuck everything in `/database/...` like you did in your old tutorial video from 2015 and that's worked so far, except for this case. Do I need to put a php script that is missing in that folder?

**Comment by jdd050** [comment]
Fixed all issues.
