### ISSUE TITLE
Cannot save 4KB file.

### ISSUE THREAD

**Issue by JumpCatGD** [Cvolton/GMDprivateServer#1130]
![изображение](https://github.com/user-attachments/assets/afc3ce6d-1ff6-42ec-bc43-df59aa34901a)
![изображение](https://github.com/user-attachments/assets/e2d2fd48-e3a1-4213-85d4-df1a2505b09c)

**Comment by Cvolton** [comment]
make sure the server has permissions to write to data/accounts

**Comment by Cvolton** [comment]
though actually this looks like getAccountURL is what's failing in which case a possible fix would depend on your specific hosting setup

**Comment by JumpCatGD** [comment]
![image-2](https://github.com/user-attachments/assets/535af9be-d8b5-439d-9f45-60410b8c02dd)
i did this and now its work
