### ISSUE TITLE
"Event" doesn't work

### ISSUE THREAD

**Issue by TrealDry** [Cvolton/GMDprivateServer#1133]
I noticed that “event” is not working properly (level is not downloading). After a quick check of the responses from the servers (getGJDailyLevel.php) it became clear what was wrong:

Response from private server:
>200001|70815

Response from official server:
>200005|10|G1zXYTUp6c1MPCwgPBgcOCwsCDwoLAB4HCR0JBxkIHQkGGQs=|5e7a23e96b038e1faddf68a6d965f0ec39ef8fe1

I hope for a quick fix. Thanks in advance.

**Comment by MegaSa1nt** [comment]
This core is not updates to 2.207

**Comment by TrealDry** [comment]
> This core is not updated to 2.207

If you have information on what principle is used to generate hashes, can you please share with me?

**Comment by MegaSa1nt** [comment]
My core is updated to 2.207, you can use that :trollface:

**Comment by TrealDry** [comment]
> My core is updated to 2.207, you can use that :trollface:

Thanks for your help!

**Comment by TrealDry** [comment]
jj
