### ISSUE TITLE
LevelString is blank and levels not downloading

### ISSUE THREAD

**Issue by portex7000** [Cvolton/GMDprivateServer#1134]
When i upload a level (both reupload from boomlings.com and making own level and uploading it that way) will upload the level but it won't download (level download failed). When i checked the level in phpMyAdmin, it was there, but the level string (data for the level) was blank

**Comment by Cvolton** [comment]
levelstrings are stored in files in data/levels

**Comment by portex7000** [comment]
Ok, those files are fine and have actual level data n them, but then why do they not download?

**Comment by MegaSa1nt** [comment]
try setting permission 777 to folder `data` recursively
