### ISSUE TITLE
Error while launching the game

### ISSUE THREAD

**Issue by Bibou1494** [Cvolton/GMDprivateServer#1135]
Hi so i wanted to make a 2.11 gdps thing, but the problem is, when i'm launching the game i get an error
![image](https://github.com/user-attachments/assets/ccea1f79-76d5-4cd1-9475-fa1d0476e2e4)
So let me translate because it's in french, so it failed to launch the game because it couldn't find a file called MSVCR100.dll.
So can you please help me with that?
Edit: Note that i was using the Geometry dash from the wiki and it did that even right after downloading

**Comment by MegaSa1nt** [comment]
You need to install Visual C++ Redistributables

**Comment by Bibou1494** [comment]
they are on the folder? well i installed them too

**Comment by Bibou1494** [comment]
So i installed them, but still the exact error

**Comment by Bibou1494** [comment]
Update i fixed it, i forgot about the x86 one but now it work
