### ISSUE TITLE
Level from the official game, Version 2.11

### ISSUE THREAD

**Issue by Bibou1494** [Cvolton/GMDprivateServer#1136]
Hi so i already made an issue about the game not launching 30 minutes ago but i have another problem, when i go to the level editor and then i search for levels, they are levels... From the official server, maybe because i couldn't replace the base64 of http://www.boomlings.com/ to mine because apperently the base64 of the robtop's server doesn't exist, or maybe its something else but i will still try to test things and i will update you if i found something.

**Comment by MegaSa1nt** [comment]
it does exist, you need to replace `http://www.boomlings.com/database`

**Comment by Bibou1494** [comment]
Update: I just want to fix the wiki, because hxd couldn't find the aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL3, because it does not exist in the code, but wha does exist is aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL, yes the same but without the 3

**Comment by Bibou1494** [comment]
> it does exist, you need to replace `http://www.boomlings.com/database`

yes i did that too

**Comment by Bibou1494** [comment]
but now... why not a single one of the levels are showed in the game ?

**Comment by Bibou1494** [comment]
Im closing for now and i will get back later
