### ISSUE TITLE
Can't comment on levels

### ISSUE THREAD

**Issue by AnubisTDG** [Cvolton/GMDprivateServer#117]
Okay, so whenever I comment on a level, it doesn't show up. I think this might have something to do with the new roles system, because I created a test account (I called it 'RobTop'. Isn't that halarious?) and uploaded a level through it. When I commented with that account, it worked fine, but when I commented on it with my account, _all_ the comments disappeared, but they were still showing up in the database. So I tried removing my role, and the comments were able to show up again. I don't know if it's because I set something up wrong or if it's just because it's still in beta, but if you could please help me I would appreciate it a lot. Thanks!

**Comment by Cvolton** [comment]
you probably set the "commentColor" variable wrong, what did you put there?

**Comment by AnubisTDG** [comment]
@Cvolton I put an RGB color code in there. That's what your supposed to do, yes?

**Comment by Cvolton** [comment]
see the latest comment in #118
