### ISSUE TITLE
Suggestion: Instant Rate Permission

### ISSUE THREAD

**Issue by ghost** [Cvolton/GMDprivateServer#122]
How about we make rating levels into a seperate permission and make like a table for ppl who send levels and someone checks them then rates the level? that would be cool af

**Comment by Cvolton** [comment]
I'm probably going to implement this. One way to do this would be making actionRateLevel a level type permission, so setting it to 1 would only add the level to a list, while having it set to 2 would cause the level to get rated immediately

**Comment by EndNation** [comment]
Is this feature added?

**Comment by EndNation** [comment]
Oh how much I hate this but I managed to remove it lel :)

**Comment by EndNation** [comment]
I mean I made this in a way lel

**Comment by Cvolton** [comment]
resolved by #461
