### ISSUE TITLE
Something went wrong. (GDPS 2.11)

### ISSUE THREAD

**Issue by TehDANKESTMemeLord** [Cvolton/GMDprivateServer#128]
Well uhhh i made a gdps in 2.11 and uhhh yeah when i tried to register it just said "Something went wrong."
Please help! i think this is because im on 2.112 but i dont know!

**Comment by AnubisTDG** [comment]
Did you edit connection.php?

**Comment by TehDANKESTMemeLord** [comment]
Yes i edited connection.php

**Comment by KadePcGames** [comment]
Are you sure you did the base64 encode. Did you check the file perms. Are you 100% That Your Domain Is As Long As http://www.boomlings.com

**Comment by TehDANKESTMemeLord** [comment]
yes i did the base 64enode and yes im 100000000% sure that my domain is as long as http://www.boomlings.com

**Comment by TehDANKESTMemeLord** [comment]
also im using free web hosting area so that might also be the problem but i dont really know

**Comment by TehDANKESTMemeLord** [comment]
Alright so IT IS NOT because of 2.112 i tried with 2.11 and still Something went wrong...

**Comment by KadePcGames** [comment]
https://github.com/KadePcGames/KadesGDPS-2.13 Use this guide and yes that dosent work iv tried it

**Comment by TehDANKESTMemeLord** [comment]
uhhh...thanks ill try it

**Comment by TehDANKESTMemeLord** [comment]
I did literally everything that it asked me to do and still Something went wrong..... Then i tried AlterVista for the gdps and uhhhh when i got onto importing the database part it just said an error
I'm gonna try another host i guess.

**Comment by TehDANKESTMemeLord** [comment]
Anyone have a recommendation for a host that i could use? Or maybe this is some kind of bug. I don't really know leave me a host i could use tho

**Comment by TehDANKESTMemeLord** [comment]
I give up. I've tried over and over and over and over and over and over AGAIN! I am done! I can not create a GDPS anymore. This only started happening when I made the 2.11 GDPS. Before that it was fine. I don't know what happened but i just can't fix it. I've tried searching and searching. Literally no one else has this issue. I am confused...

**Comment by OfficialJonesy** [comment]
the php files are not inserting to the db, same is happening with me :|

**Comment by EndNation** [comment]
@TehDANKESTMemeLord You can still host your own website using WampServer... Thats what I did at least

**Comment by EndNation** [comment]
@TehDANKESTMemeLord Btw I can probably send you a .exe, just tell me your website :)
