### ISSUE TITLE
When trying to play 6* - 10*

### ISSUE THREAD

**Issue by prixyn** [Cvolton/GMDprivateServer#129]
/title
It just kicks me out of the level, is there any way to fix this?
or is that just robtop's anticheat.

also demon rate stopped working, permission is enabled definitely though

**Comment by AnubisTDG** [comment]
It's an anticheat thing. The level length must be at least medium. If not, it will kick you out of the level.

**Comment by prixyn** [comment]
ah, understood thanks!
