### ISSUE TITLE
Alright....

### ISSUE THREAD

**Issue by KadePcGames** [Cvolton/GMDprivateServer#130]
So the new database add nothing. Still have the same problem. But i can comment on my profile as me with blue text. So its hex-edited correctly 
GDPS name: KadesGDPS 2.13
Domain: KadesGDPSdatabasegdps.tk
discord: https://discord.gg/qds2EyJ
Update:
I also dont have the roles table in my database

**Comment by DonAlex0** [comment]
Download the permsDashboardUpdate branch

**Comment by KadePcGames** [comment]
okieeeee

**Comment by KadePcGames** [comment]
Okay im done. It works :D
