### ISSUE TITLE
Level download failed...

### ISSUE THREAD

**Issue by OfficialJonesy** [Cvolton/GMDprivateServer#139]
^

master branch
Stuff is inserted into the database and everything

**Comment by Cvolton** [comment]
does the level have a file in data/levels? If not, you need to change permissions of the data folder to 777 (allow everyone to read/write/execute)

**Comment by OfficialJonesy** [comment]
I have already changed the permissions :P still no luck...
There is ONE file with an ID, but it is empty.

**Comment by OfficialJonesy** [comment]
Works all of a sudden... weird...
