### ISSUE TITLE
How to Update my server to 2.113?

### ISSUE THREAD

**Issue by UpriseDragon** [Cvolton/GMDprivateServer#141]
How to update my own server to 2.113 without losing everything? Im hosting with altervista since two months and i was wondering how to update the server without losing progress, thanks.

**Comment by EndNation** [comment]
I think you can export the database, and save the data folders and the exported database and replace everything else... I dont know and have not tried yet...

**Comment by Cvolton** [comment]
in case someone is looking at this issue years later, the updating process is now explained in `_updates/README.md`
