### ISSUE TITLE
Cant register account "something went wrong"

### ISSUE THREAD

**Issue by UpriseDragon** [Cvolton/GMDprivateServer#142]

**Comment by OfficialJonesy** [comment]
try dropping all the tables and re-importing the sql file, also, have you edited your connection.php

**Comment by UpriseDragon** [comment]
it wont work. Btw yea i edited connection.php

**Comment by OfficialJonesy** [comment]
what branch?

**Comment by UpriseDragon** [comment]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1364 Field 'rateDate' doesn't have a default value' in /membri/gmdragon5/database/tools/levelReupload.php:124 Stack trace: #0 /membri/gmdragon5/database/tools/levelReupload.php(124): PDOStatement->execute(Array) #1 {main} thrown in /membri/gmdragon5/database/tools/levelReupload.php on line 124

**Comment by UpriseDragon** [comment]
btw the branch you mean the server "version"? if that its permsDashboardUpdate

**Comment by OfficialJonesy** [comment]
Can say then, i cant use the permsDashboardUpdate branch because its completely broken for me

**Comment by UpriseDragon** [comment]
I guess it needs to be fixed at all

**Comment by Cvolton** [comment]
this issue should be fixed in 01fd42db4b82b86784d6104956713602d1a08f0f
