### ISSUE TITLE
permsDashboardUpdate branch is completely broken...

### ISSUE THREAD

**Issue by OfficialJonesy** [Cvolton/GMDprivateServer#143]
^

Nothing works, no output or anything.
Nothing going into the database
Database structure is correct though

**Comment by Cvolton** [comment]
Are you sure you just don't have error reporting disabled in PHP settings?

**Comment by OfficialJonesy** [comment]
That'd show like database connection errors right? if so, its enabled

**Comment by Cvolton** [comment]
send me a link to your gdps, so I can have a look at it

**Comment by OfficialJonesy** [comment]
I sorta deleted that one... But i will recreate it

**Comment by OfficialJonesy** [comment]
Oh btw, when files would usually echo like -1, it outputs absolutely nothing

**Comment by OfficialJonesy** [comment]
Ok npow stuff outputs but nothing goes into the database -_-

http://a.phoenixmc.co.uk/database/

**Comment by Cvolton** [comment]
this seriously looks like a PHP error is happening, the database connection error can show even with error reporting disabled, but this one can't, please enable error reporting or check your PHP/webserver log for the error

(also unrelated, but I'd recommend you to find a way to disable access to the data folder from the web, there's a .htaccess file for that included, but that won't work for you, since you're using IIS)

**Comment by OfficialJonesy** [comment]
Level reupload for example, instead of saying for example level reuploaded, or any error, just goes blank

**Comment by Cvolton** [comment]
yes, I've noticed, however when it outputs nothing, it means an error has happened before it even got to output anything, so that means that you have error reporting disabled

**Comment by OfficialJonesy** [comment]
Can you tell me how to enable it pls, Ubuntu 16.04

**Comment by OfficialJonesy** [comment]
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

**Comment by Cvolton** [comment]
can you just check the errors log? (/var/log/apache2/error.log for apache)

**Comment by OfficialJonesy** [comment]
found it,



Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'rateDate' doesn't have a default value in /var/www/html/database/tools/levelReupload.php:124 Stack trace: #0 /var/www/html/database/tools/levelReupload.php(124): PDOStatement->execute(Array) #1 {main} thrown in /var/www/html/database/tools/levelReupload.php on line 124

**Comment by Cvolton** [comment]
that's an issue that should be solved in 01fd42db4b82b86784d6104956713602d1a08f0f, can you try to recreate the server with the latest version?

**Comment by OfficialJonesy** [comment]
Actually I just fixed it xD,  changed the default value in the levels table to NULL

**Comment by Cvolton** [comment]
that's exactly what I did in the commit

**Comment by OfficialJonesy** [comment]
ohim retarded xdsorry

**Comment by OfficialJonesy** [comment]
Now whenever I do something...


Something went wrong...

**Comment by Cvolton** [comment]
its not just that value in the levels table, there are more values requiring changes and there are possibly more updates, if this is a new server, I'd just recommend you to delete the current one and start over with the current up to date version

**Comment by OfficialJonesy** [comment]
ok I shall :P

**Comment by OfficialJonesy** [comment]
Update to latest, still throws an error....

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ORDER BY userName ASC' at line 1 in /var/www/html/premium1/dashboard/stats/modActions.php:14 Stack trace: #0 /var/www/html/premium1/dashboard/stats/modActions.php(14): PDOStatement->execute() #1 {main} thrown in /var/www/html/premium1/dashboard/stats

**Comment by Cvolton** [comment]
modActions.php is currently supposed to throw this error when no accounts with the "toolModactions" permission are found (I'll add a more helpful error message later)

**Comment by OfficialJonesy** [comment]
oh ok

**Comment by OfficialJonesy** [comment]
there is only one problem now, req doesnt work, just loads forever
