### ISSUE TITLE
Change password error

### ISSUE THREAD

**Issue by UpriseDragon** [Cvolton/GMDprivateServer#148]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'salt' cannot be null' in /membri/gmdragon5/database/tools/account/changePassword.php:43 Stack trace: #0 /membri/gmdragon5/database/tools/account/changePassword.php(43): PDOStatement->execute(Array) #1 {main} thrown in /membri/gmdragon5/database/tools/account/changePassword.php on line 43

**Comment by EMREOYUN** [comment]
Is this linux host?
And "salt" column is null after work in MySQL
What is "salt" @Cvolton ?

**Comment by EMREOYUN** [comment]
Notice: Undefined variable: salt in C:\xampp\htdocs\database\tools\account\changePassword.php on line 43
In windows Hosting via Xampp

**Comment by EMREOYUN** [comment]
After i delete salt column in this php,
Password change is being unable.
Php needs salt but what is it?

**Comment by EMREOYUN** [comment]
[PROBLEM SOLVED]
Salt column does nothing, it also changes password. We need remove salt in php or nevermind salt error.
It works fine.

**Comment by EMREOYUN** [comment]
Getting errors but it changes your password.
If you get error, try with your new password to login
