### ISSUE TITLE
Cron not working

### ISSUE THREAD

**Issue by UpriseDragon** [Cvolton/GMDprivateServer#151]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1' in /membri/gmdragon5/database/tools/cron/fixcps.php:124 Stack trace: #0 /membri/gmdragon5/database/tools/cron/fixcps.php(124): PDOStatement->execute() #1 /membri/gmdragon5/database/tools/cron/cron.php(4): include('/membri/gmdrago...') #2 {main} thrown in /membri/gmdragon5/database/tools/cron/fixcps.php on line 124

**Comment by Cvolton** [comment]
that shouldn't be a ground breaking error, I need to add a warning instead of that error though

**Comment by EndNation** [comment]
@UpriseDragon Other than that any errors?

**Comment by Cvolton** [comment]
definitely fixed by this point
