### ISSUE TITLE
not working saving account

### ISSUE THREAD

**Issue by PhoneGuy1** [Cvolton/GMDprivateServer#155]
not working saving account

**Comment by EMREOYUN** [comment]
Saving account is working but it's crashs server (on my server)
If you need disable account saving; go your database and enter /accounts/backupGJAccount.php
Set this;
<?php
	echo -1;
>
It disables cloud save.
But if you need cloud save and doesn't work; it's over for me!

**Comment by EMREOYUN** [comment]
php removed on Set this; :(
It's
?php
	echo -1;
You need close <> them.

**Comment by EMREOYUN** [comment]
#156 look here

**Comment by Cvolton** [comment]
no constructive discussion in almost 3 years, closing
