### ISSUE TITLE
don't save accounts in /data/accounts

### ISSUE THREAD

**Issue by PhoneGuy1** [Cvolton/GMDprivateServer#156]

**Comment by cro128** [comment]
The same happens to me

**Comment by Cvolton** [comment]
is there a reason you suggest this? It is recommended that you disable external access to that folder obviously (which is done by default if you use Apache)

**Comment by EMREOYUN** [comment]
umm... did you set cloud save encryption to "1" in /database/config/security.php ?

**Comment by cro128** [comment]
EMREOYUN
I have it in 0 and it still does not work
Should I have it in 1?

**Comment by EMREOYUN** [comment]
It can work also in older versions

**Comment by Cvolton** [comment]
no constructive discussion in almost 3 years, closing
