### ISSUE TITLE
I can't register an account or download any online levels

### ISSUE THREAD

**Issue by Ohdeymus** [Cvolton/GMDprivateServer#157]
I have followed the tutorial and the server works fine. I can make and upload levels. But when I try to register for an account, it just says "Login Failed". Also when I try to play any uploaded levels, it says "Level download failed. Please try again later". I really don't know what to do. Please help

**Comment by EndNation** [comment]
uhm... is your port forwarded if you are hosting it?

**Comment by Cvolton** [comment]
no constructive discussion in almost 3 years, closing
