### ISSUE TITLE
How to be RobTop?

### ISSUE THREAD

**Issue by UpriseDragon** [Cvolton/GMDprivateServer#161]
I cant "be robtop" even if i put the right ID, i dont have the blue text

**Comment by Cvolton** [comment]
make sure you're changing the accountID to 71, not the userID

**Comment by UpriseDragon** [comment]
not the extID too?

**Comment by UpriseDragon** [comment]
it says something went wrong

**Comment by AnubisTDG** [comment]
Just sign out and sign back in again

**Comment by UpriseDragon** [comment]
how to get back data if my old accID was 2?

**Comment by AnubisTDG** [comment]
Just use hacks to get it back? It's a private server, it's not like you're gonna get in trouble for it or anything.

**Comment by Cvolton** [comment]
if you have a cloud save, rename the file in /data/accounts and load

**Comment by UpriseDragon** [comment]
Thanks

**Comment by EMREOYUN** [comment]
Please close all threat it it's fixed.
Thanks.

**Comment by pavlukivan** [comment]
@Cvolton run `ExitThread();` when

**Comment by EMREOYUN** [comment]
ExitThread();

**Comment by EMREOYUN** [comment]
Lel tried :(
