### ISSUE TITLE
Suggestion: Have Delete/Manage Levels permission

### ISSUE THREAD

**Issue by AnubisTDG** [Cvolton/GMDprivateServer#162]
I just thought that I would throw in a suggestion, where users with a "Manage Levels" permission can override level copy passcodes/restrictions and delete levels regardless of whether or not they're the level creator. That would be pretty cool tbh.

**Comment by Cvolton** [comment]
There is a modip permission, where one of the things it does is enabling level copying. As for deleting levels, there is no way for me to show the delete button other than tricking the game into thinking that you made the level, which isn't a thing I really want to do. You can use the !delete command though

**Comment by AnubisTDG** [comment]
Ah okay. Thanks!
