### ISSUE TITLE
cant register/login or play online levels

### ISSUE THREAD

**Issue by brownbeardaboss** [Cvolton/GMDprivateServer#172]
cant register/login or play online levels
connection.php is perfectly fine

**Comment by brownbeardaboss** [comment]
please help

**Comment by EMREOYUN** [comment]
Please look your https for musql errors and write them.

**Comment by EMREOYUN** [comment]
Mysql*

**Comment by EndNation** [comment]
@brownbeardaboss First question, goto online levels and press search, what do you see :)
