### ISSUE TITLE
Administrator of all comments

### ISSUE THREAD

**Issue by fakemancat** [Cvolton/GMDprivateServer#179]
I'm good at this core, and I know which file is responsible for that. I'm wondering if it's possible to make a player with accountID = 1 can delete any comments under any levels?
Sorry for my english, i'm from Russia :D

**Comment by Cvolton** [comment]
this is a currently unimplemented low priority feature, so it's not possible yet, when it's implemented, it'll have its own permission just like everything else

**Comment by fakemancat** [comment]
thx
