### ISSUE TITLE
Good host to use other than FWHA

### ISSUE THREAD

**Issue by Strikerrr** [Cvolton/GMDprivateServer#183]
And can someone provide some sort of tutorial I can follow? Thanks :D

**Comment by EMREOYUN** [comment]
Altervista :)
Of course not
I'll using batihost.com
But this hosting was paid.

**Comment by EndNation** [comment]
Im hosting the server on my own network... So yeah :)

**Comment by EMREOYUN** [comment]
It can hostable on home network but only can people connected your network only can connect to server

**Comment by Strikerrr** [comment]
@EMREOYUN would portforwarding be an option tho?

**Comment by EMREOYUN** [comment]
If your internet provider allows open ports, why not?
Forward port 80.

**Comment by EMREOYUN** [comment]
My home provider doesn't. But my server supports without forward :)

**Comment by EndNation** [comment]
@EMREOYUN Actually anyone can connect as long as you have an open port :)

**Comment by EndNation** [comment]
@Strikerrr Just remember to use maybe noip to mask your ip address :)

**Comment by Cvolton** [comment]
actually there are certain ISPs that don't allow port 80 and some ISPs don't allow port forwarding at all (multiple households usually share the same IP with these)

**Comment by EMREOYUN** [comment]
Exactly my ips :D

**Comment by EMREOYUN** [comment]
*Home ips*

**Comment by EMREOYUN** [comment]
*isp* i hate that keyboard
