### ISSUE TITLE
Quests Crash My Game

### ISSUE THREAD

**Issue by ZXNI** [Cvolton/GMDprivateServer#190]
When i click on quests in my gdps it crashes the game.. i see others fix it but i dont know how? could someone give me the code to fix it and how to do it?

**Comment by Jouca** [comment]
Me too does it to me strangely and I can not put them, could you help me for ID?

**Comment by EMREOYUN** [comment]
While we learn quests id, we make quests.
Do not add quests while we found ids

**Comment by Cvolton** [comment]
quest id is a thing that the database system uses to distinguish between them, it's assigned automatically if you don't fill it in

**Comment by fakemancat** [comment]
!sharecp (player nick)

**Comment by Jouca** [comment]
Ok but next ? xd
![image](https://user-images.githubusercontent.com/25087475/35824280-ac10570e-0ab2-11e8-9076-15a220f5c239.png)

**Comment by EMREOYUN** [comment]
This IDs arw working?
And dont forget writing names

**Comment by fakemancat** [comment]
![image](https://user-images.githubusercontent.com/33839807/35924192-29f84c16-0c44-11e8-93c4-7f422aebd3d7.png)

**Comment by EMREOYUN** [comment]
fakemancat we need quests id, not level packs

**Comment by Jouca** [comment]
I found !
Insert the table without the need to write something and it will give you the ID directly
![image](https://user-images.githubusercontent.com/25087475/35993543-f6121baa-0d0d-11e8-90db-ac4b17eb29aa.png)

Now follow what I'm going to explain :

Type = The type of what you need to receive your reward (1=orbs   2=diamonds   3=stars or coins)
Amount = The amount of what you will need to have
Reward = The number of diamonds you will receive by finishing the quest
Name = The name of the quest

And you can do it several times to have mixed quests :)
![image](https://user-images.githubusercontent.com/25087475/35993844-dfcad85e-0d0e-11e8-8c01-ece405c63c46.png)


Thank CVolton to help ^^

**Comment by EMREOYUN** [comment]
Alright now we need full list of quests id's

**Comment by Cvolton** [comment]
you dont have to fill in a quest id, in fact gd doesnt use quest ids at all, i just had to make quests have ids because MySQL requires that

**Comment by EndNation** [comment]
If quests crashes, did you download the correct server files?

**Comment by EMREOYUN** [comment]
@Cvolton yes works

**Comment by JeffreyRandom** [comment]
@Jouca it is really like this:
Type = The type of what you need to receive your reward (1=orbs 2=coins 3=stars)

I just wanna say that
