### ISSUE TITLE
Cannot Complete Levels

### ISSUE THREAD

**Issue by EndNation** [Cvolton/GMDprivateServer#191]
Hey guys there is a few problems, one of them is that I do not have the roles table in the database and secondly I get kicked out whenever I am trying to beat a level that is hard difficulty and above... Please help :)

**Comment by EndNation** [comment]
Nvm I fixed it :)

**Comment by bengris32** [comment]
How?

**Comment by UpriseDragon** [comment]
The lvl was too short and rated
