### ISSUE TITLE
Cannot complete levels

### ISSUE THREAD

**Issue by EndNation** [Cvolton/GMDprivateServer#192]
Ok never mind, the levels that are difficulty of hard and above cannot be completed but can be verified. When we reach 100%, it just kicks us

**Comment by Jouca** [comment]
This is a cause of the length of the level, it must be above short to be able to complete it

**Comment by EndNation** [comment]
Ok I will try it :)

**Comment by EndNation** [comment]
Thanks man it works ! :)
