### ISSUE TITLE
Banning Songs and Chests not giving anything

### ISSUE THREAD

**Issue by EndNation** [Cvolton/GMDprivateServer#193]
How can I ban songs from Newgrounds? Like not allow players to use certain songs

**Comment by EndNation** [comment]
Btw my chests are not giving anything too :(

**Comment by EMREOYUN** [comment]
Idk how to ban songs
Check your chest rewards.
If chest rewards is bigger than game limits
Chests doesnt work

**Comment by EndNation** [comment]
@EMREOYUN Whats the game limit?

**Comment by EndNation** [comment]
I know how to ban songs already :)

**Comment by EndNation** [comment]
Alright should be good :)

**Comment by EMREOYUN** [comment]
Ill using 5k diamonds and orbs maximum and giving reward. If doesnt work, do 500 diamonds.
Set shards and keys to 5 max
