### ISSUE TITLE
Server problem

### ISSUE THREAD

**Issue by dexie69** [Cvolton/GMDprivateServer#200]
I can't register an account (Something went wrong) , I cant play online levels (Download failed) , I edited the exe according to the steps perfectly.Please give me a fix asap

**Comment by hiperion14** [comment]
wipe the server and put the archives and download the last version.

because it works perfectly for me

**Comment by EndNation** [comment]
Nope u did not hex it properly, have u change the base64-encoded

**Comment by Cvolton** [comment]
issue never followed up by the original creator, closed
