### ISSUE TITLE
how to remove the moderator button

### ISSUE THREAD

**Issue by fakemancat** [Cvolton/GMDprivateServer#203]
how to remove the moderator button
![image](https://user-images.githubusercontent.com/33839807/36595530-4cceefec-18c4-11e8-8c5e-3d04728ddd8d.png)

**Comment by Priswall** [comment]
Well, one way is to not give people admin, another is to remove the texture in the game files (paint it white or black {i cant remember which}, not delete it), and a third option is to edit the code through the editor used to make the game and remove it from there. I personally would choose the first option. It's much easier

**Comment by Cvolton** [comment]
mod button now disappears properly for unmodded people as per a89d82eaf89be8bbcf7c2ea88a0463a9bcac2cb0
