### ISSUE TITLE
Can't create an account, but can play levels

### ISSUE THREAD

**Issue by Priswall** [Cvolton/GMDprivateServer#204]
I posted an issue before about not being able to play levels, but I have fixed that by chmodding all the files to have all privileges. The only problem that persists is that I can't create an account. It doesn't say that an error occurred, just that the login failed. My GD version is 2.0, if you need to know that to help me find a solution.

**Comment by EMREOYUN** [comment]
Check /lib/connection.php

**Comment by Priswall** [comment]
What am I looking for?
The code looks like this, I haven't touched it at all

`<?php
//error_reporting(0);
include dirname(__FILE__)."/../../config/connection.php";
@header('Content-Type: text/html; charset=utf-8');
try {
    $db = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password, array(
    PDO::ATTR_PERSISTENT => true
));
    // set the PDO error mode to exception
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    }
catch(PDOException $e)
    {
    echo "Connection failed: " . $e->getMessage();
    }
?>`

**Comment by Priswall** [comment]
Also, the error I get is "login failed", if that helps

**Comment by EMREOYUN** [comment]
Sorry wrong file
Send there /config/connection.php

**Comment by Priswall** [comment]
I changed it to fit my database, and I can play the levels me and my friends make, but when I want an account then it decides to stop working. The $username and $dbname are the same, $servername is "localhost", and the password is the same as the database password.

**Comment by EMREOYUN** [comment]
Did you set datatable name

**Comment by Priswall** [comment]
What do you mean? How would I do that?

**Comment by EMREOYUN** [comment]
Can you send /config/connection.php and send screenshot of your database?

**Comment by Priswall** [comment]
`<?php
$servername = "localhost";
$username = "1320499";
$password = "coolio333";
$dbname = "1320499";
?>`

![screenshot 2018-03-04 at 6 57 50 pm](https://user-images.githubusercontent.com/31701242/36952871-1b7be302-1fe3-11e8-8a73-e641af73380b.png)

**Comment by EMREOYUN** [comment]
Please send users list

**Comment by EMREOYUN** [comment]
Or did you created 1320499 user with coolio333 password?

**Comment by Priswall** [comment]
Well, I don't normally give out passwords and info like that, but yes. I did make a server that was named 1320499 and coolio333 is the password.

**Comment by EMREOYUN** [comment]
Okay now open /tools/account/changePassword.php in your web browser.
Did you get any mysql errors? If give, what is error?

**Comment by EMREOYUN** [comment]
IMPORTANT: USE WEB BROWSER, DON'T COPY THE CODE!
Mysql error shows up on page.
And looks like: Mysql Error: blablabla...
Or: Database Error: blablabla...
Maybe made a screenshot and send

**Comment by Priswall** [comment]
It seems to be working just fine...

![screenshot 2018-03-05 at 7 22 57 pm](https://user-images.githubusercontent.com/31701242/37007305-a8375e1c-20aa-11e8-915e-30fe32e90393.png)

**Comment by EMREOYUN** [comment]
Hmm... You need recompile Geometry Dash. Maybe you forgot changing something...

**Comment by DonAlex0** [comment]
This Geometry Dash Private Server doesn't totally work with versions below 2.1, you'd need to modify the server files.

**Comment by Priswall** [comment]
@DonAlex0 In what way do I need to modify the files? Do I need to Rename the [insertFileNameHere]20.php to [sameFileNameHere].php?

**Comment by DonAlex0** [comment]
@Priswall No, you would need to see what's difference between 2.0 and 2.1 connections and then delete 2.1 parts or whatever

_Sent from my T5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by EMREOYUN** [comment]
Ahh i see, you are using 2.0
You need old server files.

**Comment by Cvolton** [comment]
I'm trying to keep backwards compatibility where possible, so 2.0 should work with the up to date version

**Comment by fancythedeveloper** [comment]
Still doesn't work, I think

**Comment by fancythedeveloper** [comment]
But this time, I do get an error

**Comment by EMREOYUN** [comment]
> But this time, I do get an error

What error?

**Comment by fancythedeveloper** [comment]
Sorry for the long wait, anyways it's this.

`Notice: Undefined index: userName in /var/www/vhosts/fancyps.5v.pl/httpdocs/database/tools/account/changePassword.php on line 11

Notice: Undefined index: oldpassword in /var/www/vhosts/fancyps.5v.pl/httpdocs/database/tools/account/changePassword.php on line 12

Notice: Undefined index: newpassword in /var/www/vhosts/fancyps.5v.pl/httpdocs/database/tools/account/changePassword.php on line 13`

**Comment by EMREOYUN** [comment]
> Sorry for the long wait, anyways it's this.
> 
> `Notice: Undefined index: userName in /var/www/vhosts/fancyps.5v.pl/httpdocs/database/tools/account/changePassword.php on line 11
> 
> Notice: Undefined index: oldpassword in /var/www/vhosts/fancyps.5v.pl/httpdocs/database/tools/account/changePassword.php on line 12
> 
> Notice: Undefined index: newpassword in /var/www/vhosts/fancyps.5v.pl/httpdocs/database/tools/account/changePassword.php on line 13`

Is your code corrupted or sending a null request without filling blanks?

Code Corrupted: Redownload the file from this code.

Null Request: Fill blanks and test it again.
