### ISSUE TITLE
A few questions....

### ISSUE THREAD

**Issue by Priswall** [Cvolton/GMDprivateServer#205]
1) ~~Is there a way to remove the free 100 likes and 300 downloads for a level and/or reduce the number a bit?~~ I figured it out by exploring the phpMyAdmin

2) What web hosting service would you recommend for hosting a database?

3) What inspired you to make this?

**Comment by EMREOYUN** [comment]
2- Ill using batihost.com(paid)

**Comment by Priswall** [comment]
Anything free?

**Comment by EMREOYUN** [comment]
IDK

**Comment by EndNation** [comment]
@Priswall host it on ur own desktop... its free

**Comment by Jecket22** [comment]
2. 7m.pl, that is my recommendation!
3. I think he just done "his" gdps, after IAT quitted developing GDPS'es.

**Comment by Cvolton** [comment]
actually IAD's GDPS was based on mine

**Comment by EMREOYUN** [comment]
After 5 months xd @Priswall
