### ISSUE TITLE
.

### ISSUE THREAD

**Issue by UpriseDragon** [Cvolton/GMDprivateServer#207]

**Comment by EMREOYUN** [comment]
@Cvolton , couild i help translating in Turkish?

**Comment by Priswall** [comment]
@Cvolton , could i help translating in english?

**Comment by MrZaxTV** [comment]
@Cvolton, could i help translating in Polish?

**Comment by Jouca** [comment]
@Cvolton, could i help translating in French?

**Comment by UpriseDragon** [comment]
Thats not fun guys :P

**Comment by UpriseDragon** [comment]
k

**Comment by Jecket22** [comment]
Most of the translation packs are already translated by other users.
_If you guys were in the discord server before asking all that._
