### ISSUE TITLE
Is there a way to remove the free 100 likes and 300 downloads for a level and/or reduce the number a bit?

### ISSUE THREAD

**Issue by JeffreyRandom** [Cvolton/GMDprivateServer#214]
Taked from #205 xD

**Comment by bit0r1n** [comment]
levels - structure - find "downloads and likes" - put a tick near them(ggl translate :d) - change - default

**Comment by JeffreyRandom** [comment]
@bit0r1n Where is "levels"?

**Comment by JeffreyRandom** [comment]
Ok, i found it. Ty! 8)
