### ISSUE TITLE
I forgot my password

### ISSUE THREAD

**Issue by JeffreyRandom** [Cvolton/GMDprivateServer#219]
Hi, I lose my password's account but I have all the passwords, btw they are encrypted. How to decrypt the password? Thank you :)

**Comment by iRofYTS** [comment]
You should be able to search up MD5 Decryptor and copy the encrypted password and paste it into the box and press decrypt. Some sites dont have it so try others if it says that they cant decrypt it

**Comment by JeffreyRandom** [comment]
@iRofYTS Btw, do you have any recommended site?

**Comment by EndNation** [comment]
I made a .php that allows u to change ur gdps password
