### ISSUE TITLE
This happens when i try to change the password

### ISSUE THREAD

**Issue by UpriseDragon** [Cvolton/GMDprivateServer#221]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'salt' cannot be null' in /membri/gmdragon5/database/tools/account/changePassword.php:43 Stack trace: #0 /membri/gmdragon5/database/tools/account/changePassword.php(43): PDOStatement->execute(Array) #1 {main} thrown in /membri/gmdragon5/database/tools/account/changePassword.php on line 43

**Comment by EndNation** [comment]
How did u try to change the password??? I made a .php that allows u to change password easily

**Comment by UpriseDragon** [comment]
The gdps password i mean

**Comment by Cvolton** [comment]
duplicate of #148
