### ISSUE TITLE
Reupload levels from my GDPS to another one (GDPS)?

### ISSUE THREAD

**Issue by JeffreyRandom** [Cvolton/GMDprivateServer#224]
Hi, my friend just made a gdps, i want to reupload some levels from my server to his server. How to do it?

**Comment by iRofYTS** [comment]
Easy. change this url in the box (go to Level reupload) and change this: http://www.boomlings.com/database/downloadGJLevel22.php to: http://www.yourserverurl.com/database/downloadGJLevel22.php
then grab the id you want on the gdps and put it in the id box and reupload

**Comment by JeffreyRandom** [comment]
Ok thanks! :D
