### ISSUE TITLE
Register problem

### ISSUE THREAD

**Issue by MrZaxTV** [Cvolton/GMDprivateServer#225]
When I try to register on GDPS, server say: "Something went wrong".
I can upload a level, I edited encoded server and non-encoded server.
I don't know why this doesn't working, but pls help me.
Server hosting is: infinityfree.net

**Comment by MrZaxTV** [comment]
My Discord is: [GD] ItsZax#3593

**Comment by hiimjustin000** [comment]
I don't think IF works.
