### ISSUE TITLE
Issue with Tools and connection.php in incl/lib file

### ISSUE THREAD

**Issue by Jecket22** [Cvolton/GMDprivateServer#234]
So, the first issue is that the Tools aren't working for some reason,
so the site stays blank.
_And Exceptions are Stars related tools (unlisted.php have the same issue above) and Cronjob._

The Second Issue is that the connection.php file in incl/lib is giving out this error:
> **Connection failed: SQLSTATE[HY000] [2002] No such file or directory**

Not sure what to do by now. Hope I'll get quite help from you.

**Comment by Cvolton** [comment]
PHP is misconfigured on that server, see if you can modify php.ini. Pretty much anything using PDO to connect to the MySQL won't work. Your best bet would probably be contacting your webhost support
