### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by emmanuelog40** [Cvolton/GMDprivateServer#235]
The database doesnt work it says about create table 'accomments'

**Comment by Jecket22** [comment]
Try to re-download the files or download a newer version of database.sql. If this shouldn't fix, rename with notepad in the file "accomments" into "acccomments"

**Comment by emmanuelog40** [comment]
Jecket22 add me on discord 
emmanuelog40#3798
Try to contact me to help me
In more stuff :>

**Comment by emmanuelog40** [comment]
It still doesnt work
:(

**Comment by emmanuelog40** [comment]
Omfg

**Comment by emmanuelog40** [comment]
Help
Jesus

**Comment by emmanuelog40** [comment]
Help
Jesus

**Comment by Cvolton** [comment]
duplicate of #237 (actually it's the opposite, but people have been posting solutions there instead)
