### ISSUE TITLE
DATABASE ERROR

### ISSUE THREAD

**Issue by emmanuelog40** [Cvolton/GMDprivateServer#237]
read wot the problem says

Error

SQL query:

--
-- Databáze: `public_cvoltongdps`
--

-- --------------------------------------------------------

--
-- Struktura tabulky `accomments`
--

CREATE TABLE `acccomments` (
  `userID` int(11) NOT NULL,
  `userName` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `comment` longtext COLLATE utf8_unicode_ci NOT NULL,
  `secret` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'unused',
  `commentID` int(11) NOT NULL,
  `timestamp` int(11) NOT NULL,
  `likes` int(11) NOT NULL DEFAULT '0',
  `isSpam` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

MySQL said: Documentation
#1046 - No database selected 

thats the problem i tryed fixing it more then once i have 2 hours trying to fix this help me now

**Comment by emmanuelog40** [comment]
Can someone help

**Comment by Cvolton** [comment]
Select a database on the left

**Comment by Jecket22** [comment]
https://imgur.com/a/lNII6
Just select your database and import it. It is that easy.

**Comment by emmanuelog40** [comment]
jecket can you explain me how to import a database i tried it more then once can you add me on discord
here is my discord and if someone else how to fix it here is my discord emmanuelog40#3798

**Comment by Cvolton** [comment]
you have to click on the database name
