### ISSUE TITLE
Reupload levels from my GDPS to another one (GDPS)? (again)

### ISSUE THREAD

**Issue by JeffreyRandom** [Cvolton/GMDprivateServer#239]
My friend just made a gdps, i want to reupload some levels from my server to his server. How to do it?

PD: Im using 000webhost.com
PD2: My url is gmdsjeff.000webhostapp.com

**Comment by Cvolton** [comment]
use levelReupload.php or levelToGD.php, just change the url accordingly

**Comment by JeffreyRandom** [comment]
k ill try
