### ISSUE TITLE
Failed to connect / Account has been disabled

### ISSUE THREAD

**Issue by JeffreyRandom** [Cvolton/GMDprivateServer#240]
Well, some people on my server contact me beacuse when try to log in it says: _Failed to connect_
I really don't know how to fix.
So now, i can't log on my own account, im the "robtop" First time it says: _Failed to connect_
But now...

![failedtolog](https://user-images.githubusercontent.com/35880312/38705772-51647d48-3e70-11e8-92b3-3262c872f5d9.PNG)
It appears after 5 or 4 attemps of log in

Any body knows how to fix this error?

**Comment by iTzGamesJr** [comment]
Yo no tengo idea :D
