### ISSUE TITLE
Question about hosting

### ISSUE THREAD

**Issue by MrZaxTV** [Cvolton/GMDprivateServer#242]
Hello, do you know a free web hosting that work perfectly with GDPS?

**Comment by Jecket22** [comment]
There are a ton of free webhosting sites, but some of them have limited features. Why don't you just try to host on your own computer? Or buy a Raspberry Pi and host on it. That is also how cvolton hosts his server. Also I have currently no recommendations for a free webhosting site, as I still have problems with hosting a GDPS.

**Comment by MrZaxTV** [comment]
But you can tell some free webhosting sites then work perfectly with GDPS?

**Comment by EMREOYUN** [comment]
Altervista :D
Of course not
You can use: https://www.freewebhostingarea.com/
But you need set chmod for files.

**Comment by MrZaxTV** [comment]
Any other free hostings?

And how to set chmod?

**Comment by EMREOYUN** [comment]
1-) IDK
2-) CHMOD: Folders=755 Files=644

**Comment by MrZaxTV** [comment]
Thx for help.

**Comment by EMREOYUN** [comment]
No Problem.
Also i use batihost.com but it is paid service and only available on Turkey.
