### ISSUE TITLE
Help! when I complete a level it does not give me stars

### ISSUE THREAD

**Issue by gabryelv** [Cvolton/GMDprivateServer#243]
because when I complete a level does not give me the stars? and what version of Geometry Dash works well? 2.11 or 2.111?

**Comment by Cvolton** [comment]
Short levels can be up to 2* only

**Comment by gabryelv** [comment]
yes, but neither does the Stereo madness stars give me any original level: c

**Comment by iTzGamesJr** [comment]
Es un error de los archivos del gdps!

**Comment by Cvolton** [comment]
likely conflict with main level IDs, see #414
