### ISSUE TITLE
songAdd.php

### ISSUE THREAD

**Issue by JeffreyRandom** [Cvolton/GMDprivateServer#246]
Some user on my server use songAdd.php and he don't now the id of the song,
1. How can i use songAdd.php?
2. Where in database are "reuploaded" songs?

**Comment by gabryelv** [comment]
baia baia, gracias por tu tutorial :v me pude hacer el server para pc xd

**Comment by gabryelv** [comment]
1_ encerio no sabes usar sonAdd? :v podes subir canciones de dropbox o souncloud.
2_ song reupload era al pedo xd.

**Comment by iTzGamesJr** [comment]
Yes :D

**Comment by Cvolton** [comment]
1. Paste a direct link to the mp3
2. The "songs" table

**Comment by JeffreyRandom** [comment]
Thanks!
