### ISSUE TITLE
Have problem with loading levels.

### ISSUE THREAD

**Issue by Prevter** [Cvolton/GMDprivateServer#248]
I make a server. Then made an Android launcher and build a level. When i published it, everything was OK.
![screenshot_20180418-214828](https://user-images.githubusercontent.com/14332428/38951910-af0c057e-4352-11e8-98a4-bad3690e5cc2.png)
But then i can't see published levels. It just don't show anything. It even create an item in database. But i don't understand why it's not loading. Please help. Thanks.
Edit: Forgot to say, that i using 2.1 Geometry Dash

P.S. Don't know English very good. :)

**Comment by Nemeshio** [comment]
Yes. There is 19,20,21,22 files DownloadGJLevelsXX.php

**Comment by EMREOYUN** [comment]
Weird

**Comment by TiMuRL228** [comment]
i have the same problem too

**Comment by Cvolton** [comment]
environment specific problem, very unlikely to be solved 3.5 years later
