### ISSUE TITLE
on Android nothing is saved

### ISSUE THREAD

**Issue by cro128** [Cvolton/GMDprivateServer#250]
in the android device, nothing is saved, the stars are not saved, nor the orb, practically nothing.

on a computer if it is saved

help

**Comment by DonAlex0** [comment]
@cro128 You have changed com.robtopx.geometryjump to something different, true?

_Sent from my T5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by iRofYTS** [comment]
Remake the gdps but skip the part where you go to the androidmanafest and also in notepad++ skip the part where you do "Lcom/roptopx/geometryjump"

**Comment by EMREOYUN** [comment]
If this part skipped, custom apk name (com.blabla.blabla) doesn't work.

**Comment by Cvolton** [comment]
you need to edit the package name appropriately in the libcocos2d files

**Comment by EMREOYUN** [comment]
@Cvolton this method can be work?

**Comment by xXFireBlastXx** [comment]
@Cvolton Create a tutorial on how to have data stored on android.

**Comment by Nemeshio** [comment]
I have created Android client, and it's saves progress. Maybe the problem can be fixed if you use package name like this: com.abcdefg(7 letters).geometryserv(12 letters). The problem may be because the original package name is com.robtopx(7 letters).geometryjump(12 letters). And yours haven't got that length. Text me if this helped.

**Comment by undeefi** [comment]
Package name length doesnt matter. Something was edited incorrectly/fogotten in the original posters case.

**Comment by Cvolton** [comment]
package name length does matter, because it needs to be edited in libcocos2d.so

**Comment by undeefi** [comment]
It does? Well then.

**Comment by Alex1304** [comment]
If you have a rooted phone it is possible to make it save your data. With Lucky patcher you can "clone" the app, then in the cloned version you can edit and replace the lib file located in /data/app/com.robtopx.[name_modified_by_lucky_patcher]/lib/arm/libcocos2dcpp.so and replace the server URL as you do normally (extract the file to copy it on PC then replace the modified file)

The cons with this method is that there is no possible way to make an APK ready to install on non rooted phones

**Comment by EMREOYUN** [comment]
On rooted phone, Download Hosts Editor, add record:
Host: www.boomlings.com
IP: Yourhostip (not work on webhostings)
Done! You didnt need clone. Open original game and play.
Note: Your host need have /database on tree.
