### ISSUE TITLE
Change data / 1M Diamonds Hacked

### ISSUE THREAD

**Issue by JeffreyRandom** [Cvolton/GMDprivateServer#251]
One user in my server got hacked, idk how but he got hacked.
So, diamonds got hacked.

![](https://cdn.discordapp.com/attachments/429616528506224651/437644498525224960/Screenshot_20180423-110204.png)
_Capture by VipMix_

I try changing diamonds in database but when he got new diamonds, they return to 1003553 diamonds.

Is there any solution or he just got hacked for ever?

Please help me :(

**Comment by Cvolton** [comment]
this is impossible to do server-side, diamonds are stored in the client save data

**Comment by JeffreyRandom** [comment]
Rip, thank you btw
