### ISSUE TITLE
CRON error

### ISSUE THREAD

**Issue by fakemancat** [Cvolton/GMDprivateServer#252]
I have a very large server with your code. And apparently because of the large number of players and levels, I no longer update the creator's points. Long boot, followed by a white screen. I apologize for my English, I am from Russia and I write through Google translator

У меня есть очень крупный сервер с вашим кодом. И видимо из-за большого количества игроков и уровней у меня больше не обновляются очки креатора. Долгая загрузка, после чего белый экран. Извиняюсь за мой английский, я из россии и пишу через гугл переводчик

**Comment by fakemancat** [comment]
@bit0r1n да не, хостинг нормальный, платный. Да и был бы плохой, то сервак бы не выдержал.

**Comment by Jecket22** [comment]
It is mainly caused by the hoster itself, or because limited bandwidth. Though Cronjob.php should actually still work. NOT AUTOMATICALLY (except your hoster offers a cronjob function).

**Comment by Cvolton** [comment]
mostly fixed in 99cb5ee5d4b18169383dfa3c1c1d67f5fca6d662
