### ISSUE TITLE
Cloud Save

### ISSUE THREAD

**Issue by iRofYTS** [Cvolton/GMDprivateServer#255]
Hello. i can not save my data on my friends gdps. ive tried to change the secutiy.php file in the config folder but no luck. it works when i try to save on android but when i try on pc it says"Backup failed. please try again later". how do i fix this

**Comment by EMREOYUN** [comment]
What hosting you are using?

**Comment by geniiii** [comment]
may the world never know

**Comment by Cvolton** [comment]
closed since it's almost a year old

**Comment by EMREOYUN** [comment]
Wow @Cvolton is alive.

**Comment by geniiii** [comment]
no this is his ghost
