### ISSUE TITLE
How to change the user for Reupload ?

### ISSUE THREAD

**Issue by Jouca** [Cvolton/GMDprivateServer#256]
How to change the user for Reupload ?

**Comment by iTzGamesJr** [comment]
No tengo idea

**Comment by Cvolton** [comment]
it's currently hardcoded in /tools/levelReupload.php, so you have to edit that

**Comment by Jouca** [comment]
Yes but where is the code for change the Username ?

**Comment by Cvolton** [comment]
now, years later, there's `config/reuploadAcc.php`
