### ISSUE TITLE
Gauntlets show levels in the order they want

### ISSUE THREAD

**Issue by DonAlex0** [Cvolton/GMDprivateServer#258]
No matter what's the order you put the IDs, they are in other order

**Comment by JeffreyRandom** [comment]
Did you solve it?

**Comment by DonAlex0** [comment]
Yes, I edited the code, you can find it at https://github.com/DonAlex0/GMDPrivateServer

**Comment by JeffreyRandom** [comment]
OMG! It's really nice! Can i use all for my server?
