### ISSUE TITLE
Login Failed After Downloading This New Patch

### ISSUE THREAD

**Issue by KadePcGames** [Cvolton/GMDprivateServer#26]
Ever Since I Have Downloaded This To My GDPS It Has Been Giving Me The Login Failed Error And I Think Its Because Of The Servers wich i blame cvolton please fix this because i had good servers now i dont :/

**Comment by Cvolton** [comment]
the version of the database doesnt match the version of the php files

**Comment by KadePcGames** [comment]
ok
