### ISSUE TITLE
How to put mod suggest level ?

### ISSUE THREAD

**Issue by Jouca** [Cvolton/GMDprivateServer#263]
Hey, idk how to put mod suggest level, can help me plz ?

**Comment by fluffycq** [comment]
you have to grant mod access through settings help in the game then you can rate.

**Comment by Jouca** [comment]
Uh... Fluffycq Please details with screen because idk how to make that :s

**Comment by Cvolton** [comment]
level suggestions are now an official feature as per 15f5fce and 80802f0
