### ISSUE TITLE
Gauntlets bad order

### ISSUE THREAD

**Issue by JeffreyRandom** [Cvolton/GMDprivateServer#264]
Levels are organized the way the want, someone help?

**Comment by EMREOYUN** [comment]
Order your levels.
Level1 ID is be first level
Level5 ID is last level
If doesn't reply back

**Comment by JeffreyRandom** [comment]
It doesn't work, i just change downloads and likes, they are organized by it,

**Comment by EMREOYUN** [comment]
Alright. Problem fixed.
