### ISSUE TITLE
Daily chests won't open

### ISSUE THREAD

**Issue by MrZaxTV** [Cvolton/GMDprivateServer#267]

**Comment by iTzGamesJr** [comment]
It can be slow internet or because the DailyChest.php file is damaged or you changed something that was not in the file

**Comment by MrZaxTV** [comment]
Nope, i have a good internet connection.
File doesn't damaged or bad changed.

Small chest work without problem, but big chest doesn't work.

**Comment by Jecket22** [comment]
Don't make the rewards too high.

**Comment by MrZaxTV** [comment]
Chests working for me, but for others not.

**Comment by Cvolton** [comment]
can you post a copy of your dailychest.php file here

**Comment by MrZaxTV** [comment]
<?php
/*
	QUESTS
*/
//NOW SET IN THE QUESTS TABLE IN THE MYSQL DATABASE
/*
	REWARDS
*/
//SMALL CHEST
$chest1minOrbs = 300;
$chest1maxOrbs = 600;
$chest1minDiamonds = 2;
$chest1maxDiamonds = 10;
$chest1minShards = 1;
$chest1maxShards = 6;
$chest1minKeys = 1;
$chest1maxKeys = 6;
//BIG CHEST
$chest2minOrbs = 1500;
$chest2maxOrbs = 3000;
$chest2minDiamonds = 15;
$chest2maxDiamonds = 30;
$chest2minShards = 1;
$chest2maxShards = 6; // THIS VARIABLE IS NAMED IMPROPERLY, A MORE ACCURATE NAME WOULD BE $chest2minItemID AND $chest2maxItemID, BUT I DON'T WANT TO RENAME THIS FOR COMPATIBILITY REASONS... IF YOU'RE GETTING A BLANK CUBE IN YOUR DAILY CHESTS, YOU SET THIS TOO HIGH
$chest2minKeys = 1;
$chest2maxKeys = 6;
//REWARD TIMES (in seconds)
$chest1wait = 14400;
$chest2wait = 36400;

**Comment by MrZaxTV** [comment]
@Cvolton https://pastebin.com/6fPYg8Y8

**Comment by Cvolton** [comment]
looks fine to me, did the people trying to claim the rewards open their profiles or leaderboards at least once from that account? There's most likely still a bug where that's required

**Comment by MrZaxTV** [comment]
Idk

**Comment by MrZaxTV** [comment]
Fixed
