### ISSUE TITLE
Help!!!!!

### ISSUE THREAD

**Issue by iTzGamesJr** [Cvolton/GMDprivateServer#268]
English:
When I pass the levels of gdps does not give me stars and I also get yellow and only gives me the orbs that has happened to me whenever I create a gdps help !!!!
Spanish:
Cuando me paso los niveles de gdps no me da estrellas y tambien se me ponen amarrillas y solo me da las orbes eso me ha pasado siempre que creo un gdps ayuda!!!!

**Comment by Fire220Creep** [comment]
Mmm.. De Que Duracion Son Los Niveles?
Porque Para Que Tengan Rate Deben De Tener Por Lo Menos Una Longitud Medium Para Dar Estrellas.

**Comment by Dragon77mathbye** [comment]
If the id's of the levels are anywhere from 1-21, they will overlap with the official levels, since the ids of the official levels are 1-21. So completing a level with id 1-21 will make the game think that you already earned the stars for the respective official levels.

**Comment by Cvolton** [comment]
very likely a conflict with main levels, see #414
