### ISSUE TITLE
2.11 search problem

### ISSUE THREAD

**Issue by TiMuRL228** [Cvolton/GMDprivateServer#277]
When i just click on search, i have this
![image](https://user-images.githubusercontent.com/34861386/40441108-da3249e8-5ee1-11e8-8056-3c4185d26504.png)
But when i go to awarded, levels are visible
I tried delete all levels in db and it got
But when players uploaded 10 levels, the same thing happened
btw,sorry for english

**Comment by Numenorean** [comment]
These are server bugs
