### ISSUE TITLE
Creator points

### ISSUE THREAD

**Issue by Nemeshio** [Cvolton/GMDprivateServer#278]
When i rate my levels i'm not getting creator points. Is this a bug, or i can't get creator points if I rate my levels? (google translate)

**Comment by Cvolton** [comment]
you need to update them by running /tools/cron/cron.php

**Comment by rust2** [comment]
@Cvolton, can I make php file that will run cron.php automatically every 30min?

**Comment by Cvolton** [comment]
if your host offers you to create cron jobs, you can create a cron job that will run it every once in a while

**Comment by ParkSH127** [comment]
How can I run cron.php on 7m.pl? (google translate)
