### ISSUE TITLE
how to give a mod on private server?

### ISSUE THREAD

**Issue by 1135656** [Cvolton/GMDprivateServer#279]
help plz

**Comment by Nifidel** [comment]
If you’re talking about giving moderator status to someone in the GDPS it’s as simple as going in phpmyadmin and changing the “isAdmin” value, then if you want to assign a badge you have to use the “Roles” table for that.

**Comment by XcreatorGoal** [comment]
Which value should i put in "isAdmin"???? 1 or 2 or what?? when i put 1 then i click the button for mod "req" and it says failed try again later. any idea?

**Comment by iBcakester** [comment]
@XcreatorGoal the value for "isAdmin" is either 0 or 1, 0 being no admin and 1 being is admin. If you want the req button to work, goto roles and create a new role and fill out the things.

**Comment by skreyn** [comment]
#118

**Comment by Hector12880** [comment]
tutorial is here, the problem is in spanish: https://ayudagdps.wordpress.com/2018/01/06/2-como-hacer-el-rol-de-elder-mods-y-normal-mods-y-como-ponertelo/
