### ISSUE TITLE
How to create GDPS for android (2.113 version plz) and Ios (optionnal) ?

### ISSUE THREAD

**Issue by Jouca** [Cvolton/GMDprivateServer#287]

**Comment by MrZaxTV** [comment]
2.113 does exists for PC only, but here I give link if you want create GDPS for Android: https://youtu.be/lXbTTc3DZM4

**Comment by Jouca** [comment]
Or 2.11 version ?

**Comment by MrZaxTV** [comment]
Yes.

**Comment by hiimjustin000** [comment]
#469 Yes you already know this now with ClarifyGDPS (In which you stepped down as owner) But I will still reference my pull request.

**Comment by EMREOYUN** [comment]
[Refer Here for All Platforms](https://github.com/Cvolton/GMDprivateServer/wiki/Creating-Windows,-Android-and-IOS-Apps).

**Comment by itzmayronHD** [comment]
e33333333333333333333333333333333333333333333

**Comment by fancythedeveloper** [comment]
what
