### ISSUE TITLE
some really weird issue

### ISSUE THREAD

**Issue by ad2017gd** [Cvolton/GMDprivateServer#293]
So recently my GDPS literally broke. First, i could not play ANY levels, only the saved ones and daily + weekly. I can't search, i can't see trending, magic, etc. I don't know whats happening. I searched for broken things in files and mySQL but i can't find anything wrong.

I would also want to mention that the first object from a list (ex. leaderboards or comment history) has no content. (or just name)
examples : 
![image](https://user-images.githubusercontent.com/39013925/41433813-a779fb84-7022-11e8-9ef1-c7dbf56007fe.png)
![image](https://user-images.githubusercontent.com/39013925/41433834-b4c75250-7022-11e8-8e8c-ac29ff425797.png)
![image](https://user-images.githubusercontent.com/39013925/41433868-c7a99ef0-7022-11e8-82e6-46ee0fdbd8f0.png)
![image](https://user-images.githubusercontent.com/39013925/41433907-d533a69c-7022-11e8-8729-4667aee1a5f7.png)

Any help please?

**Comment by RealKrazy** [comment]
Reinstall MySql Database and same with PHP database files.

**Comment by Cvolton** [comment]
This looks like PHP error messages are getting printed into the output for some reason, the real cause of this is always specific to the server and as this was 3.5 years ago, I doubt this issue is still relevant.
