### ISSUE TITLE
Cannot download levels.

### ISSUE THREAD

**Issue by iBcakester** [Cvolton/GMDprivateServer#295]
So everything is working fine. I can create accounts, manage profiles, etc., but I tried to upload a level, it showed the upload sucessful page, the one with the check mark, also it creates a level in the levels section of the database. But I cannot download the level, nor can i search it. The id of the level in geometry dash also still displays as NA but on the server it displays a number. I try searching the number but i cannot find my level. Help?

**Comment by XcreatorGoal** [comment]
same
