### ISSUE TITLE
Level Star Problem

### ISSUE THREAD

**Issue by RealKrazy** [Cvolton/GMDprivateServer#296]
<b>On the my gdps i can max rate 2 stars. Since i can't rate, like demon 10 stars. ONLY DEMON 2 STARS!</b>
<b color="#ff0000">SAY ME, HOW TO FIX THIS??</b>
<b color="#00ff00">Thank you for help :)</b>

**Comment by iBcakester** [comment]
Go to the PHPMyAdming thing, go to your database, go to "levels", find your level in the list, and then change the starStar to the star value? i thing the starDemon starAuto starCoins starFeatured starHall starEpic are all just 0 or 1 value. and starDemonDiff i have no idea maybe like 0~4 or 1~5? hope i helped

**Comment by RealKrazy** [comment]
So i need to change the StarDifficulty value to star value? What i need to do with starStars? And if I wan't insane, 9 stars for example?? If I set starDifficulty to 9, it shows easy difficulty, so sinecly it's not working. Maybe I don't understand?? Butt... IDK. Any another variant?

**Comment by iBcakester** [comment]
Here is the starDifficulty values. 0=N/A , 10=EASY , 20=NORMAL , 30=HARD , 40=HARDER , 50=INSANE , 50=AUTO , 50=DEMON . The starDifficulty is probably related to the starAuto and starDemon. Here is my theory: If you set the starDifficulty to 50, it will automatically become Insane. But if you set the value of starAuto or starDemon to 1, then it will become Auto or Demon. :) . starStars is probably the amount of stars you want your level to be such as 10000000000 stars or 0 stars. i dont know i have an issue with my server so i cant try it. hope cake helped.... (again) -__-

tbh i was very confused myself my server isnt working so im just using logic...

**Comment by RealKrazy** [comment]
I mean, when i completed any level on my server, that has more than 2 stars, it's just kicking from level at the end.

i hope somebody will <b>HELP MEE!!</b>

**Comment by RealKrazy** [comment]
But on
