### ISSUE TITLE
Gauntlets problem

### ISSUE THREAD

**Issue by ItzLennyFace** [Cvolton/GMDprivateServer#297]
https://cdn.discordapp.com/attachments/449662011005992972/462335680555515904/Screenshot_20180629-221907.png

**Comment by iBcakester** [comment]
u sure u got a gauntlet ID and you got all the levelIDs correct? maybe reload it?

**Comment by ItzLennyFace** [comment]
Yes, all levelIDs is correct.

**Comment by iBcakester** [comment]
Maybe a server issue? idk

**Comment by ItzLennyFace** [comment]
No.

**Comment by iBcakester** [comment]
then idk

**Comment by RealKrazy** [comment]
Uhh... Are you sure it's issue?? Or you just wanna prank?? When you completed level just screenshot and make this issue?

**Comment by ItzLennyFace** [comment]
It isn't prank, its real.....

**Comment by Codanovia** [comment]
_glad that I complete this gauntlet before the issue occured XD_

**Comment by ItzLennyFace** [comment]
@Codanovia Oh hi.. xdd
