### ISSUE TITLE
Unable to upload levels.

### ISSUE THREAD

**Issue by TheRealDreamzy** [Cvolton/GMDprivateServer#3]
I can't upload Levels onto my GDPS.

Whenever i try, it says "Update failed, please try again later"
I have the database configured as well as my database ftp up and set for action.

Is it an error towards my server or me with Windows 10?
Thanks in advance.

-Dreamzy

**Comment by Cvolton** [comment]
Can you give me the URL of your GDPS so I can investigate further?

**Comment by TheRealDreamzy** [comment]
Yeah but i have to change it's API.
Been using a temporary one because of this.
Let me reset it to the original state and then i'll replay again with the URL.

**Comment by TheRealDreamzy** [comment]
Ok chief. I resetted the GDPS to your API.
the URL is http://dreamzy2.ueuo.com/

**Comment by Cvolton** [comment]
Can't confirm the issue, I was able to upload a level both before and after I made an account

**Comment by TheRealDreamzy** [comment]
Seems we got it to work over Discord now.
