### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by TiMuRL228** [Cvolton/GMDprivateServer#301]
How to make discord gd bot?
with this
![image](https://user-images.githubusercontent.com/34861386/42692756-834aa0a2-86ce-11e8-8164-41fbb11f064b.png)
My discord
Timur228rus#9558
or can you give me a tutorial please?
Thanks for help anyway

**Comment by ItzLennyFace** [comment]
Me too

**Comment by iBcakester** [comment]
i guess u got to code a bot first, add to your discord server, then go to config/discord.php then edit it there? idk rlly

**Comment by ItzLennyFace** [comment]
But how to code bot correctly? @iBcakester

**Comment by iBcakester** [comment]
i have no idea maybe you can look up how to make a discord bot and then idk.
or ask the 1.9GDPS team to give you the code for their gd bot

**Comment by TiMuRL228** [comment]
lol no one answered me

**Comment by iBcakester** [comment]
maybe u make the bot then link the php files to the bot to display on discord i rlly dont know

**Comment by JeffreyRandom** [comment]
https://ultimategdbot.readthedocs.io/en/stable/Self-hosting-guide/ This is a bot called UltimateGDBot, it "supports" GDPS, btw I tried, and failed. But you don't lost anything trying. :)

**Comment by DonAlex0** [comment]
There are some tutorials out there of how to create a Discord bot in general, you can use the Discord.js for coding in Java or the python one, you'd need the bot to make a request to the file you need with the command someone wrote, and retrieve the server answer with the Discord bot and then make whatever you want with the information retrieved and answer the person's requested command
