### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ItzLennyFace** [Cvolton/GMDprivateServer#302]
How to make gauntlet order by stars?

Example:
level1 = 4 star level
level2 = 5 star level
level3 = 6 star level
level4 = 7 star level
level5 = 8 star level

**Comment by iBcakester** [comment]
u type the level ids in the order you want it to be

**Comment by ItzLennyFace** [comment]
But gauntlets isn't going as it should

**Comment by iBcakester** [comment]
then idrk
