### ISSUE TITLE
Cannot download levels, although I can upload them.

### ISSUE THREAD

**Issue by Dropheart** [Cvolton/GMDprivateServer#304]
I can create an account, I can create and upload levels, although I get Something Went Wrong when I try to download them. Downloading and uploading works on 2.0, but not on 2.11. On both exes, for 2.0 and 2.11, I've replaced all instances of www.boomlings.com with my site, and on the 2.11 exe, with base64 instances of www.boomlings.com with my site encoded in base64. I'm hosting the database on my own raspberry pi using nginx, php, and mysql.

**Comment by iBcakester** [comment]
connection.php correct? idk

**Comment by DroppedHeart** [comment]
It's correct, else it wouldn't work on 2.0 and I wouldn't be able to create accounts, upload levels, etc.

**Comment by Alex1304** [comment]
Make sure PHP has permissions to write in data folder, this is where levels are stored. In a terminal, place yourself in the root directory of your GDPS files and do `chmod -R 777 data`
