### ISSUE TITLE
[Bug report] Going to the Quests page while the quests table has no content in the GDPS causes the whole game to crash

### ISSUE THREAD

**Issue by Alex1304** [Cvolton/GMDprivateServer#305]
Steps to reproduce:
- Make sure the `quests` table has no content in your GDPS database
- Launch your modified GD app on Android (haven't tested the issue on PC version)
- Go to Quests page

Expected result: The GDPS should return an empty list of quests properly so the game doesn't crash
Actual result: The whole game crashes, probably because the GDPS is returning some invalid data and the game fails to parse it

**Comment by ItzLennyFace** [comment]
You must create a quests. This isn't bug.

**Comment by Alex1304** [comment]
That should not be required tho

**Comment by ItzLennyFace** [comment]
I know, but quests should exists if you doesn't want this bug.

**Comment by iBcakester** [comment]
You need at least 4 quests to make the game not crash

**Comment by RealistikDash** [comment]
Gd doesn't know what to do when there are no quests

**Comment by Cvolton** [comment]
This is a valid bug that I know of, just a low priority one

**Comment by Cvolton** [comment]
fixed by 4bde0272ce769ab08f50068d4b72940fed0a16c3
