### ISSUE TITLE
Local Server Support (localhost)

### ISSUE THREAD

**Issue by qctfw** [Cvolton/GMDprivateServer#306]
Can i use this in a local server instead of an internet?

**Comment by qctfw** [comment]
I will use an IP to store a database actually.
Anyway thank you.

**Comment by qctfw** [comment]
Should i use "http://" for linking to my database?

**Comment by iBcakester** [comment]
hmm? if you host the database on the same machine just use localhost or 127.0.0.1 in connection.php

**Comment by qctfw** [comment]
I understand. Thanks again.
