### ISSUE TITLE
Account Linking (tools/linkAcc.php)

### ISSUE THREAD

**Issue by qctfw** [Cvolton/GMDprivateServer#307]
What "tools/linkAcc.php" is for? To sync my GD data from RobTop's server to my server or my server to RobTop's server?

**Comment by iBcakester** [comment]
lincAcc.php isnt to sync data. i never rlly found out its purpose tho. i guess its so when u reupload a level from the robtop server it doesnt reupload under the account Reupload it reuploads it onto the account you linked to.

**Comment by Cvolton** [comment]
Reuploading levels is the only thing it's currently used for

**Comment by qctfw** [comment]
Ok. Thanks for replying Cvolton.
