### ISSUE TITLE
Inconsistencies with official GD servers for some values returned

### ISSUE THREAD

**Issue by Alex1304** [Cvolton/GMDprivateServer#309]
- In `getGJUserInfo.php`, if the user is either banned from leaderboards or if the leaderboard cron has never been run once, the global rank returned is an empty string, while it does return "0" for unranked users in official GD
- Still in `getGJUserInfo.php`, if the specified accountID doesn't match with any existing account in database, the GDPS returns a user string with empty info instead of just returning "-1" as official GD server does
- In `downloadGJLevel.php`, levels that are not copyable will have the pass field (27:) equal to`Ag==` instead of "0"

The issues above don't seem to break GD, but I had to make a patch update in UltimateGDBot (a Discord bot I made to access GD API) to make it work with GD private servers based on this repository. It is also important to fix this if we want to have the GD API documented someday

**Comment by KonnorEpic** [comment]
Alex1304, how to make a bot, like yours, I just need a bot so that it can send messages about a new rated level, about a new moderator/elder in Discord?

**Comment by Alex1304** [comment]
@KonnorEpic actually you can host your own instance of the bot and configure it for a GDPS. See http://ultimategdbot.readthedocs.io/en/latest/Self-hosting-guide

**Comment by Cvolton** [comment]
these 3 issues should be fixed by this point
