### ISSUE TITLE
Newgrounds songs issue

### ISSUE THREAD

**Issue by qctfw** [Cvolton/GMDprivateServer#312]
How to get a song from Newgrounds? When i'm trying to get the song using ID ingame, it's says "Failed to fetch song info.".
And I tried using Postman too and it says: `file_get_contents(http://www.boomlings.com/database/getGJSongInfo.php): failed to open stream: Connection refused in [MY WEBSITE]/database/incl/misc/getGJSongInfo.php on line 25`

**Comment by Cvolton** [comment]
This is an issue with your host not being able to connect to RobTop's server

**Comment by qctfw** [comment]
So, how to fix this in the host?

**Comment by Cvolton** [comment]
What host are you using?

**Comment by qctfw** [comment]
I find out that cURL in my server is not supported. I tried to move to another one and worked well.
Thanks for helping.
