### ISSUE TITLE
i can't upload my level.

### ISSUE THREAD

**Issue by zetablack** [Cvolton/GMDprivateServer#313]
when i upload file in database directory, should i upload with config, dashboard....like this to folder or file.......?

**Comment by zetablack** [comment]
when i upload my level....... 
i can't see my level in my gdps

**Comment by zetablack** [comment]
plzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplzplz

**Comment by zetablack** [comment]
whywhywhywhy no answer

**Comment by iBcakester** [comment]
idk what hosting u using and when u upload does it show the Success message? Also does it create level in database?

**Comment by zetablack** [comment]
i use freewebhostingarea. and when i upload my  map it said success. and in database level table there is my level. but i can't see it in gdps

**Comment by zetablack** [comment]
![_2018_08_11_11_48_41_125](https://user-images.githubusercontent.com/40019019/43987497-92cf83d6-9d5c-11e8-8d9d-2ef340c3405f.png)
![_2018_08_11_11_45_54_618](https://user-images.githubusercontent.com/40019019/43987498-950269c0-9d5c-11e8-9001-c04ecb98eed2.png)

**Comment by zetablack** [comment]
[녹화_2018_08_11_11_46_56_709.zip](https://github.com/Cvolton/GMDprivateServer/files/2279853/_2018_08_11_11_46_56_709.zip)

**Comment by zetablack** [comment]
[녹화_2018_08_11_20_07_51_727.zip](https://github.com/Cvolton/GMDprivateServer/files/2280159/_2018_08_11_20_07_51_727.zip)

**Comment by iBcakester** [comment]
ok. So this is a problem that I have encountered before. here is my conclusion. FreeWebHostingArea does not allow you to use GDPS. I remember reading about it somewhere. So GDPS will NOT work on freewebhostingarea. use something else like AlterVista. AlterVista works fine for me. hope this helped :)

**Comment by Ladizii** [comment]
Use https://7m.pl/ instead or portforward the GDPS in your PC.

**Comment by zetablack** [comment]
Thx i will try it.

**Comment by zetablack** [comment]
how can i make database, mysql, phpmyadmin in 7m.pl?

**Comment by iBcakester** [comment]
host on raspberry pi? or just buy a hosting service like from GoDaddy or something

**Comment by Ladizii** [comment]
Hosting on a RaspBerry Pi is better, but it will require 50$, buying a VPS is equally efficient.

**Comment by zetablack** [comment]
I want buy raspberry pi but i don't know hpw to set it

**Comment by iBcakester** [comment]
you need apache and mysql thingo

**Comment by CsAndrisyt** [comment]
![image](https://user-images.githubusercontent.com/42375133/44090504-a8634212-9fca-11e8-92af-d6476cc823d7.png)

**Comment by iBcakester** [comment]
I JUST SED NO FREEWEBHOSTINGAREA Y PPL USE IT sorry for caps
just dont use freewebhostingarea too many restrictions and they dont let u make a private server there so just DONT use it
ty

**Comment by iBcakester** [comment]
but levelReupload.php loads fine for me on csandris.ueuo.com/tools/levelReupload.php

**Comment by zetablack** [comment]
Yes i think i should buy raspberry pi

**Comment by zetablack** [comment]
Any web host system able to make gdps?
(Freewebhostingarea. X)

**Comment by zetablack** [comment]
Any web host system able to make gdps?
(Freewebhostingarea. X)

**Comment by iBcakester** [comment]
Pay for service from GoDaddy? but not worth it cuz it just  a private server. Try again with AlterVista maybe  try again with a different connection?
