### ISSUE TITLE
Some Android thing...

### ISSUE THREAD

**Issue by Mantevian** [Cvolton/GMDprivateServer#317]
Not related to the servers, but... how to make the Android version don't erase the save each time I relaunch the game? It's kinda annoying, also creates a "Player" user every time... Is there any solution?

**Comment by iBcakester** [comment]
i think it has something to do with the save location of the game. maybe change the location idk never done it b4

**Comment by qctfw** [comment]
You need to change the package name too while you're changing the server URL and Base64 thing.

**Comment by qctfw** [comment]
#250

**Comment by Cvolton** [comment]
make sure the package name in libcocos2d.so matches the package name in androidmanifest.xml
