### ISSUE TITLE
Songs is not listed in the tools website

### ISSUE THREAD

**Issue by Jouca** [Cvolton/GMDprivateServer#319]
Hello,
My songs is not listed in my tools website and idk why.

![image](https://user-images.githubusercontent.com/25087475/44161255-0cdeef00-a0bd-11e8-9ffb-97da89bdd1c5.png)

The code : 

![image](https://user-images.githubusercontent.com/25087475/44161299-3435bc00-a0bd-11e8-874d-7fbb1032280c.png)

**Comment by ItzLennyFace** [comment]
The songs will appear when their ID is higher than 5000000. If you want change this, change 5000000 to any number.

**Comment by iBcakester** [comment]
just go to the database and goto the songs table and change the ids to over 5000000

**Comment by bit0r1n** [comment]
change WHERE ID >= 5000000 to WHERE ID >= 0
