### ISSUE TITLE
Level ID Length too long (Android)

### ISSUE THREAD

**Issue by qctfw** [Cvolton/GMDprivateServer#320]
I can't input level ID ingame when the level ID length is over 6. So when I type "5000001", the game only shows "500000". How to fix this?

**Comment by iBcakester** [comment]
change the id in the database to a smaller id number?

**Comment by qctfw** [comment]
I can do that. Because previously the NONG song ID starts from 1. But when I tried to put the wrong song ID. The system starts to search for a Newgrounds song. Should I limit the ID to search a Newgrounds song? (Example: Search to NG song if ID > 5000)

**Comment by iBcakester** [comment]
idk. for some reason sometimes android theres a character limit. but now there are newgrounds songs that are over 5000 tho

**Comment by DonAlex0** [comment]
The first is literally the ID 1
