### ISSUE TITLE
How to rate a level

### ISSUE THREAD

**Issue by ENvyaA** [Cvolton/GMDprivateServer#324]
Please explain in detail or send a teaching video on YouTube. thx

**Comment by iBcakester** [comment]
so u goto the level, and if you r admin, goto comments, type comment !rate [difficulty(easy,hard,etc)] [star amount]
if you r moderator, just use that shiny moderator only button to rate that level
if you have access to database, you can rate manualy there.
i dont think this is detailed but hope this helped

**Comment by iBcakester** [comment]
u have to do RoleAssign

**Comment by ENvyaA** [comment]
Added in mysql, why not take effect？

**Comment by iBcakester** [comment]
idk
