### ISSUE TITLE
How to create a command?

### ISSUE THREAD

**Issue by MrClayYT** [Cvolton/GMDprivateServer#325]
How to create a command for my private server? (remove C)

**Comment by ItzLennyFace** [comment]
Creating commands isn't supported right now. (I think so)

**Comment by MrClayYT** [comment]
and through commands.php?

**Comment by DonAlex0** [comment]
You have to know about PHP and SQL in order to create your own commands

**Comment by EndNation** [comment]
You need some php knowledge, then goto mainLib.php I think and it should be there where most commands are at.
