### ISSUE TITLE
how to edit index.php

### ISSUE THREAD

**Issue by zetablack** [Cvolton/GMDprivateServer#326]
i'm using 7m.pl to host........but i can't upload file because

**Comment by zetablack** [comment]
![kakaotalk_20180820_114111587](https://user-images.githubusercontent.com/40019019/44317815-00b4b200-a46e-11e8-8512-adf464622108.jpg)

**Comment by zetablack** [comment]
how can i solve this.

**Comment by zetablack** [comment]
where is 7m.pl ftp?

**Comment by ItzLennyFace** [comment]
FTP Server is zetagdpsaaa.7m.pl

**Comment by ItzLennyFace** [comment]
If you want help with GDPS, you can send message in Discord: ItsZax#3593

**Comment by zetablack** [comment]
Yes i opened zetagdpsaaa.7m.pl
