### ISSUE TITLE
[1.9] Level Issue

### ISSUE THREAD

**Issue by ItzLennyFace** [Cvolton/GMDprivateServer#328]
![screenshot_2018-08-22-03-52-13-933_com itszaxx geometryps19](https://user-images.githubusercontent.com/35407720/44438307-de7e7980-a5be-11e8-95cb-f7acb3476f5e.png)
![screenshot_2018-08-22-03-52-16-871_com itszaxx geometryps19](https://user-images.githubusercontent.com/35407720/44438311-e0e0d380-a5be-11e8-8126-c46d27eace7f.png)

**Comment by DonAlex0** [comment]
Server code doesn't work with 1.9

**Comment by Cvolton** [comment]
Make sure you're not logged in, the gdps source doesn't support accounts in 1.9

**Comment by ItzLennyFace** [comment]
I logout from my account and tried to upload lvl.... Same issue.
