### ISSUE TITLE
Configuring Featured page ? (First place feature etc...)

### ISSUE THREAD

**Issue by playxgd** [Cvolton/GMDprivateServer#332]
Is there any way of configuring the featured page like in the original server where robtop can rank levels (first place , second place etc...) ?

**Comment by Cvolton** [comment]
currently the levels in the featured page are ordered by when they were featured

**Comment by playxgd** [comment]
ok thx

**Comment by Chiefjack** [comment]
I know this thread is closed, but are you thinking of implementing this anytime soon, as it would be really helpful?
