### ISSUE TITLE
Rating level

### ISSUE THREAD

**Issue by GX2H912** [Cvolton/GMDprivateServer#334]
When I rate a level and I complete it with (!rate demon 999), right before the end of the level I'm brought back to the screen with the online level screen with the level's name.

**Comment by UpriseDragon** [comment]
Probably the level is too short and it kicks you out

**Comment by UpriseDragon** [comment]
Probably the level is too short to be a demon

**Comment by GX2H912** [comment]
How long should the level be?

**Comment by GX2H912** [comment]
Alright, thank you!

**Comment by Cvolton** [comment]
Also please note that gd doesn't award stars for levels with more than 10 stars
