### ISSUE TITLE
Suggestion: Normal Mod should send rate to owner

### ISSUE THREAD

**Issue by Zaxior** [Cvolton/GMDprivateServer#335]
Like, if you want this :P

**Comment by qctfw** [comment]
I've done this by modifying the mainLib.php and suggestGJStars.php . If a mod / elder mod suggests a star, a bot account (GDPSbot) will comment to that level.
![screenshot_2018-09-07-10-32-16-405_com geometrydashind gdps](https://user-images.githubusercontent.com/33951589/45197166-0a218500-b28a-11e8-930d-f72a2eeecf5e.png)

**Comment by TiMuRL228** [comment]
qctfw how u make that?

**Comment by FleFStyle** [comment]
How?

**Comment by FleFStyle** [comment]
https://github.com/Cvolton/GMDprivateServer/issues/335#issuecomment-419312701

**Comment by FleFStyle** [comment]
@qctfw how?

**Comment by ItzLennyFace** [comment]
@qctfw How?

**Comment by JeffreyRandom** [comment]
@qctfw Everybody wants to know how, including me lol

**Comment by bit0r1n** [comment]
#389

**Comment by Zaxior** [comment]
thank you @bit0r1n

**Comment by tzt345** [comment]
@qctfw How
