### ISSUE TITLE
Daily and Weekly Levels Don't Update

### ISSUE THREAD

**Issue by Chiefjack** [Cvolton/GMDprivateServer#337]
I have set a level to be daily with !daily and a weekly with !weekly yet neither of the levels become daily or weekly in my GDPS. I've tried for a few days now to get it to work. Also, in the phpmyadmin, it shows the list of levels to be daily and shows the one that should currently be daily yet it isn't showing up in game.

Please help,

ChiefJack

**Comment by Cvolton** [comment]
There are 2 possible causes for this
1) there's a bug and the daily level was set a long time in the future
2) the id (feaid in the daily table) of the current daily level is lower than the level that gd shows to you (an issue with your save data then, could happen if you copy your save data over from a different server for example)

Does the issue happen with a blank save data too? Also remember that !daily currently queues the level up for the next day (or the day after the last queued daily if there's multiple queued up)

**Comment by Chiefjack** [comment]
Sorry for the late response. Changed the feaid to a much higher number fixed it. That could get annoying doing for every daily. I haven't loaded a save data from another server either. Also, why does the game go black after exiting out of daily, weekly, or quests tab sometimes. It seems pretty random if it does choose to go black. Pressing Esc quickly after fixes it, but that is really annoying.

**Comment by Cvolton** [comment]
> Also, why does the game go black after exiting out of daily, weekly, or quests tab sometimes
RobTop issue
