### ISSUE TITLE
Send level to owner for rate

### ISSUE THREAD

**Issue by FleFStyle** [Cvolton/GMDprivateServer#341]
Reiteration: How to make sure that moderators can send levels to the creator for owner?

**Comment by bit0r1n** [comment]
#389 
or
1. Create new in database 
2. Add function to /inlc/lib/mainLib.php
3. Edit /inlc/levels/suggestGJStarts.php (add recently created function into this file)
4. use it
that's how suggest works

**Comment by Cvolton** [comment]
level suggestions are now an official feature as per 15f5fce and 80802f0
