### ISSUE TITLE
Help! All players on my server have got all permissions withou mod!! How o fix it?!

### ISSUE THREAD

**Issue by shadowplay1** [Cvolton/GMDprivateServer#342]
Help! All players on my server have got all permissions withou mod!! How o fix it?!

**Comment by DonAlex0** [comment]
Have tried creating a default role for every user with non-mod permissions?

**Comment by GGaMErZZ** [comment]
set "default role" to 0 lol

**Comment by fancythedeveloper** [comment]
This what happens when you set everything to 1 without reading them.

**Comment by Cvolton** [comment]
already been said many times, you need to create a role for regular players too and set isDefault to 1 there (and make sure to set it to 0 for the mod role)

just commenting here so i can close this
