### ISSUE TITLE
[Bug report] The cron job crashes if everyone in the gdps without exception has CP

### ISSUE THREAD

**Issue by Alex1304** [Cvolton/GMDprivateServer#343]
**Steps to reproduce:**
- Have only a few accounts registered in the GDPS
- Give a star rate on a level for every single account, so that everyone should have CP
- Run the cron job

**Expected Result:** The cron should run fine and give CP to everyone

**Actual result:** The cron crashes when executing the SQL query at line 123 of `database/tools/cron/fixcps.php`. Since everyone in the server has CP, the `$nocpppl` variable is an empty string, which invalidates the syntax of the query.

**Comment by Cvolton** [comment]
fixed by #345
