### ISSUE TITLE
Backup Failed. Please try again. How to fix it?

### ISSUE THREAD

**Issue by mfeoznik** [Cvolton/GMDprivateServer#347]
i'm using 7m.pl

**Comment by Folleach** [comment]
Maybe you are not allowed to write on the following directories:
**data/***

**Comment by TiMuRL228** [comment]
i can
![image](https://user-images.githubusercontent.com/34861386/47960023-12453900-e01d-11e8-822e-a148c4a5e285.png)

**Comment by Cvolton** [comment]
chmod 777 the data folder

**Comment by Folleach** [comment]
`chmod 777` on the data folder it isn't good way to fix.
It's better to give rights exclusively to the user who accesses the data

**Comment by Cvolton** [comment]
> `chmod 777` on the data folder it isn't good way to fix. It's better to give rights exclusively to the user who accesses the data

indeed but in this instance the OP is using 7m.pl, which doesn't give you permissions to change the owner AFAIK
