### ISSUE TITLE
 I can modify the states of my account??

### ISSUE THREAD

**Issue by Hector12880** [Cvolton/GMDprivateServer#351]
I would like to know if I can modify the coins that I have or if I can modify the orbs or the stars...

**Comment by EMREOYUN** [comment]
Enter phpmyadmin
Find ur acc
Edit orb stars etc.
Do not press your account menu in Main Menu.
Alsi do not run cron job(it bans you if modified).

**Comment by Hector12880** [comment]
Don't work :,(

**Comment by DonAlex0** [comment]
That's because in your in-game data you still have the same data and progress, changing it in the db is just visual and will change as soon as you view your profile

**Comment by Hector12880** [comment]
OK THX
