### ISSUE TITLE
Renaming Gauntlets?

### ISSUE THREAD

**Issue by Chiefjack** [Cvolton/GMDprivateServer#353]
As the title suggests, is there anyway of renaming Gauntlets, as I have some cool Gauntlets in mind that fit some of the images from the 15 Gauntlets, but the name doesn't. If there isn't a feature to rename Gauntlets, can one be added?

Thanks

**Comment by Folleach** [comment]
Names stored locally.
In order to change them you need:
1. Open the executable file of the game in the HEX editor.
2. Go to offset 2A1ED8 or find gauntlet name.
3. Edit and save
Add new gauntlet not possible.

**Comment by Chiefjack** [comment]
Also, gauntlet levels don't show up in the order I put them in when I made the gauntlet in phpmyadmin. How can I have them order correctly?

**Comment by Folleach** [comment]
> In the photo you can see the gauntlet name I wish to change. I changed the text in the box numbered '2' to 'Spook' and saved, same issue as above. Then I tried it where I renamed both boxes, same issue as above. 

Note that 1 is the name of the texture that should not be changed.
A 2 is most likely what you need.
I do not quite understand why the server may not load because of this change.

As for the order of levels.
Maybe you just need to change the request in the file "incl/levels/getGJLevels.php" on line 102.
In the variable "order" you need to specify the name of the column in the database by which the sorting will be performed.
This is my guess.

**Comment by Chiefjack** [comment]
> > In the photo you can see the gauntlet name I wish to change. I changed the text in the box numbered '2' to 'Spook' and saved, same issue as above. Then I tried it where I renamed both boxes, same issue as above.
> 
> Note that 1 is the name of the texture that should not be changed.
> A 2 is most likely what you need.
> I do not quite understand why the server may not load because of this change.
> 
> As for the order of levels.
> Maybe you just need to change the request in the file "incl/levels/getGJLevels.php" on line 102.
> In the variable "order" you need to specify the name of the column in the database by which the sorting will be performed.
> This is my guess.
> 
> ```
> if(!empty($_POST["gauntlet"])) {
> 	$order = "Column name"; //Here
> 	$gauntlet = $ep->remove($_POST["gauntlet"]);
> ```

Thanks. I didn't think Box 1 would need changing either. I'll try again with just changing Box 2. I'll also try changing the request in "incl/levels/getGJLevels.php". I'll edit this with my results.

**Comment by Folleach** [comment]
> This is my gauntlet table. I am a bit unsure of what to put instead of false in getGJLevels.php. I've tried doing "level1, level2, level3, level4, level5" and it doesn't work. Any ideas?

You must specify a column from "levels" table.

**Comment by Chiefjack** [comment]
> > This is my gauntlet table. I am a bit unsure of what to put instead of false in getGJLevels.php. I've tried doing "level1, level2, level3, level4, level5" and it doesn't work. Any ideas?
> 
> You must specify a column from "levels" table.

This is the column I want it to be ordered by: 
![image](https://user-images.githubusercontent.com/25803522/47616246-297ea680-dab2-11e8-98c3-ae4fe14213b2.png)

So I put this name into the database file: 
![image](https://user-images.githubusercontent.com/25803522/47616240-1b308a80-dab2-11e8-993c-9f48e9d33577.png)

However nothing happens in game to the gauntlet levels.
Any suggestions?

**Comment by Folleach** [comment]
You must specify a string.
```php
$order = "starStars";
```
After all, you specify the name of the column which you do not have in the variables.
