### ISSUE TITLE
Quests not Stacking/Queuing

### ISSUE THREAD

**Issue by Chiefjack** [Cvolton/GMDprivateServer#354]
I have an issue with quests where quests aren't building up over time as they do in normal GD. After completing a quest I have to wait x amount of time for another one. How can I get them to queue up like in normal GD?

**Comment by ItzLennyFace** [comment]
How many quests you add?

**Comment by Chiefjack** [comment]
> How many quests you add?

I have added 9 quests which can be seen below: 
![image](https://user-images.githubusercontent.com/25803522/48013908-65061a00-e11d-11e8-95ea-c1148f51e3cc.png)

**Comment by Zaxior** [comment]
Maybe it is fault of your hosting... Which hosting are you use?

**Comment by Chiefjack** [comment]
I am using Altervista however it seems to be working now, just takes ages for them to queue.
