### ISSUE TITLE
"Allow messages from: none" option doesn't work

### ISSUE THREAD

**Issue by Zaxior** [Cvolton/GMDprivateServer#359]
Hello,  I don't want allow messages from someone, so I selected none on "Allow messages from:", but I still get mesages from someone. Can you fix that?

**Comment by ItzLennyFace** [comment]
Oh, I forgot. GG 100 issues lmao

**Comment by DonAlex0** [comment]
If that person is the server owner they can send messages to everyone no matter what, just saying

**Comment by ItzLennyFace** [comment]
You didn't understand me. I'm server owner and I want block messages from someone, but it doesnt work.
