### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by zetablack** [Cvolton/GMDprivateServer#361]
how can i remove logout error??
i change com.robtopx.geometryjump
to com.oxabgdp.geonetrydash
and it have logout error

**Comment by DarkGD123** [comment]
U shouldn't change (geometryjump)

Do like this
Example: com.darkgdx.geometryjump

**Comment by Cvolton** [comment]
make sure you change the package name in libcocos2d.so too

**Comment by zetablack** [comment]
Lcom/rpbtopx/geometryjump or com.robtopx.geometryjump?

**Comment by Cvolton** [comment]
com.robtopx.geometryjump, dont change the smalis
