### ISSUE TITLE
Reuploaded songs automatically set their size to either 0.00 or -0.00 MB

### ISSUE THREAD

**Issue by SamHep0803** [Cvolton/GMDprivateServer#363]
As the title suggests, whenever I try to upload a song from soundclound or the size is always set to 0.00 or -0.00 MB and when i put the song ID in-game and I play it there is no sound.

I've had to switch hosts because the one I was using before did not support cURL, but the one I am using now has cURL. So I don't know how to solve the issue.

Thanks,
Sam.

**Comment by SamHep0803** [comment]
@Cvolton btw

**Comment by SamHep0803** [comment]
Update: NG and DropBox music plays. Must have something to do with the way the PS handles soundcloud content, please add the bug label.

**Comment by Cvolton** [comment]
make sure you set the soundcloud api key in the config properly

**Comment by Cvolton** [comment]
soundcloud support is completely disabled now due to api changes on their side
https://developers.soundcloud.com/blog/security-updates-api
