### ISSUE TITLE
ok. what is this

### ISSUE THREAD

**Issue by mfeoznik** [Cvolton/GMDprivateServer#365]
Before:
![image](https://user-images.githubusercontent.com/34861386/48669790-cffc1b80-eb35-11e8-8ce3-d21857c607dc.png)
![image](https://user-images.githubusercontent.com/34861386/48669793-df7b6480-eb35-11e8-8c17-bce162397983.png)
After:
![image](https://user-images.githubusercontent.com/34861386/48669801-f0c47100-eb35-11e8-8320-e58c38c94690.png)
![image](https://user-images.githubusercontent.com/34861386/48669807-10f43000-eb36-11e8-87c2-599aa2691088.png)
________________________________________
i think you understand

**Comment by geniiii** [comment]
it is 4 images

**Comment by EndNation** [comment]
You lost 1 level, but it's uploaded. Does it matter much tho?

**Comment by Cvolton** [comment]
robert moment
