### ISSUE TITLE
How do you make an ios version of a GDPS?

### ISSUE THREAD

**Issue by OfficialJacobA** [Cvolton/GMDprivateServer#372]
How do you make an ios version for a GDPS?

**Comment by OfficialJacobA** [comment]
That doesn't tell how...

**Comment by EMREOYUN** [comment]
We aren't IOS developers right? Search for it.

**Comment by OfficialJacobA** [comment]
You know what EMREOYUN... you perfectly represent to the GD Community: toxic, do it yourself stuff, don't care about complex questions. Plus NO ONE WOULD SEARCH IT UP! THIS IS A SMALL GDPS COMMUNITY! You are not thinking of what you are even saying. Saying that "Search for it" would help. Think again! Improve your character!

**Comment by EMREOYUN** [comment]
Read README.md > Setup > Part 3
It's completely "Do It Yourself"

And if you don't want something, please leave this project.

We maked our servers with "Searching Our Problems"

And if you thinking what i am even saying, why you answering me? Why you not waiting other persons to write answers.

"toxic, do it yourself stuff, don't care about complex questions" If you really think about project, PLEASE STOP USING IT!

**Comment by OfficialJacobA** [comment]
EMREOYUN it didn't work. Nice "advice". You need to edit other files as well.

**Comment by EMREOYUN** [comment]
I'm not repo owner. I can't do make changes.

**Comment by Zaxior** [comment]
@EMREOYUN If you dont know how to do that, just dont talk here cuz it makes no sense ;)

**Comment by EMREOYUN** [comment]
@Zaxior at least he gets a response right?

**Comment by Zaxior** [comment]
yes

**Comment by hiimjustin000** [comment]
#469

**Comment by fancythedeveloper** [comment]
at least the autistic kid closed it after a while
