### ISSUE TITLE
GDPS Discord Bot?

### ISSUE THREAD

**Issue by DarkGD123** [Cvolton/GMDprivateServer#374]
How Do I Make One Please Help Cuz 300+ Members Want A GDPS Bot From Our Discord Server

**Comment by EMREOYUN** [comment]
> How Do I Make One Please Help Cuz 300+ Members Want A GDPS Bot From Our Discord Server

There is no known software to connect GDPS with Discord. Sorry :(

**Comment by geniiii** [comment]
https://github.com/Cvolton/pythonCvoltonBot

**Comment by EMREOYUN** [comment]
Let me test this repo. If work, i'll tell hiw ti setup.

**Comment by ItzElectrix** [comment]
@DarkGD123 https://github.com/Alex1304/ultimategdbot/wiki/Self-hosting-guide

**Comment by DoggoTaco** [comment]
You can use UltimateGDbot. The GitHub page for it is [hEre](https://github.com/Alex1304/ultimategdbot)
