### ISSUE TITLE
Connection failed: could not find driver

### ISSUE THREAD

**Issue by EMREOYUN** [Cvolton/GMDprivateServer#375]
Connection failed: could not find driver

**Comment by Cvolton** [comment]
Your php installation is missing the PDO driver, you need to install it. If you're using a shared host then this means that they don't support PDO, which means that they don't support the GDPS

**Comment by EMREOYUN** [comment]
> Your php installation is missing the PDO driver, you need to install it. If you're using a shared host then this means that they don't support PDO, which means that they don't support the GDPS

It is Priv-Shared Host (Paid Nameserver) and What is PDO Driver?

**Comment by EMREOYUN** [comment]
@Cvolton fixed by upgrading PHP version to 7.1 and adding PDO codes to php.ini! Now everything is works. Thank to you :)
