### ISSUE TITLE
How to Make My Own GDPS Command

### ISSUE THREAD

**Issue by DarkGD123** [Cvolton/GMDprivateServer#377]
I Want To Make My Own Command Like !getpass Which Can Gets Level Password...How Do I Make One

**Comment by EMREOYUN** [comment]
Good Question. Try search in Code.

**Comment by Zaxior** [comment]
You need know PHP language to do that..

**Comment by Jecket22** [comment]
Without any understanding how PHP works you will not get anywhere until you learned it.
