### ISSUE TITLE
Bug with searching demons

### ISSUE THREAD

**Issue by cow72** [Cvolton/GMDprivateServer#386]
Hi. I found bug when searching demons. I just selected Demon, click Search and Normal levels appear, but no Demons.

Copied From Zaxior

**Comment by DarkGD123** [comment]
Seems fishy

**Comment by Zaxior** [comment]
lmao

**Comment by Cvolton** [comment]
fixed in 8ff0b2493139d31e5d88b116b3100ffe58038a79
