### ISSUE TITLE
My suggestions

### ISSUE THREAD

**Issue by krvstianeq** [Cvolton/GMDprivateServer#392]
Suggestions:
- Make e-mail confirmation system.
- Add comment ban.
- Add leaderboard anti-cheat and anti likebot.

**Comment by bit0r1n** [comment]
Comment ban?

**Comment by bit0r1n** [comment]
> 
> Maybe he meant blocking send comments?

maybe.. ¯\_(ツ)_/¯

**Comment by DarkGD123** [comment]
And also add forgot password too xD...cuz sometimes we keep forgetting our password

**Comment by Zaxior** [comment]
@bit0r1n @Folleach yea

**Comment by RealistikDash** [comment]
Send system too

**Comment by EndNation** [comment]
Someone made a send system, but Cvolton have not added it yet.
