### ISSUE TITLE
Account in database not continuing

### ISSUE THREAD

**Issue by Absman** [Cvolton/GMDprivateServer#399]
I have a 50+ players gdps
Have much accounts created but the problem is: 
The database don't continue more the account ids
Like somebody created a account after id 26
But dont shows in account in sql 7m.pl.

help!!!!!

**Comment by Zaxior** [comment]
What?

**Comment by DoggoTaco** [comment]
There is multiple pages... There should be a arrow kinda right below the first row, it should be like a solid black. Click on it and it should move you to the next page. I would post a screenshot but 7m.pl's servers are down.
