### ISSUE TITLE
How to make colored comments on non-mods users?

### ISSUE THREAD

**Issue by Zaxior** [Cvolton/GMDprivateServer#402]

**Comment by RealistikDash** [comment]
I think you have to make a role, set the colour and for "isDefault" set it to 1

**Comment by Zaxior** [comment]
Nah I don't want make it for everyone, just for some people

**Comment by RealistikDash** [comment]
Then make a role, don't change anything except the RGB value and assign it to those people

**Comment by Zaxior** [comment]
Doesn't work

**Comment by Cvolton** [comment]
GD only shows comment colors for people with a mod badge set

**Comment by EliezerYT** [comment]
IM have idea for this contact me
