### ISSUE TITLE
Recieved stars for uncompleted levels.

### ISSUE THREAD

**Issue by RealistikDash** [Cvolton/GMDprivateServer#406]
So I have created a 2nd GDPS using the newest files off GitHub. I noticed that it shows that you have gotten stars for levels you haven't completed or haven't played at all (star amount for level turns yellow). This also doesn't let you collect stars for the level.

I do have another GDPS using older files which works perfectly fine.

**Comment by Zaxior** [comment]
This is propably GD bug.

**Comment by RealistikDash** [comment]
I am using the same files that I used for my other gdps.
