### ISSUE TITLE
How to change the default like and download number

### ISSUE THREAD

**Issue by CsAndrisyt** [Cvolton/GMDprivateServer#407]
So I don't want this:

![image](https://user-images.githubusercontent.com/42375133/54079119-636c7e80-42d6-11e9-87e1-b3327299e9dd.png)

**Comment by Zaxior** [comment]
#280

**Comment by CsAndrisyt** [comment]
> #280

I want to set the DEAFULT number to 0. Not change it AFTER i uploaded it

**Comment by Cvolton** [comment]
that changes the default number, it doesn't affect existing levels at all

**Comment by CsAndrisyt** [comment]
thanks
