### ISSUE TITLE
Starting ID > 21

### ISSUE THREAD

**Issue by RealistikDash** [Cvolton/GMDprivateServer#414]
Not an issue but rather a suggestion. After a lot of issues, I have found out that default levels take up IDs 1-21 (eg Stereo Madness = 1, Deadlocked = 20 and Fingerdash). This means that if you complete Fingerdash, you won't be able to get stars for the level with an ID of 21 as GD will think you already got the stars for it (because of Fingerdash).

**Comment by Zaxior** [comment]
Thats a RobTop fault

**Comment by RealistikDash** [comment]
I know but to prevent it change the default is to > 21

**Comment by RealistikDash** [comment]
Clean fix: Reseed autoincrement to a value > 21 (in the 50s to make sure it isnt broken when newer in-game levels come out).

Dirty workaround: Upload a level and manually change its ID to a higher value. Wait for another level to get uploaded and then delete your initial level.

Closing issue.
