### ISSUE TITLE
Reupload Account When Someone Re-uploading A Level

### ISSUE THREAD

**Issue by DarkGD123** [Cvolton/GMDprivateServer#424]
When I Reupload A Level..The Player Name Is (-) How Do I Set A Re-uploaded Level On A Account

**Comment by DarkGD123** [comment]
Please

**Comment by EMREOYUN** [comment]
!setacc <username>

Write in reuploaded level's comments.

**Comment by DarkGD123** [comment]
@EMREOYUN Do u how to set the reupload levels to a re-upload account :D

**Comment by EMREOYUN** [comment]
Idk. I just set !setacc everytime :D
