### ISSUE TITLE
How to change amount of CP you get from a rate / feature / epic?

### ISSUE THREAD

**Issue by Chiefjack** [Cvolton/GMDprivateServer#426]
As title says ^^

**Comment by DarkGD123** [comment]
I dunno if that's possible

**Comment by DarkGD123** [comment]
@Cvolton is it possible

**Comment by Cvolton** [comment]
you need to edit the cron script directly (fixcps.php), the values are hardcoded

**Comment by Chiefjack** [comment]
> you need to edit the cron script directly (fixcps.php), the values are hardcoded

Where are the values in fixcps.php?

**Comment by MarcGD130** [comment]
@Chiefjack you find what u need to edit?

**Comment by Chiefjack** [comment]
> @Chiefjack you find what u need to edit?

Yes

**Comment by DarkGD123** [comment]
@Chiefjack how?

**Comment by DarkGD123** [comment]
@Chiefjack also let me join to ur gdps xD

**Comment by Chiefjack** [comment]
> @Chiefjack also let me join to ur gdps xD

https://discord.gg/hj2smn9

Download in there. I’ll explain how later today, I’m about to go to school so can’t atm

**Comment by DarkGD123** [comment]
So...how @Chiefjack

**Comment by Chiefjack** [comment]
> So...how @Chiefjack

Go to tools/cron/fixcps.php. Where it says `$creatorpoints = $creatorpoints + $cpgain;` add or remove a `+ $cpgain` to add or remove an extra CP.
