### ISSUE TITLE
Downloads won't go above 2

### ISSUE THREAD

**Issue by Chiefjack** [Cvolton/GMDprivateServer#427]
As title says. Why is this and how do I fix it?

**Comment by DarkGD123** [comment]
LMAO....it need people to increase the download number

**Comment by Chiefjack** [comment]
There are people. When I last checked there were 20+ people.

**Comment by Chiefjack** [comment]
There doesn't seem to be an issue with likes now as some levels have more than 2. But downloads are still stuck at 2.

**Comment by Chiefjack** [comment]
@Cvolton can you take a look at this? Is this a bug or something. I asked the person who setup the database etc and he said he used the latest version of this.

**Comment by Cvolton** [comment]
are you behind a proxy? Downloads are supposed to be limited to one per ip address, this sounds like all users are detected as being from the same IP. Check the actions table to see if there isn't one IP address listed for everything

**Comment by Chiefjack** [comment]
> are you behind a proxy? Downloads are supposed to be limited to one per ip address, this sounds like all users are detected as being from the same IP. Check the actions table to see if there isn't one IP address listed for everything

I checked the users and actions tables in phpmyadmin and everyone has a different IP. Any other causes for this. If it was to do with IP, surely likes wouldn’t go above 2 either.

**Comment by Chiefjack** [comment]
@Cvolton can you take a look at this please. See my previous reply for info.

**Comment by Ember1234** [comment]
> @Cvolton can you take a look at this please. See my previous reply for info.

Were you able to solve the problem?

**Comment by Chiefjack** [comment]
> > @Cvolton can you take a look at this please. See my previous reply for info.
> 
> Were you able to solve the problem?

Yes, I fixed it. Go to incl/levels/downloadGJLevel.php. Go to line 56. Change the 2 to a large number, EG. I set it to 200000 because there will never be 200000 people in my GDPS.
