### ISSUE TITLE
Send levels to me

### ISSUE THREAD

**Issue by elnexreal** [Cvolton/GMDprivateServer#428]
I want the moderators to be able to send me levels but I do not know how and where to put the code that the users pass

please explain with images

**Comment by bit0r1n** [comment]
what

**Comment by geniiii** [comment]
![guy](https://user-images.githubusercontent.com/24881499/56693726-e5313380-66ed-11e9-89e5-b41bedef2da1.jpg)

**Comment by DarkGD123** [comment]
@AxelPundang English

**Comment by AxelPundang** [comment]
how do I give the moderators permission to send levels

**Comment by DarkGD123** [comment]
@bit0r1n

**Comment by bit0r1n** [comment]
1. Create role with permission `actionRequestMod`
2. Merge my pull request (#393)

**Comment by MarcGD130** [comment]
@AxelPundang you have gdps discord lemme join also close this issue

**Comment by AxelPundang** [comment]
so

with a discord server?

ok i dont have it

**Comment by Cvolton** [comment]
level suggestions are now an official feature as per 15f5fce and 80802f0
