### ISSUE TITLE
Is this the right thing to make mods rate only difficult/stars

### ISSUE THREAD

**Issue by MarcGD130** [Cvolton/GMDprivateServer#429]
actionRateDemon=1
actionRateStars=0/1
actionRateDifficulty=1
actionRequestMod=1
ect ect
isDefault=1

**Comment by Cvolton** [comment]
isDefault=1 means that you give everyone the role

**Comment by MarcGD130** [comment]
Ok

**Comment by MarcGD130** [comment]
Thanks for the help
