### ISSUE TITLE
Problem with the mod!

### ISSUE THREAD

**Issue by j4ck-code** [Cvolton/GMDprivateServer#434]
I made my roles (moderator and elder moderator) and so i assigned them you know. But, now i cant assign roles to anyone. There are other mods that were assigned, but now it dosent work.

**Comment by DarkGD123** [comment]
lmao make new role and assign them with the new role that u created...I think that's how do it

**Comment by rosenishere** [comment]
idk bro i will try if it works i will close it

**Comment by ItzElectrix** [comment]
You go to roleassign in phpmyadmin or whatever you use to access the database. What you do is that you click Insert, and then put in the correct Account ID and Role ID, then click Go. Have the person restart GD and then click req, and you should be good to go.
