### ISSUE TITLE
Rated levels not working cuz ....

### ISSUE THREAD

**Issue by BULL3TB0T** [Cvolton/GMDprivateServer#437]
Becuz if i rate my level to normal and higher and when i play with it and then it bugs out from the level at the end. Why? I cant fix it. But also auto and easy is working..
OH another thing too profile viewing is bugged too for me cuz it says in every account is GLOBAL RANK 1

**Comment by bit0r1n** [comment]
anti cheat don't kick you if level have rate and his length more than short(from medium to xl)

**Comment by BULL3TB0T** [comment]
but u have discord? can i show it to you?

**Comment by BULL3TB0T** [comment]
OH nevermind ty !!! ily <3
