### ISSUE TITLE
How do I make the mod star rate only

### ISSUE THREAD

**Issue by DarkGD123** [Cvolton/GMDprivateServer#438]

**Comment by BULL3TB0T** [comment]
if you gave them rank that can mod rate. lol

**Comment by DarkGD123** [comment]
@BULL3TB0T lmao

**Comment by EndNation** [comment]
Just give the mods "actionRateStars" I think that's what it is.

**Comment by Cvolton** [comment]
preventing people from featuring levels requires modifications to suggestGJLevels.php
