### ISSUE TITLE
there is issue but i need help with the quest too.

### ISSUE THREAD

**Issue by BULL3TB0T** [Cvolton/GMDprivateServer#439]
how to use this "quests" tab on the sql 
and chests are not working because when i open it the chest is freezed. and then 10 seconds and it says "something went wrong"
_______________________________________________________________________________________________________________
+ more issue

i cant delete the levels from the server. if i press remove nothing happens. how can i fix it tho?

**Comment by ItzElectrix** [comment]
For the quest tab, you need to put something in for the type, amount, reward, and what it would be called.
Here are what the types match up to:
1 = Orbs
2 = Coins
3 = Stars
for the rest, you can put whatever you want as long as it makes sense and follows through to the other quests you fill in.
As for the chests, are you sure you changed the exe file and both connection.php and dailyChests.php correctly? If not, that might be the issue.

**Comment by BULL3TB0T** [comment]
Ye. i did. everything is fine but sometimes is freezing. do u have discord?

**Comment by EMREOYUN** [comment]
Use the delete command for deleting levels.
I didn't remember the command right now.

**Comment by CharMixGd** [comment]
The command is !delete
