### ISSUE TITLE
Issue with Android ver of GDPS

### ISSUE THREAD

**Issue by ItzElectrix** [Cvolton/GMDprivateServer#440]
Ok, so maybe I'm doing something wrong, but let me tell you what I'm doing. I'm using apktool to extract the files, change the texture pack, the database, and the icons, recompiling the folder, and signing the new apk file using SignApk. However, when I try installing the apk file, it won't install for some reason. Does anyone know how to solve this issue?

**Comment by Cvolton** [comment]
if you don't change the package name, you have to uninstall old gd before installing the gdps

**Comment by ItzElectrix** [comment]
I did change the package name though. Idk if just renaming the file does it since I'm not sure where I should actually change it, but the file name is different. Again, I probably didn't do it write since I'm not that good with this stuff :V

**Comment by EMREOYUN** [comment]
"change the texture pack, the database, and the icons"

Seems you corrupted the apk file somehow.

**Comment by Cvolton** [comment]
the package name is defined in androidmanifest.xml, the file name has nothing to do with it

**Comment by ItzElectrix** [comment]
> the package name is defined in androidmanifest.xml, the file name has nothing to do with it

Even after I change the package name, the app still won't install.

**Comment by DarkGD123** [comment]
dms me @ItzElectrix I'm on clarifygdps lmao TheRealAleX#4802

**Comment by EMREOYUN** [comment]
Try without changing any texture and icon.

**Comment by DarkGD123** [comment]
@ItzElectrix Do u Use PC to do that?
If u do try to just edit the website encode website and package name...
Just don't add custom texture

**Comment by ItzElectrix** [comment]
Yes I use PC. I can try without the texture pack, but I would want one added for it.

**Comment by ItzElectrix** [comment]
Even after I change just the package name, it still won't install. I don't know if I'm trying to download the wrong file or something.

**Comment by EMREOYUN** [comment]
Can you send one of your compiled apk to us?(Texture not changed and signed)

**Comment by ItzElectrix** [comment]
Apk files won't send here. The file type isn't supported.

**Comment by ItzElectrix** [comment]
I think I know what my issue is. I need to find a way to combine the newly compressed apk file with the signed one, and I don't know how to do that. I've been uploading the non-signed version the whole time.

**Comment by ItzElectrix** [comment]
Never mind, I figured out my issue, and it works now. Thanks a lot for your help, guys.
