### ISSUE TITLE
I can't import database.sql

### ISSUE THREAD

**Issue by rust2** [Cvolton/GMDprivateServer#441]
![Screenshot](https://user-images.githubusercontent.com/43823272/58133933-bbacee80-7c3e-11e9-8cea-f812eecf08a7.png)

What should I do?

**Comment by DarkGD123** [comment]
Redo it

**Comment by rust2** [comment]
@DarkGD123,
It appears every time when I redo it

**Comment by Cvolton** [comment]
make sure to select a database before importing

**Comment by rust2** [comment]
@Cvolton, I'm trying to import this DB as others DBs, and others are importing successful

**Comment by rust2** [comment]
@Cvolton, I'm sure that I'm selecting this DB

**Comment by EMREOYUN** [comment]
You are using old version of mysql. Upgrade to 5.5.3(i think that version of that error fixed) version.

**Comment by DarkGD123** [comment]
I think he's self hosting himself

**Comment by rust2** [comment]
@EMREOYUN, Ok I'll try update it

**Comment by EMREOYUN** [comment]
@DarkGD123 Can be. I'm always self hosting my server via xampp.
