### ISSUE TITLE
Suggest System Message

### ISSUE THREAD

**Issue by DarkoN1** [Cvolton/GMDprivateServer#443]
so i got suggest system working correctly but instead of checking suggestList.php 
i want get message in game with level id who suggested etc. any ideas? sorry for bad english
Thanks.

**Comment by DarkGD123** [comment]
@bit0r1n

**Comment by bit0r1n** [comment]
if you want send message from bot, you can use function from mainLib `sendDiscordPM(user_id, message)`.
or if you want use webhook, use this function
`<?php
	$url = "webhook_url";
	$hook = json_encode([
		"content" => "message content"
	], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
	$ch = curl_init();
	curl_setopt_array( $ch, [
		CURLOPT_URL => $url,
		CURLOPT_POST => true,
		CURLOPT_POSTFIELDS => $hook,
		CURLOPT_HTTPHEADER => [
		"Length" => strlen($hook),
			"Content-Type" => "application/json"
		]
	]);
	$response = curl_exec($ch);
	curl_close($ch);
?>`

**Comment by DarkoN1** [comment]
> 
> 
> if you want send message from bot, you can use function from mainLib `sendDiscordPM(user_id, message)`.
> or if you want use webhook, use this function
> 
> `<?php $url = "webhook_url"; $hook = json_encode([ "content" => "message content" ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE); $ch = curl_init(); curl_setopt_array( $ch, [ CURLOPT_URL => $url, CURLOPT_POST => true, CURLOPT_POSTFIELDS => $hook, CURLOPT_HTTPHEADER => [ "Length" => strlen($hook), "Content-Type" => "application/json" ] ]); $response = curl_exec($ch); curl_close($ch); ?>`

i mean when mod suggests a level i get message with a level id.

**Comment by bit0r1n** [comment]
😑

**Comment by DarkoN1** [comment]
@bit0r1n

**Comment by DarkoN1** [comment]
ok. where i need put the 			sendDiscordPM(id, message) aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by DarkoN1** [comment]
> 
> 
> expressionless

can ya help meh?

**Comment by bit0r1n** [comment]
`$gs->sendDiscorsPM(id, "suggested level by ".$accountID.". Level ID: ".$levelID)` near suggest function

**Comment by DarkoN1** [comment]
> 
> 
> `$gs->sendDiscorsPM(id, "suggested level by ".$accountID.". Level ID: ".$levelID)` near suggest function

![hmm](https://user-images.githubusercontent.com/51049087/58384174-059b2900-7fdf-11e9-9939-5bb9f078f647.PNG)
like this?

**Comment by bit0r1n** [comment]
try it

**Comment by DarkoN1** [comment]
> 
> 
> try it

nope. doesnt work

**Comment by DarkoN1** [comment]
i tried sendDiscorsPM and sendDiscordPM tho

**Comment by bit0r1n** [comment]
@DarkoN1 what's error (error_log)?

**Comment by DarkoN1** [comment]
where i can find that

**Comment by bit0r1n** [comment]
in the folder with suggestGJStars

**Comment by DarkoN1** [comment]
![hmm2](https://user-images.githubusercontent.com/51049087/58384224-ae498880-7fdf-11e9-8492-56bd317d690e.PNG)
hmm

**Comment by bit0r1n** [comment]
try to change id from integer to string

**Comment by bit0r1n** [comment]
or maybe you didn't configurate bot access

**Comment by DarkoN1** [comment]
bot is working on discord

**Comment by DarkoN1** [comment]
> 
> 
> try to change id from integer to string

discord id?

**Comment by bit0r1n** [comment]
bot access config placed on ~/config/discord.php
hmh, your account id

**Comment by DarkoN1** [comment]
![aaaaa](https://user-images.githubusercontent.com/51049087/58384317-ae965380-7fe0-11e9-99c1-9331b62bf23b.PNG)


> 
> 
> bot access config placed on ~/config/discord.php
> hmh, your account id

![aaaaa](https://user-images.githubusercontent.com/51049087/58384320-b3f39e00-7fe0-11e9-8281-8a3aab66d979.PNG)

**Comment by DarkoN1** [comment]
bot is working on discord. and account id is typed.

> 
> 
> bot access config placed on ~/config/discord.php
> hmh, your account id

**Comment by DarkoN1** [comment]
> 
> 
> `$gs->sendDiscorsPM(id, "suggested level by ".$accountID.". Level ID: ".$levelID)` near suggest function

oof, it didnt worked cuz at end there wasnt ;  thanks so much dude

**Comment by DarkoN1** [comment]
@bit0r1n 
![444444](https://user-images.githubusercontent.com/51049087/58384651-80b30e00-7fe4-11e9-920b-932cb76365ba.PNG)

is there way to put username instead of accountID ?

**Comment by bit0r1n** [comment]
`$gs->getAccountName($accountID)`

**Comment by DarkoN1** [comment]
> $gs->getAccountName($accountID)

![1235edrf](https://user-images.githubusercontent.com/51049087/58384719-5281fe00-7fe5-11e9-819c-fc942807569e.PNG)
bot is still sending me id. or i did something wrong

**Comment by bit0r1n** [comment]
put it in message content😑

**Comment by DarkoN1** [comment]
oooo

**Comment by DarkoN1** [comment]
did it thanks

**Comment by DarkGD123** [comment]
Hey @bit0r1n I use a Webhook but it has token..but has no secret...do I only put the token on discord.php? Or I will leave it blank

**Comment by bit0r1n** [comment]
@DarkGD123 bot has ID and TOKEN, you leave it(full webhook link) in url variable

**Comment by DarkGD123** [comment]
Also where do i put this code in mainLib.php line <?php $url = "webhook_url"; $hook = json_encode([ "content" => "message content" ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE); $ch = curl_init(); curl_setopt_array( $ch, [ CURLOPT_URL => $url, CURLOPT_POST => true, CURLOPT_POSTFIELDS => $hook, CURLOPT_HTTPHEADER => [ "Length" => strlen($hook), "Content-Type" => "application/json" ] ]); $response = curl_exec($ch); curl_close($ch); ?>

**Comment by DarkGD123** [comment]
`<?php $url = "webhook_url"; $hook = json_encode([ "content" => "message content" ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE); $ch = curl_init(); curl_setopt_array( $ch, [ CURLOPT_URL => $url, CURLOPT_POST => true, CURLOPT_POSTFIELDS => $hook, CURLOPT_HTTPHEADER => [ "Length" => strlen($hook), "Content-Type" => "application/json" ] ]); $response = curl_exec($ch); curl_close($ch); ?>`


Where do I put This in mainLib.php line @bit0r1n

**Comment by bit0r1n** [comment]
you can copy from here https://altir.xyz/webhook

**Comment by bit0r1n** [comment]
and put variable webhookurl into discord.php

**Comment by DarkGD123** [comment]
Ok thanks

**Comment by DarkGD123** [comment]
If I make a discord bot what will I put it so it will send to its channel destination..and like saying someone sent a lvl @bit0r1n

**Comment by bit0r1n** [comment]
> 
> 
> If I make a discord bot what will I put it so it will send to its channel destination..and like saying someone sent a lvl @bit0r1n

for sending message to guild's channel remake function sendDiscordPM(in url variable replace channelID variable to guild's channel id)

**Comment by DarkGD123** [comment]
![Screenshot_20190530-094812](https://user-images.githubusercontent.com/42462384/58602616-2eae0900-82c0-11e9-963e-1b3eaba6e8a5.png)

**Comment by DarkGD123** [comment]
Also I already put my Webhook id
