### ISSUE TITLE
Why the downloads dont pass above 302?

### ISSUE THREAD

**Issue by Novi890s** [Cvolton/GMDprivateServer#444]
I dont know why see this
Download:302
Likes:104

**Comment by DarkGD123** [comment]
Database>levels table>structure>downloads 300 and likes 100 change them to 0..done

**Comment by DarkGD123** [comment]
K

**Comment by DoggoTaco** [comment]
> I dont know why see this
> Download:302
> Likes:104

Are you asking why the levels downloads and likes are above 0 on upload?

**Comment by Jecket22** [comment]
I assume you use 7m.pl.
If so, there's the issue,.

**Comment by Cvolton** [comment]
fixed in 5e3afedcd992d42911d0fb7b82e93045e6fed6b8, 0a123cb5ef87c16ee41a84fc24cde5caa14d7d74 and ace54eca528a309c8784bc1d87d10c152f769efb
