### ISSUE TITLE
RoleAssign from page

### ISSUE THREAD

**Issue by DarkoN1** [Cvolton/GMDprivateServer#445]
so i need help to make .php page where users with isAdmin=1 permission can Assign Roles. Thanks

**Comment by bit0r1n** [comment]
you can use this code
https://pastebin.com/s6sHUK55

**Comment by DarkoN1** [comment]
> 
> 
> you can use this code
> https://pastebin.com/s6sHUK55

anyone can use this code :/ i want do it only for admins

**Comment by DarkoN1** [comment]
> 
> 
> you can use this code
> https://pastebin.com/s6sHUK55

thanks, and one more question do u have code to remove assigned roles?
