### ISSUE TITLE
PROBLEMS WITH DAILY, WEEKLY FOR ID 71

### ISSUE THREAD

**Issue by EliezerYT** [Cvolton/GMDprivateServer#454]
Hi iam creator for server.. and create first account with Robtop (AccID: 71 )  and me not update dailys and weeklys.. other members yes and for me no.. solution plz =)

**Comment by DarkGD123** [comment]
LMAO U didn't set a level daily/weekly

**Comment by EliezerYT** [comment]
yes others members show this

**Comment by Vorrik** [comment]
Yeah, this problem, help me pls

**Comment by EliezerYT** [comment]
respond me lplz im waiting

**Comment by DoggoTaco** [comment]
1. Did you give yourself mod or admin? Just giving yourself robtops id won't automatically give it to you.
2. Did you do the !daily command on the level you want to make daily? After that you will need to wait till it is available the next day.

**Comment by EliezerYT** [comment]
men this other users view the daily level me nope
