### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by AnimeDasher** [Cvolton/GMDprivateServer#456]
Hey, I am needing an up to date tutorial for this! This method is so old and I need a gdps for my yt.
Any help will be appreciated.
I use
FileZilla
7m.pl
tell me if i should use something else.

**Comment by bit0r1n** [comment]
you need only ftp client(to connect), mysql, web hosting with php (since 5.6)

**Comment by AnimeDasher** [comment]
I got everything setup now, but when I customise the exe it still says that its on the normal gd servers, the connection.php is working, and i edited the exe, it says something about base 64 somewhere or something like that, any way in fixing that?
Also thx for the response.

**Comment by bit0r1n** [comment]
you need encode your server url(path to root folder with server files" to base64 and change it in client exe

**Comment by AnimeDasher** [comment]
? how ?

**Comment by bit0r1n** [comment]
https://youtu.be/6HDJoJ7vpOI

**Comment by AnimeDasher** [comment]
im still lost -_- i looked at the video and I am so confused

**Comment by bit0r1n** [comment]
at what point are you confused.. it's simple

**Comment by AnimeDasher** [comment]
aight, so the server I have is in Free Hosting Arena, adn your doing stuff with local, have not slept in 30 hrs so please understand why im so dumb. But yeah I have every boomlings thing set to my website webpage url (www.animdaps.ueuo.com) thing, what now

**Comment by bit0r1n** [comment]
just do all from video but change in your mind "http://localhost" to "http://animdaps.ueuo.com" (and don't forget about link length limit in 33 characters(33-24=9-1(/)=8 characters to 'root' server folder))

**Comment by AnimeDasher** [comment]
do you speak english, and is it possible we can get in a discord call, if we can : AnimeDasher#8452

**Comment by bit0r1n** [comment]
sry, i cant speak english

**Comment by AnimeDasher** [comment]
k

**Comment by AnimeDasher** [comment]
How do you get that bot

**Comment by AnimeDasher** [comment]
and is the length limit a required length

**Comment by bit0r1n** [comment]
bot is my, you can invite on https://altir.xyz/invite (or you can just google "base64 encode"), and length limit is required, if liength doesn't match original length - you can't launch app

**Comment by AnimeDasher** [comment]
it says only certain people can access that command, can I have access

**Comment by bit0r1n** [comment]
if you say about 'eval' command - i can't give access to this command, you can use for example http://string-functions.com/length.aspx this site

**Comment by AnimeDasher** [comment]
when i put in https://www.boomlings.com/database
i get 36 char, is that ok?

**Comment by AnimeDasher** [comment]
i am 1 char off on my website :( how do i resolve this

**Comment by bit0r1n** [comment]
maybe you putted quotes at start and end, and original link doesn't have https://, he has http://

**Comment by AnimeDasher** [comment]
k, its the right size now, now once I get my url base64 encoded where do I go from there?

**Comment by bit0r1n** [comment]
now use hex editor, and open game exe file(you can view this in video) and edit original url/base64 url to your url/base64 url

**Comment by AnimeDasher** [comment]
I have but what do i do once I have done it, what do i save it as

**Comment by bit0r1n** [comment]
just save file (ctrl s)

**Comment by AnimeDasher** [comment]
gonna restart on the hex editiong to make sure i am doing it right

**Comment by bit0r1n** [comment]
just replace all, editor will notice you, if you put larger/shorter link/encoded link

**Comment by AnimeDasher** [comment]
aight, im retarded
http://www.boomlings.com/database
https://animdaps.ueuo.com/database
are these correct?

**Comment by bit0r1n** [comment]
no, remove 1 character

**Comment by AnimeDasher** [comment]
from?

**Comment by bit0r1n** [comment]
you can just rename folder for ex. `databas`

**Comment by AnimeDasher** [comment]
k

**Comment by AnimeDasher** [comment]
![image](https://user-images.githubusercontent.com/52329847/60396390-16d4d980-9b39-11e9-81d5-465c7084050b.png)

Says it cannot find the http://boomlings.com/database as a base 64

**Comment by bit0r1n** [comment]
http://www.boomlings.com/database

**Comment by AnimeDasher** [comment]
it says it cannot find the base 64 and the url, am I good to go now?

**Comment by AnimeDasher** [comment]
game refuses to boot -_-

**Comment by bit0r1n** [comment]
url: http://www.boomlings.com/database
base64: aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL2RhdGFiYXNl

url: https://animdaps.ueuo.com/databas
base64: aHR0cHM6Ly9hbmltZGFwcy51ZXVvLmNvbS9kYXRhYmFz

**Comment by bit0r1n** [comment]
when you edit file editor says something besides successfully replacement

**Comment by AnimeDasher** [comment]
trying now

**Comment by AnimeDasher** [comment]
![image](https://user-images.githubusercontent.com/52329847/60396521-93b48300-9b3a-11e9-8c68-3bf18aa73d0c.png)

Did that first, that good?

**Comment by AnimeDasher** [comment]
Then i got this
![image](https://user-images.githubusercontent.com/52329847/60396537-b5156f00-9b3a-11e9-9c28-893f2cb67429.png)

**Comment by bit0r1n** [comment]
maybe, dont forget to replace url, not only base64

**Comment by AnimeDasher** [comment]
I have done both, what do i do now.

**Comment by AnimeDasher** [comment]
I did exactly what you told me to and it wont open ; _ ;

**Comment by bit0r1n** [comment]
now configure server-side (upload files, edit conenction config, import sql file into database)

**Comment by AnimeDasher** [comment]
like the game files?

**Comment by bit0r1n** [comment]
no, just view in video, mysql data access and database

**Comment by AnimeDasher** [comment]
So do i delete everything from server apart from the 'Databas' directory, then add everything back?

**Comment by bit0r1n** [comment]
no, just upload files to "databas" folder

**Comment by AnimeDasher** [comment]
? the database files? and what do i need to edit, cause I have the connection edited I think

**Comment by bit0r1n** [comment]
~/config/connection.php

**Comment by bit0r1n** [comment]
upload server files from archive to "databas" folder

**Comment by AnimeDasher** [comment]
there are files already there

**Comment by AnimeDasher** [comment]
will there be issues

**Comment by AnimeDasher** [comment]
I have put the archive into the server, but when I try open the game .exe it still refuses to load the game. I am assuming that there are further steps.

**Comment by bit0r1n** [comment]
just take my exe pls maybe i will soon go crazy

[GeometryDash.zip](https://github.com/Cvolton/GMDprivateServer/files/3342907/GeometryDash.zip)

**Comment by AnimeDasher** [comment]
k thx im tired af, but is it setup?

**Comment by AnimeDasher** [comment]
what do you want me to do with exe

**Comment by bit0r1n** [comment]
nothing, just use

**Comment by AnimeDasher** [comment]
doesn't work -_- I gfive up, thx for the help anyways.

**Comment by DarkGD123** [comment]
Idiot

**Comment by DarkGD123** [comment]
Idiot

**Comment by ItzElectrix** [comment]
I can try helping even though I'm late. @AnimeDasher, Where are you at right now?

**Comment by AnimeDasher** [comment]
got a working bot :3

**Comment by AnimeDasher** [comment]
*server
