### ISSUE TITLE
cron error

### ISSUE THREAD

**Issue by MegaSa1nt** [Cvolton/GMDprivateServer#457]
( ! ) Warning: file_put_contents(../logs/fixcpslog.txt): failed to open stream: No such file or directory in /var/www/vhosts/annamilklve.7m.pl/httpdocs/database/tools/cron/fixcps.php on line 18
--

1 | 0.0006 | 288640 | {main}( ) | ../fixcps.php:0
2 | 0.0007 | 289064 | file_put_contents ( ) | ../fixcps.php:18

what the hell? cp not updating.

**Comment by bit0r1n** [comment]
pls read warning, don't create dumb issue. create file "fixcpslog.txt" in folder ~/tools/logs/ or in ~/tools, i don't remember exactly

**Comment by Jecket22** [comment]
Simply create a log file in the logs folder. You can also simply ignore it.

**Comment by EndNation** [comment]
Create a folder called logs in tool. And in that folder, create an empty file called fixcpslog.txt
