### ISSUE TITLE
W h y ? ? ?

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [Cvolton/GMDprivateServer#460]
I delete my account in the database at accounts and users.
Then I register again.
After I log in , pop your account is disabled.
Why ? ? ?

**Comment by bit0r1n** [comment]
try to delete account from `~/data/accounts`

**Comment by WOSHIZHAZHA120** [comment]
I didn't save the data......

**Comment by WOSHIZHAZHA120** [comment]
@bit0r1n i didn't save the data...

**Comment by WOSHIZHAZHA120** [comment]
it's OK now.
