### ISSUE TITLE
How create a verification email? 

### ISSUE THREAD

**Issue by Gibsix** [Cvolton/GMDprivateServer#462]
I need to create to this for secure of server

**Comment by DarkGD123** [comment]
u need a lot of stuff

**Comment by bit0r1n** [comment]
you can view this functional in https://github.com/DonAlex0/GMDPrivateServer

**Comment by DarkGD123** [comment]
How do I get a smtp @bit0r1n

**Comment by bit0r1n** [comment]
if you have own domain (amd email server), smtp is a outgoing mail server
