### ISSUE TITLE
Problem with Editing GeometryDash.exe

### ISSUE THREAD

**Issue by ItzElectrix** [Cvolton/GMDprivateServer#463]
Okay, so this doesn't have much to do with the server part of the GDPS, but I thought this would be a good place to ask.
So I've been trying to edit certain things in the exe file so it's more suited for a GDPS. I've been currently working on changing anything that says "RobTop Games" to my name (ItzElectrix). However, after I change the name in the free rewards, I get the error shown in the image below.
![Capture](https://user-images.githubusercontent.com/50182312/61741487-080bcc00-ad5f-11e9-96cf-8db39ce80696.JPG) 
Is there any way I can fix it so that I don't get the error, but I can still put my name in instead of RobTop Games?
(oh and btw i already know about keeping the character count the same, so i know that's not an issue)

**Comment by Cvolton** [comment]
This error is related to the quick launch shortcut, try opening the exe directly

**Comment by ItzElectrix** [comment]
Okay, that worked. Thanks!
