### ISSUE TITLE
Connection.php

### ISSUE THREAD

**Issue by Hakine** [Cvolton/GMDprivateServer#464]
How can i edit it?
Im using http://hakinegdpss.rf.gd/

**Comment by DonAlex0** [comment]
Don't even bother, your server's hosting service doesn't support engines that don't support JS, thus it doesn't support GD (completely verified this).

**Comment by Hakine** [comment]
oh

**Comment by Hakine** [comment]
7m.pl support it, but 3gb

**Comment by DonAlex0** [comment]
I'm just saying, what hosting service to use is up to you, but least make sure it supports GD

**Comment by Hakine** [comment]
ok thank you
