### ISSUE TITLE
Mod badges colour

### ISSUE THREAD

**Issue by SharkWhiteGD** [Cvolton/GMDprivateServer#466]
How can I change the colour of a mod's badge, so I can easily see if it is a mod(yellow badge) or a helper? (with, for example, a black badge)

**Comment by bit0r1n** [comment]
gd have only 2 badges, and they stores on client side

**Comment by SharkWhiteGD** [comment]
but I've seen some gdps with custom badges

**Comment by SharkWhiteGD** [comment]
oh okay, thanks :)
