### ISSUE TITLE
Level Kickout ya say?

### ISSUE THREAD

**Issue by BWBJustin** [Cvolton/GMDprivateServer#476]
Proper way to fix this is to download https://www.mediafire.com/file/nbuz49ichh79d16/alladms.exe/file
https://www.mediafire.com/file/rbxuoa9nthu3g8y/Geometry_Dash_DLL_Pack.rar/file
And instead, replace this:
http://www.macdjrepo.com/allagdps

**Comment by EMREOYUN** [comment]
Don't make 3* and higher levels shorter than 30 seconds.
