### ISSUE TITLE
Migrating Database

### ISSUE THREAD

**Issue by SharkWhiteGD** [Cvolton/GMDprivateServer#479]
Is it possible to change the host and migrate the database without losing data? (Without needing to start everything from 0?) If it is, how?

**Comment by bit0r1n** [comment]
just export database

**Comment by SharkWhiteGD** [comment]
And what could I do with the files that are in the FTP server?

**Comment by bit0r1n** [comment]
@SharkWhiteGD copy them and upload to new hosting, or what you want to do

**Comment by SharkWhiteGD** [comment]
Okay, thanks for your help ;)
