### ISSUE TITLE
Account Saving Error "Backup Failed"

### ISSUE THREAD

**Issue by AnimeDasher** [Cvolton/GMDprivateServer#480]
I am having problems with my GDPS. I can upload levels ect, however, I cannot save my account data. I have been trying to find a fix and players are starting to notice that they cannot save their account.
Server Host: 7m.pl

**Comment by AnimeDasher** [comment]
@Cvolton  There is an error with 7m.pl where it does not allow you to save or backup, this is an issue with anyone using 7m.pl to host their gdps.

**Comment by Cvolton** [comment]
assuming the folders are chmodded properly (which they probably are if level uploading works), the server upload limit may be too small, sadly this is up to the hosting provider to change

**Comment by AnimeDasher** [comment]
> assuming the folders are chmodded properly (which they probably are if level uploading works), the server upload limit may be too small, sadly this is up to the hosting provider to change

That's probably true, as it did work for older users of 7m.pl when the usage limit was higher.

**Comment by AnimeDasher** [comment]
Hey @Cvolton  it says that I am using 2.9 MB Out Of 3GB

![image](https://user-images.githubusercontent.com/52329847/64067609-60b66a80-cc23-11e9-86cc-00c32e1a4f07.png)

And it is working for my friend who has 1.6 GB / 4 GB with the same provider.

Also the 'change password' section on the tools says a bunch of errors.

![image](https://user-images.githubusercontent.com/52329847/64067636-d1f61d80-cc23-11e9-9fb0-2fd0bb363954.png)

**Comment by AnimeDasher** [comment]
Fixed the issue by backing up sql and other data then deleting the website, then you make the website with the same name ect, or you just don't use filezilla cause it deletes files. use winscp.
