### ISSUE TITLE
How to ban hackers? PLS IMPORTANT

### ISSUE THREAD

**Issue by SharkWhiteGD** [Cvolton/GMDprivateServer#481]
Well, somebody hacked my server and now the leaderboard consists of accounts called "Transhack(number)". Do I need to ban each account? There are like THREE HUNDRED. Is there any faster way?

**Comment by DarkGD123** [comment]
delete the accounts or ban them via *leaderboardsBan.php*

**Comment by Jecket22** [comment]
Just run cronjob in the tools page, it's that easy.
