### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by GoodGamerG** [Cvolton/GMDprivateServer#483]
How to setup discord bot?

**Comment by bit0r1n** [comment]
`~/tools/bot/*` is just GET endpoints. For example, in NodeJS you can use default `https` module to make GET requests, or something else from npm.

**Comment by valkyrienyanko** [comment]
@GoodGamerG If you're still interested in setting up a discord bot you should take a look at this https://discord.js.org/#/

**Comment by Cvolton** [comment]
you can use the bot I use as a base, just keep in mind that it also includes a few features unrelated to the GDPS https://github.com/Cvolton/pythonCvoltonBot
