### ISSUE TITLE
I forgot my password :c pls help !

### ISSUE THREAD

**Issue by VoomiTo421** [Cvolton/GMDprivateServer#485]
Hi, i forgot my password :v im so noob to memorize can any one help me please ?

**Comment by VoomiTo421** [comment]
:v

**Comment by bit0r1n** [comment]
generate password with `password_hash("your password", PASSWORD_DEFAULT);` and replace password in database to this

**Comment by Dom1nusYT** [comment]
> generate password with `password_hash("your password", PASSWORD_DEFAULT);` and replace password in database to this

Where i need help too

**Comment by bit0r1n** [comment]
@Dom1nusYT what you mean

**Comment by Dom1nusYT** [comment]
how to create new password?

**Comment by bit0r1n** [comment]
use php method password_hash

**Comment by Dom1nusYT** [comment]
where?

**Comment by Dom1nusYT** [comment]
> use php method `password_hash `

pls help

**Comment by bit0r1n** [comment]
@Dom1nusYT what you want??
if you need execute php code somewhere, just google `php sandbox`

**Comment by Catover203** [comment]
bit0r1nPass = $2y$10$6iNwkbJ5WXgLSGjH8TeoM.Sjj4UhQ/Fm7jozbhilBNdkFXXCVxzAW
hashed password, just change this in your database
