### ISSUE TITLE
Uploaded Levels can't be play

### ISSUE THREAD

**Issue by MissCupcake9** [Cvolton/GMDprivateServer#489]
basically when i upload a level with custom music or not whatever the lenght what happens is i can get the level and look at it but when i lick the play button it just reload and nothing happens if this can help im using the 2.0 (since i tried everything to make a 2.1 server but it never worked and if anyone can help with this it would be nice)

**Comment by bit0r1n** [comment]
hmm, that strange, this emulator saves/gives full level string. on your server only you or all players have this problem?

**Comment by MissCupcake9** [comment]
everyone has this problem everyone can upload levels custom music work fine rate work as well but no one can play any online levels

**Comment by Cvolton** [comment]
make sure the server has write permissions to the data folder

**Comment by MissCupcake9** [comment]
> make sure the server has write permissions to the data folder

may you please be a little more specific is it in the databse i need to check or is it in the GD file or in net2ftp files i uploaded?

And is it a speicific file i need to modify kind of new to the servers i ran into many issues but this one was really confusing me... i also did all the step in your video on how to make a GD server

**Comment by Cvolton** [comment]
in net2ftp chmod 777 the data folder
