### ISSUE TITLE
How to transfer levels to accounts on a gdps

### ISSUE THREAD

**Issue by Telpo** [Cvolton/GMDprivateServer#501]
What's the command to transfer levels in a gdps, all I think I remember is that is.!t something but I've tried every combination and got nothing, plz help

**Comment by Jecket22** [comment]
It has no command. You will find all the tools in \<yourlink\>/\<database\>/tools

**Comment by Cvolton** [comment]
!setacc?

**Comment by Telpo** [comment]
Thx cvolton it was that
