### ISSUE TITLE
CP isn't working

### ISSUE THREAD

**Issue by GDDogeYT** [Cvolton/GMDprivateServer#516]
My players made some levels and they got featured, although they didn't get any CP ._. Can you please help me?

**Comment by bit0r1n** [comment]
you need to run cron job for updating this info

**Comment by GDDogeYT** [comment]
> you need to run cron job for updating this info

what is cron job and where is it?

**Comment by bit0r1n** [comment]
script for update info located in `~/tools/cron/cron.php`, you need run this script for updating
cron job runs this script automatically

**Comment by GDDogeYT** [comment]
> script for update info located in `~/tools/cron/cron.php`, you need run this script for updating
> cron job runs this script automatically

im using an ftp client, so i basically just double click the cron.php?

**Comment by DoggoTaco** [comment]
To run the script you can go to <Your Website Name>/database/tools/ and find the cron option.

**Comment by GDDogeYT** [comment]
> To run the script you can go to /database/tools/ and find the cron option.

i found the cron directory, but how do i run cron.php?

**Comment by bit0r1n** [comment]
just open this php file as usually site page

**Comment by GDDogeYT** [comment]
> just open this php file as usually site page

Wow it actually worked thanks guys!
