### ISSUE TITLE
Android apk

### ISSUE THREAD

**Issue by ImYoshiGD** [Cvolton/GMDprivateServer#517]
I'm trying to make my GDPS to PC(done) and Android, but when I make the android game apk
and I open it, the aplication closes with the message: "(APK) has stopped."

I need help, please.

**Comment by EMREOYUN** [comment]
You did something wrong, or you didn't some parts of creating an APK. Please watch tutorial carefully and redo things.

"(APK) has stopped." can causeable for any reason regards of that.

**Comment by ImYoshiGD** [comment]
Okay, could that error be a cause of a different apk version?

**Comment by EMREOYUN** [comment]
Which version you are trying to make APK?

**Comment by ImYoshiGD** [comment]
In the phpMyAdmin, the version is "21", it could be 2.100, but I'm not sure if all numbers are showed, I tried with 2.113 and 2.11 versions and didn't work.

**Comment by EMREOYUN** [comment]
2.11 and beyond is not tested and may not work on APK versions. If you can, use 2.1 APK.

**Comment by DoggoTaco** [comment]
> 2.11 and beyond is not tested and may not work on APK versions. If you can, use 2.1 APK.

2.11 worked for my gdps.



> I'm trying to make my GDPS to PC(done) and Android, but when I make the android game apk
> and I open it, the aplication closes with the message: "(APK) has stopped."
> 
> I need help, please.

Make sure you followed everything carefully and stuff. If you just opened the apk in like notepad++ and replaced robtops database with yours, that won't work at all.

**Comment by ImYoshiGD** [comment]
Yes, I tried to replace in NotePad++ using folders that were not on my PC, from OneDrive.
Now I fixed it and now the GDPS works for Android. Sorry for the lost time and trying to help me ^^
