### ISSUE TITLE
Saving and syncing accounts has stopped working (PLEASE HELP REALLY IMPORTANT)

### ISSUE THREAD

**Issue by GDDogeYT** [Cvolton/GMDprivateServer#520]
So basically i have a GDPS with like 30+ people and its doing great but for some reason the account Save and Load isnt working. People are really unhappy and half of them lost their progress! Please help!

**Comment by GDDogeYT** [comment]
Here

**Comment by GDDogeYT** [comment]
Basically it worked before and now it doesn't

**Comment by Cvolton** [comment]
There could be many reasons for this to happen
1. The server doesn't have write access to the "accounts" folder (this is unlikely if it worked before though)
2. The save files are too large for the limit set on the server (if you're on a shared host, there is usually no way for you to change this. You can test this by attempting to back up a saved game with very little progress.)

**Comment by GDDogeYT** [comment]
Ok im pretty sure its the second one ima test it
