### ISSUE TITLE
How to setup a bot using discord.php

### ISSUE THREAD

**Issue by CattoDev** [Cvolton/GMDprivateServer#521]
Hey i was wondering how to setup a bot for my GDPS and what can it do?

**Comment by bit0r1n** [comment]
Bot in this emulator can link your gdps account with discord account. You can understand what discord.php need by variables names

**Comment by GDDogeYT** [comment]
> Bot in this emulator can link your gdps account with discord account. You can understand what discord.php need by variables names

https://imgur.com/di2YYF7 Ok so I basically change the "$discordEnabled = 0" to "$discordEnabled = 1" but can you tell me how do i code the discord bot like is there any other package i need to install?

**Comment by DoggoTaco** [comment]
> is there any other package i need to install?

There are already coded bots like UltimateGDBot that are open source and have instructions, so you don't need to code your own.

**Comment by bit0r1n** [comment]
you no need to install any packages, simple(or example) methods are located in `~/incl/lib/mainLib.php`

**Comment by EMREOYUN** [comment]
@Cvolton is discord code works now? If yes, can you provide "How To" to wiki?

**Comment by Cvolton** [comment]
it was always in a semi-functional state, it's meant to be used in conjunction with this https://github.com/Cvolton/pythonCvoltonBot (or a custom bot implementation)

**Comment by EMREOYUN** [comment]
> it was always in a semi-functional state, it's meant to be used in conjunction with this https://github.com/Cvolton/pythonCvoltonBot (or a custom bot implementation)

Still we need a wiki or "How to Do" to setup properly.

**Comment by RxNationGaming** [comment]
> it was always in a semi-functional state, it's meant to be used in conjunction with this https://github.com/Cvolton/pythonCvoltonBot (or a custom bot implementation)

@Cvolton I cannot run it on heroku

**Comment by GGaMErZZ** [comment]
> > it was always in a semi-functional state, it's meant to be used in conjunction with this https://github.com/Cvolton/pythonCvoltonBot (or a custom bot implementation)
> 
> @Cvolton I cannot run it on heroku

you problaby runned it wrong lol (idk how to host that bot on heroku i just know you prob runned it wrong)
