### ISSUE TITLE
Online Levels' Stars

### ISSUE THREAD

**Issue by ImYoshiGD** [Cvolton/GMDprivateServer#522]
I don't know why, but when I rate a level on my GDPS, the level's stars appears colored in yellow like I had passed it. This issue is happening to all on my GDPS.

I need help, please.

**Comment by ImYoshiGD** [comment]
Thanls for the help...

**Comment by bit0r1n** [comment]
this problem applies to all levels or to levels with 1-2~2 id?

**Comment by ImYoshiGD** [comment]
1-2~2 id? What's that?

**Comment by bit0r1n** [comment]
@ImYoshiGD from 1 to 21 or 22

**Comment by ImYoshiGD** [comment]
Ah yes, every level from 1 to 21/22 IDs are getting that bug

**Comment by bit0r1n** [comment]
And this applies for other levels? Maybe problem with account file

**Comment by ImYoshiGD** [comment]
It seems that doesn't apply for other levels, that problem was for 4 players

**Comment by DonAlex0** [comment]
Levels with IDs 1-21/22 and ID 3001 will have their stars marked as obtained if the main level associated with that ID has been completed, going from Stereo Madness to Fingerdash being IDs 1-21/22, and The Challenge being the ID 3001

**Comment by ImYoshiGD** [comment]
Thanks you bit0r1n and DonAlex0 for the help <3
