### ISSUE TITLE
How to make a GDPS Android Version on Android

### ISSUE THREAD

**Issue by DarkGD123** [Cvolton/GMDprivateServer#536]
Note: this doesn't work sometimes on Android 8 and above for some reasons :v also I'm bad at English.

Requirements:

• A Webhost ( I use 7m.pl )
• AndFTP 
• Your website
• APK Editor Pro ( 1.9.7 above )
• [Hex Editor app](https://m.apkpure.com/hex-editor/com.myprog.hexedit) 
• A GD Android File ( yeah )
• Your Brain

Procedure:

1. Add a page then name your website (if you don't have account please make one).. then wait for 2 minutes for the server ftp and database login details to send in your email check spam if it's not in primary.

btw your gdps website should be 11 characters + 7m.pl which is 17 in total cuz www.boomlings.com has 17 characters (ex. yeetgdps123.7m.pl)

2. After u got the ftp and database login details go to AndFTP and tap + and add your ftp server and put your server host which is your website but don't add http:// cuz it won't work then your ftp username and ftp password and add it.

3. Go to your FTP server and add a folder named database to add a folder tap the three dots top right on your screen.

4. After you created your database folder, download the GMDPrivateServer Files then go to GMDPrivateServer-master folder and config folder edit connection.php with your database user and your database password.

$host is sql.7m.pl if u dunno new gdps owners
$dbname and $username is the same just put your database username in there.

7. then save then open AndFTP then go to your ftp server and go to database folder and tap the phone button and go to GMDPrivateServer-master folder and select everything inside the folder and upload it by tapping the upload button (which is like download button but arrow is up)..and please wait for the uploading until is complete.

8. when the upload is complete go to sql.7m.pl and login to your database.

9. After you login tap the databases button and tap your database username and tap the right arrow to find import 

10. after you got in to import section tap choose file and go to GMDPrivateServer-master folder and tap database.sql and scroll down and tap go 

11. After importing is complete extract The Geometry Dash APK file.

12. Open APK Editor Pro and find Geometry Dash APK file and select common edit.

13. Change the package name (depends on you what's the name but don't remove the com.) And make sure that the package name has the same length as com.robtopx.geometryjump and you can change the Geometry Dash name as well.. then save

14. Close APK Editor Pro then Go to Geometry Dash Android folder then go to lib folder and armeabi folder.. then edit libcocos2dcpp.so using HEX Editor.

15. Search for the www.boomlings.com/database by tapping the magnifying glass and change HEX Fragment to String and check find and replace and check replace all and replace the website with your website without http:// then tap search. it should say 32 items replaced then save by tapping the floppy disk.

16. Open your website and go to base64encode.com and encode www.boomlings.com/database with http:// and put it on search then encode your website as well with http:// and put it on replace with.. then tap search. It should say 22 items replaced.

17. Search for com.robtopx.geometryjump and replace it with your package name then tap search and it should say 3 items replaced. Then save.

18. Open APK Editor Pro then find gen_signed.apk and rename it to anything you want but don't remove .apk then select the APK and select simple edit.

19. Go to lib folder and armeabi folder and replace the old libcocos2dcpp.so with the new libcocos2dcpp.so by tapping the pencil button then save.

20. Open gen_signed.apk then try it for yourself

have fun!

Also if there's 3 folders in lib folder edit the libcocos2dcpp.so in those 3 folders and replace them after u edit them

**Comment by DarkGD123** [comment]
If it didn't work just comment in here :3

**Comment by Flux3on** [comment]
I suggest making this a gist on your profile instead of an issue report on the GDPS

**Comment by masckmaster2007** [comment]
a

**Comment by Yan-007** [comment]
When I encoded www.boomlings.com/database to base64, it got me d3d3LmJvb21saW5ncy5jb20vZGF0YWJhc2U=, but when I search it in HEX Editor - it is don't give me any results

**Comment by masckmaster2007** [comment]
![image](https://user-images.githubusercontent.com/63162857/177223077-f1a8b913-bdfd-4111-8e6b-8329c3a30819.png)
http://yourdomain.com/database

**Comment by Yan-007** [comment]
> Если это не сработало, просто напишите здесь :3

After editing GD file, it is doesn't startup. Black screen, 0 FPS on Bluestacks 5, on real device it crashes

**Comment by Nikagdx** [comment]
> Note: this doesn't work sometimes on Android 8 and above for some reasons :v also I'm bad at English.
> 
> Requirements:
> 
> • A Webhost ( I use 7m.pl ) • AndFTP • Your website • APK Editor Pro ( 1.9.7 above ) • [Hex Editor app](https://m.apkpure.com/hex-editor/com.myprog.hexedit) • A GD Android File ( yeah ) • Your Brain
> 
> Procedure:
> 
> 1. Add a page then name your website (if you don't have account please make one).. then wait for 2 minutes for the server ftp and database login details to send in your email check spam if it's not in primary.
> 
> btw your gdps website should be 11 characters + 7m.pl which is 17 in total cuz [www.boomlings.com](http://www.boomlings.com) has 17 characters (ex. yeetgdps123.7m.pl)
> 
> 2. After u got the ftp and database login details go to AndFTP and tap + and add your ftp server and put your server host which is your website but don't add http:// cuz it won't work then your ftp username and ftp password and add it.
> 3. Go to your FTP server and add a folder named database to add a folder tap the three dots top right on your screen.
> 4. After you created your database folder, download the GMDPrivateServer Files then go to GMDPrivateServer-master folder and config folder edit connection.php with your database user and your database password.
> 
> $host is sql.7m.pl if u dunno new gdps owners $dbname and $username is the same just put your database username in there.
> 
> 7. then save then open AndFTP then go to your ftp server and go to database folder and tap the phone button and go to GMDPrivateServer-master folder and select everything inside the folder and upload it by tapping the upload button (which is like download button but arrow is up)..and please wait for the uploading until is complete.
> 8. when the upload is complete go to sql.7m.pl and login to your database.
> 9. After you login tap the databases button and tap your database username and tap the right arrow to find import
> 10. after you got in to import section tap choose file and go to GMDPrivateServer-master folder and tap database.sql and scroll down and tap go
> 11. After importing is complete extract The Geometry Dash APK file.
> 12. Open APK Editor Pro and find Geometry Dash APK file and select common edit.
> 13. Change the package name (depends on you what's the name but don't remove the com.) And make sure that the package name has the same length as com.robtopx.geometryjump and you can change the Geometry Dash name as well.. then save
> 14. Close APK Editor Pro then Go to Geometry Dash Android folder then go to lib folder and armeabi folder.. then edit libcocos2dcpp.so using HEX Editor.
> 15. Search for the [www.boomlings.com/database](http://www.boomlings.com/database) by tapping the magnifying glass and change HEX Fragment to String and check find and replace and check replace all and replace the website with your website without http:// then tap search. it should say 32 items replaced then save by tapping the floppy disk.
> 16. Open your website and go to base64encode.com and encode [www.boomlings.com/database](http://www.boomlings.com/database) with http:// and put it on search then encode your website as well with http:// and put it on replace with.. then tap search. It should say 22 items replaced.
> 17. Search for com.robtopx.geometryjump and replace it with your package name then tap search and it should say 3 items replaced. Then save.
> 18. Open APK Editor Pro then find gen_signed.apk and rename it to anything you want but don't remove .apk then select the APK and select simple edit.
> 19. Go to lib folder and armeabi folder and replace the old libcocos2dcpp.so with the new libcocos2dcpp.so by tapping the pencil button then save.
> 20. Open gen_signed.apk then try it for yourself
> 
> have fun!
> 
> Also if there's 3 folders in lib folder edit the libcocos2dcpp.so in those 3 folders and replace them after u edit them
