### ISSUE TITLE
levelReupload.php password

### ISSUE THREAD

**Issue by Enttixy** [Cvolton/GMDprivateServer#542]
I just wanna know if is there an way to put password on levelReupload.php, because ppl spams reuploaded levels on the server ;-; Ok thanks.

**Comment by Cvolton** [comment]
edit the file or delete it altogether if you don't want people to reupload levels

**Comment by Enttixy** [comment]
But can't it be like Map pack maker? Put the username and the password? It would be great

**Comment by XoticStudios** [comment]
Edit the form in levelReupload.php to have a password.

**Comment by ItzElectrix** [comment]
yeah, if you know basic php you can put it in yourself, it doesn't have to be something everyone should use

**Comment by Catover203** [comment]
just uhhh, I don't want to use this file

**Comment by Enttixy** [comment]
Okaay. Thanks everyone c:
