### ISSUE TITLE
Level ids.

### ISSUE THREAD

**Issue by ImJustASimpleMan** [Cvolton/GMDprivateServer#545]
I created level with id 666 from mysql now all levels are id 667+ how i can fix it? They were id 20+

**Comment by Cvolton** [comment]
This is normal behavior, as it would otherwise start erroring out once it would hit level 666 and refuse to upload any more levels. You can edit the AUTO_INCREMENT value manually, but this is not recommended.

**Comment by ImJustASimpleMan** [comment]
so i cant do anything? ;-;
