### ISSUE TITLE
Warning: session_start(): open(/var/lib/php5/sessions/sess_95vpg56t0c8upc9j13ct7d60f4, O_RDWR) failed: No space left on device (28) in /var/www/vhosts/sa1ntgoldey.7m.pl/httpdocs/database/dashboard/index.php on line 2

### ISSUE THREAD

**Issue by MegaSa1nt** [Cvolton/GMDprivateServer#546]
Warning: session_start(): open(/var/lib/php5/sessions/sess_95vpg56t0c8upc9j13ct7d60f4, O_RDWR) failed: No space left on device (28) in /var/www/vhosts/sa1ntgoldey.7m.pl/httpdocs/database/dashboard/index.php on line 2
What i can do?

**Comment by Cvolton** [comment]
either you ran out of free disk space for the GDPS (it is usually limited on most hosts), or your host did

**Comment by GGaMErZZ** [comment]
how is this still open lmao

**Comment by Cvolton** [comment]
closed: host-specific issue unrelated to the project
