### ISSUE TITLE
My ID's Jumped From 100 odd to over 100000

### ISSUE THREAD

**Issue by AnimeDasher** [Cvolton/GMDprivateServer#547]
Like i said in the title the level id's in the gdps have skyrocketed and I have no clue on how to fix this!
Any suggestions on how to fix this would be greatly appreciated.

**Comment by Cvolton** [comment]
You can edit the AUTO_INCREMENT value for the levels table in the database manually (in the options tab in phpmyadmin for example). Make sure there are no levels with an ID higher than your AUTO_INCREMENT value though, as it would start erroring out once it'd hit that ID and refuse to upload any more levels

**Comment by AnimeDasher** [comment]
that caused all the levels to get their id's confused, thanks for the help tho
