### ISSUE TITLE
"Something went wrong"

### ISSUE THREAD

**Issue by LemonadeZentix** [Cvolton/GMDprivateServer#553]
Welp... I was Wasting like 7 Hours rnTrying to figure out.... Tried everything (not changing the Server) but nothing worked welp... I tried
- changing Version 2.13 -> 2.11
- configure everythin i had to
- reinstalling the files and Database multible times 
- Troubleshooting everything i that could be wrong.....
- Changed the connection.php to localhost

I watched Every Tutorial, Every Issue..... Everything

I need Sleep its 1:30 am so welp hope you could help me

![image](https://user-images.githubusercontent.com/52041515/76154439-9bbabe80-60dc-11ea-877f-fc135264032b.png)

**Comment by DonAlex0** [comment]
Tried setting servername to localhost?

**Comment by LemonadeZentix** [comment]
Nope Nothing

> Tried setting servername to localhost?
