### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by CatRyBou** [Cvolton/GMDprivateServer#554]
When I go to gdps1.oueu.com/database I get a forbidden access error.

PLS Help

**Comment by EMREOYUN** [comment]
Make sure your database folder have chmod 755

**Comment by Cvolton** [comment]
the link you posted isn't even valid

**Comment by EMREOYUN** [comment]
> the link you posted isn't even valid, oueu is a domain for sale

oueu.com this domain is seems sale from 2019

**Comment by SpookyBear0** [comment]
@anishvundela I think you meant gdps1.ueuo.com/database

**Comment by EMREOYUN** [comment]
> @anishvundela I think you meant gdps1.ueuo.com/database

That is also down.

**Comment by Cvolton** [comment]
closing as this is not a general issue and the issue got no updates in months, feel free to request reopening this
