### ISSUE TITLE
Local Storage Android Bug

### ISSUE THREAD

**Issue by AnimeDasher** [Cvolton/GMDprivateServer#556]
When I edit the com.robtopx.geometryjump on android to something different like com.animx.gdps so the normal gdps client and the private server can both be installed, it works and lets me install both on my phone, however even though i changed the path off the gdps local save data location, it refuses to save data locally to the device. This results in users having to use the cloud save option. I Really need help on finding a fix for this as I would like android users to be able to have geometry dash and my private server installed on the same phone.

**Comment by Cvolton** [comment]
this really sounds like you didn't edit the location in libcocos2dcpp.so, or that you edited it wrong (made a typo etc.). Since your mentioned package name has a different length, I presume that that might be the issue as well

**Comment by AnimeDasher** [comment]
can i send you the files, or the apk for you to look at? ; Because as I have attempted to do what you said but when I changed them files you mentioned the game would not boot.

**Comment by Cvolton** [comment]
make sure the replacement string is the same length as the original

**Comment by AnimeDasher** [comment]
Thank you for the help, I re edited everything in the correct way and it seems to be working!
