### ISSUE TITLE
Level Completion Kick

### ISSUE THREAD

**Issue by fancythedeveloper** [Cvolton/GMDprivateServer#557]
Anyway to fix getting kicked out of a level on a GDPS right before hitting the finish glow at the end of a level? The first level I uploaded worked mine but the two others don't.

**Comment by Cvolton** [comment]
dupe of
#537 #437 #296 #284 #212 #191 #129 and possibly more
tl;dr levels above 2* must be at least medium length

**Comment by fancythedeveloper** [comment]
k
