### ISSUE TITLE
1.9 account bug

### ISSUE THREAD

**Issue by qwetydash** [Cvolton/GMDprivateServer#562]
When I make a account and I go to login I get this message "This account has been disabled"
In a 1.9 GDPS, somebody can help me? Because I want to have a 1.9 GDPS

**Comment by EMREOYUN** [comment]
Are you using this code for GDPS?

**Comment by qwetydash** [comment]
> Are you using this code for GDPS?

Yes :(

**Comment by qwetydash** [comment]
> Are you using this code for GDPS?

Yes I'm using the cvolton code for make my 1.9 GDPS

And don't works
![Screenshot_20200326-233456](https://user-images.githubusercontent.com/62737047/77759426-52360300-6ffa-11ea-9821-99cc3e3e4a30.jpg)
I get this

**Comment by Cvolton** [comment]
accounts are disabled in 1.9 due to security issues

**Comment by qwetydash** [comment]
> accounts are disabled in 1.9 due to security issues

:( In the 2.0 works?

**Comment by Cvolton** [comment]
yes

**Comment by qwetydash** [comment]
> yes

So just on the 1.9 don't work the account, ok I will make my gdps on the 2.0
