### ISSUE TITLE
My leaderboards are hacked.

### ISSUE THREAD

**Issue by trubiso** [Cvolton/GMDprivateServer#565]
Everything is fine, but in the leaderboard we all show up as "Sakujes" and cron.php doesn't do anything. What can I do to fix this?
![image](https://user-images.githubusercontent.com/33161454/78082566-aacb1e80-73b3-11ea-90f2-79996903e283.png)

**Comment by EMREOYUN** [comment]
Try executing cronjob, this will ban users that uses stats hacks.

**Comment by DarkGD123** [comment]
This thing only pops up every April 1st

**Comment by Flux3on** [comment]
If you really don't like it, replace this code block from lines 132 to 136 in [incl/getGJScores.php](https://github.com/Cvolton/GMDprivateServer/blob/master/incl/scores/getGJScores.php#L132):
```php
if($date == "01-04"){
	$lbstring .= "1:sakujes:2:".$user["userID"].":13:999:17:999:6:".$xi.":9:9:10:9:11:8:14:1:15:3:16:".$extid.":3:999:8:99999:4:999:7:".$extid.":46:99999|";
}else{
	$lbstring .= "1:".$user["userName"].":2:".$user["userID"].":13:".$user["coins"].":17:".$user["userCoins"].":6:".$xi.":9:".$user["icon"].":10:".$user["color1"].":11:".$user["color2"].":14:".$user["iconType"].":15:".$user["special"].":16:".$extid.":3:".$user["stars"].":8:".round($user["creatorPoints"],0,PHP_ROUND_HALF_DOWN).":4:".$user["demons"].":7:".$extid.":46:".$user["diamonds"]."|";
}
```

To this single line of code:
```php
$lbstring .= "1:".$user["userName"].":2:".$user["userID"].":13:".$user["coins"].":17:".$user["userCoins"].":6:".$xi.":9:".$user["icon"].":10:".$user["color1"].":11:".$user["color2"].":14:".$user["iconType"].":15:".$user["special"].":16:".$extid.":3:".$user["stars"].":8:".round($user["creatorPoints"],0,PHP_ROUND_HALF_DOWN).":4:".$user["demons"].":7:".$extid.":46:".$user["diamonds"]."|";
```

I removed it from my leaderboards. It's kinda funny, but I also want to be able to see my server's leaderboards.

**Comment by AToska21** [comment]
bruh
