### ISSUE TITLE
Unregistered User Levels on levelToGD.php

### ISSUE THREAD

**Issue by cynir** [Cvolton/GMDprivateServer#569]
Hello, I apologize if this is a really dumb question with a painfully obvious answer, but I'm stumped as to how you would transfer an unregistered user's level from a GDPS to GD. I started up a GDPS with Geometry Dash 1.4 yesterday, and since there weren't any user accounts back then, inputting a password on levelToGD.php isn't an option. Is there some sort of default password to put in, or do I just put in anything? If I leave the password field blank, nothing happens, and sometimes when putting in random letters it does nothing or gives me an error saying the password/username combination is incorrect. If there's no actual way how to do this, that's a shame, but otherwise help with this issue would be greatly appreciated.

**Comment by Cvolton** [comment]
The reason the password check is there is so people don't reupload levels they didn't make. levelToGD.php can be edited so it doesn't require you to log into a GDPS account
