### ISSUE TITLE
Account comment color

### ISSUE THREAD

**Issue by DomikTV** [Cvolton/GMDprivateServer#571]
How to change color of posts in account page?

**Comment by EMREOYUN** [comment]
•You need assign yourself Moderator or Elder Moderator rank
•Change comment color on groups for any of them.

**Comment by DomikTV** [comment]
Only the color of the comment changes under the levels but not on the account page

**Comment by EMREOYUN** [comment]
I think only account ID:81 (formerly RobTop's account) have blue text in account posts. Ask to @Cvolton.
