### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Ben569483** [Cvolton/GMDprivateServer#582]
So, when I try to open the GDPS, it does absolutely nothing. My URL is exactly 17 characters long (bengame1.ueuo.com)and I have changed the server using HxD. Now, going to open it, nothing happens. Any help?

**Comment by EMREOYUN** [comment]
What do you mean at nothing happens?

**Comment by ItzElectrix** [comment]
did you add a /database at the end in the exe?

**Comment by Ben569483** [comment]
I tried adding /database and I get "Invalid access to memory location" and before without /database the app just opens then it instantly closes

**Comment by EMREOYUN** [comment]
You can't add or remove bytes from client, otherwise it will not open.
Move all server files to bengame1.ueuo.com/database.
Edit values on client like this( www.boomlings.com/database -> bengame1.ueuo.com/database)
Edit values on client as base64 coded (same with up but encode them base64)
And try it.

**Comment by Ben569483** [comment]
I've tried changing it from www.boomlings.com/database to bengame1.ueuo.com/database and it doesn't work. And the base64 won't work either.

**Comment by EMREOYUN** [comment]
It seems your server not working well. Did you added and created the database?

**Comment by Ben569483** [comment]
Yeah, I created the database using the database.sql file

**Comment by EMREOYUN** [comment]
![image](https://user-images.githubusercontent.com/35144629/80289875-40a36080-874a-11ea-93e1-31361eb18ba8.png)
But server don't think the same.

**Comment by Ben569483** [comment]
Does that mean I’m screwed?

**Comment by EMREOYUN** [comment]
I can't say it because i don't know what is happening in free web hostings. Did you setup connection.php file correctly?

**Comment by Ben569483** [comment]
Yeah, I put the username and password into it correctly.

**Comment by Phytee** [comment]
You could try another hosting service, like 7m.pl or 5v.pl

**Comment by GGaMErZZ** [comment]
the domain of your gdps server thing must be 17 letters. i tested server with more and less than 17 letters and it broke

**Comment by GGaMErZZ** [comment]
maybe its my own fault making it fail but idk

**Comment by ItzElectrix** [comment]
![image](https://user-images.githubusercontent.com/50182312/81183078-b4c8da00-8f7c-11ea-8fa8-b7382ff7d851.png)
This is what I see.
Looking at this makes me assume that you didn't configure connection.php correctly. Are you sure you put the correct thing in the server name and username?

**Comment by Ben569483** [comment]
Yeah. This is what is in the file for bengame1.ueuo.com/database/connection.php

<?php
$servername = "localhost";
$username = "103725";
$password = "MyPassword";
$dbname = "103725";
?>

The "MyPassword" is not really my password obviously

**Comment by Ben569483** [comment]
I think I have fixed the issue with that photo because this is what it does now
![image](https://user-images.githubusercontent.com/35010334/81192349-050e5f00-8fb2-11ea-9eb8-d340a38b762f.png)

**Comment by EMREOYUN** [comment]
> the domain of your gdps server thing must be 17 letters. i tested server with more and less than 17 letters and it broke

![image](https://user-images.githubusercontent.com/35144629/81220900-bf21bd00-8fea-11ea-9fe9-66f1a0f0f855.png)
I don't think so.



> I think I have fixed the issue with that photo because this is what it does now but the app still doesn’t open.
> ![image](https://user-images.githubusercontent.com/35010334/81192349-050e5f00-8fb2-11ea-9eb8-d340a38b762f.png)

Restart from beginning and re-edit your client. Your server seems fine and you don't need to do anything on there.

**Comment by Ben569483** [comment]
I’ll try redoing it tomorrow. It’s getting late here in the UK, it’s 9:33 PM

**Comment by EMREOYUN** [comment]
> I’ll try redoing it tomorrow. It’s getting late here in the UK, it’s 9:33 PM

Alright. Just ask anything goes wrong.

**Comment by Ben569483** [comment]
When I try to import database.sql to phpmyadmin, it says this 
![image](https://user-images.githubusercontent.com/35010334/81293869-ec5f8100-9065-11ea-8b6d-344f55c0e7e7.png)

**Comment by EMREOYUN** [comment]
> When I try to import database.sql to phpmyadmin, it says this
> ![image](https://user-images.githubusercontent.com/35010334/81293869-ec5f8100-9065-11ea-8b6d-344f55c0e7e7.png)

Create a database and import into it.

**Comment by ItzElectrix** [comment]
Select one of the databases on the left-hand side of the screen, then import the sql.

**Comment by Ben569483** [comment]
Seems like I abandoned this, tried it again and still the same thing happens, the game doesn’t open with a new setup. My new URL is bengame8.ueuo.com

**Comment by EMREOYUN** [comment]
> Seems like I abandoned this, tried it again and still the same thing happens, the game doesn’t open with a new setup. My new URL is bengame8.ueuo.com

Your current index seems empty

**Comment by fancythedeveloper** [comment]
@Ben569483 WYM if I can make the EXE for you?

**Comment by Ben569483** [comment]
> @Ben569483 WYM if I can make the EXE for you?

Well you could try, I think I’m doing everything right but there’s a chance I’m being an idiot and missing something out haha

**Comment by fancythedeveloper** [comment]
> > @Ben569483 WYM if I can make the EXE for you?
> 
> Well you could try, I think I’m doing everything right but there’s a chance I’m being an idiot and missing something out haha

So I'm assuming its bengame8.ueuo.com/database or just bengame8.ueuo.com?

**Comment by Ben569483** [comment]
bengame8.ueuo.com/database

**Comment by fancythedeveloper** [comment]
Done!
[BenGDPS.zip](https://github.com/Cvolton/GMDprivateServer/files/5983166/BenGDPS.zip)
You can name the EXE inside of the ZIP whatever you want, btw.

**Comment by Ben569483** [comment]
> Done!
> [BenGDPS.zip](https://github.com/Cvolton/GMDprivateServer/files/5983166/BenGDPS.zip)
> You can name the EXE inside of the ZIP whatever you want, btw.

It still does the same thing :/, does it work for you?

**Comment by Ben569483** [comment]
Got it to work for now, it’s something to do with Steam BUT I’m having trouble creating accounts on my GDPS

**Comment by Ben569483** [comment]
While looking at my FTP it said all the php files were 0 bytes

**Comment by DarkGD123** [comment]
You use freewha am i right?

**Comment by DarkGD123** [comment]
freewha's ftp system is broken

**Comment by Ben569483** [comment]
Oh, I never realised that the FTP was broken. Do you know any other alternative free web hosting places?

**Comment by DarkGD123** [comment]
000webhost would be ok

**Comment by Ben569483** [comment]
I think 000webhost only uses localhost for their MySQL connections

**Comment by fancythedeveloper** [comment]
@DarkGD123 @Ben569483 Its broken?
In my experience, there web FTP kinda sucked but it worked fine for me.

**Comment by DarkGD123** [comment]
Yeah when you upload the files, the process will stop  sometimes and some of the files are 0 bytes

**Comment by Ben569483** [comment]
![291AD21B-F953-4976-8498-A0B9FFDB92FD](https://user-images.githubusercontent.com/35010334/108054759-faa3ea00-7046-11eb-99ad-16bde9a302f2.jpeg)
This is what I see in the FTP

**Comment by fancythedeveloper** [comment]
> ![291AD21B-F953-4976-8498-A0B9FFDB92FD](https://user-images.githubusercontent.com/35010334/108054759-faa3ea00-7046-11eb-99ad-16bde9a302f2.jpeg)
> This is what I see in the FTP
> All the PHP files are 0 bytes

Pretty sure I got around it by uploading the master ZIP itself, then extracting it in the FTP.

**Comment by Ben569483** [comment]
> > ![291AD21B-F953-4976-8498-A0B9FFDB92FD](https://user-images.githubusercontent.com/35010334/108054759-faa3ea00-7046-11eb-99ad-16bde9a302f2.jpeg)
> > This is what I see in the FTP
> > All the PHP files are 0 bytes
> 
> Pretty sure I got around it by uploading the master ZIP itself, then extracting it in the FTP.

I’ll try that

**Comment by Ben569483** [comment]
That worked, only issue is you need Steam to be able to open the game, after this last issue is fixed I can finally close this issue.

**Comment by Ben569483** [comment]
I can’t comment on levels or on my account tho

**Comment by fancythedeveloper** [comment]
> I can’t comment on levels or on my account tho

Did you do connection.php?

**Comment by Ben569483** [comment]
Yep, I set it up correctly

**Comment by fancythedeveloper** [comment]
What happens when you try to comment then?

**Comment by Ben569483** [comment]
It gives me no error but the comment doesn’t show up

**Comment by fancythedeveloper** [comment]
Does leaderboards work fine?

**Comment by Ben569483** [comment]
The leaderboard loads the creator tab and the friends tab, but the others show nothing.

**Comment by Ben569483** [comment]
All of the PHP files seem to have uploaded correctly, so idk what’s causing it

**Comment by Ben569483** [comment]
Comments now work, but level downloading doesn’t work.

**Comment by Ben569483** [comment]
Now all of a sudden nothing on the GDPS will load. Profiles and levels and everything else which requires the server won’t load. Like huh?????

**Comment by DarkGD123** [comment]
yeah its broken

**Comment by Ben569483** [comment]
It works now, but level downloading still doesn’t work.

**Comment by fancythedeveloper** [comment]
Real weird why that happens, when I tried it like 8 months ago, it worked fine.

**Comment by Ben569483** [comment]
Level downloading doesn’t work, when I try to CHMOD the level files the FTP gives me an error

**Comment by Ben569483** [comment]
i only remembered this a few days ago, got it all working now, the issue was FreeWHA and me not changing Base64 encodings. pro tip: use a custom domain if possible
