### ISSUE TITLE
2.11 - Rewords of Map pack is not working

### ISSUE THREAD

**Issue by RedLime** [Cvolton/GMDprivateServer#583]
I made one map pack. The reward for that was 10 stars and 3 coins. However, the reward is only 10 stars, not 3 coins. Even this does not generate any data in the database's action. (updateGJUserScore.php i think this one)

**Comment by RedLime** [comment]
Also, if user was log out and log in and load again, the map pack reward will not be received again.
Is there a solution for this?

**Comment by DarkGD123** [comment]
The limit only of the reward is 10 stars and 2 coins

**Comment by RedLime** [comment]
> The limit only of the reward is 10 stars and 2 coins

thanks! it is works!

**Comment by RedLime** [comment]
I'll close this issue

**Comment by RedLime** [comment]
> Also, if user was log out and log in and load again, the map pack reward will not be received again.
> Is there a solution for this?

+ i reopen this issue, cause that problem not solved

**Comment by Cvolton** [comment]
the stars limit is also bound to the difficulty and IIRC you can't get 2 coins from 2* packs but I may be wrong on that regard

**Comment by RedLime** [comment]
> the stars limit is also bound to the difficulty and IIRC you can't get 2 coins from 2* packs but I may be wrong on that regard

2 coins are works nice. but it is only that the receipt of the map pack reward is not saved in the account data.
