### ISSUE TITLE
discord problems

### ISSUE THREAD

**Issue by Mefewe** [Cvolton/GMDprivateServer#584]
Sorry for the English - Google translator is sometimes terrible.

In general, I set up discord.php, and decided to call the sendDiscordPM function
from mainLib.php. I call it like this:

`<?php
require_once "lib / mainLib.php";
$ gs = new mainLib ();
$ gs-> sendDiscordPM ("699543033946832897", "TEST_E");
?>` 

However, when opening the file, the output is as follows: Notice: Undefined index: 
id in /var/www/u0831230/data/www/gdlightservers.ru/database/incl/lib/mainLib.php on line 548

This line of code has:

` $ channelID = $ responseDecode ["id"];` 

The code lines do not coincide with the original, because I added new functions to the mainLib.php file. In general, how can I fix this? (If anything, messages are not sent)

**Comment by ItzElectrix** [comment]
what is $responseDecode defined as in mainLib.php?

**Comment by FamryAmri** [comment]
$responseDecode is in array of id but maybe in array couldnt in set

**Comment by Lezzica** [comment]
Try to use a numeric index like `$ channelID = $ responseDecode[0];` instead and see if that got it working. If you get a different response than expected, try a different number. I haven't tested this out for myself but it should work, otherwise the response may be invalid.

**Comment by Mefewe** [comment]
im fixed this!
