### ISSUE TITLE
how to make maximum 2 downloads more

### ISSUE THREAD

**Issue by GGaMErZZ** [Cvolton/GMDprivateServer#586]
EVERY LEVEL have **2 DOWNLOADS** idk why PLUS I SAW A 2 DOWNLOAD LVL WITH 12 LIKES WHAT????

**Comment by GGaMErZZ** [comment]
![Screenshot_2020-04-26-12-51-06](https://user-images.githubusercontent.com/62007585/80390919-abd26b80-88df-11ea-8e4b-fb9fcf03ab10.png)

**Comment by GGaMErZZ** [comment]
`f`

**Comment by DarkGD123** [comment]
Go to `incl/levels` and edit `downloadGJLevel.php` goto line 56 and change the value of 

`if($query6->fetchColumn() < 2)` to
`if($query6->fetchColumn() < [anynumber])`

Example:
`if($query6->fetchColumn() < 100000)`

**Comment by DarkGD123** [comment]
If u want to change the likes..login to your database and go to`levels` table and go to `structures` and change the value of the `likes` to 0.

**Comment by GGaMErZZ** [comment]
ok yeet thx

**Comment by GGaMErZZ** [comment]
issue fixxed
