### ISSUE TITLE
Account disabled

### ISSUE THREAD

**Issue by GDDogeYT** [Cvolton/GMDprivateServer#588]
Someone on my gdps got his account disabled, but when i go to look into the database he isn't banned... what could've cause this and how to fix?

**Comment by RedLime** [comment]
that's cause many password error. but i can't find database on banned too :(

**Comment by DarkGD123** [comment]
Let him create a new account and transfer his data by retyping his old account ID with his new ID

**Comment by Cvolton** [comment]
The account doesn't actually get disabled, you just get prevented from logging into any account for an hour if you enter the wrong password 7 times
