### ISSUE TITLE
Levels don't show in Level Search or ID

### ISSUE THREAD

**Issue by fancythedeveloper** [Cvolton/GMDprivateServer#593]
When I upload a level, the ID is still NA and there's nothing in level search or searching by ID.

When I try to reupload a level, over the ID, it gives an error.
`Warning: file_put_contents(../data/levels/3): failed to open stream: Permission denied in /home/vhosts/clgdpsv2.ueuo.com/database/tools/levelReupload.php on line 126`
Anyone knows how to fix this? I'm using FreeWHA as making pages are disabled currently on 5v and 7m.

**Comment by Cvolton** [comment]
chmod 777 the data folder recursively

**Comment by fancythedeveloper** [comment]
Already did that earlier, but thanks!
