### ISSUE TITLE
1.0 server!

### ISSUE THREAD

**Issue by GoodGamerG** [Cvolton/GMDprivateServer#594]
Hello! How to create 1.0 server? I upload files on the server and mysql but when I upload lvl its give me a upload error! sorry for my bad english)

**Comment by DarkGD123** [comment]
GDPS files doesn't support 1.0 I think

**Comment by GoodGamerG** [comment]
Starting from which version does it support?

**Comment by Flux3on** [comment]
> Starting from which version does it support?

1.0. @DarkGD123 clearly didn't read [README.md](https://github.com/Cvolton/GMDprivateServer/blob/master/README.md).

**Comment by GoodGamerG** [comment]
@Flux3on I can't setup it. Upload level failed. And in lib.so there is have'nt base 64 code

**Comment by Flux3on** [comment]
What host are you using?

**Comment by GoodGamerG** [comment]
VDS host

**Comment by GoodGamerG** [comment]
Does it work in 7m.pl?

**Comment by Flux3on** [comment]
7m.pl is broken as of how but Free web hosting area should work. Can we continue this conversation on Discord? Mine is Flux3on#6010

**Comment by EMREOYUN** [comment]
@GoodGamerG We didn't tested on 1.0 and client creation section for 2.11 version. 1.0 does not contain base64 strings and you can pass it, only change normal strings. @Cvolton did we have 1.0 support on server files?

**Comment by Cvolton** [comment]
I can confirm that 1.0 is fully supported in the latest version

**Comment by GoodGamerG** [comment]
Wow, can you help me with install it?

**Comment by GoodGamerG** [comment]
@Cvolton maybe you can give me an old core for 1.0 server?

**Comment by Cvolton** [comment]
there's no old core, 1.0 support was added only a few months after 2.1 support, just use the latest version

**Comment by fancythedeveloper** [comment]
I've had success before running GDPSs on older versions, like 1.8.

**Comment by Flux3on** [comment]
Why would you want to run 1.0 anyway

I strongly recommend making a 1.2 server instead of a 1.0 server. It's basically the same as 1.0 just with less bugs and a few more features like new songs and a new gamemode, but doesn't add any new block styles so it still kinda feels like 1.0.

**Comment by fancythedeveloper** [comment]
True, 1.2 is 1.0 but with more stuff.

**Comment by GoodGamerG** [comment]
Ok thanks all!
