### ISSUE TITLE
Database connection working but "something went wrong"

### ISSUE THREAD

**Issue by GDDogeYT** [Cvolton/GMDprivateServer#599]
Hi, i made a gdps using infinityfree.net (the best free hosting service), and it all seemed to be working fine until i tried to register an account. It gave me "something went wrong" error. So i checked the connection.php file and everything was correct, i even tried to open a php file like "registerGJAccount.php" and there weren't any errors... Can someone please tell me whats going on? Also yes, I entered the link into the gdps app correctly.

**Comment by fancythedeveloper** [comment]
You probably forgot to modify connection.php, also if your hoster's FTP thing has a CHMOD option, similar to FreeWHA, make sure its set so that Everyone can Read/Write/Execute (777).

**Comment by GDDogeYT** [comment]
> You probably forgot to modify connection.php, also if your hoster's FTP thing has a CHMOD option, similar to FreeWHA, make sure its set so that Everyone can Read/Write/Execute (777).

ok so i set it to 777 but i still can't register an account

**Comment by DarkGD123** [comment]
what host did you put?

**Comment by DarkGD123** [comment]
infinityfree.net doesn't support this GDPS lol

**Comment by DarkGD123** [comment]
Infinityfree doesn't support php

**Comment by DarkGD123** [comment]
leaving this #478

**Comment by GDDogeYT** [comment]
welp that sucks
