### ISSUE TITLE
7m.pl 

### ISSUE THREAD

**Issue by Dom1nusYT** [Cvolton/GMDprivateServer#601]
![image](https://user-images.githubusercontent.com/56830961/82317890-f55b3580-9a09-11ea-9eb6-b48bee9e90fa.png)
help pls

**Comment by fancythedeveloper** [comment]
For your tools, go to (insert name you put).7m/database/tools

**Comment by Dom1nusYT** [comment]
![image](https://user-images.githubusercontent.com/56830961/82318248-7ca8a900-9a0a-11ea-8216-43b27e9a60ce.png)
then?

**Comment by fancythedeveloper** [comment]
What are you doing anyways?

**Comment by Dom1nusYT** [comment]
> What are you doing anyways?

is 7m.pl down?
