### ISSUE TITLE
under construction

### ISSUE THREAD

**Issue by Dom1nusYT** [Cvolton/GMDprivateServer#602]
![image](https://user-images.githubusercontent.com/56830961/82399600-79f09700-9a90-11ea-9578-5391b1172b3e.png)
what will happend if i delete page? i need help cuz this 
![image](https://user-images.githubusercontent.com/56830961/82399657-9c82b000-9a90-11ea-826f-a04b3ea453ad.png)

**Comment by DarkGD123** [comment]
the page will be gone

Also that's a index file in ur screen rn

**Comment by Dom1nusYT** [comment]
i deleted

**Comment by Lezzica** [comment]
Mind me, but I think that making issues like these is irrelevant here. Consider closing this.
