### ISSUE TITLE
Cannot upload levels more than 60k objects and players cannot save their data.

### ISSUE THREAD

**Issue by Robotition** [Cvolton/GMDprivateServer#605]
I wanna know how can I make the object limit higher for levels with a lot of objects. And some players cannot save their data.

**Comment by DarkGD123** [comment]
Maybe the server can't handle it since it's big

**Comment by Robotition** [comment]
> 
> 
> Maybe the server can't handle it since it's big

So do I just need to upgrade my storage on my server because it's only 300 MB.

**Comment by fancythedeveloper** [comment]
That shouldn't be the issue.

**Comment by Lezzica** [comment]
Depending on the server host, your upload/download size may be limited. You should get into contact with your host if that's the issue. Otherwise I recommend you to either find a new host or host yourself a server.
