### ISSUE TITLE
List of commands

### ISSUE THREAD

**Issue by Drakunovu** [Cvolton/GMDprivateServer#606]
What is the list of commands and also, I see the list of commands in a file but they don't works it says Comment upload failed. Please try again later.

**Comment by DarkGD123** [comment]
That means it works lol

**Comment by RedLime** [comment]
check #159 issue. `Comment upload failed. Please try again later.` it mean "-1", the command works fine.

**Comment by Drakunovu** [comment]
Thank you all!
