### ISSUE TITLE
I cant register

### ISSUE THREAD

**Issue by QuantumWormhole** [Cvolton/GMDprivateServer#612]
I keep getting the something went wrong error, and I cant fix it. pls help

**Comment by fancythedeveloper** [comment]
Make sure /config/connection.php is setup correctly.

**Comment by fancythedeveloper** [comment]
Also make sure you actually uploaded the files to the FTP server

**Comment by QuantumWormhole** [comment]
All are correct

**Comment by EMREOYUN** [comment]
Make sure you changed everything in your app. Refer [https://github.com/Cvolton/GMDprivateServer/wiki/Creating-Windows,-Android-and-IOS-Apps](wiki)

**Comment by QuantumWormhole** [comment]
I did multiple checks. I have been trying to fix this for a quarter of the 2.2 wait

**Comment by QuantumWormhole** [comment]
anything else I could try?

**Comment by fancythedeveloper** [comment]
What hoster are you using?

**Comment by fancythedeveloper** [comment]
If you're using FreeWHA, go to its Web FTP, checkmark the database folder, and set it so Owner, Others, and Everyone can Read/Write/Execute or known as 777, just in case.

**Comment by QuantumWormhole** [comment]
It worked because I switched from winscp to FileZilla. Moral of the story, use FileZilla and not winscp.

**Comment by Cvolton** [comment]
issue resolved, closing
