### ISSUE TITLE
5v.pl issue

### ISSUE THREAD

**Issue by fancythedeveloper** [Cvolton/GMDprivateServer#613]
Has anyone else been having an issue making a GDPS on 5v.pl now? My existing older GDPSs work, but when I try to make a new one, I can't make a level or make an account and leaderboards don't work. I've made sure connection.php is correct and that everything I need is uploaded, does anyone know the fix for this, assuming its fixable? Just note that 7m.pl works fine, just not 5v.pl.

**Comment by hiimjustin000** [comment]
Did you edit the files? Did you upload the edited connection.php?

**Comment by fancythedeveloper** [comment]
Yes.

**Comment by hiimjustin000** [comment]
Are they all correct?

**Comment by fancythedeveloper** [comment]
_Yes_

**Comment by QuantumWormhole** [comment]
Use 7m.pl and FileZilla

**Comment by fancythedeveloper** [comment]
Read the bottom.

**Comment by fancythedeveloper** [comment]
Bumping this right now, seems like level lists work and reuploads work, but stuff like Leaderboards don't. For example, when I try to login, it just gives
```
Server: nginx/1.14.2
Date: Mon, 15 Jun 2020 00:58:57 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding

1db
<br />
<b>Fatal error</b>:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'userID' doesn't have a default value in /home/FancyGDPS/public_html/classik1pt9/database/accounts/loginGJAccount.php:45
Stack trace:
#0 /home/FancyGDPS/public_html/classik1pt9/database/accounts/loginGJAccount.php(45): PDOStatement-&gt;execute(Array)
#1 {main}
  thrown in <b>/home/FancyGDPS/public_html/classik1pt9/database/accounts/loginGJAccount.php</b> on line <b>45</b><br />
```
_BTW this was found using WireShark_

**Comment by RealistikDash** [comment]
That could mean autoincrement was messed up. Could you look into that?

**Comment by fancythedeveloper** [comment]
I didn't do anything tho.

**Comment by Jecket22** [comment]
Yeah the database is messed up, [have a fix (that might or might not work out).](https://github.com/Cvolton/GMDprivateServer/files/5129118/alter_table_fix.zip)

Simply import the sql included in the zip to your database.

**Comment by fancythedeveloper** [comment]
Gonna test that later, if it works, I'll close the issue

**Comment by fancythedeveloper** [comment]
Just tested it, seems to work, issue closed!

**Comment by RobloxNationGaming** [comment]
> Has anyone else been having an issue making a GDPS on 5v.pl now? My existing older GDPSs work, but when I try to make a new one, I can't make a level or make an account and leaderboards don't work. I've made sure connection.php is correct and that everything I need is uploaded, does anyone know the fix for this, assuming its fixable? Just note that 7m.pl works fine, just not 5v.pl.

I made a GDPS on 5v.pl :/
