### ISSUE TITLE
300 Downloads and 100 Likes

### ISSUE THREAD

**Issue by Robotition** [Cvolton/GMDprivateServer#614]
How do I stop the downloads and likes going automatically to 300 and 100? I tried looking at all of the php files and I can't find anything.

**Comment by fancythedeveloper** [comment]
The default downloads/likes is in the SQL, not any PHP.

**Comment by RedLime** [comment]
check mysql in 'levels' table on "downloads" and "likes". you should see default value is "300" and "100". just change to 0

**Comment by Robotition** [comment]
> 
> 
> check mysql in 'levels' table on "downloads" and "likes". you should see default value is "300" and "100". just change to 0

Okay thanks, that worked.

**Comment by LBlazen** [comment]
but how can you make it 0 0 always ?

**Comment by fidgetplayz48** [comment]
> but how can you make it 0 0 always ?

^

**Comment by fidgetplayz48** [comment]
FIGURED IT OUT!!!
go to levels table, structure, then set default downloads and likes to 0
kinda stupid for default values tbh

**Comment by fancythedeveloper** [comment]
Pretty sure it's set to 300 downloads and 100 likes because there's 2 icons that are locked behind those, and not every GDPS has All Icons hack.
