### ISSUE TITLE
leaderboard ban for reupload acc

### ISSUE THREAD

**Issue by Shio7** [Cvolton/GMDprivateServer#618]
How can i ban it? i banned that acc from stars, diamonds, etc, but it is still showing from cp ranking pages

**Comment by Shio7** [comment]
I used it already

**Comment by Wyliemaster** [comment]
if you go into the users section in the database there is an option for creator ban. pretty sure thats to ban them from the CP leaderboards. setting the value from 0 to 1 is what i would assume you would do it

**Comment by Shio7** [comment]
Thank you
