### ISSUE TITLE
Can't upload a level

### ISSUE THREAD

**Issue by RobertTopala** [Cvolton/GMDprivateServer#62]
When I upload a level, thats show NA id and it can't be found in Geometry Dash

**Comment by AggPro** [comment]
Can you please explain more?


That must be a server error and/or you have an old version of CvoltonGDPS

**Comment by RobertTopala** [comment]
I have the last version of CvoltonGDPS, the unique information I can give is the server error when it check the files to upload a level

**Comment by RobertTopala** [comment]
Fatal error: Call to a member function rowCount() on null in /home/u800066094/public_html/database/uploadGJLevel20.php on line 84

**Comment by Cvolton** [comment]
delete line 84, thats a bug i'll fix in a commit later today
