### ISSUE TITLE
Cant play levels or like posts

### ISSUE THREAD

**Issue by LeafyYT** [Cvolton/GMDprivateServer#622]
None of my levels load and I cant like any posts/comments.
https://i.imgur.com/UYFeJCJ.png

**Comment by fancythedeveloper** [comment]
Are the leaderboards also blank? If they are, that means something wrong with connection.php probably.

**Comment by LeafyYT** [comment]
nope, they work fine

**Comment by fancythedeveloper** [comment]
Ok, check the FTP server and see if there's any level data in /database/data/levels, if there isn't, something is wrong.

**Comment by LeafyYT** [comment]
There is a deleted folder... https://i.imgur.com/Jnq2Xu1.png

**Comment by LeafyYT** [comment]
I'm using my own dedicated server (DataWagon)

**Comment by fancythedeveloper** [comment]
Maybe you didn't modify the EXE correctly, make sure that all normal and base64 links are replaced.

**Comment by LeafyYT** [comment]
I am 90% sure they are but ill double check. What url should I encode? http://boomlings.com or http://boomlings.com/database

**Comment by LeafyYT** [comment]
This is the only unreplaced un-encoded url http://www.boomlings.com/databas/checkIfServerOnline.php

**Comment by LeafyYT** [comment]
Nope, nothing is un-encoded/replaced...

**Comment by fancythedeveloper** [comment]
Hmm... weird.

**Comment by LeafyYT** [comment]
Ikr

**Comment by LeafyYT** [comment]
Here is the whole thing if u need it... https://www.mediafire.com/file/kijosyngvk4txgb/XGDPS.zip/file

**Comment by Cvolton** [comment]
make sure the server has write access to the data folder and its subdirectories

**Comment by LeafyYT** [comment]
That’s so smart I’ll try that. Sorry to ask but since I’m not a Ubuntu know it all I’m not exactly sure what command to use. Maybe you could help me with that also. :) Would me much appreciated 👏

**Comment by LeafyYT** [comment]
It worked, thank you soo much! (I still cant like posts tho...)
