### ISSUE TITLE
"Type" field in Actions table

### ISSUE THREAD

**Issue by ItzElectrix** [Cvolton/GMDprivateServer#625]
I was wondering if anyone knows what each of the numbers in the "type" field mean in the Actions table. The numbers seem to go from 2 through 10, and numbers like 7 are numbers that appear the most often in the table.

**Comment by WOSHIZHAZHA120** [comment]
Me too, should have a document about this...
Let @Cvolton write one?

**Comment by RedLime** [comment]
> Me too, should have a document about this...
> Let @Cvolton write one?

totally agree

**Comment by bit0r1n** [comment]
```
2 - user loginned
3-?(cuz $_POST['type'] + 2) - level like/dislike??
6 - something with password generating, i can't understand
7 - level downloaded, serves for "suspend downloads farm" (if this action by user exists, downloads number for level will not incease)
8 - delete level
9 - user updating his score (opens his profile from main menu)
10 - exists when sessionGrants enabled, used probably for cooldown in gjpcheck
```
i found only these actions, if you find more types, you can mention me

**Comment by fancythedeveloper** [comment]
Also, what's the poll thing in the SQL for?

**Comment by ItzElectrix** [comment]
ok, thanks!
