### ISSUE TITLE
One Point Nine

### ISSUE THREAD

**Issue by fancythedeveloper** [Cvolton/GMDprivateServer#627]
Seems that making a 1.9 GDPS doesn't work, 2.0 and 2.1(1) work just fine, just not 1.9.

**Comment by DarkGD123** [comment]
You need to have a specific files i think

**Comment by DarkGD123** [comment]
Try this one https://github.com/DonAlex0/GDPS19

**Comment by fancythedeveloper** [comment]
Thank you Yeet! It works!
