### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by dexie69** [Cvolton/GMDprivateServer#63]
title describes this problem perfectly

**Comment by RobertTopala** [comment]
Can you describe exactly what do you did step by step?

**Comment by dexie69** [comment]
I used the files in my server , step by step , when i launched the gdps
executable , nothing happened , no leaderboards , cant upload levels .The
only thing that worked was log-in.

On Mar 26, 2017 6:23 PM, "RobTop Games" <notifications@github.com> wrote:

Can you describe exactly what do you did step by step?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cvolton/GMDprivateServer/issues/63#issuecomment-289291186>,
or mute the thread
