### ISSUE TITLE
Something went wrong, wait later. 

### ISSUE THREAD

**Issue by okjjkjk** [Cvolton/GMDprivateServer#630]
As soon as I change libcocos, I get this error everywhere. Help me! 

DumtriX#8025

**Comment by fancythedeveloper** [comment]
Is this Android or PC? If its PC, you edit the EXE.

**Comment by okjjkjk** [comment]
Done! It fixed, its the LibCocos2dxpp and the **

`connection.php`

**

**Comment by EMREOYUN** [comment]
Please close issue if it is solved @okjjkjk

**Comment by DarkGD123** [comment]
Close the issue m8

**Comment by RobloxNationGaming** [comment]
Why it always says something went wrong in my GDPS help!!
