### ISSUE TITLE
link for redirection for android apks 

### ISSUE THREAD

**Issue by Telpo** [Cvolton/GMDprivateServer#635]
Hello so basically my friend has a gdps and wanted to make it android but its link was too long to replace so instead he got shorter link of the required length : craftpixel.net/dx/database which redirects to the main database

i tried making the android using craftpixel.net/dx/database, everything when replacing is right but the app still is not connected to the database, can anyone help with some answers

_idk if re-directive links are supported or not when making an android apk_ so could someone please give me an answer

**Comment by EMREOYUN** [comment]
So if you followed my steps on wiki, you actually search http://craftpixel.net/dx/ instead of http://craftpixel.net

**Comment by Telpo** [comment]
yeah i used  http://craftpixel.net/dx/ to make the apk but it still doesnt work, also where can i find the wiki

**Comment by fancythedeveloper** [comment]
https://github.com/Cvolton/GMDprivateServer/wiki
Click the Wiki button.

**Comment by Telpo** [comment]
> If you followed my steps on wiki, you actually search http://craftpixel.net/dx/ instead of http://craftpixel.net
Oh I see I misread that I'll try 
I read the wiki and I see

**Comment by EMREOYUN** [comment]
> > If you followed my steps on wiki, you actually search http://craftpixel.net/dx/ instead of http://craftpixel.net
> 
> Oh I see I misread that I
> 
> Ive read the wiki and I think I'll follow ur steps and get back to u

dx folder redirects to invalid directory. You may get errors and your database folder is not fully completed.

**Comment by Telpo** [comment]
hello again, so i made him change the link to http://craftpixel.net/database123  which redirects to his database which is http://104.192.0.114/000000000002/ (he hid the index for some reason its not actually invalid url) and changed the apk and every replacement went well but it still wont work its still unlinked

**Comment by EMREOYUN** [comment]
> hello again, so i made him change the link to http://craftpixel.net/database123 which redirects to his database which is http://104.192.0.114/000000000002/ (he hid the index for some reason its not actually invalid url) and changed the apk and every replacement went well but it still wont work its still unlinked

This is the problem about http hosting. What program or panel you are using on address you given to there?

**Comment by Telpo** [comment]
hello again, sorry for the late response
He said hes using Apache and Ubuntu 18.04

**Comment by EMREOYUN** [comment]
> hello again, sorry for the late response
> He said hes using Apache and Ubuntu 18.04

Server not returned an error to me(seems fine). Try recompiling your client again or try with that IP address but fills exact 17 characters.

**Comment by Mathieu57** [comment]
I can fix it in 2 minutes dm le on discord: MathieuAR@0673

**Comment by Telpo** [comment]
> I can fix it in 2 minutes dm le on discord: MathieuAR@0673

Dude tysm!! 
I'll redirect the server owner to you 
If u need me instead ask him
He's dxrkify.mp3@4200

**Comment by EMREOYUN** [comment]
@Telpo Close the issue if fixed.

**Comment by Telpo** [comment]
Tysm everyone for the contributions! especially emeroyn and Mathieu 👍  its fixed now and its working

**Comment by EMREOYUN** [comment]
Another time my name writen wrong. Hooray.
