### ISSUE TITLE
Reuploading Levels Account

### ISSUE THREAD

**Issue by MrScootman7** [Cvolton/GMDprivateServer#640]
Ok, so... Is there any possible way to make it so if someone Reuploads a Lvl from RobTop server it reuploads under a account and not the unkown user thing

And, make NA the defualt reupload rate

**Comment by Cvolton** [comment]
Rating is hard coded to be transferred over in levelReupload.php, so you'd have to edit that. Same for the default reupload account if you want to change it. People can already reupload to their own accounts if they link their normal GD and gdps accounts using the linkacc tool

**Comment by MrScootman7** [comment]
So does it set the default reupload like if anyone reuploads any level?

**Comment by MrScootman7** [comment]
wait nvm got right
