### ISSUE TITLE
Email is invalid

### ISSUE THREAD

**Issue by anhminh01997** [Cvolton/GMDprivateServer#642]
When i try to register an account it says invalid email even though i entered the right email format

**Comment by fancythedeveloper** [comment]
try something like a@a.m or a@b.c, that should work

**Comment by anhminh01997** [comment]
> 
> 
> try something like [a@a.m](mailto:a@a.m) or [a@b.c](mailto:a@b.c), that should work

Doesn't work
![(Screenshot)](https://user-images.githubusercontent.com/47952456/90319921-59f33700-df0a-11ea-8ca2-1484e3902e94.png)

**Comment by Mathieu57** [comment]
Your version is possibly broken try with this one and link it to your gdps

Link: http://gdps.mathieuar.fr/GD-2.1.zip

**Comment by anhminh01997** [comment]
> 
> 
> Your version is possibly broken try with this one and link it to your gdps
> 
> Link: http://gdps.mathieuar.fr/GD-2.1.zip

Nope Still doesn't work

**Comment by EMREOYUN** [comment]
Your email must contain valid end prefixes lile .com .net .xyz etc.

**Comment by fancythedeveloper** [comment]
3 letter emails like a@a.m and a@b.c has worked in the past, so unless that changed recently, then something else is wrong.

**Comment by anhminh01997** [comment]
turns out i just forgot to change text values in notepad++ thx for the help tho
