### ISSUE TITLE
How do i someone else ban on comment?

### ISSUE THREAD

**Issue by RedLime** [Cvolton/GMDprivateServer#644]
![1597581726318.jpg](https://user-images.githubusercontent.com/25276450/90334563-7b871800-e009-11ea-9fb6-1bb2b24f4f92.jpg)
Recently, RobTop server confirmed that the comment upload has a "Banned" message. What do I have to do to use or add this in the GDPS?

**Comment by EMREOYUN** [comment]
I think we didn't make a feature for it.

**Comment by Wyliemaster** [comment]
Hasnt been implemented as far as i know

**Comment by fancythedeveloper** [comment]
There's a PR for it though.

**Comment by fancythedeveloper** [comment]
Pull Request #650

**Comment by RedLime** [comment]
> Pull Request #650 

Yeah, i found and make that works fine.

**Comment by WOSHIZHAZHA120** [comment]
Permanently banning comments will return -10
(Google Translate)

**Comment by RedLime** [comment]
> Permanently banning comments will return -10
> (Google Translate)

yes, but tempban is will return `temp_(duration sec)_(reason)`. i got this, and i did that pull request.

**Comment by WOSHIZHAZHA120** [comment]
> > Permanently banning comments will return -10
> > (Google Translate)
> 
> yes, but tempban is will return `temp_(duration sec)_(reason)`. i got this, and i did that pull request.

Yes but you can add permanently ban.

**Comment by Wyliemaster** [comment]
> > > Permanently banning comments will return -10
> > > (Google Translate)
> > 
> > yes, but tempban is will return `temp_(duration sec)_(reason)`. i got this, and i did that pull request.
> 
> Yes but you can add permanently ban.

Can confirm, i did this earlier today. All you do is add a collumn in database for it
Get the database to check it and if its 1, echo -10

Example: https://youtu.be/TPUeU3JqznI

**Comment by WOSHIZHAZHA120** [comment]
> > > > Permanently banning comments will return -10
> > > > (Google Translate)
> > > 
> > > 
> > > yes, but tempban is will return . i got this, and i did that pull request.`temp_(duration sec)_(reason)`
> > 
> > 
> > Yes but you can add permanently ban.
> 
> Can confirm, i did this earlier today. All you do is add a collumn in database for it
> Get the database to check it and if its 1, echo -10
> 
> Example: https://youtu.be/TPUeU3JqznI

I know and i already have it in my GDPS.

**Comment by WOSHIZHAZHA120** [comment]
You can try if ban status == 1 for temp ban
and ban status == 2 for perm ban
