### ISSUE TITLE
Change or Add Main levels

### ISSUE THREAD

**Issue by RedLime** [Cvolton/GMDprivateServer#645]
Some GDPS have seen the main levels being changed or added. How do I change or add the main level of the mobile and PC versions?

**Comment by fancythedeveloper** [comment]
Watch Absolute's Level Manager video.

I suggest you Google things before you ask.

https://youtu.be/ZOTbHyuXx4I

https://www.youtube.com/watch?v=1NC6T6y_09k (for Android)

**Comment by RedLime** [comment]
> Watch Absolute's Level Manager video.
> 
> I suggest you Google things before you ask.
> 
> https://youtu.be/ZOTbHyuXx4I
> 
> https://www.youtube.com/watch?v=1NC6T6y_09k (for Android)

oh wait, i'm dumb. i forgot a google 🤣 
thanks for this comment!
