### ISSUE TITLE
Is there a way to disable bcrypt?

### ISSUE THREAD

**Issue by imadofficial** [Cvolton/GMDprivateServer#646]

**Comment by EMREOYUN** [comment]
I'm waiting the answer also.

**Comment by imadofficial** [comment]
I mean you are a contributor

**Comment by EMREOYUN** [comment]
I'm just a translator and edited some parts of code and created wiki part.
I'm not an expert.

**Comment by EMREOYUN** [comment]
> I mean you are a contributor. But do you know a way how to bypass it?
> I got it bypassed at register but not at login

Just try to do whatever done in register into login also.

**Comment by imadofficial** [comment]
But what do I need to modify?

**Comment by EMREOYUN** [comment]
I don't know, you said you modified and got pass registering.

**Comment by imadofficial** [comment]
Yea but I dont know about the login

**Comment by EMREOYUN** [comment]
> Yea but I dont know about the login

Idk what did you do and idk how to disable BCrypt(and i'm not sure it can be disabled or not).

**Comment by Cvolton** [comment]
Why would you want to disable bcrypt in the first place?

**Comment by fancythedeveloper** [comment]
Though if you **really**, **_really_** want to remove bcrypt, you could try removing the changes from [commit e62e6d](https://github.com/Cvolton/GMDprivateServer/commit/e62e6df1b6254a0b206a9c8148d76c085dbd7453).

**Comment by imadofficial** [comment]
Thanks!

**Comment by Catover203** [comment]
It can be not have secure, it have an :
+ You can remove but the hacker can assess and steal painttext password
+ It can turned into password storage, I are making some strong password encrypt

**Comment by Cvolton** [comment]
pain
