### ISSUE TITLE
Gauntlets

### ISSUE THREAD

**Issue by MrScootman7** [Cvolton/GMDprivateServer#647]
there is no curretn function to add it from the dashboard so u need to do from winscp, so i did that and the thigns sort by id and i looked in winscp how do i make so it dose NOT sort by id and by the order i put them

**Comment by fancythedeveloper** [comment]
WinSCP? You do gauntlets through the SQL.

**Comment by MrScootman7** [comment]
No there is a line of code in WinScp in levelpacks.php which sorts it by ID and i dont want tthat i removed the line everything

**Comment by RedLime** [comment]
check this issue. needs edit getGJLevels.php
#643

**Comment by MrScootman7** [comment]
can u dm me on Discord? _Mr.Scatman7#3843
