### ISSUE TITLE
Ever wanted a GDPS community?

### ISSUE THREAD

**Issue by imadofficial** [Cvolton/GMDprivateServer#649]
Welcome to the GDPS community, the server where we can talk as a community. It's inactive right now but we can make it active. You can make friends or just talk about stuff in our server. I am transparent and open for feedback.
Join today at: https://discord.gg/7bVBhDc

**Comment by fancythedeveloper** [comment]
Please close this, why advertise in the issue section of a repository?

**Comment by EMREOYUN** [comment]
@imadofficial This isn't advertising area, this is for issues and problems.

@Cvolton

**Comment by imadofficial** [comment]
Idk really

**Comment by imadofficial** [comment]
I saw other people advertising

**Comment by EMREOYUN** [comment]
> I saw other people advertising

Gimme the issue id of them
