### ISSUE TITLE
Creating an account works, but I can't login into it?

### ISSUE THREAD

**Issue by GDDogeYT** [Cvolton/GMDprivateServer#656]
I'm using 5v.pl to host my new gdps, account creating works, but I can't login?

Also I opened the loginGJAccount.php file and this popped up...

![image](https://user-images.githubusercontent.com/57293929/91173963-eb1e9680-e6de-11ea-86d3-6ad8afbfb4de.png)

**Comment by fancythedeveloper** [comment]
You're not suppose to open it on a browser, so that's normal.

**Comment by RedLime** [comment]
its only works on ingame.

**Comment by GDDogeYT** [comment]
> its only works on ingame.

yea i tried to login ingame...

**Comment by Jecket22** [comment]
You probably imported the database.sql improperply. That did happen to me too, but after a small fix in the database, it worked again like a charm.

You probably want to try that out. [alter_table_fix.zip](https://github.com/Cvolton/GMDprivateServer/files/5129118/alter_table_fix.zip)

**Comment by GDDogeYT** [comment]
So it was the problem that the database was imported properly... Now it works, thanks @Jecket22 !
