### ISSUE TITLE
Player stars are doubling

### ISSUE THREAD

**Issue by GDDogeYT** [Cvolton/GMDprivateServer#659]
Hi, I just made my new gdps and its doing fine, but one of my friends is somehow doubling stars by reloading his profile? Please tell me how to fix it ASAP

**Comment by DarkGD123** [comment]
Hm

**Comment by Jecket22** [comment]
What if your friends just plays levels that got rated later on after they beat it? If that's not the case, then you should use cronJob.php in the tools page.
