### ISSUE TITLE
Main levels

### ISSUE THREAD

**Issue by Guillamet** [Cvolton/GMDprivateServer#671]
Hi,

Is it possible to change main levels in a GDPS ? I already googled that but nothing found. I found nothing on the phpmyadmin or the ftp too (maybe i'm too blind)

Can you please help me?
thx

**Comment by fancythedeveloper** [comment]
You can't change the main levels from the server, you have to use Absolute's Level Manager to do that.

**Comment by RedLime** [comment]
#645

**Comment by Guillamet** [comment]
thank you !
