### ISSUE TITLE
Read the comment

### ISSUE THREAD

**Issue by GalaxyDashGDPS** [Cvolton/GMDprivateServer#674]
How can i get the user id of a user without entering to the database

**Comment by fancythedeveloper** [comment]
You could try GDBrowser, but I assume you don't know how to use node.js.

**Comment by GalaxyDashGDPS** [comment]
Yeah i tried to do it in glitch but it don't work and how can i disable a user account?

**Comment by Jecket22** [comment]
For one, you cannot get an UserID of someone without accessing the database, unless you manage to use black magic. Also, isBanned probably disabled the account... If not, you can just delete the account or its password. Levels won't be automatically removed if the account is deleted.

**Comment by GalaxyDashGDPS** [comment]
Ok now i will close the issue
