### ISSUE TITLE
Downloads does not work on 2.0

### ISSUE THREAD

**Issue by Riax00** [Cvolton/GMDprivateServer#675]
Hello! Im trying to fix an issue for over 2 hours. It is about displaying downloads in GD 2.0

When someone clicks/get the level for the first time, it should add 1 download to the database.
It works, but it wills stop working after it gives out 2 downloads. It is tested and 100% accurate.
I can change the default downloads to 5 for example, it will only work to 7.
0 downloads as default, will only work to 2 downloads, then it will stop adding them.

while this sounds like barely a problem, I really really want to fix it. It is weird seing a level with 2 downloads and 16 likes....
I think that the only possible fix is reinserting the database... and i dont really want to do that. 

Thanks for help

**Comment by fancythedeveloper** [comment]
This isn't a 2.0 issue.
#586

**Comment by Riax00** [comment]
Thanks, any way to do it without importing the whole database again?
Thanks for help

**Comment by fancythedeveloper** [comment]
You don't need to modify the database, just edit /database/incl/levels/downloadGJlevel.php.

**Comment by Riax00** [comment]
Thanks
