### ISSUE TITLE
The server is not replaced (Main Level Customizer)

### ISSUE THREAD

**Issue by RedLime** [Cvolton/GMDprivateServer#676]
[ItalianAPK's vid](https://www.youtube.com/watch?v=1NC6T6y_09k)
I do it Like this video, I edited the libcocos2dapp.so file to work on my server.

And this has changed the Main Level, but the server has not changed to my server.

I checked the libcocos2dapp.so in my apk file, but there was no link to the RobTop server anywhere. Is there anything I missed?

**Comment by DarkGD123** [comment]
did you edit the base 64 of the boomlings website in it

**Comment by RedLime** [comment]
> did you edit the base 64 of the boomlings website in it

yes i did

**Comment by fancythedeveloper** [comment]
@RedLime Try searching for uploadGJ or something and you can find the link that's in the APK.

**Comment by RedLime** [comment]
> @RedLime Try searching for uploadGJ or something and you can find the link that's in the APK.

i found something my mistakes. thanks
