### ISSUE TITLE
UploadGJLevel.php is error

### ISSUE THREAD

**Issue by Catover203** [Cvolton/GMDprivateServer#677]
It was error web use free freewha.com or awardspace.com, use my fixed gdps

**Comment by fancythedeveloper** [comment]
FreeWHA is bad because literally in the terms, you can't use it for a Game server, had to learn it the hard way.

**Comment by Catover203** [comment]
yeah

**Comment by Catover203** [comment]
I paid for my own serser, it was 5$ per month

**Comment by fancythedeveloper** [comment]
I'm using Google Cloud for my VPS, good enough for me.
