### ISSUE TITLE
Place your issues here, I will help

### ISSUE THREAD

**Issue by Catover203** [Cvolton/GMDprivateServer#678]
Place your issues here, i can help you
Because i understand php
And i was fix a ton of error

**Comment by ForeverGD** [comment]
Make your own kernel (Cvolton modification)

**Comment by Jecket22** [comment]
How about you just comment to other issues, simple as that, wasting no time for others to make a comment to an issue to state their issue.

**Comment by Cvolton** [comment]
![nadzvukový](https://user-images.githubusercontent.com/5721187/97025805-d7fe3a80-1558-11eb-8685-ea2436e4d79c.png)
