### ISSUE TITLE
GDPyS, A new type of gdps.

### ISSUE THREAD

**Issue by spookybear0** [Cvolton/GMDprivateServer#679]
Me and RealistikDash (from VPS) have been working on a new type of gdps called GDPyS, it is made in python and has more features, runs faster, and just overall works better. More information [here](https://github.com/RealistikDash/GDPyS/tree/rewrite).

**Comment by Catover203** [comment]
GDPS is use an php and robtob write a program code is php
Your server cant workingwith org gd

**Comment by Intelligent-Cat** [comment]
will both of you shut up because:
1. this isn't a damn place to advertise
2. anything that can start a web server can be used as GDPS client
