### ISSUE TITLE
Upgrading to 2.2 Database

### ISSUE THREAD

**Issue by MrScootman7** [Cvolton/GMDprivateServer#680]
After the release of 2.2 there will prob be a new database file. In this case. How are we gonna upgrade, because you will need to delete the old one and gte the new which means all accounts levels etc. please help me. If anyone can give me a specific answer thanks. otherwise i would like for cvolton to maby explain thanks

**Comment by fancythedeveloper** [comment]
It might take a while, but once 2.2 is out, GDPS will hopefully get 2.2 compatibility.

**Comment by Joxlyn** [comment]
When 2.1 came out, Cvolton worked a lot to update the database, if I remember correctly, it took a month for it to be 100% working at 2.1

**Comment by MrScootman7** [comment]
well yes, but what im asking is. will you like just import a new database and delete the old one (will delete all accounts levels etc.) im just curious about it tho

**Comment by fancythedeveloper** [comment]
um, idk if you can just directly just import the new SQL,

you could try exporting the current SQL, dropping all of your tables, then importing the 2.2 SQL, then importing your exported SQL

**Comment by Cvolton** [comment]
the current way I recommend upgrading is exporting data from the database, importing the new database structure and importing the exported data on top of that

**Comment by MrScootman7** [comment]
> the current way I recommend upgrading is exporting data from the database, importing the new database structure and importing the exported data on top of that

thats actually smart i dont know how i thought about that lmfao. well, i was just curious have a nice one cya ig
