### ISSUE TITLE
GDPS will not let me run on my database, but it runs on RobTop's database.

### ISSUE THREAD

**Issue by CUKESIM** [Cvolton/GMDprivateServer#684]
I am planning on making a GDPS but its not working. Can i get help?
![image](https://user-images.githubusercontent.com/56658781/99092815-469e4900-2597-11eb-83b4-e077fdc6d650.png)

**Comment by Intelligent-Cat** [comment]
full URL to the GDPS database should be exactly 26 characters, e.g. www.boomlings.com/database

**Comment by CUKESIM** [comment]
yes, the url is http://afoebgeom.7m.pl

**Comment by Intelligent-Cat** [comment]
that URL is 24 characters.

**Comment by CUKESIM** [comment]
bruh someone told me that it was supposed to be 9 charcters like the boomlings name. my apologies. i will close this issue once this is resolved. thanks!

**Comment by Intelligent-Cat** [comment]
it should be 11

**Comment by CUKESIM** [comment]
ok so, it works but registering will not work. that goes with publishing a level, it wont show up in the recent tab or the search bar :/
![image](https://user-images.githubusercontent.com/56658781/99109240-1f06ab00-25ae-11eb-8ee3-7161ac39e594.png)

**Comment by DarkGD123** [comment]
have you ever tried to put the database details in `connection.php` correct?

**Comment by CUKESIM** [comment]
![image](https://user-images.githubusercontent.com/56658781/99137227-f5ba3f00-25ee-11eb-9640-9b6b2c0742c8.png)

my friend told me to patch the gd client, can i get guides?

**Comment by DarkGD123** [comment]
What gd version do you use

**Comment by CUKESIM** [comment]
i think the current version, i used this tutorial but i dont know what version this gd is https://www.youtube.com/watch?v=lbqfqfGrwUU

**Comment by CUKESIM** [comment]
i used my friend's gdps and replaced databases and base64 and that didnt work neither, it was 1.2

**Comment by CUKESIM** [comment]
it says "1.0.6"

**Comment by CUKESIM** [comment]
![Uploading image.png…]()

**Comment by CUKESIM** [comment]
or can you just dm me on discord and solve the issue for me

CUKESIM#5749

**Comment by RobloxNationGaming** [comment]
Because you didn't edit it on hex editor you need 2 apps
Hex editor & base64 encoder

**Comment by fancythedeveloper** [comment]
I swear is someone necrobumping old issues? WTF.

**Comment by CUKESIM** [comment]
This issue has been resolved months ago.
