### ISSUE TITLE
Mod access says "failed, nothing found" when i gave myself mod access

### ISSUE THREAD

**Issue by NoahGMD** [Cvolton/GMDprivateServer#687]
the new requestUserAccess.php fix made it say "failed nothing found" instead of "success, elder moderator access granted"
![Screenshot_20201115-091614](https://user-images.githubusercontent.com/73782137/99187208-3d41e780-2723-11eb-9651-1673e3fa4d0b.png)

**Comment by DarkGD123** [comment]
hm thats weird

**Comment by NoahGMD** [comment]
also i copied over all the code correctly, i spent half an hour checking.

**Comment by fancythedeveloper** [comment]
Did you do the roleassign thing right? I'm assuming you did.

**Comment by NoahGMD** [comment]
lemme check

**Comment by NoahGMD** [comment]
i gave myself mod access before updating the code so i am admin but i cant mod anybody else right now...

**Comment by fancythedeveloper** [comment]
Wait, did you use roleassign or is the isAdmin thing?

**Comment by NoahGMD** [comment]
i used both. is that what the issue is?

**Comment by NoahGMD** [comment]
I tried changing isAdmin to 0 and it didn't work so idk what to do now.

**Comment by Catover203** [comment]
@NoahGMD 
Use my GDPS

**Comment by DarkGD123** [comment]
totally not advertising ^

**Comment by NoahGMD** [comment]
lol

**Comment by Intelligent-Cat** [comment]
lol that thing sucks even unstable gdos is better than that

**Comment by Ben569483** [comment]
You have to create the mod role, then go to roleassign and put in the first 2 boxes a 1 and the 3rd box a 71
