### ISSUE TITLE
Load "Sync Failed"

### ISSUE THREAD

**Issue by MrScootman7** [Cvolton/GMDprivateServer#688]
So i just backed up my data from my phone and loaded on PC and I keep getting "Sync Failed" Error, I refreshed. Checked if the servers were down. It wasent, help.
Edit: Happens to everyone else

**Comment by DarkGD123** [comment]
Have you check `data/levels` folder and chmod it?

**Comment by MrScootman7** [comment]
chmod?

**Comment by DarkGD123** [comment]
> chmod?
> 
> Add me on Discord rq: Mr.Scatman7#3843

My Discord Is Yeet also im in your gdps

**Comment by MrScootman7** [comment]
i saw Lol

**Comment by DarkGD123** [comment]
Another issue like this #538

**Comment by MrScootman7** [comment]
For these that need help: Its 7m.pl or your host that is displaying ads over the Saved data which the webserver isnt able to see.
