### ISSUE TITLE
Bug in upload update time levels

### ISSUE THREAD

**Issue by RobertTopala** [Cvolton/GMDprivateServer#69]
There is a bug that cause the time ago shows the time like this "27/03/2017 20-18" when the time should be something like this "2 weeks ago"

**Comment by Cvolton** [comment]
works as intended

**Comment by rosenishere** [comment]
lool issue 69

**Comment by Cvolton** [comment]
![saddery](https://cdn.discordapp.com/emojis/375297208288804875.png?v=1)

**Comment by tzt345** [comment]
LoololololololololololololoololololololLoololololololololololololoololololololLoololololololololololololoololololololLoololololololololololololoolololololol 69 XD!!!!
