### ISSUE TITLE
what is the 'polls' table on the database?

### ISSUE THREAD

**Issue by NoahGMD** [Cvolton/GMDprivateServer#690]
i was on the phpMyAdmin and found a table called 'poll'. idk what it's for. does anyone know?
![Screenshot_20201130-172437_kindlephoto-1458989334](https://user-images.githubusercontent.com/73782137/100673311-3de89980-3331-11eb-887b-281e4ade8f7e.png)

**Comment by fancythedeveloper** [comment]
#244

**Comment by NoahGMD** [comment]
ok
