### ISSUE TITLE
Yeah

### ISSUE THREAD

**Issue by MarcGD130** [Cvolton/GMDprivateServer#694]
Is it possible to decrypt the save data that came from `data/accounts`

**Comment by DarkGD123** [comment]
I dont know either

**Comment by Jecket22** [comment]
yes, in fact it's the same method as decrypting the save data from %localappdata%/<gdps> if I remember correctly

**Comment by bit0r1n** [comment]
https://github.com/gd-programming/gddocs/blob/master/docs/topics/localfiles_encrypt_decrypt.md#decryption

**Comment by MarcGD130** [comment]
thanks for the info

**Comment by DarkGD123** [comment]
so any script tool to do like decryption and such
