### ISSUE TITLE
When I go up a level, this level automatically has 100 likes and 300 downloads.

### ISSUE THREAD

**Issue by iLui** [Cvolton/GMDprivateServer#696]
When I go up a level, this level automatically has 100 likes and 300 downloads.

**Comment by DarkGD123** [comment]
Check #586

**Comment by iLui** [comment]
I did not understand very well what I have to do

**Comment by DarkGD123** [comment]
Go to your database and go to levels table and go to structure tool and change the value of downloads and likes to 0

**Comment by iLui** [comment]
Thanks a lot! it worked!
