### ISSUE TITLE
any way I could change the Downloads and Likes to go above 2 on the Database?

### ISSUE THREAD

**Issue by Riax00** [Cvolton/GMDprivateServer#707]
-- I DO NOT HAVE ACCESS TO FTP --

Hello, can someone please tell me a way to make the downloads and likes go above 2 on phpmyadmin?

My private server is hosted on gdps.mathieuar.fr, they block ftp access.
Is there a way to make it go above 2 on the database?
Thanks for help

EDIT: I know that you can change it somewhere in one of the files, but I do not have FTP access so I would not be able to insert it.

**Comment by Cvolton** [comment]
I believe you should contact the owner of said service to fix the issue.

**Comment by NoahGMD** [comment]
why aren't the likes going above two? did you edit something when ftp access was availible?

**Comment by RealistikDash** [comment]
Most likely some rate limiting measure messing with the configuration of the server or the other way round.
