### ISSUE TITLE
7m.pl costs 3$ now?

### ISSUE THREAD

**Issue by DuckyGit** [Cvolton/GMDprivateServer#711]
So i try to register on 7m.pl and it says i need to pay $3.

Is there any other 7m.pl alternatives i can use? (except 5v.pl since it redirects to 7m.pl and freewha since its broken)

**Comment by DarkGD123** [comment]
GDPS Free Hosting By MathieuAR

**Comment by DarkGD123** [comment]
And 000webhost.com

**Comment by DuckyGit** [comment]
@DarkGD123 Im not gonna host on some VPS i cant access since i dont have a phone number on discord and 000webhost doesnt work.

**Comment by DuckyGit** [comment]
000webhost has a database version GDPS desnt support

**Comment by DarkGD123** [comment]
> @DarkGD123 Im not gonna host on some VPS i cant access since i dont have a phone number on discord and 000webhost doesnt work.

Well go waste money on paid hosting then, no offense

**Comment by ElectroFlameOfficial** [comment]
you can use freewha but you might wanna make sure it stays active (has traffic from and to the main website, not the database)

**Comment by DarkGD123** [comment]
well freewha is good but its ftp system is bad but still useful

**Comment by ElectroFlameOfficial** [comment]
better than nothing yk

**Comment by DarkGD123** [comment]
just use freewha its pretty nice (just make it alive though)

**Comment by DuckyGit** [comment]
sorry but i now cant access the freewha ftp system

**Comment by DarkGD123** [comment]
> sorry but i now cant access the freewha ftp system

Yeah their ftp system is bad

**Comment by Jecket22** [comment]
Can't really recommend any free hosts, most I've tried would block geometry dash from accessing the server. So best I would just use a paid webhost, even $.5 hosts are good enough for a gdps. I personally use a virtual private server to have more control over everything, which is also just around $3/month.

**Comment by Cvolton** [comment]
I've enabled the Discussions feature now so if you wish to continue this, I recommend you move over there.
I'm closing this issue as it isn't really relevant to the core project

**Comment by RobloxNationGaming** [comment]
> GDPS Free Hosting By MathieuAR

Welp GDPS Free Hosting Is Dead

**Comment by ElectroFlameOfficial** [comment]
...dead for now. mathieu is trying to get it up again.

**Comment by Jecket22** [comment]
@Cvolton mind you closing this convo
