### ISSUE TITLE
Beta Dashboard not working

### ISSUE THREAD

**Issue by ElectroFlameOfficial** [Cvolton/GMDprivateServer#712]
I'm currently trying to create a GDPS for a friend that wants the main tools area to be the beta dashboard. every time i try loading up the database i get this error: 
![image](https://user-images.githubusercontent.com/51268650/105109808-48025b00-5a8b-11eb-960d-8c386139d458.png)
Any way to fix this?

**Comment by Intelligent-Cat** [comment]
you blind
read the error

**Comment by ElectroFlameOfficial** [comment]
if i didn't try fixing it i wouldn't have come here.

**Comment by Cvolton** [comment]
your credentials in config/connection.php are wrong

**Comment by EMREOYUN** [comment]
Make sure the IP address is the machine hosts your website is allowed on your database config
![image](https://user-images.githubusercontent.com/35144629/121960125-59b40a00-cd6e-11eb-98ca-6756220d7f81.png)

**Comment by EMREOYUN** [comment]
Make sure the IP address is the machine hosts your website is allowed on your database config
![z3Oe9q6Tvp](https://user-images.githubusercontent.com/35144629/121960319-9b44b500-cd6e-11eb-8041-7844f4385529.png)

**Comment by ToppLeDev** [comment]
die
