### ISSUE TITLE
Cannot login into account

### ISSUE THREAD

**Issue by SergeyMC9730** [Cvolton/GMDprivateServer#713]
I recently setup my private server in Termux with installed MySQL, Apache and PHP. I made an account and tried to login into it. I got this error:
 
![image](https://user-images.githubusercontent.com/57207009/106858490-b5a1be80-66fc-11eb-894e-f50c302bec67.png)

But I can upload any levels:

![image](https://user-images.githubusercontent.com/57207009/106858695-044f5880-66fd-11eb-9ea3-883a73e50ac0.png)

So how can I fix it?

**Comment by LimeGradient** [comment]
how did you fix this issue?

**Comment by SergeyMC9730** [comment]
> how did you fix this issue?
i dont remember it was three years ago lol
