### ISSUE TITLE
7m.pl bugging

### ISSUE THREAD

**Issue by DarKSoulZ964** [Cvolton/GMDprivateServer#719]
Whenever I try to register for an account, it says: "Your IP address has been blocked". Any tips on what to do?
![7m pl](https://user-images.githubusercontent.com/79947347/109834366-b8160c00-7c07-11eb-84e5-8d5f58981482.jpg)

**Comment by DarKSoulZ964** [comment]
And when i try with webhost, the application for the template always just doesn't let me open it

**Comment by DarKSoulZ964** [comment]
Can anyone help?

**Comment by Cvolton** [comment]
contact 7m.pl support, this is outside of the project scope

**Comment by DarkGD123** [comment]
This happens to me too, if you made like multiple accounts in one IP

**Comment by DarKSoulZ964** [comment]
> This happens to me too, if you made like multiple accounts in one IP

But even on m,y first try it just wouldn't work
