### ISSUE TITLE
When I rated a level & complete it it kicked me out of the level plz fix it

### ISSUE THREAD

**Issue by RobloxNationGaming** [Cvolton/GMDprivateServer#723]
Plz

**Comment by Cvolton** [comment]
make sure the star amount matches the difficulty and that it's more than 30 seconds long if it's normal or higher difficulty

**Comment by Dragon77mathbye** [comment]
In other words, if a level is rated higher than 2 stars on a level that is shorter than 30 seconds (Tiny or Short length) than the anticheat will kick you out at the end

**Comment by Dragon77mathbye** [comment]
Also how can you turn off the anticheat so you can complete levels of this length? I know it's possible because XGDPS and a few others have done it

**Comment by RobloxNationGaming** [comment]
> Also how can you turn off the anticheat so you can complete levels of this length? I know it's possible because XGDPS and a few others have done it

Nvm I fixed It By This Repository :D
https://github.com/Cvolton/GMDprivateServer/tree/1b5acbf5fac6d56a2b14b394134741e296000596

**Comment by Dragon77mathbye** [comment]
It doesn't fix it for mobile though

**Comment by Dragon77mathbye** [comment]
How do I fix the same issue for mobil

**Comment by Cvolton** [comment]
Glad you got it to work, though I'd like to note that this is caused by the client-side anticheat and therefore cannot be solved by downgrading to a version of the GDPS from August like you imply it does. Moreover, various security improvements were made since then and running outdated versions is therefore also considered a security risk.

**Comment by Dragon77mathbye** [comment]
> Glad you got it to work, though I'd like to note that this is caused by the client-side anticheat and therefore cannot be solved by downgrading to a version of the GDPS from August like you imply it does. Moreover, various security improvements were made since then and running outdated versions is therefore also considered a security risk.

Is there another way to do it besides downgrading?
