### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by trubiso** [Cvolton/GMDprivateServer#726]
I can create accounts but cannot log into them, level uploading and all of the rest works fine.

**Comment by trubiso** [comment]
Ok, I found the problem (using wireshark)

At accounts/loginGJAccount.php it says `require_once "../lib/mainLib.php";` when in reality it should say `require_once "../incl/lib/mainLib.php";`. Hope this gets fixed in a commit

**Comment by Cvolton** [comment]
still valid, reopening
