### ISSUE TITLE
How do I make a local gdps?

### ISSUE THREAD

**Issue by Dragon77mathbye** [Cvolton/GMDprivateServer#727]
Since I have very little experience with hosting, and I want a local server, how can I do that?
I have XAMPP installed

Thanks in advance

**Comment by DarkGD123** [comment]
https://github.com/Cvolton/GMDprivateServer/wiki/Installiation-Guide-for-WebHostings-and-Dedicated-Servers#using-xampp

**Comment by Dragon77mathbye** [comment]
How do I make this long enough to not change the file size?

bG9jYWxob3N0Lw==

(That's localhost base64 encoded aka my host site)

and boomlings is this long:

aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL3

**Comment by DarkGD123** [comment]
> How do I make this long enough to not change the file size?
> 
> bG9jYWxob3N0Lw==
> 
> (That's localhost base64 encoded aka my host site)
> 
> and boomlings is this long:
> 
> aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL3

I mostly do like making the same length as the website like (localhost:8080/database or something)

**Comment by Dragon77mathbye** [comment]
even after adding http:// and :3306 it still is two characters short

**Comment by Dragon77mathbye** [comment]
How do I fix that?

**Comment by Dragon77mathbye** [comment]
I tried http://localhost/dragon7/ but now I can't run the file

**Comment by Safariminer** [comment]
> I tried http://localhost/dragon7/ but now I can't run the file

Make your folder's name shorter and the problem will be solved. Remember: YOU CANNOT CHANGE SOME TEXT IN THE EXECUTABLE IF IT CHANGES THE EXECUTABLE'S SIZE, OR ELSE... welp... or else, your file won't launch.

**Comment by Dragon77mathbye** [comment]
But the file is the same size

**Comment by DarkGD123** [comment]
I mostly do this sometimes (make sure its 26 tho)

http://localhost:8080/gdps/gddata

Total of 33 words/characters since it has http://

**Comment by Dragon77mathbye** [comment]
Despite changing the links, running the file still opens robtop's servers

**Comment by Cvolton** [comment]
make sure to change the non-base64 encoded strings as well

**Comment by Dragon77mathbye** [comment]
I did except for the boomlings that did not have a /database after it, but I can't make localhost/dragon77gdps1234 the right length in any way

**Comment by DarkGD123** [comment]
Isnt like xampp has like a website with port like

localhost:8080 or localhost:8000

**Comment by Dragon77mathbye** [comment]
![image](https://user-images.githubusercontent.com/74103504/110403990-0d10b280-804c-11eb-8591-9fc6756d6852.png)
But it's not long enough

**Comment by Dragon77mathbye** [comment]
![image](https://user-images.githubusercontent.com/74103504/110404032-20238280-804c-11eb-8446-8c1141b93aff.png)

**Comment by DarkGD123** [comment]
Idk what you're doing but

If you gonna make a directory make sure you put it in htdocs folder

**Comment by Dragon77mathbye** [comment]
I have the directory in htdocs
![image](https://user-images.githubusercontent.com/74103504/110547003-4e14cf80-80fd-11eb-805f-1f0753b8c3d8.png)

**Comment by fancythedeveloper** [comment]
To be honest, I don't understand why not just host it publicly instead of privately, I can help you with that if you need.

**Comment by Dragon77mathbye** [comment]
I wanted to host a private gdps to "experiment" with if you know what I mean

**Comment by fancythedeveloper** [comment]
Fair enough, but it seems hardest to host than just a regular public GDPS, you can just keep that private by not distributing the download.

**Comment by Dragon77mathbye** [comment]
But I also wanted to be  able to work on it offline

**Comment by Cvolton** [comment]
From what I can gather, I see several mistakes being made in this thread
- Address set to localhostu:3306 - http runs on port 80, so it should be changed to just http://localhost or http://localhost:80 (both bring identical results)
- Mismatch in address length - you need to make sure that whatever it is you're replacing the original with is the exact same length as the original (count the characters)

**Comment by Cvolton** [comment]
> the xampp control panel says it's running on port 3306

That's mysql, the http server is handled by apache, which runs on port 80

**Comment by Dragon77mathbye** [comment]
it's still not long enough to replace HTTP://boomlings.com/

**Comment by fancythedeveloper** [comment]
http://localhost/gmd/ would probably be long enough

**Comment by Dragon77mathbye** [comment]
It shows the normal gd servers when I run it but uploading a level goes to the gdps

**Comment by fancythedeveloper** [comment]
You didn't modify all the links then, the older ones are plaintext while the 2.1 ones are base64.
I suggest reading [this](https://github.com/Cvolton/GMDprivateServer/wiki/Creating-Windows,-Android-and-IOS-Apps).

**Comment by Dragon77mathbye** [comment]
I did read it...when it's just http://localhost/ without the /database then idk what to do because it's not long enough

**Comment by fancythedeveloper** [comment]
maybe make a new folder in the localhost folder called like lhgdps or anything with 6 letters, then move the database folder to there, and then replace http://www.boomlings.com with that

**Comment by Dragon77mathbye** [comment]
I get this error:
![image](https://user-images.githubusercontent.com/74103504/110969866-2903a500-8327-11eb-86ed-81e271075bbe.png)

**Comment by fancythedeveloper** [comment]
Did you click All instead of just Forward?

**Comment by Dragon77mathbye** [comment]
Yes, I did

**Comment by Dragon77mathbye** [comment]
I'm so confused, can someone make an up-to-date video tutorial for localhost pls

**Comment by Jecket22** [comment]
Assuming you have a folder structure like `XAMPP/htdocs/database/...`, you must replace
`aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL2RhdGFiYXNl` `http://www.boomlings.com/database`
with
`aHR0cDovL2xvY2FsaG9zdDo4MC8vLy8vL2RhdGFiYXNl` `http://localhost:80//////database`

**Comment by Jecket22** [comment]
actually wait, since you have your folder named "dragon77gdps1234", you should replace
`aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL2RhdGFiYXNl` `http://www.boomlings.com/database`
with
`aHR0cDovL2xvY2FsaG9zdC9kcmFnb243N2dkcHMxMjM0` `http://localhost/dragon77gdps1234`

**Comment by Dragon77mathbye** [comment]
I have done that, I can't find the base64 encoded http://www.boomlings.com/
It gets 0 results

**Comment by fancythedeveloper** [comment]
> I have done that, I can't find the base64 encoded [http://www.boomlings.com](http://www.boomlings.com/)
> It gets 0 results

Did you click this?
![image](https://user-images.githubusercontent.com/30706150/111044966-a3aced00-8419-11eb-8339-40d75976319b.png)

**Comment by Dragon77mathbye** [comment]
Yes

**Comment by Cvolton** [comment]
make sure you're not trying to edit an already edited file

**Comment by Dragon77mathbye** [comment]
I'm not

**Comment by Dragon77mathbye** [comment]
ok server side is working, but client side is not
the level did upload when I tried but I can't view it
![image](https://user-images.githubusercontent.com/74103504/111082640-c43f7a80-84df-11eb-87e5-5a09b8f68c62.png)

**Comment by Dragon77mathbye** [comment]
![image](https://user-images.githubusercontent.com/74103504/111082913-3ebcca00-84e1-11eb-894a-390e9125cf07.png)

**Comment by Dragon77mathbye** [comment]
MathieuAR got it working for me so I have a working local gdps.

**Comment by Dragon77mathbye** [comment]
Thanks for your help though
