### ISSUE TITLE
Database Backup, older levels not downloading.

### ISSUE THREAD

**Issue by Optimal7** [Cvolton/GMDprivateServer#729]
Hi so I exported my database that contains levels, accounts etc. And i imported on my new Host and older level's are unable to download..

Any fix?

**Comment by Cvolton** [comment]
Have you transferred over the data folder as well?

**Comment by Optimal7** [comment]
The OVH thing happened and my host has FTP Disabled so eh is the data folder required for it??

**Comment by Optimal7** [comment]
like is the levels in the data folder?

**Comment by Cvolton** [comment]
It is required, as that is where the actual level data and cloud saves are stored

**Comment by Cvolton** [comment]
Uploading new versions of the missing levels will make them downloadable again, as the file will be recreated by the update process then

**Comment by Optimal7** [comment]
yes but what im asking is, if i upload a missing level same name and so to update it will it work?

**Comment by Cvolton** [comment]
yes because that's how updates work?

**Comment by Optimal7** [comment]
ight cool

**Comment by Intelligent-Cat** [comment]
i cant believe you even opened an issue here

**Comment by Jecket22** [comment]
@Intelligent-Cat that's completely reasonable and fine, shut
@Optimal7 have you tried chmodding all levels instead of only the folder? Usually it doesn't apply recursively to all files so you have to do that manually.

**Comment by Optimal7** [comment]
backups of the database were made not the webserver so everything is lost tho

**Comment by Intelligent-Cat** [comment]
@Jecket22 I mean I've like answered this to him on Discord and yet he still made an issue on this repo

Plus why are you guys continuing this issue further, just put the data folder in there and boom everything works again and as Cvolton said updating a level will eventually recreate the level data file which would make the level be able to downloaded again.

**Comment by Intelligent-Cat** [comment]
By the way if you are changing hosts remember to use the same package name for Android version so that people's data is not lost and that they can update their levels in order to make them are redownloadable.

**Comment by Optimal7** [comment]
Yes I know I'm not as stupid as I seem

**Comment by Intelligent-Cat** [comment]
Just some advice in case.

**Comment by Optimal7** [comment]
alr
