### ISSUE TITLE
WTH is this error!?! & This thing too

### ISSUE THREAD

**Issue by RobloxNationGaming** [Cvolton/GMDprivateServer#732]
Help
![Screenshot_2021-03-12-15-44-40-45](https://user-images.githubusercontent.com/77547237/110908568-fcad5000-8349-11eb-86cd-67a2dcb5481e.png)

**Comment by RobloxNationGaming** [comment]
WTH I Linked It Into My 7m.pl & doesn't work bruh
![Screenshot_2021-03-12-15-57-16-55_0dabdca0218ea00235d0a19c80ea8b7e](https://user-images.githubusercontent.com/77547237/110910066-d25c9200-834b-11eb-84e5-5391f7205d1f.png)

**Comment by ExyN-Github** [comment]
Your not supposed to visit files the server uses to make some functions work

Also your database url is shorter than 33 characters, http://rubrubrub.7m.pl/a/database should do

**Comment by Intelligent-Cat** [comment]
Please close this as it was thankfully solved by @ExyN-Github.

**Comment by Cvolton** [comment]
Please give us an update if this issue is still valid, otherwise I'm closing this
