### ISSUE TITLE
I just wanted to replace the facebook link

### ISSUE THREAD

**Issue by Lixtrain** [Cvolton/GMDprivateServer#736]
Hi. I just want to change the code of the game. When i go to the main menu i just clicked on the RobTop Logo. But i want to change that. How?

**Comment by Intelligent-Cat** [comment]
There is a way, but just like replacing the server's link (www.boomlings.com), you should actually make the character counts exactly the same so that the game does not become unplayable.

**Comment by Intelligent-Cat** [comment]
But I don't remember the exact link of that button so you gotta figure that out yourself, sorry.

**Comment by Lixtrain** [comment]
> There is a way, but just like replacing the server's link ([www.boomlings.com](http://www.boomlings.com)), you should actually make the character counts exactly the same so that the game does not become unplayable.

Thanks. But in which file?

**Comment by Intelligent-Cat** [comment]
Depending on your platform, you will need to edit different things. For Windows you will need to edit GeometryDash.exe. For Android you will need to edit a compiled Android file named libcocos2d.so, which I myself do not remember the location. Remember, some links are Base64 encoded if you want to edit 2.1+.

**Comment by Lixtrain** [comment]
> Depending on your platform, you will need to edit different things. For Windows you will need to edit GeometryDash.exe. For Android you will need to edit a compiled Android file named libcocos2d.so, which I myself do not remember the location. Remember, some links are Base64 encoded if you want to edit 2.1+.

This helped me alot. Thank you!
