### ISSUE TITLE
How do you change version of gdps?

### ISSUE THREAD

**Issue by Dragon77mathbye** [Cvolton/GMDprivateServer#738]
How do I change the version of gd?

I wanted to make a **1.9 gdps** or something

**Comment by DarkGD123** [comment]
download a gd version on google then do some editing

**Comment by Kolyah35** [comment]
Just download this https://4pda.ru/forum/dl/post/5368266/Geometry Dash 1.9.1.apk and watch this https://youtu.be/Peiuj9ELM6s.
If I helped you, close issue plz
