### ISSUE TITLE
Top 100 leaderboard not working

### ISSUE THREAD

**Issue by dexie69** [Cvolton/GMDprivateServer#74]
everything else works

**Comment by Cvolton** [comment]
can you report more details about the issue?

**Comment by dexie69** [comment]
Every other leaderboard works , the systems work , but the "Top 100" is blank,

**Comment by RobertTopala** [comment]
Cvolton changed the ranks system, make sure you had gameVersion in 21 in the database of your server for all accounts, or wait to them to appear.

**Comment by dexie69** [comment]
I waited , the gameversion is changed to 21 , still nothing. ( i waited 2 hrs)

**Comment by Cvolton** [comment]
can you give me your gdps url?

**Comment by dexie69** [comment]
privategdp.esy.es

**Comment by dexie69** [comment]
Last commit didn't fix anything
