### ISSUE TITLE
Wait wth is this!?!

### ISSUE THREAD

**Issue by RxNationGaming** [Cvolton/GMDprivateServer#741]
@Cvolton 
![Screenshot_2021-04-01-11-50-52-24_16936c4ccfb42e800253c064b436fde4](https://user-images.githubusercontent.com/81674505/113241162-ad22ca00-92e0-11eb-80f5-d3b31387fa70.png)

**Comment by RxNationGaming** [comment]
Is this a bug

**Comment by RxNationGaming** [comment]
This is not funny

**Comment by Cvolton** [comment]
It is

**Comment by RxNationGaming** [comment]
Bruh u need to fix it
@Cvolton

**Comment by DarkGD123** [comment]
Thats just normal, every 1st of april, it does raid the server
