### ISSUE TITLE
Mod Suggestion system

### ISSUE THREAD

**Issue by techsionGD** [Cvolton/GMDprivateServer#743]
after trying to get it to work, instead of sending it to the suggestion table, it just rates it.
I have the mod role permissions on 
actionRateStars = 0
actionRateDifficulty = 0
actionRequestMod = 1
actionSuggestRating = 0
please help

**Comment by Cvolton** [comment]
Are you sure you don't have an admin role set to default? A common mistake some GDPS owners do is setting everything to 1 on an owner role including isDefault, which effectively gives everyone owner

**Comment by techsionGD** [comment]
i am such a dumbass tysm it works
