### ISSUE TITLE
im an admin in my gdps, and i have a problem

### ISSUE THREAD

**Issue by MegaSa1nt** [Cvolton/GMDprivateServer#744]
all my players can load their accounts, but i cant

how to fix that?

**Comment by Cvolton** [comment]
does a file with your account id exist in data/accounts?

**Comment by MegaSa1nt** [comment]
Yes, my data in ftp updating every time i click on save button

**Comment by Cvolton** [comment]
are you using 7m.pl? If so, the limit there for save data loading is 1 MB, anything larger can get uploaded but not downloaded back

**Comment by MegaSa1nt** [comment]
Bad.

**Comment by MegaSa1nt** [comment]
Dead post
