### ISSUE TITLE
using bot with suggestion system

### ISSUE THREAD

**Issue by techsionGD** [Cvolton/GMDprivateServer#746]
it doesnt work, did i do somet wrong?
![image](https://user-images.githubusercontent.com/82057487/114191958-dd9fdf00-9944-11eb-9e37-f77df68b37ab.png)

**Comment by techsionGD** [comment]
i have dms open, and the discord.php is configured.

**Comment by Cvolton** [comment]
Discord has made some API changes and the DM functionality is currently broken as a result, so this is a bug

**Comment by techsionGD** [comment]
do webhooks work?

**Comment by Cvolton** [comment]
status update: just tested this and the DM functionality is fine, I just happened to have discord.php misconfigured on my own server

the GDPS doesn't have any webhook support built in but they should be fine provided you add them yourself

**Comment by techsionGD** [comment]
so this means its just an issue on my side?

**Comment by Cvolton** [comment]
very likely, make sure your bot token is correct and that the bot can DM your account

**Comment by techsionGD** [comment]
bot token is correct, i checked 4 times, and my dms are open (plus its in my server)

**Comment by techsionGD** [comment]
ok nvm i found out. the bot needs to be online..

**Comment by techsionGD** [comment]
How would you make it so it tells you the difficulty name instead of the number 
![image](https://user-images.githubusercontent.com/82057487/114209437-886cc900-9956-11eb-9ee8-dd70f3518d40.png)

**Comment by techsionGD** [comment]
nvm i figured it out,
anyone else who needs it here, just add this to your dm message: $gs->getDifficulty($difficulty["diff"],$difficulty["auto"],$difficulty["demon"])

**Comment by tzt345** [comment]
> How would you make it so it tells you the difficulty name instead of the number
> ![image](https://user-images.githubusercontent.com/82057487/114209437-886cc900-9956-11eb-9ee8-dd70f3518d40.png)

How!!!! PLZ Tell me!!!
