### ISSUE TITLE
How to make apk

### ISSUE THREAD

**Issue by gmdxrillex** [Cvolton/GMDprivateServer#75]
How can we make an apk to use gdps on android

**Comment by theo546** [comment]
this is a little bit hard, but anyway,
the file you need to modify(in apk) are:
lib/armeabi/libcocos2dcpp.so ; lib/armeabi-v7a/libcocos2dcpp.so and lib/x86/libcocos2dcpp.so
the url in the 2.1 in 'encoded' in base64, you can use any base64 decoder online(or on your computer)
'uncompile' the apk, put the modified file, recompile it, sign it, done.

**Comment by EndNation** [comment]
@gmdxrillex https://www.youtube.com/watch?v=lXbTTc3DZM4&t=224s
