### ISSUE TITLE
Is there or will there ever be a way to set the number of orbs a level gives?

### ISSUE THREAD

**Issue by Dragon77mathbye** [Cvolton/GMDprivateServer#752]
The title says it all--Is there or will there ever be a way to set the number of orbs a level gives without it relying on the star count? Like if I wanted to make an 11 star level give 550 orbs.

**Comment by Kolyah35** [comment]
Hmmm, try in phpmyadmin database

**Comment by Cvolton** [comment]
this would require a client-side modification

**Comment by Dragon77mathbye** [comment]
> this would require a client-side modification

How do I do that?

**Comment by Intelligent-Cat** [comment]
modding requires a lot of knowledge
