### ISSUE TITLE
Something went wrong (7m.pl)

### ISSUE THREAD

**Issue by Sonic918** [Cvolton/GMDprivateServer#753]
when I registered an account and logged into it, I got the message "something went wrong" when loading a profile. It's the same when I post a level. How to fix?

**Comment by RobloxNationGaming** [comment]
Make sure the domain name has 11 characters like this:
manster6969
That is 11 characters

**Comment by RobloxNationGaming** [comment]
Or u dint encoded it with base64

**Comment by Sonic918** [comment]
I have already solved this problem.  I just used the wrong version of the game

**Comment by RobloxNationGaming** [comment]
Ok

**Comment by cafeed28** [comment]
if you solved the problem close the issue @Sonic918
