### ISSUE TITLE
exe wont open, invalid access to memory location

### ISSUE THREAD

**Issue by clsslc** [Cvolton/GMDprivateServer#755]
hello, i tried to make gdps and I'm pretty sure everything where it was supposed to be

I used database.sql to make the SQL database and put all the gmd private server files into the ftp thingy
Im pretty sure i configured the config file correct, which i can provide if needed 

but when i attempt to open gd i get the error "(path\GDPS.exe) Invalid access to memory location." 
the URL i used to create it was stoteamgdps.7m.pl which is 17 characters long, i replaced the boomlings.com with stoteamgdps.7m.pl and in b64 i replaced http://www.boomlings.com/database with http://www.stoteamgdps.7m.pl/database (in b64), when i saved gd turned into a unknown icon and i got the error
any help
![image](https://user-images.githubusercontent.com/72023323/116577044-1eed3400-a8de-11eb-9d0a-74d307186b3b.png)

**Comment by clsslc** [comment]
if any more info or something is needed I will willingly provide

**Comment by Cvolton** [comment]
your replaced url is 4 characters too long, replace www.boomlings.com with stoteamgdps.7m.pl, without the www

**Comment by clsslc** [comment]
thank you,i appreciate
