### ISSUE TITLE
cant register

### ISSUE THREAD

**Issue by clsslc** [Cvolton/GMDprivateServer#756]
Warning: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/callsai/public_html/stoteamgdps/database/incl/lib/connection.php on line 10
Connection failed: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
Notice: Undefined variable: db in /home/callsai/public_html/stoteamgdps/database/tools/account/registerAccount.php on line 22

Fatal error: Call to a member function prepare() on null in /home/callsai/public_html/stoteamgdps/database/tools/account/registerAccount.php on line 22

is what I get when I try to sign up

**Comment by Cvolton** [comment]
$servername in config/connection.php probably doesn't resolve to a valid hostname (this should be set to 127.0.0.1 or localhost in most cases, otherwise the mysql server hostname is always documented by the hosting provider)

**Comment by clsslc** [comment]
https:// screwed with some stuff, removing it fixed it
