### ISSUE TITLE
Disclose locale licenses

### ISSUE THREAD

**Issue by RealistikDash** [Cvolton/GMDprivateServer#758]
When looking through the dashboard locale files, I have spotted notes implying the exclusive license to use them on CvoltonGDPS, stating an explicit prohibition of their use elsewhere. This is obviously confusing as the full project is blanketed as GPL v3, and finding out the locale information requiring deep digging into the source code. I would recommend specifically disclosing the note that it is prohibited to use specific translation files within your own instance of the project inside the readme.

Examples of files affected:
- Polish Translation https://github.com/Cvolton/GMDprivateServer/blob/f5feaa6fe798e2d522bf5cdda1784a3c52aef7e5/dashboard/incl/lang/localePL.php#L94-L100
- Russian Translation https://github.com/Cvolton/GMDprivateServer/blob/f5feaa6fe798e2d522bf5cdda1784a3c52aef7e5/dashboard/incl/lang/localeRU.php#L3-L16

The messages are gems lol.

**Comment by ElectroFlameOfficial** [comment]
these are the funniest aggressive messages i've ever seen that don't even look aggressive lmfao

**Comment by ElectroFlameOfficial** [comment]
> ```i can delet your site kthxbye```
> GitHub equivalent of the "I got your IP"

LMAO

**Comment by Jecket22** [comment]
oh my god this throws me back to the Cvolton GDPS community back in 2016 lmao
