### ISSUE TITLE
Account unlink when I restart the GDPS

### ISSUE THREAD

**Issue by tzt345** [Cvolton/GMDprivateServer#760]
When I restart my GDPS it got acc unlink for no reason fix it plz

**Comment by Catover203** [comment]
It APKEditor prolem, not from source code (my bad EL)

**Comment by notqoid** [comment]
https://youtu.be/Ttg-iPxLkQ4 = how to make an app for your gdps, then change the package name in libcocos file. make sure that the package name you want is exactly 24 characters long like com.robtopx.geometryjump
