### ISSUE TITLE
"account has been disabled"

### ISSUE THREAD

**Issue by mmitochondira** [Cvolton/GMDprivateServer#764]
my account got disabled on my gdps... help?

**Comment by Catover203** [comment]
use your phpMyAdmin for enable

**Comment by mmitochondira** [comment]
where do i find the

**Comment by mmitochondira** [comment]
> use your phpMyAdmin for enable

where do i find the option to enable?

**Comment by mmitochondira** [comment]
oh, and it is happening to everyone at my house. I know why, it's because I am using MHV6 but how do I "unban" myself

"YOUR ACCOUNT HAS BEEN DISABLED CONTACT ROBTOP FOR SUPPORT"

**Comment by Catover203** [comment]
1.Go to your database (Like PHPMyAdmin, SQLBuddy,...) then click to database
![IMG_1621641178603_1621641379265](https://user-images.githubusercontent.com/63941519/119208124-f4e8f500-baca-11eb-84b5-30cb843d1b56.jpg)

2.They will show a list of database. Click to your GD Database
![IMG_1621641312719_1621641368575](https://user-images.githubusercontent.com/63941519/119208144-0205e400-bacb-11eb-87bc-bbec817ebb53.jpg)

3.Find row name accounts and click this row
![IMG_1621641299366_1621641372844](https://user-images.githubusercontent.com/63941519/119208148-029e7a80-bacb-11eb-9b46-19b3dcaf4630.jpg)

4.Find your account and click to edit on your account row
![IMG_1621641267934_1621641376213](https://user-images.githubusercontent.com/63941519/119208149-03cfa780-bacb-11eb-8461-34f12501124e.jpg)

5.Set isBanned to 0
![IMG_1621641355702_1621641366028](https://user-images.githubusercontent.com/63941519/119208151-04683e00-bacb-11eb-977b-9763b460adbc.jpg)

**Comment by Cvolton** [comment]
The GDPS has a security mechanism where it disables all login access for an hour after 7 failed attempts from the same IP address. Every failed attempt is stored in the actions table. Since the game doesn't have a separate message for this, it shows the "account has been disabled" one. The isBanned variable mentioned above is related to leaderboard bans, not disabling accounts.

**Comment by Catover203** [comment]
> The GDPS has a security mechanism where it disables all login access for an hour after 7 failed attempts from the same IP address. Every failed attempt is stored in the actions table. Since the game doesn't have a separate message for this, it shows the "account has been disabled" one. The isBanned variable mentioned above is related to leaderboard bans, not disabling accounts.

That was anti DDOS Attack right

**Comment by Cvolton** [comment]
> That was anti DDOS Attack right
It's to prevent bots from bruteforcing the passwords

**Comment by mmitochondira** [comment]
thank you cvolten, I just tried coming back on after a while and it worked :)
