### ISSUE TITLE
load bug

### ISSUE THREAD

**Issue by Barang2** [Cvolton/GMDprivateServer#765]
i maked 2.0 gdps, save is succesful but load is something wrong. + custom level download failed bug

**Comment by Cvolton** [comment]
7m.pl doesn't support downloading of levels and saves that are over 1 MB

**Comment by Barang2** [comment]
nah. i not used 7m.pl

**Comment by Barang2** [comment]
i used freewha.com

**Comment by Catover203** [comment]
Did you chmod data directory to 0777?

**Comment by Barang2** [comment]
> Did you chmod data directory to 0777?

you mean PHPmyadmin?
no

**Comment by Catover203** [comment]
> > Did you chmod data directory to 0777?
> 
> you mean PHPmyadmin?
> no

The directory (folder), connect to FTP Server and CHMOD them, and it not on PHPMyAdmin.

(my bad English)

**Comment by Barang2** [comment]
> > > Did you chmod data directory to 0777?
> > 
> > 
> > you mean PHPmyadmin?
> > no
> 
> The directory (folder), connect to FTP Server and CHMOD them, and it not on PHPMyAdmin.
> 
> (my bad English)

Resolved. Thank you.
