### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by ChA0S-f4me** [Cvolton/GMDprivateServer#770]
When I try to register in PS, it throws this error. `connection.php` and DB setuped correctly.

**Comment by tzt345** [comment]
@ChA0S-f4me Did you put it correctly? Make sure it's correctly connected on your mysql database & make sure your Domain name is 11 characters long :)

**Comment by tzt345** [comment]
> @ChA0S-f4me Did you put it correctly? Make sure it's correctly connected on your mysql database & make sure your Domain name is 11 characters long :)

Sorry for my bad English

**Comment by ChA0S-f4me** [comment]
@tzt345 It connected correctly and domain name has 11 characters

_What is your native language?)_

**Comment by tzt345** [comment]
> @tzt345 It connected correctly and domain name has 11 characters
> 
> _What is your native language?)_

Let me see your Domain name

**Comment by ChA0S-f4me** [comment]
@tzt345 I test it on local machine (open server).
http://cha0s-gdps.com

**Comment by tzt345** [comment]
> @tzt345 I test it on local machine (open server).
> http://cha0s-gdps.com

Your site doesn't work

**Comment by ChA0S-f4me** [comment]
> 
> 
> > @tzt345 I test it on local machine (open server).
> > http://cha0s-gdps.com
> 
> Your site doesn't work

**I test it on local machine (open server)**

**Comment by EMREOYUN** [comment]
Visit one of your php files in /tools directory and check php throws any errors on the website.

**Comment by Arvi65** [comment]
Hi, I'm having the same problem as well and I've checked the registerAccount.php in the tools directory. It's given me this error:

Parse error: syntax error, unexpected ')', expecting ']' in /home/umpahhGDPS/public_html/umpahhhgdps/database/tools/account/registerAccount.php on line 45

Do you also happen to know what I should enter in the port section in the connection.php in /config?

Thanks.

**Comment by EMREOYUN** [comment]
> Hi, I'm having the same problem as well and I've checked the registerAccount.php in the tools directory. It's given me this error:
> 
> Parse error: syntax error, unexpected ')', expecting ']' in /home/umpahhGDPS/public_html/umpahhhgdps/database/tools/account/registerAccount.php on line 45
> 
> Do you also happen to know what I should enter in the port section in the connection.php in /config?
> 
> Thanks.

@Arvi65 How did you manage to get this error? Can you send me the 45th line of your `registerAccount.php` at the path the error was occurred?

**Comment by EMREOYUN** [comment]
@Arvi65 Can you replace the line with `$query2->execute([':userName' => $username, ':password' => $hashpass, ':email' => $email,':time' => time(), ':isActive' => $preactivateAccounts ? 1 : 0, ':gjp2' => GeneratePass::GJP2hash($password), PASSWORD_DEFAULT]);` and try again?

**Comment by Arvi65** [comment]
I'm now able to try to register, but when I do, another error pops up:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens' in /home/umpahhGDPS/public_html/umpahhhgdps/database/tools/account/registerAccount.php:45 Stack trace: #0 /home/umpahhGDPS/public_html/umpahhhgdps/database/tools/account/registerAccount.php(45): PDOStatement->execute(Array) #1 {main} thrown in /home/umpahhGDPS/public_html/umpahhhgdps/database/tools/account/registerAccount.php on line 45

And In GD, it still gives "Something went wrong..."

**Comment by EMREOYUN** [comment]
@Arvi65 Try with this line `$query2->execute([':userName' => $username, ':password' => $hashpass, ':email' => $email,':time' => time(), ':isActive' => $preactivateAccounts ? 1 : 0, ':gjp2' => GeneratePass::GJP2hash($password)]);`

**Comment by Arvi65** [comment]
Everything is working now! Thank you so much!

**Comment by EMREOYUN** [comment]
Beautiful

**Comment by EMREOYUN** [comment]
@Cvolton It's kinda forgotten but this issue has been resolved with PR #870. You can proceed to close this issue.
