### ISSUE TITLE
commands don't set rateDate

### ISSUE THREAD

**Issue by Cvolton** [Cvolton/GMDprivateServer#771]
see title

**Comment by EMREOYUN** [comment]
Any further explanations? I checked commands.php and found nothing wrong.

**Comment by Cvolton** [comment]
Dupe of #693

**Comment by TheTechRobo** [comment]
wait...but you opened it??

**Comment by EMREOYUN** [comment]
> wait...but you opened it??

I did not, i created a pull request regarding this issue.

**Comment by TheTechRobo** [comment]
I wasn't talking to you. Cvolton opened the issue and...?

![image](https://user-images.githubusercontent.com/52163910/122648548-c83ef200-d0f7-11eb-8639-214ae54c68d7.png)

**Comment by Cvolton** [comment]
> wait...but you opened it??

and i opened the other one as well and forgot about it afterwards

**Comment by EMREOYUN** [comment]
> I wasn't talking to you. Cvolton opened the issue and...?

Oh i thought you said to me. My bad.
