### ISSUE TITLE
Level download failed, please try again later.

### ISSUE THREAD

**Issue by APTKOP** [Cvolton/GMDprivateServer#779]
hello, i have problem. When i choose level, it says this: 
![image](https://user-images.githubusercontent.com/52624723/124642710-d3847280-de98-11eb-8498-8983f6097d0c.png)
What i can do?

**Comment by TheTechRobo** [comment]
It may have been removed from the server while you were downloading it.

**Comment by APTKOP** [comment]
> It may have been removed from the server while you were downloading it. That has happened to me in the main game once or twice.
> 
> Does this happen with EVERY level?

Yes but i fixed it by editing php code of level uploading

**Comment by Jecket22** [comment]
Consider closing this then

**Comment by Cvolton** [comment]
issue seems to have been resolved, closing
