### ISSUE TITLE
unable to upload levels, unable to view levels, etc 

### ISSUE THREAD

**Issue by notqoid** [Cvolton/GMDprivateServer#784]
![Screenshot_20210728_181840](https://user-images.githubusercontent.com/87503354/127439378-585429b1-7193-4f24-b26a-4b6515542e87.jpg)

**Comment by notqoid** [comment]
i can create and login into an account however

**Comment by tzt345** [comment]
@Cvolton

**Comment by Cvolton** [comment]
> @Cvolton 

I have email notifications enabled for all issues.

Regarding the issue itself, the upload page doesn't do form validation on entry so it's expected that it'll show this in a browser.

Make sure the server has full permissions to the data directory and its subdirectories (chmod 777 possibly)

**Comment by notqoid** [comment]
@Cvolton i did chmod 777 to data directory. you can upload levels, but you can't see the levels

**Comment by notqoid** [comment]
issue resolved, i just have to edit getGJlevels.php in /incl/levels/getGJlevels.php by adding `$ordergauntlet = false;` on top of //header. gonna close this issue now
