### ISSUE TITLE
GDPS doesn't work with different database folder name

### ISSUE THREAD

**Issue by redoverflow** [Cvolton/GMDprivateServer#785]
I want to make the database folder name shorter (to dbse) so I can do a bigger website name for the GDPS, but it doesn't work, in GD I can't post levels nor register an account. The website length is four characters longer, so it should be right. What do I do?

**Comment by redoverflow** [comment]
nevermind, issue fixed

**Comment by RXNationGMG** [comment]
Got that same issue
