### ISSUE TITLE
Load doesn't work

### ISSUE THREAD

**Issue by TrueGPX** [Cvolton/GMDprivateServer#79]

**Comment by Cvolton** [comment]
what host are you using

**Comment by TrueGPX** [comment]
Hostinger

**Comment by Cvolton** [comment]
does uploading levels work?

**Comment by TrueGPX** [comment]
Yes

**Comment by Cvolton** [comment]
try disabling the advanced cloud save security in /config/security.php and save/load again

**Comment by TrueGPX** [comment]
Doesn´t works

**Comment by Cvolton** [comment]
do files get created in /data/accounts?

**Comment by TrueGPX** [comment]
Yes

**Comment by Cvolton** [comment]
remove these 4 lines from /accounts/syncGJAccount.php

`include_once "../incl/lib/defuse-crypto.phar";
use Defuse\Crypto\KeyProtectedByPassword;
use Defuse\Crypto\Crypto;
use Defuse\Crypto\Key;`

**Comment by TrueGPX** [comment]
Still don´t working

**Comment by Cvolton** [comment]
did you save again after disabling the advanced security?

**Comment by TrueGPX** [comment]
Yes

**Comment by Cvolton** [comment]
can you check the content of your save data in /data/accounts if it's a "H4sIAAAAA" like thing

**Comment by TrueGPX** [comment]
That file doesn´t exists

**Comment by Cvolton** [comment]
there should be a file named as your accountid, check the content of that one

**Comment by TrueGPX** [comment]
The content of the file is:
H4sIAAAAAAAAA91daXPiuBb9K9R8z4y1eKvqzlSAsCSQjQAJX1zGGHAwmLYNCfz6J--2pBhPT5Ke19PTDVwdy_LRuVdXshHf_n5b27W96XqWs_n-B_hT-OPv829b2_L8orW2eCGfv_8ByfvzbzPL8M-_rc73ur0zr01za7rf_loRe2Bc7DVBEEBo8M7Jq5dZIc8KENeqcK0qzwq5NUCJa5V5ViRwrUkNQsHKbRnmtgFjrpXbMsyvN7liKW8Vk_bCAr8Kr72CzLUirhVTVkPQAM2NpUn0xVoa_5oAt8cllTrL1HJnGuDWwJyKtIgWATHR3BlAA7QGLY2Rz0x3fY3bRkzrhNSI2BoVGuY6U8dnzx0cTbcxPDnTJNJKxnu8pbXVEN3OkDVIK8zSZNbE6JBQxvgHsYmsie9y_M5CXCcQGTIErXj4X2Hk2G1sx1iNeEFlRyoCMucYY-f5zvp2-mIafpOEpeiQ2l8hP4uRY-_WZmhzg8PckMz5G9e-tfWD6Q6b3WZ8ngEQIYCCKImAOCcESIYqRIoiKwL5g5GMQRjovOzoGz2u1jvvWxuzr7urQvnQM924fuscwiBoWFlpy00Ot85ltVA0IAqISwId5Erqum0nFQrFEqKPuCTorlxJkygvOQYUSh4C-SYHFU802FqzuE-s82JRw7GdpCSQOV0EkxqLDRz4rqmvkrJiC03dX17O56bhU-WuuXVc35xdGEvL3Jtrc-N7udHHdNam7x7-1I3ln7rvm-utn7mTkAa7PMzbTdeWX44xSEt9x02j5gnYiTMmMFgOm1n62tnMvLQ6JCigFJhWCBEsBSbXIQGpFIezM5fiksABg3cluNTvRVyKk7MLKcWlMVUov94kiKlyGSwd6mQuLNFTwjLkXuvLbr09JYAQk3YWlwpX982mNZ-XV2RbK_M0Ij0Vl8wohp7UbIRKr70MlKiLe2ExJlEWv99M0h-nWhSBkgaJJZikPYgvphCDSzs1woilFx9hUoWXYBJ1830vhCTCLmmNWtapIQQwaSILAachTILESDkhmOs2cYfTuUUxBvu6m8U5yBVOhMlCHA-zIwOs4Vgb75R4MmDqGydwaejndkmGw6UCyHBiGWcZTCrTSgaTy_SSwZQyz8xgpdJKYam8TsBANRgsU2IGQ9VgpfElg4nVYFI1GDO55MOYmR4fxmTeXBhk5q58GDMl58NKnT2DMZk-H8bMf3njKSqTeBhfSjvTJmmgDcH0xPhViAq4BHNiiCsGA_6IWiEQFIMAN7uqEAAqOH_R8UsgallsKDp8CaTU2YuOXgJBpyGlmqjg3BUcu-jUJRDlNEQ9CYGlo3UFJ67gwBWct4LjRpAKAzoqk3cEwWXyjiBimeoiiHQaIpdJKoIopyGl3RhCypOuMFgBNQlWKvdUEUg-EdGis5UqIoKUKmLuWmZ-jlk2YynvcZNMa09PtiMULO31GDMt646IIyHBSNyeT0aYUjXHpys6RbS81O71tfiKws-5t6vG5XW8NIHjpYkVoNYqVvEaW94Sn2Xgm67p1Pr6bGN6XtyslczAmSoBU6WEk6WXxBIvD1vhhCcGpVFM1VRFI_9iIfiX-h_IcvAio9SUYwNWu3rIXD2kr76uG6va7ab26JI371688iVsiPhdNiKiIgBNBqpGBmLIQDQZd46tuwvT8nyaCUgzAX-VLvJ80EzgakxghglMM9F0D7Xb3Wka0KfSEImfS0NUxPcOsRoNIkODyHqHZ9Yu5iRC1IK3NB2IpgP_KjoiPfDpkKrRITF0SDQdDX3j13qmX2s7J6kQfxUVeX3QVMjVqJAZKmSaiisyCgdr8EUWMM2C9KkslISJqIgfJpRqLCgMCwrNwqO1NsnIaSytDeMcDBfyp3IBEDwRLPhkqNXIUBkyVMY7DoZtMgkEQ4PyxZJI35dJIk6VT-dTQmphHB2lrQepLZ5sWWFWGJlkwJiy5EygSX0j6dmW5lSkOVW_WlppJhKX8cMNqJqlctJUJk9t2DuSQ7vz3YbJ0xg-cjx-BiEQyTQhOQJKVFYxbwVs4gqYzPVxaTokS3Hmtcu96R58EoMWp4n53Aw2JiaXp2bExEqJXxhqKmaxgE1jWae5tE3Dd521vqldzPbmxt-5bGBiufncnJYjmlQl0Zv3qKmY1oIsnkQZoB89fbCS2TRXYo_J3GzqcWKOxND1ubkvR0oZP-_wFQRhuaiKmMKKKTFgc2LW8WJ1zQ4bfW29nZbV5ybFAU-EjsK4H1EX8UT8L55KM7qqmBgDNjNmSemYb_rC2dRajmswqRDLyedmxwjIwXWnoYeIKKcVwk7w6T1WKubIIE3nADP7yTIBmHKXZgLhchSVCuRsJWGtbuueX7tzHcP0PE60Z1It8Lnpd6yzlGaitoxmUZIo3gssV8zBQZYt_ouYxhsqa_B0hPvcjD1QKXHbdNUnFGVKF4Y4DHNIfj_GwUKMq5jJA5URrswIF2I2hVURo1u1ymjcjpY4LUO3a01nbW2CJ45Oa_dz5wkBvQHZadwM9JqxL4tSGigSiefXHytOF6DwE_JlVmGapj4LHkg0Z6cl-7kzATqwhhImTEaGgMLAEkfWgLv04apMtCgvWlhxhgABI1rIiFZBjGYrB1tmQGuRGGG6M91bnhzN4AfPNhKNCVXJCZH0FdEX9H-5zp88qV-FA86k6TfhoOLcKEL-phxUnARFyN-Ug4qzmAj5m3JQcdISIX9TDipOUSLkb8pBxQlEhPxNOaiY8UfI35ODqgv3EfL34yD3dEguS1BEXJGXCEml1mn70tQaKdmssWpu_c6MhxOWmSljyzXNWvjIdzp9iEsm0FgY65YwGdRts_NwmIyB3W0_2NOxuut27OWs3do8P10tDTRcTNojf4r6i-nYPs7a9sv0UD_MxlfkbzepQ9Db9rHbuXH0p_vvybmSh4uoL06t0slx9nWplZR0qpz2vMpcFkhAYmZKGEPZkjyAjKxwgUOYfX0pS3YR3WmpOtH76gTpEkJqUgQapKTOk1bNuAJmXKFM5oL2hX_SbqN0Ft8EFlHF8BkhKRcBrIv89OSTM_d0Pb8WPldG6_929RU6BRydZmMIq9OcMNm58MfLkI2tUjHYsDqVi4D_Y9niiqsCEZKSLXuzWoGMbjF7rzozUWG9LIinKyi1afYoVSLkERx5z1D1gyBMAvN-uh4upvB5MWsvSUBfLo31g22g-8VsPToY0N5PN_2w_GFt7yZwdJi0W0e9gRfDdWs3aat-t_1mE6zXs-qTaRj8FRLkR8tp-03sdmbL6eZ-8Tyov-jtljdtj0gdQ63bejiYg_rVdHOzDM7_OFZXk_vvH-Vg7PrQPx0ahEoul0X-fzIW4M92wpMuh5NLgCqWREmulCmRBEkSZA2ogoaV0GMggBqAUvhelKEGCUTF0Ueo4XBdNyjF5F8okcMVDWNZC_YTEDUFkRdUwS8RF3TKWcWKy1cRknJWhfFMxHomes8zSxIuZsAhM4TlsbZ1XrNHur42CcoWbUqVzmbg_8UcB8kSV0JQln_JgFH1ebcQeWqKtLf2es20a_7O8vxMLml-snn-6PAp_aymJEZBKnt7BDMCgv9SQFTc42gFM_cw0r5Ti11XcbUrQlLhI0MlxMF0-E_DB2RXCpno8KrvzZqx1G3bJCM6M5CTAVofT7aT8T0ZoDGZbamWPn6zPz-QYF6nZ7flf3UgYQfIfx9aMD-CYPFLAgsujm0Vb0tEyKKkZqZt-mbNN7OvGny8TjJRVMujvmLq8l-feKSRp_LkGLOTY8Q-PCCyoUescJOip9deTb1GNGHRcedx3Dp225PlM7S9bqcFgonEbFB3Jk9X_vNYXHabW0hrq3t9-YDE4euQIy6JERcQxWrykv4z8jqZlHOycDEZZxWc85RyWSoKox8Iwkj0eSlOGncq3gqMkO9KM_esC2_phpErZ_2YeQS-Yy2WtZ41ZwfJ9nJrHOrBX0Fvk5luWw1mscdZo-5Nnib2tFHfBrPeGZmFBp8Nq76aQtHuNepkZnq_0MdCbjZbP0zRaNVtq-tu2xbIjHc0vHyojy6HUrdFBuL2aE_Kdt2WPSRlQzLj3emHuhjOitfqodt5cIizrCfjljB7urK7A3J8syt1L6_ABPUJxsZkMF_SPoIUpcQbSjMx-A8dBNF9WuIynHRN-FCXqT6PBUDBKsoiSepaoioiDKu4VvxokohzTy9KUv6RTjV7Oim2KMxAnWWR2f2B_J2S6ktIbFrJ3gjIrixbLyr56qWMGQ18SKKZfLW2g73uRfKfNB4_PnWN7v2h1Ts8PA3ur-s_Wvfj_epKuahPJmcL52x-twRG40Z6241u-tLNnbkXVuutKM5R_9pugvXRGwyexvrD4839k7zy7s72b43b8UPjrf56nEyuJOH5bdJH4H667HWPwub-eBgPrketo-m1HrvbN3c_GA23x3ZLuWr3O-2n11soN-7vp-aTsqqD1ZN0uXctZ3SURXXx8qy2pX1vM9y_dLCxExrN6Ztk3D7p1-PWvHF38XT_dPmwMNutobDazlC_3rh-vHTMoSiN1ru75nPfvnQaZmPtXV3cImN_Nu8L_pP-dLg64L7kPh6u70eO7TyP9MvHVU8Zbu6EUWvvtC-WCFxI3cP8rmEMOz-a7nzVMe9WLaf7Ij3LP9y72XDygpSdd3v28tja98Z1R9je3faRTEISfvSe2v2Xuf728gOplxPlpnM_fBRnZ0tovbUaF_7VodkXodHzR4-Dm_n8-GPaqZ95h8vd3QAvjflz79h9sBUdGb26i_od76Ltv_Qna_PZdY-tC6w25SZ020dpJMtvLuq9unJPHB0BHs4goVSV2uPOdHC4Ot5ZN97xMG8dx_r1UnzuCuLEmKPdDnl-TzX12xUQ_cuFfhQf1sgUJbPXm-F203yAF2JX3hwe4Z68aq8Pstaf9I3-ZINl56qlCrAprcilOgtt9vTmvE6G6BE6E_ltoJpbrXHrKJ2-2zEu59rdTm5N9LnaUPvYbiqd_aKjIPe6-9i_Jkr8gmV77oSoWnLyayZE_6_Tn1xUpa8gNMbT9mjECG_OqrQl_12gYGc0DWjBvVjyIsSXC-IGZKWgtFRiSnPNRMz5cw8TpffCsmrTO8gFE2BMInznjALLQW4dKthPLqk_ITqwAY4NcmyIY8Mcm8ixSRwbvTNtz9zQzSMmunXERDeOmOi2ERPdtPDWtja3bD_exzIpivkbaOGOxvSAHezQl25_mBIPk327khMn0x5MfaY3zUiISDc5o1mgN5OhN-Nitt0CNEPMDjvZfjpKuuNIuoEOVlBydYDuOUB3W7obTloNvekws20VpNub7mKTMJDtWSPjBLTbWD92JpnfaLT8sxKuFww0w1lvg4WOWdaThsZxrUgPnIJg2xSePaiF8dkYzNg3GrNbTwhlrBt6a9sYyN3wllxe4YkTpDL8hEZ6z5fQiPgV4kLMGMS7AGefc8uhqZiFdHsXlTWlghRTU6r6DCWzJszWhTBTF2BRkHMga0o9K1cXZFuReUvOlmohOzbbQTnXEJnTEoG2pdTLxb7McGz0xzizCRxgOiagHDClXcxwGcnFtkBE9btCfVa5jYVsU4HAayrbUshpKNtOtdjM_IwKAoaINPxkgU5mQUmr4m2DsspzWk-JhxRGZjE0hKYOYs4xInVQbn4INf5kMVkLoPOf9J5u_DkXIzTLu3Cj8S6ZTGsCt3KVqlwuVEYql9PNndPJJBRVmFufXr3TbrpqhapaEqiK45tiSa38G7p0rZCqFZxsLX8xna5X4tabpKTxF8F-ssfAZ_YYUkSKAkVWFFHAAviATgN0p6kYAQxV6Wf6TvykvkP_qN6sP6GGK_UnpvrzUz0QyRh9QMchAZym94O6TUGiBGHyzcaP6Dva736unz7V74AKoXqS4Z_rPOXr-k4FUAp-BEH6Mr_LkhFIjaCAMdBpKqDzWKBSBihQjQtsIA_qN4Mpc_4rgMn9Gc4lS9QlF27lJDlOw7Hrwc8cHGtntSD_o1PdtLyQthK9yrKadFB0pe65-mfwEyThr1VQXw-OtyADgigifufTjU2xhda-6r6x_Hv__frVHixedz3zQLf3wdxtbUefUc1VqaaeCVRDFXodJ6aafaCufXWhZb8VtHH8mr80a7rh73S7ttU979Vxk9NH2CSjotb2osKkhela3nU918VRt0emgsK8pfM6cDaLoD7T9fJRISi6c52Fa3peXS8EDMO2gm8Mt3VXX5icgsuZ5TsuXZk5e9B9c0AmfU1Lt51FvnzqOP5u6yUsJZFmam109zCKfqQpUXXCIGmYY-_8rOQsiZzhLzf9Ff7C0_n_ABQOJCP-aQAA;H4sIAAAAAAAAC-WY23KiWBSGXyXV9yTA5mRVkinOIAdFRIUbirMcBAVU4OlH02pPzPSkuy-6Zmq0qPL_N8Lei7U-Fjz_0W2Kh0NUN2lVvnxBHuEvf7w-b4u0ad-7D0l20i9f0NPv1-cwDdrX5_xVVTUXRp6f8pN11m7a0HX9ptuHp7OTu_C34ZzllTeVvmLPT-mbhVAXB7k66JvRvFpl6W2i8OF0gOZtALsMSFgj05cPSyyN_gg4je44AciMFZO8YUGObOjHROkNbLFXp6FXJQsS87WC4KU-3JvRURyDY5_3h8LmkqTaCRxJz5zG0-XJTp5vtNLPaAvfNIqruPahr0XxCDem02Vx7akd5toqvAnN2tCRbNZWeblKnK6p6K2uTDbhZAPtYp2WhnqQBlMrUs2Zye1SYK0MjWk-nyxWEmecl_Dycl0bflmblpaR5tX51UfAu2iiyCVa6C1-xH38KPjijK4Ohl8cHIFxHNz-i1_3BOBqyV9PUL9CCEAfR_Bp3_rrAHoZOE_hYoGLBT-SN4_4drnhy5quFxC50-idBncau9P4nSbuNHmnqTs9up_PhwnezxB5P8Wn8Ot2Tmvkk7S-GNQp3t9PdUB8uJyj6z4wfPVI5KN3nVgYFVEbPbRR035WJkcDcDLdCacyKeKumVfbY28cfYxGTYHTITpCO2srkBCNabGwj9fzgE11TWHnVZPkKsMLSRvb7MIqjJaZySPRMbV9wGYWvp5jK1KAFrFBonO60GIf2iJF48oZlDdmNlZiplRsyJvMA8yTw9xLx3IZb6KmVBgCZJS0anzRULpGiGZ7e3uqnNmpPDoqbhYCNUeZ1E-EFRbQCU1_Vi7gbxc_TA1tmCB6baAwp4F28I56awwaLfXc1NLUgKfYTksYg9UmBpPKR_pdbd7VIIK9l_ivV-g_VSL2IVuIW4K7v_F7jcKNDPAHJJzT-A4JyP8OCOiPAgGDfwAICIr8KhKEOooewmhTlbequIw4aJAEGwF2TKaIpFnvLJFCFmeFvxztZalYh6JQ2qvxOgBW4oiL1gda4i-LIRSLzO-ZPlyOT5t8PQbsicUgS3rlrYyXz-hjHonzTZpXUSPPOnQuC15QGZFNA1aQaiz3yyixSmtQXalUghqiWCexZtu14YUCz69tudoL_JDMd81W4XUxs8KNPB4SyzsEFiRAXcnWxJwlg3ydke52U7mUI211Cg68crZCsGGFrnMAsankiDYPLyeDNNX79b7FIEnd66UsyIO4aMzpwGIwHfILugwWPNEi6VKvlFqEaAH4XaPlv06hHsysmcrLdMLBTFsYPJOPDiRYJuqoz_qtXDhHYhe5KaS5hJ_WfeGwO3suENO6KkOPa6YeVsZyAGbrRUtXu9pWC0VSLKBErMPri0UalsAYlHCl7xc7fwzVIsks5zs6QJHYxu0xMSqnIbuWwCyIuCFmgtVhtRKxw0gfymUYkpOwdCCoaQiiCxaoPSpLkdj2DvAhgsI7lGR1zNg58QFV9hLUrk0OdyAVL3GNjD3HLSGKlNxQOgyHA4-67pLwRShASAb13aHZU7Fd7Kq2pZgzWn-NrODKyFvG_wxrAfUfgi1xWwf8sTNDYQzBHj92ZiPskQLnNX2Xxdc-kLgd9P9CZ_CjdAaj79P5p0mc1qfnqCI6RMU9iif558gc7IrVZiy_IpLVPqvnWjdFx0ovCz3EMj0lHClZafY0R2oTfzuFSYXdkrvlyNzE-CY_wERmjFEznWqbZbZnaHmZqmrGjM4I3TGyOojmZCG7sqBXsefRh9EKV_cKlGPagTU65FCQVVn5Ds5DsLvmMp8cdBfmsqgrTUVeSPuEK08dIN6LHk95ShhsW8dEOJhzNqvgYK8NO4GSgmnSbomNZT5up7mJT9WQcgWLlns1sl1A-o46C_25CtVH1ISWAAvxNu6ClranR3lToGQbJD_2nPS9xs9qBrbTa1qktSJoDVs6-7-hsbtVGIHdUwu8P-s_0Qj799PoJ7vBD9H4dzAJ_E4mnSOKvMsBAn0v_5Ih3yD29rIFfZ8sT1_fxDy9vbF5_RPNXUmLzhEAAA==

**Comment by TrueGPX** [comment]
If you want i can upload that file

**Comment by Cvolton** [comment]
whats your gdps url

**Comment by TrueGPX** [comment]
http://trugpxgdps.esy.es/

**Comment by TrueGPX** [comment]
![screenshot capture - 2017-04-12 - 17-19-33](https://cloud.githubusercontent.com/assets/27302194/24965408/3c8f5230-1fa4-11e7-8a13-028d22da6c65.png)
Is this normal?

**Comment by Cvolton** [comment]
it is normal in that file, the file responsible for load is syncgjaccount, not backupgjaccount, backupgjaccounts works properly, considering your save data got saved right

**Comment by Pizzaroot** [comment]
Cvolton is cute.
Lovin' it

**Comment by Cvolton** [comment]
bug fixed in the latest commit

**Comment by TrueGPX** [comment]
Thanks! :D
