### ISSUE TITLE
database.sql issue

### ISSUE THREAD

**Issue by firestorm1434** [Cvolton/GMDprivateServer#794]
When im trying to upload database.sql, im keeping seeing Error
SQL query:

--
-- Database: `public_cvoltongdps`
--

-- --------------------------------------------------------

--
-- Table structure for table `acccomments`
--

CREATE TABLE `acccomments` (
  `userID` int(11) NOT NULL,
  `userName` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `comment` longtext COLLATE utf8_unicode_ci NOT NULL,
  `secret` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'unused',
  `commentID` int(11) NOT NULL,
  `timestamp` int(11) NOT NULL,
  `likes` int(11) NOT NULL DEFAULT 0,
  `isSpam` int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
MySQL said: Documentation

#1046 - No database selected
how do i fix this?

**Comment by Cvolton** [comment]
select a database
theres a list of databases on the left in phpmyadmin and you need to select one from that
do that
click the database
click it now

**Comment by firestorm1434** [comment]
ty very much! it worked.
