### ISSUE TITLE
No connection.php file

### ISSUE THREAD

**Issue by JWMediaOfficial** [Cvolton/GMDprivateServer#795]
I'm following the tutorial on youtube but I can't type the connection.php code because my display is ass. :P

**Comment by RXNationGMG** [comment]
It's on **config/connection.php** ok

**Comment by orangejacob** [comment]
`<?php
$servername = "localhost";
$username = "username";
$password = "pass";
$dbname = "username";

try {
	$db = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
	$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch(PDOException $e)
{
	echo "Connection failed: " . $e->getMessage();
}
?>`

**Comment by Cvolton** [comment]
feel free to reopen/request reopening with additional information
