### ISSUE TITLE
gdps setup error

### ISSUE THREAD

**Issue by FanyaOff** [Cvolton/GMDprivateServer#797]
![image](https://user-images.githubusercontent.com/73064979/143265140-9e6767ed-89e1-43e1-8489-4097da3d09a2.png)
please help me, translate:
Cannot launch this app on your pc when i editing links in HxD

**Comment by FanyaOff** [comment]
i replaced all http://www.boomlings.com to http://api.viaps.ga

**Comment by Optimal7** [comment]
The URL you are replacing it must be the same length as "www.boomlings.com/database", otherwise the executable will break.
So if "http://api.viaps.ga" is your URL and i am assuming you have "/database" as the directory. So you can extend the database dir to be the same length as the main url.

**Comment by FanyaOff** [comment]
![image](https://user-images.githubusercontent.com/73064979/143578069-e8a3fa30-3054-4c06-9bc5-313246f88b8a.png)
i fixed, but i have this error(

**Comment by FanyaOff** [comment]
![image](https://user-images.githubusercontent.com/73064979/143578146-816c269f-196e-472a-8820-a879b4ce4283.png)
connection with database is work

**Comment by FanyaOff** [comment]
> The URL you are replacing it must be the same length as "www.boomlings.com/database", otherwise the executable will break. So if "http://api.viaps.ga" is your URL and i am assuming you have "/database" as the directory. So you can extend the database dir to be the same length as the main url.

Help me pls

**Comment by erstec** [comment]
@FanyaOff Looks like you haven't edited base64-encoded URL's

**Comment by FanyaOff** [comment]
> @FanyaOff Looks like you haven't edited base64-encoded URL's

Where i can change this?

**Comment by erstec** [comment]
> > @FanyaOff Looks like you haven't edited base64-encoded URL's
> 
> Where i can change this?

In the same .exe

Write me on Discord ErNis#3947 and I will help you
