### ISSUE TITLE
Loading levels failing for meh

### ISSUE THREAD

**Issue by TheOpGaming** [Cvolton/GMDprivateServer#80]
**downloading levels doesnt seem to be working for me, everything is blank...**

**Comment by TheOpGaming** [comment]
server page is www.officialjonesy.com/gdp

**Comment by Cvolton** [comment]
chmod 777 the /data folder

**Comment by TheOpGaming** [comment]
?

**Comment by Cvolton** [comment]
either through SSH or in your FTP client (depends on what you have access to) change the file permissions to enable everything for the "data" folder

**Comment by TheOpGaming** [comment]
Ok i tried that but still no luck, I tried remaking everything too and now nothing is going into the db. I checked all the details inside connection.php and they seem to be correct...

**Comment by TheOpGaming** [comment]
ok i got the db to work, but some stuff like downloading levels is failing
