### ISSUE TITLE
what does "Connection failed: SQLSTATE[HY000] [2006] MySQL server has gone away" mean?

### ISSUE THREAD

**Issue by fidgetplayz48** [Cvolton/GMDprivateServer#805]
so after some troubleshooting, i found a thread that talked about the "something went wrong" error
and at the end, someone told to them check database/accounts/registerGJAccount.php

I did that to see for errors and read that, what does this mean?
did I make a typo? did the SQL server just disable for some reason?

**Comment by RubyPiec** [comment]
it means youre going to die very very soon

**Comment by fidgetplayz48** [comment]
figured it out, if you are using freewha change it to `localhost`
