### ISSUE TITLE
Can't download levels

### ISSUE THREAD

**Issue by fidgetplayz48** [Cvolton/GMDprivateServer#806]
The title says it all, i can't download levels for some reason? basically everything else works!

**Comment by Cvolton** [comment]
make sure the server has write perms to the data directory and its subdirectories

**Comment by fidgetplayz48** [comment]
i have, all folders are 777

**Comment by fidgetplayz48** [comment]
I tried again and made all files writeable aswell, nothing's changed?
Maybe i forgot something?

**Comment by fidgetplayz48** [comment]
for more information, i am using freewha if that is the problem

**Comment by fidgetplayz48** [comment]
i managed to fix it by downloading the untested upload PHP, thanks for the help anyways!
