### ISSUE TITLE
issue with leaderbord getGJscore.php error on line 69

### ISSUE THREAD

**Issue by yannordi** [Cvolton/GMDprivateServer#807]
hello i have a gmd server and i have this error on my logs :  
the leaderbord is empty

PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in C:\\xampplatest\\htdocs\\s3\\incl\\scores\\getGJScores.php:69\nStack trace:\n#0 C:\\xampplatest\\htdocs\\s3\\incl\\scores\\getGJScores.php(69): PDOStatement->execute(Array)\n#1 C:\\xampplatest\\htdocs\\s3\\getGJScores20.php(2): include('C:\\\\xampplatest\\\\...')\n#2 {main}\n  thrown in C:\\xampplatest\\htdocs\\s3\\incl\\scores\\getGJScores.php on line 69

**Comment by CoderQCFromScraatch** [comment]
probably modified some code there
