### ISSUE TITLE
Literally everyone(mod or not) can use the bottom right rating button to rate.

### ISSUE THREAD

**Issue by QuantumWormhole** [Cvolton/GMDprivateServer#811]
Is there a way to stop this or is this coded in a way where if  a high enough % of people who suggest stars ittl rate?

**Comment by QuantumWormhole** [comment]
Also suggest system doesnt work

**Comment by Cvolton** [comment]
this sounds like you set up the roles wrong

**Comment by QuantumWormhole** [comment]
> this sounds like you set up the roles wrong, make sure you didn't set an admin role as default

uhh... how do I set a role as default?

**Comment by fidgetplayz48** [comment]
> uhh... how do I set a role as default?

in roles theres a column named "isDefault" make sure admin has that on 0

**Comment by QuantumWormhole** [comment]
ty

**Comment by QuantumWormhole** [comment]
IT WORKED ty. im dum i put everything as 1 for admin role lol.
