### ISSUE TITLE
Error when upload a song from direct url from server

### ISSUE THREAD

**Issue by FanyaOff** [Cvolton/GMDprivateServer#815]
Hello, when i try upload a song it gives me error:
This URL doesn't point to a valid audio file.

My link:
http://u96227ak.beget.tech/music/telegram.mp3

**Comment by Cvolton** [comment]
your host is blocking GD, the server sees this:
![image](https://user-images.githubusercontent.com/5721187/152421951-5153e045-ed1c-42a1-88d5-3162f3500bed.png)

**Comment by FanyaOff** [comment]
and how can i fix it?

**Comment by Cvolton** [comment]
use a different host if you don't have access to nginx settings

**Comment by FanyaOff** [comment]
i bought ubuntu vps, installed LAMP, and i get same error

http://176.118.165.70/music/1.mp3

**Comment by FanyaOff** [comment]
I can easily access the site from any PC
![Screenshot_1](https://user-images.githubusercontent.com/73064979/152657649-ac67a6f3-585d-4ea7-8b80-a2d455b98f22.png)

**Comment by Cvolton** [comment]
unable to recreate the issue, that link works for me

**Comment by FanyaOff** [comment]
Did you try it on ur gdps? And what can be done in this situation?

**Comment by FanyaOff** [comment]
i fixed it
