### ISSUE TITLE
Something went wrong 

### ISSUE THREAD

**Issue by IfkumRfnl** [Cvolton/GMDprivateServer#816]
Hi all! I did everything according to the instructions. I uploaded the server to host infinityfree, configured mysql database, through hex editor updated links in the game, but when I try to create an account I get the error "Something went worng". I tried creating an account through the browser (tools/account/registerAccount.php) and the account was successfully created. Checked as well the other files, there were no errors anywhere. The domain has exactly the same number of characters as in www.boomlings.com and there were no errors in the hex editor. I used Geometry Dash v2.1, which I downloaded from the instruction.

**Comment by Cvolton** [comment]
as far as I'm aware, infinityfree doesn't allow requests from Geometry Dash

**Comment by IfkumRfnl** [comment]
Ok, I'll try another host
