### ISSUE TITLE
levelReupload.php Error

### ISSUE THREAD

**Issue by GX2H912** [Cvolton/GMDprivateServer#82]
Once I place the ID in the box and change nothing else, as soon as I hit the enter button I come up with errors that show this on the page:

An error has occured.
Error code: Destination host forbidden, unlock the connection from your Altervista control panel (Resources > PHP Settings)
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'levelName' cannot be null' in /membri/gdpsmandara/tools/levelReupload.php:123 Stack trace: #0 /membri/gdpsmandara/tools/levelReupload.php(123): PDOStatement->execute(Array) #1 {main} thrown in /membri/gdpsmandara/tools/levelReupload.php on line 123

**Comment by Cvolton** [comment]
verify your altervista account
