### ISSUE TITLE
Stats and levels don't work

### ISSUE THREAD

**Issue by FanyaOff** [Cvolton/GMDprivateServer#821]
I changed the hosting to my VPS, replaced all the links, but there was a problem that nothing in the game loads (login to the account works)

i changed http://gdpsapis.viaps.ml/database/ to http://193.168.227.237/viapsgmdps/
and changed all base64 links
aHR0cDovL2dkcHNhcGlzLnZpYXBzLm1s to aHR0cDovLzE5My4xNjguMjI3LjIzNw==

what is the problem?
attached screenshots + exe game file

https://drive.google.com/file/d/1iJMi_bgGav9TMvQNdwGVfiBg6W78Tq6C/view?usp=sharing
![Screenshot_1](https://user-images.githubusercontent.com/73064979/153716902-7857f421-8552-48d0-be39-0a5e658795e3.png)
![Screenshot_2](https://user-images.githubusercontent.com/73064979/153716904-fe443a74-6f1a-450b-9ecc-bdedd7a0b723.png)

**Comment by Cvolton** [comment]
I guess you didn't carry over the data properly? I've succesfully been able to make an account but the user ID is 2, while in the data folder it seems that there should be at least 4 registered accounts. (As a side note, I'd recommend enabling .htaccess support in apache configuration, so the data folder isn't exposed publicly)

**Comment by FanyaOff** [comment]
right now I'll try to reinstall the server from scratch
