### ISSUE TITLE
WILL NOT BOOT

### ISSUE THREAD

**Issue by jmxamongusmodder** [Cvolton/GMDprivateServer#827]
I TRIED EVERYHTING WONT BOOT EVEN THROUGH STREAM U LIED

**Comment by TheTechRobo** [comment]
You can't just say "IT WON'T BOOT ASDFGHJKL" without saying what's wrong. Please elaborate.

**Comment by fancythedeveloper** [comment]
> You can't just say "IT WON'T BOOT ASDFGHJKL" without saying what's wrong. Please elaborate.

This ^^

**Comment by AToska21** [comment]
He means the GD executable will not start. I can fix it for him if he provides his GDPS server hostname.

**Comment by fancythedeveloper** [comment]
> He means the GD executable will not start. I can fix it for him if he provides his GDPS server hostname.

He probably fucked up a step by accident while editing the EXE, I assume.

**Comment by Cvolton** [comment]
op never elaborated
