### ISSUE TITLE
Some error thingy (Happening in a lot of the files)

### ISSUE THREAD

**Issue by TheOpGaming** [Cvolton/GMDprivateServer#83]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db677710812.links' doesn't exist' in /homepages/2/d677650796/htdocs/gdp/tools/levelReupload.php:111 Stack trace: #0 /homepages/2/d677650796/htdocs/gdp/tools/levelReupload.php(111): PDOStatement->execute(Array) #1 {main} thrown in /homepages/2/d677650796/htdocs/gdp/tools/levelReupload.php on line 111

^^^^^^^^^^^^^^^^^^^
Not using altervista

**Comment by TheOpGaming** [comment]
could it be something to do with MySQL 5.5?

**Comment by TheOpGaming** [comment]
Level download failed also

**Comment by AggPro** [comment]
whats your php version?

**Comment by Cvolton** [comment]
This is caused by the database structure not matching the version of the files, this is usually caused by updating improperly

**Comment by TheOpGaming** [comment]
ok

**Comment by TheOpGaming** [comment]
is there a way to fix it? php 5.6 btw...

**Comment by TheOpGaming** [comment]
still happening... Dunno what to do..

**Comment by AggPro** [comment]
try using newer php xd

**Comment by pavlukivan** [comment]
again, import the db structure
@Cvolton suggestion: auto table import script, opened #164

**Comment by EndNation** [comment]
@TheOpGaming Easy, you goto the line it says where there is an error then search on google how to fix the error, I fixed some alr

**Comment by geniiii** [comment]
your gdps has hiv

**Comment by Cvolton** [comment]
no constructive response in over 3 years, closing
