### ISSUE TITLE
Flooding gd accounts

### ISSUE THREAD

**Issue by Sagerka** [Cvolton/GMDprivateServer#831]
в игре создаются аккаунты боты которые флудят /
![Screenshot_2022-05-16-07-45-47-780_ru yandex searchplugin](https://user-images.githubusercontent.com/105643210/168581364-101ad72f-6957-4180-973d-9f76a776dceb.jpg)
ru
the game creates accounts bots that flood /en

**Comment by Cvolton** [comment]
the latest version has unregistered accounts disabled by default

**Comment by Sagerka** [comment]
Ok
