### ISSUE TITLE
Weird dashboard bug

### ISSUE THREAD

**Issue by Boalbads** [Cvolton/GMDprivateServer#836]
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/68003904/169639110-d8b5adb0-b1c2-4275-aa38-4c45562a5429.png">

On other devices, it appears perfectly, but for me, it appears like that (All the buttons still work, logging in, etc.) Can somebody help me?

**Comment by Boalbads** [comment]
It used to work, but then it stopped randomly

**Comment by Cvolton** [comment]
possible issue with an extension like dark reader?

**Comment by Boalbads** [comment]
Yeah thanks, it was one of my extensions.
