### ISSUE TITLE
Question: Will the suggest list be on the dashboard?

### ISSUE THREAD

**Issue by Boalbads** [Cvolton/GMDprivateServer#837]
Will the suggest list ever be on the dashboard, or is it only on DB and /tools?

**Comment by Cvolton** [comment]
I'm currently trying to think about what to do with the dashboard, it might be best to scrap the current implementation and actually update the tools page to resemble something more like what I was going for with the dashboard instead

**Comment by Boalbads** [comment]
Okay, I personally think the current dashboard should be an option (even if its not finished) if you do follow through with that idea.
