### ISSUE TITLE
Imported gdps to run locally on XAMMP, certain stuff not working.

### ISSUE THREAD

**Issue by CameronWDMorgan** [Cvolton/GMDprivateServer#839]
Recently moved my gdps from GDPSFH to run locally on XAMMP with a domain I bought, Leaderboards work (apart from Creators and Top 100?), and level uploading works (uploaded levels and saw them get uploaded in phpmyadmin/explorer)

However, Level loading doesn't work (as shown in image)
![image](https://user-images.githubusercontent.com/97979492/171503133-80e67b2b-ac74-4da6-a91f-e34e97f5a7b3.png)

Apache Access Logs:
![image](https://user-images.githubusercontent.com/97979492/171504936-cbdd2dfe-45d9-47e0-b775-ee36b0b7a72f.png)

Any help or suggestions would be great!

**Comment by CameronWDMorgan** [comment]
> Sorry that this isn't related to the issue, but how did you change the server URL in your GD EXE file? I am also moving my GDPS from GDPSFH to this, and I'm wondering how I can do so.

Make the geometry dash client from scratch by following the Wiki guides linked Here: [https://github.com/Cvolton/GMDprivateServer/wiki/Creating-Windows,-Android-and-IOS-Apps](url)

**Comment by Cvolton** [comment]
if you only updated the php files then that's gonna be an issue, make sure to update the database structure as well using the sql files in `_updates`, i don't remember what version gdpsfh uses but i know it's not the most up to date one

**Comment by CameronWDMorgan** [comment]
Updated the files.folders and sql, levels now load, but now accounts and all leaderboards wont load.

**Comment by TechStudent11** [comment]
> > Sorry that this isn't related to the issue, but how did you change the server URL in your GD EXE file? I am also moving my GDPS from GDPSFH to this, and I'm wondering how I can do so.
> 
> Its no problem I hope I can help 👍
> 
> Make the geometry dash client from scratch by following the Wiki guides linked Here: [https://github.com/Cvolton/GMDprivateServer/wiki/Creating-Windows,-Android-and-IOS-Apps](url)
> 
> EDIT: You will also need to get the database files and more from the fgdpsh discord server with "ps!getbackup" (this will make it so levels accounts, and stats etc are retained) just be sure to update the PHP files with new ones and to modify the connection.php file so it points to your server

Thanks!

@Cvolton I have a question; I have exported the SQL file from the PHPmyAdmin dashboard to get all the accounts, levels, etc. Would it be the same process to import it into the GDPS as this:
> EDIT: You will also need to get the database files and more from the fgdpsh discord server with "ps!getbackup" (this will make it so levels accounts, and stats etc are retained) just be sure to update the PHP files with new ones and to modify the connection.php file so it points to your server

**Comment by CameronWDMorgan** [comment]
Fixed everything by going through the database.sql file (downloaded from repo) and adding in actions_downloads manually.
