### ISSUE TITLE
Android GDPS Instant Closing

### ISSUE THREAD

**Issue by CameronWDMorgan** [Cvolton/GMDprivateServer#846]
I know that its usually because someone edited the files wrong, but it should be working, i changed the com.robtopx.geometryjump (or whatever it was) in manifest and libcocos2dcpp.so to the correct one (same length), I have changed all the urls in base64 and regular with and without /database/ at the end. They install but when tapping on the app it asks for permissions, I accept and then it closes out instantly and will not open on my phone and nox emulator.

The APK:https://drive.google.com/file/d/1mR0ebnw9cf65y1hJg7qpVpPB7RmoJIH7/view?usp=sharing

Any suggestions would be great :D

**Comment by EMREOYUN** [comment]
Editing .so files is not easy, I guess. I heard they have security protection with digital signatures. Personally, I don't know how to edit .so files. When I create GDPS, I simply just change the app name and sacrifice the save ability. Perhaps, someone else may discover the way to edit it but I don't know really.

**Comment by masckmaster2007** [comment]
Well i did that as usual and it seems like newer android versions don't like that.
GD on Android 4.4 and 6 works fine btw

**Comment by Cvolton** [comment]
> Editing .so files is not easy, I guess. I heard they have security protection with digital signatures. 

no they don't

**Comment by EMREOYUN** [comment]
> > Editing .so files is not easy, I guess. I heard they have security protection with digital signatures. 
> 
> no they don't, it's literally just an executable

Then may I ask why editing .so files makes the game unbootable, even though just changing package name by Hex Editor?

**Comment by CameronWDMorgan** [comment]
Still haven't found a solution, tried re-doing it recently and it still fails:
Contact me on discord if you can help, dms are open. Anim27#5778

**Comment by CameronWDMorgan** [comment]
Resolved, followed this tutorial using their apk and it worked. (followed on pc with HxD and APK Editor Studio)
https://www.youtube.com/watch?v=_7MF2dPRLng
