### ISSUE TITLE
Can't open the .exe file on mac using wine.

### ISSUE THREAD

**Issue by SamHep0803** [Cvolton/GMDprivateServer#85]
Hi i'm having a problem where I can't open the .exe file after editing the hex. I am on a mac but using  wine to open the files I have a screenshot and also the video I was watching to create it.

Video: https://www.youtube.com/watch?v=7ePoMX-A2eU&t=286s

Screenshot: http://imgur.com/a/hgXel

Oh and I also have the hosted address: http://samsam1.16mb.com/

**Comment by SamHep0803** [comment]
Forgot to tell, I used hostinger to make the address and host it.

**Comment by TheOpGaming** [comment]
did u get any changing file size warnings when replacing the values?

**Comment by RobertTopala** [comment]
Your URL must be 33 long including the HTTP://

**Comment by Cvolton** [comment]
your url length doesn't seem to be matching the boomlings url length (1 character too short)

**Comment by SamHep0803** [comment]
I put www.boomlings.com in a word counter it was 17 letters and i put my url in and it also had 17 letters also @TheOpGaming yes it did

**Comment by SamHep0803** [comment]
So what do I do then?

**Comment by SamHep0803** [comment]
@RobertTopala Hi robtop I've already tried that, i failed and started again and now i'm here with nobody answering me

**Comment by SamHep0803** [comment]
Hi nevermind I've figured it out RobTop and Cvolton was right. My URL was to short.

**Comment by SamHep0803** [comment]
I managed to open the file but now I can't register
