### ISSUE TITLE
Can someone help me with making an Android GDPS?

### ISSUE THREAD

**Issue by CameronWDMorgan** [Cvolton/GMDprivateServer#855]
I have tried over a few times making my GDPS, when I edit the android manifest it stops booting, when I leave the manifest alone it works (connects to gdps server etc) but it doesn't save data on close (cause editing android manifest seems to make it not load on phones and emulators). 
My discord is: Anim27#5778

**Comment by EMREOYUN** [comment]
Editing manifest files may corrupt the game so you need to be careful about it, and changing just the application name brings up the save issue where you can't save your progress without saving and restoring from the GDPS.

**Comment by CameronWDMorgan** [comment]
Still haven't found a solution, tried re-doing it recently and it still fails:
Contact me on discord if you can help, dms are open. Anim27#5778

**Comment by CameronWDMorgan** [comment]
> Editing manifest files may corrupt the game so you need to be careful about it, and changing just the application name brings up the save issue where you can't save your progress without saving and restoring from the GDPS.

Dont you need to edit the manifest to get it to not save over normal geometry dash?

**Comment by EMREOYUN** [comment]
> Dont you need to edit the manifest to get it to not save over normal geometry dash?

Yes but you need to be careful
> Editing manifest files may corrupt the game so you need to be careful about it

**Comment by CameronWDMorgan** [comment]
Resolved, followed this tutorial using their apk and it worked. (followed on pc with HxD and APK Editor Studio)
https://www.youtube.com/watch?v=_7MF2dPRLng
