### ISSUE TITLE
Can't login or create levels.

### ISSUE THREAD

**Issue by SamHep0803** [Cvolton/GMDprivateServer#86]
Hi, I managed to get the exe to start but now I can't register or do anything that you could do in Normal GD.

My PHP version is 5.6 though I did try 7.0.

I don't know if it's my host (by the way i'm using hostinger with the address samsam12.16mb.com.

I did try and see if the connection.php gave me a 404 error I've even got a screenshot of the filezilla screen: http://imgur.com/a/eYIE7 (I blocked out my private things)

**Comment by Cvolton** [comment]
you need to move the database folder into the public_html folder

**Comment by SamHep0803** [comment]
oh wow thanks

**Comment by SamHep0803** [comment]
Well when no one was responding i gave up and deleted the hostinger address and now it has changed and you can't get a free host. I am now using Awardspace and the connections.php is giving me a 404 again ill show you: http://imgur.com/a/k9D88

**Comment by SamHep0803** [comment]
unless you wouldnt mind making me one and giving me the details

**Comment by AggPro** [comment]
hostinger issues. happens the same thing to me

**Comment by SamHep0803** [comment]
Do you know any web hosts that do work @AggPro ?

**Comment by AggPro** [comment]
i personally use 000webhost


**NOTE:**If you want to use it, make sure thet the URL looks like:

> **http://**name1234**.000webhostapp.com/**

**Comment by AggPro** [comment]
000webhost
@SamHep0803
