### ISSUE TITLE
I can't register

### ISSUE THREAD

**Issue by rh3nz420** [Cvolton/GMDprivateServer#864]
I can't register in game and in the tools page.

When I try to register in the tools page, it shows up like this:

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'secret' in 'field list' in /home/vhosts/CENSORED/database/tools/account/registerAccount.php:40 Stack trace: #0 /home/vhosts/CENSORED/database/tools/account/registerAccount.php(40): PDOStatement->execute(Array) #1 {main} thrown in /home/vhosts/CENSORED/database/tools/account/registerAccount.php on line 40

I also tried In game and it basically says register failed or idk. Can y'all help me?

**Comment by nixide1** [comment]
Did you import the database?

**Comment by rh3nz420** [comment]
of course I did

**Comment by nixide1** [comment]
You are using older registerAccount.php, secret column is now in the users table
https://github.com/Cvolton/GMDprivateServer/commit/85576f52848d16130e790d88db63b5a41083d188

**Comment by rh3nz420** [comment]
ok thanks it works now
