### ISSUE TITLE
How to like a level in 1.0?

### ISSUE THREAD

**Issue by KoLeS2109** [Cvolton/GMDprivateServer#868]
I cant like any levels in 1.0(((

**Comment by Cvolton** [comment]
Copy the likeGJItem PHP file in the root and name it likeGJLevel, that should probably fix it, I'll make a commit to the main repo that does this soon

**Comment by KoLeS2109** [comment]
I already did that, but it didn't help. the like button is pressed, but there is no change in the database.

**Comment by CoderQCFromScraatch** [comment]
You can't unlike a level in GD, you have to like/dislike another level.

**Comment by KoLeS2109** [comment]
> You can't unlike a level in GD, you have to like/dislike another level.

you misunderstood, the like button works, but there is no reaction from the server side, for example, changes in the database

**Comment by Cvolton** [comment]
the code looks for a post field called itemID to determine the ID of the liked level, this is probably called levelID in 1.0 instead and because of that it doesn't recognize it and tries to like level ID 0

**Comment by CoderQCFromScraatch** [comment]
colton found the problem, he should fix it or i might make a PR to fix it.

**Comment by KoLeS2109** [comment]
![image](https://user-images.githubusercontent.com/93978604/185801462-ea9020c1-f264-43e6-af44-3e5e14119862.png)

I'm very bad at php and can't create likeGJLevel.php, but a captured one http packet, it may be helpful for you

**Comment by MegaSa1nt** [comment]
скопируй файл likeGJItem.php в корневую папку и назови его likeGJLevel.php

**Comment by KoLeS2109** [comment]
Всё заработало, спасибо за помощь

**Comment by MegaSa1nt** [comment]
> Всё заработало, спасибо за помощь

рад был помочь!
