### ISSUE TITLE
my gdps will not work and i dont know whats wrong

### ISSUE THREAD

**Issue by 1cabii** [Cvolton/GMDprivateServer#872]
ive been trying to open a gdps forever and i keep running into errors, ive very certain ive configured connection.php correctly, ive imported database.sql into phpmyadmin, and ive uploaded all the files to the ftp server. the tools page doesnt even load, neither does anything else on the website, only the website will
my host is http://cabiigdps1.x10.mx if that helps me with my issue
i created this account just to make this post lmao
im using x10hosting btw

**Comment by nixide1** [comment]
It doesn't look like you have uploaded any files, database directory returns 404

**Comment by 1cabii** [comment]
tf? i did upload them, but maybe i uploaded it to the wrong server

**Comment by 1cabii** [comment]
nvm got my gdps working

**Comment by FunWithAlbiYT** [comment]
H0W DID YOU FIX IT???
