### ISSUE TITLE
Levels uploaded to the servers always have at least 300 downloads and 100 likes

### ISSUE THREAD

**Issue by Startive** [Cvolton/GMDprivateServer#873]
Somehow everytime i upload a level to the server it gets alot of downloads and likes for no reason. No one else has access to the GDPS besides me and for some reason it magically gets alot of downloads and likes. Any fixes? 
![image](https://user-images.githubusercontent.com/90710922/179422353-2ff5b60e-4237-4567-b72e-22345af40a9a.png)

**Comment by nixide1** [comment]
Change the default value in the levels table

**Comment by Startive** [comment]
thanks but it should already be 0 by default

**Comment by MegaSa1nt** [comment]
close this
