### ISSUE TITLE
How to use custom songs on Android GDPS?

### ISSUE THREAD

**Issue by andrressliz** [Cvolton/GMDprivateServer#875]
It seems the Android version of GD won't let you input any song ID with over 6 characters. It just trims it. This causes trouble since the songs reuploaded via the page are 7 characters long. Is there any way to fix this?

**Comment by MegaSa1nt** [comment]
you can try to delete all 7 char long songs

**Comment by andrressliz** [comment]
@MegaSa1nt I mean, of course, that'd be the easy solution - but thing is that people from my GDPS want to use those songs. I've thought of manually making them 6-char longs via the database, but it would probably overwrite newgrounds songs, or the newground ones would overwrite these, making them unusable.

**Comment by MegaSa1nt** [comment]
i fixed this issue by using randomizer to song id

**Comment by MegaSa1nt** [comment]
@andrressliz what link do you use?

**Comment by fancythedeveloper** [comment]
BTW, there's ways to bypass the 6 digit limit on vanilla GD without having to use a patched APK. Just set your keyboard to floating mode and it will bypass it, if your phone keyboard doesn't have a floating mode, then just download one that has it, like Gboard.

**Comment by MegaSa1nt** [comment]
or you can modify your apk
https://www.youtube.com/watch?v=kvmBi-eLK8M

**Comment by fancythedeveloper** [comment]
That too, but my method is if you don't wanna do that.

**Comment by andrressliz** [comment]
@MegaSa1nt oh wow! Thanks for that. Did it and it's working smoothly.
Thanks to everyone who replied too!
