### ISSUE TITLE
The Safe and Event Level not work!

### ISSUE THREAD

**Issue by WhoreMan** [Cvolton/GMDprivateServer#878]
I was trying to do a GDPS with the 2.2 editor unlocked and most of the functions work.

The problem is that levels do not appear in The Safe and it does not load the Event Level either.

(It is interesting because if I enter Featured or Lists the levels do appear but when I try to enter The Safe or Event Level, the levels do not load)

Is there support for these features?

![image](https://user-images.githubusercontent.com/109772401/180338540-0416586a-2de5-4f12-98de-d2411168f261.png)

![image](https://user-images.githubusercontent.com/109772401/180338582-a722ddd7-2acc-46bd-a345-c81c2cbf4b90.png)

And yes, the levels are daily levels and with type 0, 1, 2

![image](https://user-images.githubusercontent.com/109772401/180338995-90b7757e-fff9-4eb5-bea8-7990ebef4197.png)

![image](https://user-images.githubusercontent.com/109772401/180339029-7b3e7d3e-9542-4cca-8334-84e88599d161.png)

**Comment by MegaSa1nt** [comment]
No, it's not, check Pull requests

**Comment by WhoreMan** [comment]
Uhh, i thought the features were ready...

I said it especially because there are servers (such as the GDPS Editor) that already have these features.

But thanks!

**Comment by Cvolton** [comment]
> These features are still in the untested branch

They were merged to master a while ago. There isn't a built in way to set event levels yet though.

**Comment by WhoreMan** [comment]
Interesting, thanks for replying!
