### ISSUE TITLE
Level uploading doesnt work

### ISSUE THREAD

**Issue by MegaSa1nt** [Cvolton/GMDprivateServer#880]
https://youtu.be/TqKvKA5GCZ0
Account saving doesnt work as well
data folder has 777 perms

**Comment by RuvSleep** [comment]
I have same problem.

**Comment by Cvolton** [comment]
Check the php error log

**Comment by MegaSa1nt** [comment]
theres no errors, it says "Upload complete" and nothing appearing in error log

**Comment by MegaSa1nt** [comment]
OMG i fixed that
it seems that 'settingsString' doesnt have a default value, and thats all!
https://youtu.be/_cn2jUb4X1w
