### ISSUE TITLE
Fatal error in registerAccount.php

### ISSUE THREAD

**Issue by FunnyManJD** [Cvolton/GMDprivateServer#887]
I got my GDPS working, but I can't create an account. I tried to create an account through the account management page but it keeps giving me this error:

> Connection failed: SQLSTATE[HY000] [1045] Access denied for user '#####'@'localhost' (using password: YES)
Notice: Undefined variable: db in /home/#####/public_html/#####/database/tools/account/registerAccount.php on line 27

>Fatal error: Call to a member function prepare() on null in /home/#####/public_html/multiclipo2/database/tools/account/registerAccount.php on line 27

Can someone help me?

**Comment by Cvolton** [comment]
that doesn't look like a working gdps

your db credentials are wrong

**Comment by MegaSa1nt** [comment]
connection.php wrong

**Comment by FunnyManJD** [comment]
> connection.php wrong

Yeah, but how do I fix them?

**Comment by MegaSa1nt** [comment]
write valid data?

**Comment by FunnyManJD** [comment]
> write valid data?

Yeah

**Comment by FunnyManJD** [comment]
Okay... I fixed it (somehow) by entering the password that I used to log in "sql2. 7m.pl" instead of the one that was sent to me by an email!
