### ISSUE TITLE
Best way to edit geometrydash.exe?

### ISSUE THREAD

**Issue by tryzombie501** [Cvolton/GMDprivateServer#89]
Title is my question

**Comment by tryzombie501** [comment]
IDA pro seems to be the best method for me just curious on other people methods.

**Comment by absolute-gamer** [comment]
Using IDA is overkill for just editing a few links, use a hex editor (and something to encode/decode base64).

**Comment by absolute-gamer** [comment]
The most popular method is hex editing the links, it’s just easy and convenient for people.

**Comment by Cvolton** [comment]
a hex editor like hxd or even notepad++ will work just fine, you don't need to use IDA for this
