### ISSUE TITLE
Using GMDPrivateServer for 1.9 (1.8 not needed anymore)

### ISSUE THREAD

**Issue by masckmaster2007** [Cvolton/GMDprivateServer#890]
I want to create a GDPS for these 2 versions combined, but it doesn't seem to work...
First, i want to make registered account work, but i also fear about security because i've read that it isn't secured AT ALL.

Please help me I'm confused.

**Comment by MegaSa1nt** [comment]
1.9 doesnt have accounts
![image](https://user-images.githubusercontent.com/49565695/183069392-c353e58d-31ae-4594-aec6-37189f3eab05.png)

**Comment by masckmaster2007** [comment]
![image](https://user-images.githubusercontent.com/63162857/183835848-277f09d4-8731-4de0-ac8f-a7c613952b7a.png)
lol what

**Comment by masckmaster2007** [comment]
![image](https://user-images.githubusercontent.com/63162857/183836478-e45555ea-d806-490b-8a65-4ef503d6c49d.png)
this might help you understand (empty response)

**Comment by MegaSa1nt** [comment]
this is how it works
server doesnt allow you do anything with account because 1.9 doesnt have password verification and everyone with login bypass can do anything from your account

**Comment by fancythedeveloper** [comment]
What about 1.8? Since the issue name mentions that as well.

**Comment by masckmaster2007** [comment]
> this is how it works
> 
> server doesnt allow you do anything with account because 1.9 doesnt have password verification and everyone with login bypass can do anything from your account

I mean I'm unregistered, so I'm safe. But **nothing works**.

**Comment by masckmaster2007** [comment]
> What about 1.8? Since the issue name mentions that as well.

Yea I'm talking about 1.8 because I managed to get Geometry Dash for Windows Phone.

**Comment by MegaSa1nt** [comment]
> > this is how it works
> > server doesnt allow you do anything with account because 1.9 doesnt have password verification and everyone with login bypass can do anything from your account
> 
> I mean I'm unregistered, so I'm safe. But **nothing works**.

oh, check config/security.php and set $unregisteredSubmissions to true

**Comment by masckmaster2007** [comment]
It doesn't change anything

**Comment by masckmaster2007** [comment]
![image](https://user-images.githubusercontent.com/63162857/184310741-a4f6ceb6-3849-48f5-b336-4ef60762e2ac.png)
I was using a broken 1.9 fork. I switched to pure GMDPrivateServer and it works

**Comment by masckmaster2007** [comment]
![image](https://user-images.githubusercontent.com/63162857/184312057-5712a483-19d9-4f53-98f8-7540a11feca3.png)
aaaand i get this

**Comment by MegaSa1nt** [comment]
set default value to banReason

**Comment by masckmaster2007** [comment]
> set default value to banReason

![image](https://user-images.githubusercontent.com/63162857/184312687-4caeacea-fccc-4445-bc17-c230240d9fe9.png)
Well, i forgot to drop the 1.9 database and import the new one, now it works

**Comment by MegaSa1nt** [comment]
gg!

**Comment by masckmaster2007** [comment]
Ok last thing. HOW IS ABSOLUTE'S 1.9 GDPS DEALING WITH REGISTERED ACCOUNTS

**Comment by masckmaster2007** [comment]
> they have a modded version of 1.9 that adds additional security measures

oh

**Comment by masckmaster2007** [comment]
Only way to hack into these accounts would be to compromise the whole system...

**Comment by masckmaster2007** [comment]
So how can i enable registered accounts by force ?

**Comment by masckmaster2007** [comment]
also, it seems like if unregistered submissions are on, you can create an account and connect, but doing any action will create a unregistered "clone" of that registered account. Interresting

**Comment by masckmaster2007** [comment]
EDIT: bruh registered accounts work now. what ?

**Comment by masckmaster2007** [comment]
Closing it myself. I managed to do an IP check
Here are the files below if anyone's interested into making this an actual thing
loginGJAccount - https://pastebin.com/LGAKfDx1
registerGJAccount - https://pastebin.com/qWZ6JRuQ
