### ISSUE TITLE
Bug while downloading level

### ISSUE THREAD

**Issue by maxito25** [Cvolton/GMDprivateServer#893]
When i upload a level and i go to play it, it says "level download failed, please try again later"

**Comment by MegaSa1nt** [comment]
check data/levels

**Comment by maxito25** [comment]
i checked it and there is nothing in that folder even when i did everything correctly

**Comment by MegaSa1nt** [comment]
theres no files in data/levels?

**Comment by maxito25** [comment]
nope

**Comment by maxito25** [comment]
everything else works, like downloading user data, map packs, rating a level, etc

**Comment by MegaSa1nt** [comment]
> nope

thats why level downloading doesnt work, idk whats the problem

**Comment by Cvolton** [comment]
make sure the server has write perms to the data dir and all of its subdirectories, the easiest way to do so is to chmod 777 (enable all perms)

**Comment by maxito25** [comment]
> chmod 77

it worked! thank you so much
