### ISSUE TITLE
Message decoding

### ISSUE THREAD

**Issue by MegaSa1nt** [Cvolton/GMDprivateServer#895]
Hi everyone! Does anyone know how gd converts body from message to readable text?

![image](https://user-images.githubusercontent.com/49565695/184321150-47177822-519b-48c2-81a8-73ef95aa1c7c.png)

Both body and subject is 'test', both body and subject are utf8 in database, but subject easily decodes as it is base64
How can i decode message body?

**Comment by Cvolton** [comment]
xor 14251

**Comment by MegaSa1nt** [comment]
![image](https://user-images.githubusercontent.com/49565695/184477112-f74b1a12-e26f-41e3-a489-82f9c30027a2.png)
![image](https://user-images.githubusercontent.com/49565695/184477118-8da423b1-a3e6-4eb5-b0e3-67183e972537.png)
What did i do wrong?

**Comment by MegaSa1nt** [comment]
> xor 14251

plus base64 encode, thanks!
