### ISSUE TITLE
Can't register/upload levels

### ISSUE THREAD

**Issue by AnubisTDG** [Cvolton/GMDprivateServer#90]
Hi! I'm trying to create a gdps and I cannot seem to be able to create an account without the game returning the error "Login Failed". When I go to upload levels, it says that they have uploaded successfully, but they don't seem to be showing up anywhere on the server. My webhost is x10 hosting and the link is http://tdgpr.x10host.com/. I've been trying to figure this out for months now. I am using Geometry Dash 2.0. Please help.

**Comment by Cvolton** [comment]
you didn't edit the mysql settings (config/connection.php)

**Comment by AnubisTDG** [comment]
@Cvolton I tried that and it still doesn't work. :/ Did I edit something wrong in connection.php or is it another problem entirely?

**Comment by AnubisTDG** [comment]
Nvm just got it to work thank you very much for the help! :)

**Comment by AnubisTDG** [comment]
@Cvolton Okay. I created an account and it worked, but now I can't give myself admin or upload levels.

**Comment by AnubisTDG** [comment]
Nvm it's working now thanks for the help! :)

**Comment by AnubisTDG** [comment]
@Cvolton I do have one small question however. Is the admin supposed to get blue text like on the real geometry dash server? Because it doesn't seem to be showing up for me. I upgraded the server to 2.1 btw.

**Comment by Cvolton** [comment]
the accountid needs to be 71 for the text to be blue

**Comment by AnubisTDG** [comment]
Thank you so very much! :D
