### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by portal007gms** [Cvolton/GMDprivateServer#901]
Help, i have been trying to do this for so long but GD always just says something went wrong when i try to register an account

Here's the connection.php:

$servername = "sql2.7m.pl";
$port = 3306;
$username = "username";
$password = "password";
$dbname = "database name";

Also there is the correct login and stuff there i just censored it here and yes i checked a lot of times if its typed correctly

**Comment by MegaSa1nt** [comment]
check dashboard for any database errors

**Comment by portal007gms** [comment]
and where do i look for that?

**Comment by MegaSa1nt** [comment]
send your database link

**Comment by portal007gms** [comment]
If you mean the link to the database server then its sql2.7m.pl

**Comment by MegaSa1nt** [comment]
no, your server link
like *server*.7m.pl

**Comment by portal007gms** [comment]
oh ok
nstrgdp.7m.pl

**Comment by MegaSa1nt** [comment]
![image](https://user-images.githubusercontent.com/49565695/186660051-a0b45ec1-a45b-4944-b2ba-4fa3b349d107.png)

**Comment by MegaSa1nt** [comment]
![image](https://user-images.githubusercontent.com/49565695/186660145-32865ed9-6b62-41fd-a289-66830226afad.png)
maybe this is the problem

**Comment by portal007gms** [comment]
Well if the account registration works then why doesn't it work in gd?
also is there any fix to that error?

**Comment by MegaSa1nt** [comment]
check line 36 in incl/lib/ip_in_range.php

**Comment by portal007gms** [comment]
the line is just
`class ipInRange {`

**Comment by MegaSa1nt** [comment]
lol wtf

**Comment by portal007gms** [comment]
And logging in says login failed
