### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by Boalbads** [Cvolton/GMDprivateServer#902]
I have been working on a 1.02 GDPS using CrystalCloud hosting, when I try to upload a level, it says upload failed. But when I make a level from the database, it will appear when I search the ID, I think connection.php is connect, can anybody help?
My servername is 127.0.0.1
and I left the port at 3306
the DB name, pass, and username should be correct

**Comment by Boalbads** [comment]
Fixed, just had to allow green users to do stuff.

**Comment by Boynfriend** [comment]
Bruh, how are you fixed it? Say please.
