### ISSUE TITLE
GDPS Account Deletion

### ISSUE THREAD

**Issue by UnknownUser648** [Cvolton/GMDprivateServer#906]
Please add an account deletion option!

**Comment by MegaSa1nt** [comment]
![image](https://user-images.githubusercontent.com/49565695/187041288-7d3a2057-31de-4e5c-a02d-ceaa97d7aee5.png)

**Comment by UnknownUser648** [comment]
Okay, but I mean how people without admin privileges will unregister their accounts?

**Comment by MegaSa1nt** [comment]
You can create a php script for this

**Comment by UnknownUser648** [comment]
I wanted it to be official when unpacking the server, but ok!
