### ISSUE TITLE
Profile loading error

### ISSUE THREAD

**Issue by LucTheDumbGuy** [Cvolton/GMDprivateServer#912]
Hello there people from Github!
I was making a GDPS and encountered this problem when I wanted to see if I modded myself, but when I clicked on my profile it said: Something went wrong.
Can someone help?

**Comment by MegaSa1nt** [comment]
anything else work fine?

**Comment by LucTheDumbGuy** [comment]
> everything else works fine?

Sadly, no..

**Comment by LucTheDumbGuy** [comment]
Only level creating+uploading Creating+Logging into accounts

**Comment by MegaSa1nt** [comment]
pls send your gdps link

**Comment by LucTheDumbGuy** [comment]
Wdym?

**Comment by LucTheDumbGuy** [comment]
Like the files or the site?

**Comment by LucTheDumbGuy** [comment]
http://rndomweb.ueuo.com/database
