### ISSUE TITLE
Upload ban problem...

### ISSUE THREAD

**Issue by KoLeS2109** [Cvolton/GMDprivateServer#915]
I tried to implement the function of prohibiting uploading levels to people, where isUploadBanned == 1 in the users table. But the problem is that now everyone can't post the levels, where could I have made a mistake?

![Screenshot_20220909-151915_ES File Explorer.jpg](https://user-images.githubusercontent.com/93978604/189349156-25bce4b2-3938-4c66-b9b7-1d8e879819ff.jpg)

**Comment by nixide1** [comment]
`$uploadBan->fetchColumn()`

**Comment by KoLeS2109** [comment]
Thx for help, all works)
