### ISSUE TITLE
"Something went wrong" error when creating an account

### ISSUE THREAD

**Issue by ABwebGamesFan** [Cvolton/GMDprivateServer#917]
I just made a GDPS, Everything works fine, accept for the account system. I tried making one and it said "Something went wrong" I tried again with a different email just to make sure, and I still got the error. I'm using the 2.113 Steam version and I use crystalcloud to host the servers.

**Comment by ABwebGamesFan** [comment]
UPDATE: I tried using the web version to register and i got this error: "Connection failed: SQLSTATE[HY000] [1045] Access denied for user 'abwebfangdps_db'@'localhost' (using password: YES)"

**Comment by ABwebGamesFan** [comment]
ANOTHER UPDATE: I fixed it. I had to change connection.php

**Comment by powerty989** [comment]
> ANOTHER UPDATE: I fixed it. I had to change connection.php

how?
