### ISSUE TITLE
Warning: require(../incl/lib/connection.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by EnigmaGD** [Cvolton/GMDprivateServer#922]
Is there a way to fix this?

**Comment by Cvolton** [comment]
more information required

**Comment by MegaSa1nt** [comment]
No, its not, check pls incl/lib/connection.php or recreate gdps

**Comment by EnigmaGD** [comment]
> No, its not, check pls incl/lib/connection.php or recreate gdps

where do i check?

**Comment by MegaSa1nt** [comment]
in ftp (place, where you uploaded gdps)

**Comment by EnigmaGD** [comment]
how do i add it?

**Comment by EnigmaGD** [comment]
> send me friend request in discord pls, i'll help you, МегаСвятой#9096

Thank you for the help :D
