### ISSUE TITLE
Description sometimes is blank

### ISSUE THREAD

**Issue by MegaSa1nt** [Cvolton/GMDprivateServer#923]
![image](https://user-images.githubusercontent.com/49565695/191623402-e62a5056-fce4-4b5a-8f0d-eba304a41a9b.png)
![image](https://user-images.githubusercontent.com/49565695/191623469-8de1dbe1-9cd8-423c-b2db-328ced6de806.png)

**Comment by MegaSa1nt** [comment]
![image](https://user-images.githubusercontent.com/49565695/191625668-6c82f2eb-c92a-4336-be5d-fa74e0314a88.png)
![image](https://user-images.githubusercontent.com/49565695/191625678-21d4df15-e102-43ca-8437-6e238b5452df.png)

**Comment by Cvolton** [comment]
there was a bug where descriptions for non-copyable levels didn't work, this was fixed in 971a86ddb849bbf1d3f169e87c8ade5ebbbd8746 though

**Comment by MegaSa1nt** [comment]
thanks!
