### ISSUE TITLE
Unable to see account

### ISSUE THREAD

**Issue by labrosggv** [Cvolton/GMDprivateServer#924]
For some reason I can create an account, but I can't see it. Also I can see the normal gauntlets and mappack. Another problem that I have is that I can find levels from the normal gd server and I can't upload levels. In the connections.php file servername = "127.0.0.1" and port = 3306(I changed username, password and dbname to the ones that I should. I know that they work beause when I create a new account I can see it in the database). I noticed that in step 3 in the readme.md file it said that some links in the gd executable are encoded with base64, but when I encoded www.boomlings.com with a base64 encoder I caoldn't find anything that matched.

**Comment by MegaSa1nt** [comment]
hey! send me a friend request in discord, ill help you - МегаСвятой#9096
