### ISSUE TITLE
Leaderbords and comment checking doesnt work without account

### ISSUE THREAD

**Issue by MegaSa1nt** [Cvolton/GMDprivateServer#926]
![image](https://user-images.githubusercontent.com/49565695/192151956-8ce0ced2-0f7c-48e6-8c27-7f6726005cbc.png)
![image](https://user-images.githubusercontent.com/49565695/192151980-be657aaf-534a-4a93-b7ed-bb79f1478a68.png)

**Comment by nixide1** [comment]
#927
