### ISSUE TITLE
Is it possible to "ban" a user from uploading levels?

### ISSUE THREAD

**Issue by TAL9988** [Cvolton/GMDprivateServer#930]
The IP-Ban process is something I tried, and it doesn't seem to work effectively.

I believe an "Upload Ban" function would be very beneficial and make things simpler and better for the owners of a GDPS.
The concept of upload banning is rather self-explanatory; in short, once a user is banned, their ability to upload levels is removed.

**Comment by KoLeS2109** [comment]
Yes, its possible, but you need to edit uploadGJLevel.php

![Screenshot_20220928-184220_ES File Explorer.jpg](https://user-images.githubusercontent.com/93978604/192824716-eda072b0-8ffc-4b3e-bcc8-7067a5cb093a.jpg)


Like this



Code:


$uploadBan = $db->prepare("SELECT isUploadBanned FROM users WHERE userID = :userID");
$uploadBan->execute([':userID' => $userID]);
if($uploadBan->fetchColumn() != 0){
 exit("-1");
}


PS: in SQL in table users add "uploadBan"
Table

**Comment by KoLeS2109** [comment]
Yes, its possible, but you need to edit uploadGJLevel.php

![Screenshot_20220928-184220_ES File Explorer.jpg](https://user-images.githubusercontent.com/93978604/192824716-eda072b0-8ffc-4b3e-bcc8-7067a5cb093a.jpg)


Like this



Code:


$uploadBan = $db->prepare("SELECT isUploadBanned FROM users WHERE userID = :userID");
$uploadBan->execute([':userID' => $userID]);
if($uploadBan->fetchColumn() != 0){
 exit("-1");
}


PS: in SQL in table users add "uploadBan"
Table




![Screenshot_20220928-184834_Chrome.jpg](https://user-images.githubusercontent.com/93978604/192826105-b21527a7-38bd-4748-83c9-23385f50d28e.jpg)

**Comment by TAL9988** [comment]
Thanks! It worked :)

**Comment by KoLeS2109** [comment]
> Thanks! It worked :)

Enjoy!
