### ISSUE TITLE
Autoban issue

### ISSUE THREAD

**Issue by MegaSa1nt** [Cvolton/GMDprivateServer#936]
It seems like autoban.php doesn't count daily levels and weekly demons, so it banning all people, who beated all levels + daily/weekly

![image](https://user-images.githubusercontent.com/49565695/194778922-4b5680d2-6176-47ae-a9a5-5b9ac44d350e.png)
![image](https://user-images.githubusercontent.com/49565695/194778939-e934662b-a3c4-4bde-886d-dfb6de7c4ab1.png)

**Comment by Cvolton** [comment]
doesn't seem that dailies are accounted at all oddly enough, this also includes stars and user coins

**Comment by MegaSa1nt** [comment]
how can i fix this?
