### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by RobertTopala** [Cvolton/GMDprivateServer#94]

**Comment by SamHep0803** [comment]
Hi @RobertTopala !!!

**Comment by SamHep0803** [comment]
anywhere i can pm you?

**Comment by RobertTopala** [comment]
You can do it via Discord, i will use a fake one because I don't want to you know my real one, it's this: DonAlex0 #1816

**Comment by SamHep0803** [comment]
Ok I friend requested you

**Comment by RobertTopala** [comment]
But you can help me with my problem?

**Comment by Cvolton** [comment]
if you have $cloudSaveEncryption set to 1 in config/security.php, change it to 0

**Comment by Cvolton** [comment]
keep it as 0 and chmod 777 the data folder (change the file permissions, so everything's enabled)

**Comment by RobertTopala** [comment]
Everything is in 777
