### ISSUE TITLE
How do i get more people on the Creator Board without Creatorpoints?

### ISSUE THREAD

**Issue by NightDust12** [Cvolton/GMDprivateServer#940]
Whenever i view the creatorboard on my gdps, it only shows people with CreatorPoints and not new people that join. How do i fix that?

**Comment by MegaSa1nt** [comment]
what?

**Comment by fancythedeveloper** [comment]
> Whenever i view the creatorboard on my gdps, it only shows people with CreatorPoints and not new people that join. How do i fix that?

That's literally THE POINT?
