### ISSUE TITLE
Client doesn't connect to my server

### ISSUE THREAD

**Issue by nolemretaWxd** [Cvolton/GMDprivateServer#946]
Some calls like quests, weekly and daily levels and updating scores are made to my server, but eg. searching and downloading levels are not.
My domain name has the same length as boomlings.com and I don't have http to https redirect (http://www.nolemretaw.pl).
Game's exe file doesn't have any original strings left (in addition to that, I've searched the exe file for hex and string versions of direct boomlings.com IP)
![obraz](https://user-images.githubusercontent.com/31414969/201427321-ad72130f-fc2d-4b47-8345-e74928b50881.png)
(first one is official server, 2nd is my server)

![obraz](https://user-images.githubusercontent.com/31414969/201427783-cc256f8c-5507-4f15-9dbd-af55303cb0e5.png)
I also wasn't able to find getGJLevels21.php or Z2V0R0pMZXZlbHMyMS5waHA= (base64 of getGJLevels21.php) in exe file

**Comment by Cvolton** [comment]
searching for Z2V0R0pMZXZlbHMyMS5waHA= exactly won't give you results, searching for L2dldEdKTGV2ZWxzMjEucGhw (`/getGJLevels21.php`) will. This is due to the way base64 is structured - it turns every group of 3 bytes/characters into 4 characters.

**Comment by nolemretaWxd** [comment]
> searching for `Z2V0R0pMZXZlbHMyMS5waHA=` exactly won't give you results, searching for `L2dldEdKTGV2ZWxzMjEucGhw` (`/getGJLevels21.php`) will. This is due to the way base64 is structured - it turns every group of 3 bytes/characters into 4 characters - the amount of characters I removed from the full URL (`http://www.boomlings.com/database/getGJLevels21.php`) is 33, which is divisible by 3 and as such it produces a result that's also a part of the full thing

Searching for `L2dldEdKTGV2ZWxzMjEucGhw` found something, and I was able to find another boomlings.com URL encoded as `aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL2`, which wasn't included in wiki's tutorial
After replacing that, everything works, except for downloading levels

**Comment by nolemretaWxd** [comment]
> > searching for `Z2V0R0pMZXZlbHMyMS5waHA=` exactly won't give you results, searching for `L2dldEdKTGV2ZWxzMjEucGhw` (`/getGJLevels21.php`) will. This is due to the way base64 is structured - it turns every group of 3 bytes/characters into 4 characters - the amount of characters I removed from the full URL (`http://www.boomlings.com/database/getGJLevels21.php`) is 33, which is divisible by 3 and as such it produces a result that's also a part of the full thing
> 
> Searching for `L2dldEdKTGV2ZWxzMjEucGhw` found something, and I was able to find another boomlings.com URL encoded as `aHR0cDovL3d3dy5ib29tbGluZ3MuY29tL2`, which wasn't included in wiki's tutorial After replacing that, everything works, except for downloading levels

The issue with that was because server didn't have permission to create files in data/levels directory, which also isn't explained in wiki (which imo as for replacing server URLs is a okay start, but imo it's better to just sit down with wireshark or something similar to look out for any leftover boomling.com calls)
