### ISSUE TITLE
levelReupload.php not working

### ISSUE THREAD

**Issue by mmitochondira** [Cvolton/GMDprivateServer#948]
![image](https://user-images.githubusercontent.com/84156980/201938883-1d1fd853-21b2-4422-a4ec-7357f10cb69c.png)

it's doing whatever the hell this is

**Comment by mmitochondira** [comment]
Another thing, it's not letting me upload object heavy levels. It just... breaks

**Comment by MegaSa1nt** [comment]
> it's doing whatever the hell this is

so... where is level name?

**Comment by mmitochondira** [comment]
What I could try is assigning ":name" to 'reuploaded level' for testing purposes, but also note there are a lot of undefined indexes for levelArray. idfk anything about arrays in php. and idk if changing the value for ":name" will break anything, but it's worth a shot. But I do think that the other values will also bug out.

**Comment by mmitochondira** [comment]
> What I could try is assigning ":name" to 'reuploaded level' for testing purposes, but also note there are a lot of undefined indexes for levelArray. idfk anything about arrays in php. and idk if changing the value for ":name" will break anything, but it's worth a shot. But I do think that the other values will also bug out.

This sorta worked. however, it then stated that levelDesc cannot be null. So I'm pretty sure it has something to do with the arrays being out of index

**Comment by Cvolton** [comment]
the real issue seems to be that you're not getting the level data in the first place, you can try echoing the raw response to know what you're actually getting
