### ISSUE TITLE
Likes and downloads

### ISSUE THREAD

**Issue by hollybite1337** [Cvolton/GMDprivateServer#950]
what if I upload a level and it automatically gets 100 likes and 300 downloads?

**Comment by MegaSa1nt** [comment]
because gdps is set up to do that
![image](https://user-images.githubusercontent.com/49565695/202924877-9ef92cd0-afe2-40ef-9c9e-122c963888ca.png)
![image](https://user-images.githubusercontent.com/49565695/202924881-d552cb3d-f034-4f25-a860-5cb6863b0d5a.png)
