### ISSUE TITLE
Fatal error in registerAccount.php

### ISSUE THREAD

**Issue by pKunnn** [Cvolton/GMDprivateServer#951]
I can't register in-game and in the site. in-game i get the "something went wrong" text and in the site i get 

> `"Fatal error: Call to a member function prepare() on null in /home/PKun/public_html/gdbrazilian/database/tools/account/registerAccount.php on line 27"`

and i think my connection.php is right 

![imagem_2022-11-21_203413654](https://user-images.githubusercontent.com/88407278/203179308-78e8d398-264e-4a63-8c69-e3aff2b42f8f.png)

the worst part is: i already created a gdps before and i never got this error

**Comment by MegaSa1nt** [comment]
Lol, check incl/lib/connection.php, it should have:
$db = PDO::thingy

**Comment by pKunnn** [comment]
LMAOOO IT WORKED
(idk why but this is how my connection.php was lol)
![imagem_2022-11-22_165440994](https://user-images.githubusercontent.com/88407278/203409096-70f2ec68-b991-4ce6-baae-c344af8a83f7.png)
