### ISSUE TITLE
Levels above 1gb can't be downloaded in-game

### ISSUE THREAD

**Issue by mmitochondira** [Cvolton/GMDprivateServer#960]
Object heavy levels that are more than one gigabyte in the data folder found inside the directory cannot be downloaded in-game. Is there any way to fix this? Either through manual means or any loopholes? Anything?

**Comment by MegaSa1nt** [comment]
> Object heavy levels that are more than one gigabyte in the data folder found inside the directory cannot be downloaded in-game. Is there any way to fix this? Either through manual means or any loopholes? Anything?

7m.pl issue. Dont use it

**Comment by mmitochondira** [comment]
> 

ok ty

**Comment by mmitochondira** [comment]
> 7m.pl issue, Dont use it

Okay thank you! I tried switching to 000webhost. I can't quite get the server to run because of how funky the database system is. But that's aa topic for another day.
