### ISSUE TITLE
levelReupload.php not working

### ISSUE THREAD

**Issue by ersopasyt** [Cvolton/GMDprivateServer#961]
When I try to reupload a level in levelReupload.php, when I hit "Reupload", the page does not show any text, it is blank. But if I put a wrong ID, I get the error "This level doesn't exists". I have checked the levelReupload.php file to see if there was something wrong but nothing, I deleted and replaced it and nothing. What can I do? My PHP version is 7.4

**Comment by Boynfriend** [comment]
Bro how to upload level say pls i cant upload its saying Upload failed
