### ISSUE TITLE
Changed Demon/Star in database but didn't show up In-game.

### ISSUE THREAD

**Issue by SamHep0803** [Cvolton/GMDprivateServer#97]
There is a bug where if you change a users demons and stars (there could be more but thats all i've tried) it will update in the database but not visually in-game. Just wanted to let @Cvolton know.

**Comment by Cvolton** [comment]
works as intended, the game overrides it with the values stored in the save data, you have to use a client-side hack to change that

**Comment by SamHep0803** [comment]
oh ok

**Comment by SamHep0803** [comment]
Which hack then?

**Comment by SMJSGaming** [comment]
unless you somehow can get into someone else's pc it is not possible to do such hack.
