### ISSUE TITLE
issue with level uploading

### ISSUE THREAD

**Issue by shikoshib** [Cvolton/GMDprivateServer#970]
everything in my gdps works fine, except for the level uploading. i checked my http requests through wireshark and found out that the client actually sends the level string, but **for some reason** it's not being applied to the database. and it turns out that i can't download this level.
however, if i'll paste the level string into the database manually, the level actually downloads.
how to fix it?

**Comment by shikoshib** [comment]
nvm i fixed it

**Comment by zkayns** [comment]
how did you fix this??

**Comment by shikoshib** [comment]
> how did you fix this??

it was quite a while ago and i deleted my gdps
but basically i put the 777 permissions for all the files on the server (i.e. everyone can read and write to files)
it's required and i didnt know about it
