### ISSUE TITLE
Automatic CP

### ISSUE THREAD

**Issue by dekrypted** [Cvolton/GMDprivateServer#973]
Hello,

I know I can edit a user's CP from the SQL database, but is there a way to have it automatically give CP when a level is rated?

**Comment by MegaSa1nt** [comment]
![image](https://user-images.githubusercontent.com/49565695/213884309-ebe67889-fd03-40b6-8e4b-43e1a697333c.png)
do this here

**Comment by MegaSa1nt** [comment]
![image](https://user-images.githubusercontent.com/49565695/213884333-f198776e-f591-4766-bcfd-0bf77a24c712.png)
and here

**Comment by dekrypted** [comment]
oh I see, automatically running the cron :)

thank you very much!

**Comment by crypton1871** [comment]
bro how is this not made by cvolton yet 💀

**Comment by MegaSa1nt** [comment]
> bro how is this not made by cvolton yet 💀 

#891
