### ISSUE TITLE
Adding Stars to daily chests.

### ISSUE THREAD

**Issue by SamHep0803** [Cvolton/GMDprivateServer#98]
Hi, @Cvolton I am star grinding in the normal GD servers and I was opening a Daily Chest, and I was wondering, can you add stars to Daily chests? It's just a suggestion.

**Comment by SamHep0803** [comment]
Ok it's been 5 days with no response come on @Cvolton

**Comment by pavlukivan** [comment]
it's impossible

**Comment by SamHep0803** [comment]
NUUU wait... rlly?

**Comment by Cvolton** [comment]
closed because impossible currently, may be possible later with client-side modifications

**Comment by SamHep0803** [comment]
Yay
