### ISSUE TITLE
Certain rates of levels fade to black when complete.

### ISSUE THREAD

**Issue by 0mgRod** [Cvolton/GMDprivateServer#982]
When a level is rated and I complete it, instead of giving rewards and stuff for completing, it fades to black.

There are 2 (maybe 3) exceptions for rates that work as intended:

- Auto
- Easy
- Maybe Normal

**Comment by MegaSa1nt** [comment]
Robtop's anticheat, don't rate short and tiny levels

**Comment by 0mgRod** [comment]
> Robtop's anticheat, don't rate short and tiny levels

Thanks for informing. Is there a way to change the anticheat code to prevent this from happening?

**Comment by MegaSa1nt** [comment]
> > Robtop's anticheat, don't rate short and tiny levels
> 
> Thanks for informing. Is there a way to change the anticheat code to prevent this from happening?

Use anticheat bypass

**Comment by 0mgRod** [comment]
> > > Robtop's anticheat, don't rate short and tiny levels
> > 
> > 
> > Thanks for informing. Is there a way to change the anticheat code to prevent this from happening?
> 
> Use anticheat bypass

Thank you! Also, is the anticheat bypass only for the mods so then when rated, the levels will work for everyone without needing the bypass or is it that everyone would need to use it for the levels to work?

**Comment by Cvolton** [comment]
everyone needs to use it

**Comment by 0mgRod** [comment]
Oh god...

![image](https://user-images.githubusercontent.com/89850217/219899135-ad825d82-e266-49ce-b770-5ba3541bcf66.png)
