### ISSUE TITLE
How can I make a script that gives the player the Subzero, Meltdown and World icons?

### ISSUE THREAD

**Issue by 0mgRod** [Cvolton/GMDprivateServer#983]
Since there is no way to link a GDPS account to any of the GD spinoff games, how can I make the player get the icons for free instantly is they don't have them and they log on?

**Comment by MegaSa1nt** [comment]
> Since there is no way to link a GDPS account to any of the GD spinoff games, how can I make the player get the icons for free instantly is they don't have them and they log on?

Use icon bypass
