### ISSUE TITLE
Error 503 (Something went wrong)

### ISSUE THREAD

**Issue by AcePlayzGamesYT** [Cvolton/GMDprivateServer#989]
Hey, so i made my gdps but if i go to ANYTHING that requires the files or smth it says something went wrong and if i go to any of the things manually i get error 503, my connection php is: https://pastebin.pl/view/raw/7797f192  I have set the perms(everything 777) and i am using 7m.pl, i have been spending HOURS trying to figure this out.
![image](https://user-images.githubusercontent.com/94937764/221740855-80d7f171-8773-46bc-b029-087c7a8187a4.png)

**Comment by MegaSa1nt** [comment]
this is not your side of problem ig

**Comment by AcePlayzGamesYT** [comment]
wdym?
